### ISSUE TITLE
How to know if a role has a certain ability?

### ISSUE THREAD

**Issue by ethan4ma** [JosephSilber/bouncer#101]
@JosephSilber  How to know if a role has a certain ability? thx.

**Comment by JosephSilber** [comment]
$role->can('ability')

**Comment by IamSwap** [comment]
@JosephSilber This gives me error `Call to undefined method Illuminate\Database\Query\Builder::can()`.  
I am fetching single role by id `$role = \Bouncer::role()->find($id);` & checking if role has ability.

**Comment by IamSwap** [comment]
never mind, got it by `$role->abilities->pluck('name')`.

**Comment by jorgeneira** [comment]
It seems the can() method is not implemented yet. As a workaround you can do:

```php
$hasAbility = \Bouncer::role()->whereId($id)->whereCan('ability')->exists();

**Comment by IamSwap** [comment]
@jorgeneira  Thanks! I was doing it following way, which works too. But implemented your solution:
```php
$role = \Bouncer::role()->find($id);
$hasAbility = in_array('ability', $role->abilities->pluck('name'));
```

**Comment by JosephSilber** [comment]
Whoops. Dunno why I thought we had that on the `Role` model.

Just pushed [some code](https://github.com/JosephSilber/bouncer/commit/d1b11870117deb0579c92868752444d7ded48d30) to enable that. You should now be able to simply check it with:

```php
if ($role->can('ability')) {
    //
}
```
