### ISSUE TITLE
Is there a way to just create role without abilities?

### ISSUE THREAD

**Issue by icodebuster** [JosephSilber/bouncer#105]
I am trying to create a RolesTableSeeder to create some roles by default.
Here is the code that I was trying.

    <?php

    use Illuminate\Database\Seeder;

    class RolesTableSeeder extends Seeder
    {
        public function run()
        {
            Bouncer::allow('SuperAdmin');
            Bouncer::allow('Admin');
            Bouncer::allow('Moderator');
            Bouncer::allow('User');
        }
    }

The above code did not create any roles in the database.

I just need only the roles for time being.

**Comment by icodebuster** [comment]
Sorry,
Figured out the solution you simply need to call the `to` method with empty array.

    Bouncer::allow('ABC')->to([]);

**Comment by JosephSilber** [comment]
```php
Bouncer::role(['name' => 'super-admin')->save();
```

**Comment by icodebuster** [comment]
Thank you :+1:
