### ISSUE TITLE
Execution time for large amounts of permissions/abilities

### ISSUE THREAD

**Issue by andaril** [JosephSilber/bouncer#106]
I have permission system for models. There are like 10 different permissions for every entity and around 100-200 entities.

So all goes fine with caching until u add new item and caches for user became invalid. In next request u get error
```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' 
with message 'Maximum execution time of 30 seconds exceeded' in 
/app/vendor/silber/bouncer/src/Database/Ability.php:107
```

Is there a way not to purge all cache but add some more data to it?

**Comment by JosephSilber** [comment]
That line number doesn't exist in the latest commit, so it's hard for me to debug it.

Can you please upgrade to the latest commit and post the error here again?

**Comment by andaril** [comment]
Of course I will update. But it is rare error for me, like 1 in 10 days.

I look through package and found same line, moved from ability model.
https://github.com/JosephSilber/bouncer/blob/master/src/Database/IsAbility.php#L89

I know from laravel that casting algorithm is too slow with large sets of data. So here i think same problem.

**Comment by JosephSilber** [comment]
That's not enough. In order to properly diagnose this, I'll need the full stack trace. Thank you.

**Comment by andaril** [comment]
There are no full stack trace for fatal error in production env.
![log](http://i.imgur.com/OMkJvcd.png)

I will try to reproduce this on dev comming week.

**Comment by JosephSilber** [comment]
Closing this pending more information.
