### ISSUE TITLE
Clearing all user roles and role abilities before update?

### ISSUE THREAD

**Issue by twocatszerokarma** [JosephSilber/bouncer#107]
Hello
I want to create a view like this: http://imgur.com/a/GjxHq
My goal is to be able to manage permissions with a UI.
Before I assign (save) abilities and/or permissions, I'd like to clear all permissions first (e.g. i'd like to clear the user_roles and roles_abilities tables). This would take care of disallowing abilities and retracting roles, and then I would only need to save new abilities and roles.
What is the best way to accomplish this functionality with this package?

**Comment by JosephSilber** [comment]
These are regular Eloquent relationships, so you can easily achieve that with the `detach` method:

```php
$user->roles()->detach();
$user->abilities()->detach();
```

**Comment by twocatszerokarma** [comment]
I see, sorry I am new to laravel.
I suppose I would have to loop through all users to accomplish this then?

**Comment by JosephSilber** [comment]
Yes. Just loop through all your users and call detach on the relationships.
