### ISSUE TITLE
What is the use of entity_id and entity_type in abilities table?

### ISSUE THREAD

**Issue by ratulcse27** [JosephSilber/bouncer#109]

**Comment by Arcesilas** [comment]
It's used for polymorphic relations: it allows bouncer to assign permissions on any model. The `entity_type` is the model, and the `entity_id` is the id of the related model.
See https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relations for more information

**Comment by JosephSilber** [comment]
To be clear, it's only similar to true polymorphic relations, but they're not actual polymorphic relations.

Both of these columns can be null. Also, there can be an entity_type without an entity_id. Finally, the entity_type can be an asterisk.

These columns are used internally by Bouncer to manage abilities. They're not accessed via a true Eloquent polymorphic relation.
