### ISSUE TITLE
Extending Bouncer

### ISSUE THREAD

**Issue by subdesign** [JosephSilber/bouncer#110]
Can I extend Bouncer with my special checks? We have a more complex ACL, and need unique functions for complex checks, and I want to use Bouncer:: facade to it, and not to mix with our special named functions.

For example: Bouncer::mySpecialCheck($user);

Thanks

**Comment by JosephSilber** [comment]
Bouncer allows you to define a callback for an ability:

```php
Bouncer::define('my-special-ability', function () {
    return // some custom logic...
});
```

You can then check it like you would any other ability:

if ($user->can('my-special-ability')) {
    // proceed
}
