### ISSUE TITLE
Human Label on Abilities

### ISSUE THREAD

**Issue by rafaellupo** [JosephSilber/bouncer#111]
Hi @JosephSilber ! 
I've got the day to implement Bouncer on my project, and doing some use case review I found something here. I see the Abilities model doesn't has a label property. 
Well, in this project, users are supposed to give permissions to another users through a Form with roles / permission listing and checkboxes. Do you have any suggestion of how can I have this approach regarding having an human label to the checkboxes ? 
Maybe I can just humanize the abilities name, maybe extend bouncer.

**Comment by Arcesilas** [comment]
Could it be related to #12 ?

**Comment by Arcesilas** [comment]
Sorry, I was thinking of #86 instead :)

**Comment by rafaellupo** [comment]
Yes, nice ! Thanks

**Comment by JosephSilber** [comment]
@rafaellupo since many people have been asking about this, [I just added](https://github.com/JosephSilber/bouncer/commit/558f69321a3b6a9b1285732077846243a2a0c504) a default `title` column to the `abilities` and `roles` tables.

**Comment by rafaellupo** [comment]
@JosephSilber perfect ! One question, in order to use "allow to" with the title should be this way, right ? 
```php
$ability = Ability::create(['name'=>'delete-any-post', 'title'=>'Can Delete Any Post']);
Bouncer::allow($user)->to($ability, Post::class);
```
