### ISSUE TITLE
How to add new fields to tables

### ISSUE THREAD

**Issue by sobhanattar** [JosephSilber/bouncer#112]
Hi
Actually this is a question and not an issue, I want to know is there any way using Facade to add some columns like "display_name" to "ability" table and use it during programming. Something Like this:

`Bouncer::allow('admin')->to('ban-users', 'display_name_value');` or
`Bouncer::ability('ban_users', 'display_name_value');`

This way we have this opportunity to assign a human readable name to an ability and use it in view files for assigning to users and roles.

**Comment by JosephSilber** [comment]
To add additional attributes, create the ability on your own, then pass it to Bouncer:

```php
use Silber\Bouncer\Database\Ability;

$ability = Ability::create([
    'name' => 'ban-users',
    'title' => 'Ban users',
]);

Bouncer::allow('admin')->to($ability);
```

To create an ability for a model, you can use the `createForModel` method:

```php
$ability = Ability::createForModel(User::class, [
    'name' => 'ban',
    'title' => 'Ban users',
]);

Bouncer::allow('admin')->to($ability);
```
