### ISSUE TITLE
Problem installation under L5.3

### ISSUE THREAD

**Issue by Tjoosten** [JosephSilber/bouncer#113]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework 5.3.x-dev
    - Conclusion: don't install laravel/framework 5.3.x-dev
    - silber/bouncer 0.1.x-dev requires illuminate/database ~5.1.20|5.2.* -> satisfiable by illuminate/database[5.1.x-dev, 5.2.x-dev, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.6, v5.2.7].
    - silber/bouncer v0.1.7 requires illuminate/database ~5.1.20|5.2.* -> satisfiable by illuminate/database[5.1.x-dev, 5.2.x-dev, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.6, v5.2.7].
    - don't install illuminate/database 5.1.x-dev|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database 5.2.x-dev|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.20|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.22|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.25|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.28|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.30|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.31|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.1.41|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.0|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.19|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.21|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.24|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.25|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.26|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.27|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.28|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.31|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.32|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.37|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.43|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.6|don't install laravel/framework 5.3.x-dev
    - don't install illuminate/database v5.2.7|don't install laravel/framework 5.3.x-dev
    - Installation request for laravel/framework 5.3.* -> satisfiable by laravel/framework[5.3.x-dev].
    - Installation request for silber/bouncer ^0.1.7 -> satisfiable by silber/bouncer[0.1.x-dev, v0.1.7].

Installation failed, reverting ./composer.json to its original content.
MacBook-van-Tim:IMA tim$

**Comment by JosephSilber** [comment]
Bouncer's `0.1` branch does not support Laravel 5.3.
