### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Tjoosten** [JosephSilber/bouncer#114]
```bash
ErrorException in User.php line 11:
Declaration of Silber\Bouncer\Database\HasRolesAndAbilities::is($role) should be compatible with Illuminate\Database\Eloquent\Model::is(Illuminate\Database\Eloquent\Model $model)
```

**Comment by JosephSilber** [comment]
The reason for this error is because you're using Laravel 5.3, which introduced an `is` method on the base model that does something completely different.

I'm afraid I'll have to rename Bouncer's `is` method to something else :cry:

**Comment by Tjoosten** [comment]
Xhen there is a fix for this one?

**Comment by JosephSilber** [comment]
This has now been updated [here](https://github.com/JosephSilber/bouncer/commit/145bf653015ce6ba1a9c42999805158ef7c4cc40).

You should now use the `isAn`/`isA` methods instead of `is`:

```php
if ($user->isAn('admin')) {
    //
}
```

**Comment by Tjoosten** [comment]
But i do `composer update` nothing happen for the bouncer package

**Comment by JosephSilber** [comment]
What's the version constraint you have in there? You need dev-master.

**Comment by antoniopaisfernandes** [comment]
@Tjoosten Are you using 'dev-master' version?

**Comment by Tjoosten** [comment]
Alright i had the wrong constraint. My bad. Guys thx u for fixing this
