### ISSUE TITLE
Want to add 'friendly name' column to roles table

### ISSUE THREAD

**Issue by dambridge** [JosephSilber/bouncer#12]
Foresee any issues with my doing this in a separate migration?

**Comment by JosephSilber** [comment]
I'm not sure I understand what the friendly name is for.

Why aren't you using the "friendly name" as the actual `name`?

**Comment by JosephSilber** [comment]
Closing this pending further details.

**Comment by dambridge** [comment]
Erm, totally confused myself there. The roles table and migration still had a 'title' column instead of 'name'. I'm assuming you updated at some point and my composer didn't catch it. Weird.

**Comment by dambridge** [comment]
Yep, I'm an idiot. Composer was hard tagged to 0.0.8!
