### ISSUE TITLE
default user model location

### ISSUE THREAD

**Issue by leantony** [JosephSilber/bouncer#120]
Hi,
I have my user model in App\Models\User
Am trying to load all users assigned to a role
But getting an empty collection
When I change the user model to App\Models\User in Silber\Bouncer\Database\IsAbilityTrait, I end up getting a collection of users

So, how do I change the location from where the package loads the user model?

**Comment by JosephSilber** [comment]
Bouncer uses whatever model you've set up in your auth configure file.

**Comment by leantony** [comment]
Yah ive seen that in the service provider. Thanks
