### ISSUE TITLE
5.3 Compatible Release

### ISSUE THREAD

**Issue by bkuhl** [JosephSilber/bouncer#121]
Currently I'm using `1.0.0-alpha.1` and would like to upgrade to Laravel 5.3.  However, that release isn't compatible.  I noticed the master branch has been updated for 5.3, but also includes other changes.  Can  you release a new `1.x` version that allows upgrading to 5.3?

**Comment by JosephSilber** [comment]
I hope to release alpha 2 by then end of the week (no promises).

If you can't wait, you can use dev-master in the meantime.

**Comment by bkuhl** [comment]
Sweet.  I'll wait so I can see a change log before upgrading.  Thanks for putting your time into making a cool package like this.

**Comment by JosephSilber** [comment]
[Alpha 2 was just tagged](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-alpha.2) with support for Laravel 5.3.
