### ISSUE TITLE
UUID support?

### ISSUE THREAD

**Issue by autaut03** [JosephSilber/bouncer#124]
I'm using laravel 5.3 and have to use a new version of bouncer, 1.0.0-alpha2. In the old one I changed the 'user_id' column type from integer to uuid and that was it. But now I can't do it like this because you started using "morphs" which uses integer id. How can I add support for uuid or even both uuid and integer id?

**Comment by JosephSilber** [comment]
There's nothing in the morphs that would prevent you from using UUIDs. Simply change your migration so that the role id column and the permissions table's entity_id column both allow UUIDs.

**Comment by autaut03** [comment]
Yep, that would have worked if you only use user permissions for one table. But in 1.0 there's an ability to give permissions to anything (like "User model" or "ApiKey model"), isnt it? Anything can be done about that or should it be just hardcoded as in previous versions?

**Comment by JosephSilber** [comment]
If you want to assign roles/abilities to a different model, you should make that model also use a UUID.

**Comment by autaut03** [comment]
Is it real to make some "mixed" data type so that it would support both binary(16) for uuid and integer(11) for plain ids?

**Comment by autaut03** [comment]
In the migration while creating Models::table('abilities') you dont use "morphs". Please fix.

**Comment by JosephSilber** [comment]
Can you explain that in a little more detail?

What would you like to see changed, and why?

**Comment by autaut03** [comment]
In the bouncer migration file there's two lines of code: 
`$table->integer('entity_id')->unsigned()->nullable();
 $table->string('entity_type')->nullable();`

They're the same as 
`$table->morphs('entity');`

This is a little bug that I would like you to get fixed.

**Comment by JosephSilber** [comment]
How is that a bug?

**Comment by autaut03** [comment]
in all other places you used "morphs" and now manually set entity_id and entity_type.

**Comment by JosephSilber** [comment]
Again, why is that a bug?

**Comment by autaut03** [comment]
Ehm... because it is =/ what's wrong =/
