### ISSUE TITLE
Poll: can you live without Bouncer's query scopes?

### ISSUE THREAD

**Issue by JosephSilber** [JosephSilber/bouncer#126]
Bouncer currently allows you to scope queries by whether they have a certain ability:

```php
$users = User::whereCan('create', Post::class)->get();
$users = User::whereCannot('create', Post::class)->get();

$roles = Bouncer::role()->whereCan('create', Post::class)->get();
$roles = Bouncer::role()->whereCannot('create', Post::class)->get();
```

As more and more features are being added to Bouncer, I've found that maintaining these query scopes adds a big burden onto the package's development, to the point where it's actively hindering my ability to add new and exciting features.

As this feature is not even being used by most people, I've come to the realization that the cost/benefit ratio seems to be leaning towards them not being worth it. I'm planning on removing them from Bouncer.

Before fully committing to removing it, I'd like to run an informal poll here. Please answer with _one_ reaction on this comment:

:+1: - I don't use these query scopes, or I don't think they're worth maintaining at the cost of other features.

:-1: - I use these query scopes and rely upon them a lot. I'd be devastated if they're removed.

**Comment by JosephSilber** [comment]
It seems pretty clear that these query scopes were barely used, [so I've removed them](https://github.com/JosephSilber/bouncer/commit/492982c40c6e7df88dc084872c3a99ee3acfcfe4).

**Comment by SeoFood** [comment]
If you want to still use it in your Models simple add this:
```php
/**
 * @param \Illuminate\Database\Eloquent\Builder $query
 * @param string $ability
 */
public function scopeWhereCan($query, $ability)
{
    $query->where(function ($query) use ($ability) {
        // direct
        $query->whereHas('abilities', function ($query) use ($ability) {
            $query->byName($ability);
        });
        // through roles
        $query->orWhereHas('roles', function ($query) use ($ability) {
             $query->whereHas('abilities', function ($query) use ($ability) {
                 $query->byName($ability);
             });
         });
     });
}
```

**Comment by ElectricCarbon** [comment]
This is ridiculous. Why would a feature like this be removed? This is essential to any permission management system and really allows much more depth.
