### ISSUE TITLE
Add method in Role model

### ISSUE THREAD

**Issue by swimlappy** [JosephSilber/bouncer#13]
Hello,

Would it be possible to have a scope method added to the Role model to return a list of available roles?  Something like this for example

```
    public function scopeOrderedList($query)
    {
        return $query->orderBy('name')->lists('name', 'id');
    }
```

For example, this would be useful when building select boxes for someone to choose a role from.

```
$roles = Role::orderedList()->toArray();

```

Then pass that into a view.

Thanks

**Comment by JosephSilber** [comment]
You can add your own methods to the role model by [extending it](https://github.com/JosephSilber/bouncer/releases/tag/v0.0.22):

```php
namespace App;

use Silber\Bouncer\Database\Role as BaseRole;

class Role
{
    public function scopeOrderedList($query)
    {
        return $query->orderBy('name')->lists('name', 'id');
    }
}
```

Once you've created your model, simply tell bouncer to use it:

```php
Bouncer::useRoleModel(\App\Role::class);
```

Put that in your 'AppServiceProvider`'s `boot` method, and you're good to go!

**Comment by swimlappy** [comment]
Excellent!  That keeps things clean.  Thanks!  And I really like Bouncer, perfect for an app I'm working on!

**Comment by dhcmega** [comment]
Hi, is this still the way to go? Because with last versions (Laravel 5.5.14, Bouncer v1.0.0-beta.4) if I change the RoleModel with Bouncer::useRoleModel(\App\Role::class), I get "This action is unauthorized".
