### ISSUE TITLE
Gate policies are ignored due to automatic ability wildcards

### ISSUE THREAD

**Issue by eComEvo** [JosephSilber/bouncer#131]
Suppose I want to create an `edit-posts` ability I plan to make assignable to certain roles that I want to be revocable in full, even for their own posts:
```
Bouncer::ability(['name' => 'edit-posts', 'title' => 'Edit posts'])->save();
Bouncer::allow('author')->to('edit-posts');
Bouncer::allow('admin')->to('edit-posts');
```

However, I don't want them to be able to edit any other user's posts even while they have `edit-posts` permissions so I create a `Gate` policy associated with my `Posts` model:
```
class PostPolicy
{
    public function edit(User $user, Post $post)
    {
        return $user->can('edit-posts') // Can user edit posts in general?
           && (
             $user->isAn('admin') || // Do they also have the admin role?
             $user->id == $post->user_id; // Or is this their post?
        );
    }
}
```

```
class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        \App\Models\Post::class => \App\Policies\PostPolicy::class
    ];
}
```

When I check for full permissions, the `Gate` always allows:
```
\Gate::allows('edit', [$post]); // TRUE no matter the role or who the post belongs to.
```

If I trace this in Xdebug, I see the following gating message:
```
Bouncer granted permission via ability #4.
```

In the abilities table, record #4 is `edit-posts` and the trace shows the `PostPolicy` is never even being checked.

Do I have my logic completely wrong here for what I'm looking to accomplish with Bouncer?

**Comment by eComEvo** [comment]
Apparently this works if I rename `PostPolicy::edit` to `PostPolicy::editPolicy` but I'm still wondering...is this the optimal way to go about doing this sort of check?

Is it best practice to also add `entity_type` at the time the ability is created?

**Comment by JosephSilber** [comment]
I'm afraid the code you posted is not the actual code you're using.

`Gate::allows('edit', [$post])` would not have Bouncer use the `edit-posts` ability. The two have nothing in common.

Additionally, while Bouncer allows you to use policies, that's only for abilities not granted through Bouncer. If you grant an ability through Bouncer, the gate will never hit your policy class.

**Comment by eComEvo** [comment]
This is the functional part of the code I'm using. It's abbreviated for posting here. I did have a typo earlier where I wrote `PostPolicy::editPolicy` in a follow-up comment instead of `PostPolicy::editPosts`. Is that what looked weird?

If I run `\Gate::allows('edit-posts', [$post]);` then I can trace it down this chain:

* `Gate::check()`
  * `Gate::raw()`
    * Line 242: `if (is_null($result = $this->callBeforeCallbacks($user, $ability, $arguments))) {`

It's this line where `$result` contains the message `Bouncer granted permission via ability #4.`

If I grant `edit-posts` to these two roles and create the method `PostPolicy::editPosts`, then I can trace the code all the way through where it gets to line 243 to call `PostPolicy::editPosts` and then watch it make a 2nd call within `PostPolicy::editPosts` where it only reaches line 242 in which Bouncer authorizes due to the `$user->can('edit-posts')` call within `PostPolicy::editPosts`.

So it is reaching the policy, but once it is within the policy, it is deferring to Bouncer on the 2nd check which lacks the `$arguments` portion of `can()`.

I'm not sure if this fits in with what you meant.

**Comment by JosephSilber** [comment]
You originally said you were checking `Gate::allows('edit', [$post])`, but now you're saying you're checking for `Gate::allows('edit-posts', [$post])`. So which is it?

**Comment by eComEvo** [comment]
At first I was checking `Gate::allows('edit', [$post])` and saw my `PostPolicy:edit` method ignored. Then I commented it isn't ignored if I do `Gate::allows('edit-post', [$post])` and `PostPolicy:editPost` respectively.

Within my Bouncer abilities, there is no `edit` but there is an `edit-post`. Does Bouncer take some liberty with matching the model type `Post` with `edit-post` when I only gave the Gate `edit` that first time around?

**Comment by JosephSilber** [comment]
No it doesn't.

**Comment by JosephSilber** [comment]
Can you explain in simple terms what your end goal is? Not how you tried to accomplish it.

Simply tell me what your permission requirements are, so that I can see if Bouncer can help you with that.

**Comment by eComEvo** [comment]
My goal is to give a list of permissions to a role that can be assigned to a user.

In this case, I want those permissions to be denied if the user doesn't own a post and that user does not have the admin role, OR if the user no longer has that specific ability anymore regardless of their role.

**Comment by JosephSilber** [comment]
Register the ability and the role with Bouncer:

```php
Bouncer::ability(['name' => 'edit-posts', 'title' => 'Edit posts'])->save();

Bouncer::allow('admin')->to('edit-posts');
```

Then create this policy:

```php
class PostPolicy
{
    public function edit(User $user, Post $post)
    {
        return $user->id == $post->user_id && $user->can('edit-posts');
    }
}
```

Which you then check at the gate:

```php
Gate::authorize('edit', $post);
```

**Comment by eComEvo** [comment]
Unfortunately that didn't work. However, this worked:
```
class PostPolicy
{
    public function editPosts(User $user, Post $post)
    {
        return $user->id == $post->user_id && $user->can('edit-posts');
    }
}
```

Then checked it like so:
```
Gate::authorize('edit-posts', $post);
```

Thanks for helping me figure this out!

**Comment by JosephSilber** [comment]
With [the just-released alpha 3](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-alpha.3), you can replace all that code with this one line:

```php
Bouncer::allow('admin')->toOwn(Post::class, 'update');
```

You can then run this check:

```php
Gate::authorize('update', $post);
```

...and it'll automatically check if `$post->user_id == $user->id`. No need for that policy class at all.
