### ISSUE TITLE
What is the proper composer require statement to get 5.3 support?

### ISSUE THREAD

**Issue by gn0rt0n** [JosephSilber/bouncer#134]
In starting a new 5.3 project, what is the proper way to require this in composer so that it will get future update with composer update?

Specifically:   "silber/bouncer": "v1.0.0-alpha.3" works, but   "silber/bouncer": "v1.0.0-alpha.*" doesn't.

I want to be able to keep this updated in the future.

**Comment by JosephSilber** [comment]
You can set the version to dev-master, which will automatically always get you the latest version.

However, this is very dangerous. Since Bouncer is still in alpha, new releases may break backwards compatibility. Running composer update may unexpectedly break your app.

**Comment by gn0rt0n** [comment]
Ok. Thank you for your quick response.
