### ISSUE TITLE
can't use mongo db eloquent here

### ISSUE THREAD

**Issue by hartono-sulaiman-kaskus** [JosephSilber/bouncer#135]
Hi

I have some issues, i use package "jenssegers/mongodb", but i can not extend bouncer to use Custom model

what should i do?

**Comment by JosephSilber** [comment]
I unfortunately do not know anything about that package, or about using Eloquent with MongoDB, so I cannot officially support it.

**Comment by hazeem1991** [comment]
did any one found a way to fix this problem
