### ISSUE TITLE
Are there plans to create a sort of admin dashboard or GUI?

### ISSUE THREAD

**Issue by twocatszerokarma** [JosephSilber/bouncer#136]
Are there plans to create a sort of admin dashboard or GUI to manage roles and permissions (e.g. add, create, delete, assign)?

**Comment by jonagoldman** [comment]
I think the UI is something very specific to each application and it should not be part of the package. Not only because each app has different requirements but also use different front end technologies. Regular CRUD, AJAX, Angular, React, Vue, npm, ES6, babel.... you get the idea.

**Comment by JosephSilber** [comment]
Correct. At present, it doesn't make much sense for Bouncer to include a frontend GUI to manage roles/permissions.
