### ISSUE TITLE
Could not install on Laravel 5.3.19

### ISSUE THREAD

**Issue by tridcatij** [JosephSilber/bouncer#137]
Can you explain how to resolve it?
[http://prnt.sc/cwxudl](http://prnt.sc/cwxudl)

**Comment by MECU** [comment]
I'm on 5.3.18 with the same problem.

**Comment by Jeroen-G** [comment]
For Laravel 5.3 you need Bouncer v1.0, which is in alpha. Tell composer you want this (unstable) version, not the latest stable one.

**Comment by MECU** [comment]
`composer require silber/bouncer v1.0.0-alpha3` worked for me. Thanks.
