### ISSUE TITLE
How to make Bouncer work in Lumen?

### ISSUE THREAD

**Issue by nmfzone** [JosephSilber/bouncer#139]
Do you have any plan to make it work in Lumen, @JosephSilber?

If isn't, can someone tell me how to make it work with Lumen, especially the latest Lumen version.

I've tried to figure it out by myself but always failed.

Thank you.

**Comment by nmfzone** [comment]
Whoops! I think I make a mistake. So the BouncerServiceProvider must be load before AppServiceProvider (because I register some seed in here).

Bouncer works like a charm in Lumen :+1:

**Comment by mithublue** [comment]
Hi,
How to make it work with lumen, can you let us know ?

**Comment by JosephSilber** [comment]
It's right there in the docs:

https://github.com/JosephSilber/bouncer/blob/master/readme.md#installing-bouncer-in-a-non-laravel-app

**Comment by mghase** [comment]
how did you resolve it
