### ISSUE TITLE
How to assign an ability to a user without having a role?

### ISSUE THREAD

**Issue by aronzillo** [JosephSilber/bouncer#140]
The scenario would be:

I have 4 types of users root, admin, vendor, accountant and cashier. My root user would have access to everything, the administrator can create users (each with a role and their abilities).

Administrators can create other users and freely assign their roles and abilities. But it also requires that 'x' user has some skill that doesn't belong to their role (the accountant can 'billing', but for convenience I want the cashier to do it, or the accountant can 'ban-user' without changing user role, just adding ' Special Ability'), how would you do that?

**Comment by JosephSilber** [comment]
Do you mean giving the user an ability directly, not through a role?

https://github.com/JosephSilber/bouncer/blob/master/readme.md#giving-a-user-an-ability-directly
