### ISSUE TITLE
Issue with prefixed tables

### ISSUE THREAD

**Issue by Procu** [JosephSilber/bouncer#141]
Bouncer will provide some errors when you set table prefix in database configuration, for example when using getAbilities().

The problem is that you are using whereRaw (prefix is not injected by query builder)
https://github.com/JosephSilber/bouncer/blob/master/src/Database/Queries/Abilities.php#L110
https://github.com/JosephSilber/bouncer/blob/master/src/Database/Queries/Roles.php#L62

**Comment by JosephSilber** [comment]
Fixed in https://github.com/JosephSilber/bouncer/commit/e68ecb0fd5e9b674c0b67bfbc588e547398652e5

Please let me know if it now works for you.

**Comment by Procu** [comment]
now every query is broken becouse prefix is added twice

**Comment by JosephSilber** [comment]
Took another stab at it here: https://github.com/JosephSilber/bouncer/commit/a8343629f0c1f4a1de7f33508013d3870fbabe91

Please let me know if it now works for you.

**Comment by Procu** [comment]
I fixed two more queries
