### ISSUE TITLE
Could you please give examples of where we could use these Facade methods like useUserModel()? 

### ISSUE THREAD

**Issue by orkempire** [JosephSilber/bouncer#146]
I'm trying to understand where we would be able to utilize the three methods available with the Bouncer facade:
`useAbilityModel()`
`useRoleModel()`
`useUserModel()`

**Comment by cilsilver** [comment]
I think creating a basic tutorial will relief much issues.

**Comment by JosephSilber** [comment]
@orkempire those are used for when, for example, you want to use your own `Role` model:

```php
use Silber\Bouncer\Database\IsRole;

class Role extends Eloquent
{
    use IsRole;

    // Here you can put any custom methods...
}

Bouncer::useRoleModel(MyRole::class);
```

@cilsilver th elack of documentation is the reason Bouncer is still in beta. As I've explained [here](https://github.com/JosephSilber/bouncer/issues/43#issuecomment-257481556), the beta period will be spent fully fleshing out the documentation.

**Comment by orkempire** [comment]
@cilsilver thank you. Could you please add this to the documentation? I think that would enhance Bouncer's capability. Until now I never knew I could utilize this functionality.

**Comment by JosephSilber** [comment]
@orkempire I added a whole section to the docs on configuration. Here's the section discussing using your own custom models: https://github.com/JosephSilber/bouncer#custom-models
