### ISSUE TITLE
is it possible to add a where condition when assigning permission?

### ISSUE THREAD

**Issue by vesper8** [JosephSilber/bouncer#147]
I manage a hockey statistics website where coaches/players get to enter their team's/league's results so I have to do a lot of checking to make sure they can only view/edit teams that belong to certain leagues / regions.

Is it currently possible to do something like this?

```
Bouncer::allow($user)->toManage(Game::class)->whereIn('categoryId', [1, 2, 3])->whereIn('regionId', [2,3]);
```

**Comment by Jeroen-G** [comment]
Is the user in the particular category/region or is the game?

**Comment by vesper8** [comment]
The game is. The user signs up and requests privilege to administer games/teams in specific regions/categories.

**Comment by Jeroen-G** [comment]
Then you could allow it to manage `$game` instead, where `$game` has been queried with the constraints.

**Comment by vesper8** [comment]
But there might be 100s of games that a user would be allowed to manage because all those games belong to a regionId and a categoryId. Is it possible to use Bouncer to in this case without iterating over every game? There's also the case for games that don't exist yet, but that the user can only create for a certain regionId and certain categoryId

**Comment by JosephSilber** [comment]
Bouncer does not sore such constrains in the database.

You should use a policy in your code for this.
