### ISSUE TITLE
How to check if there are any users with a given ability?

### ISSUE THREAD

**Issue by hailwood** [JosephSilber/bouncer#149]
Basically as part of our seed we want to check if there are any users that can login as an admin.
This means they would have the 'admin.login' ability either directly or by being associated with a role that has the ability.

With the older version of bouncer it was easy because you could go `User::whereCan('admin.login')->exists()`

**Comment by JosephSilber** [comment]
If your needs are simple, you can add [this query scope](https://github.com/JosephSilber/bouncer/issues/126#issuecomment-246983616) to your model.
