### ISSUE TITLE
Ability to create Post::class error - v1.0.0-beta.1

### ISSUE THREAD

**Issue by Waguilar33** [JosephSilber/bouncer#150]
Just installed Bouncer on a new laravel project using the new v1.0.0-beta.1 release. I have created a Post migration, Post model and when I try to run the following command on tinker:

// Give a user the ability to create posts
`Bouncer::allow($user)->to('create', Post::class);`

error:
PHP error:  Class 'app\Supplier' not found in `C:\laragon\www\mighty\vendor\silber\bouncer\src\Conductors\Traits\AssociatesAbilities.php on line 113`

Am I missing something?

**Comment by JosephSilber** [comment]
Can you post the whole stack trace?

**Comment by Waguilar33** [comment]
I'm fairly new to Laravel and I dont really know where to get the stack trace... Also, I tried running
`\Bouncer::allow($user)->to('create', 'App\Supplier'); `

and everything worked.

**Comment by JosephSilber** [comment]
You can find the stack trace in `storage/logs`.

**Comment by Waguilar33** [comment]
I think I found my error. Following many laracast videos I change the namespace to "app" and then tried to run the 
`Bouncer::allow($user)->to('create', Post::class);`
and the error was looking for "app\Supplier" not "App\Supplier" so switch the namespace to App and everything works now

**Comment by Waguilar33** [comment]
I have tried to get the stack trace but nothing appears in `storage/logs`

**Comment by JosephSilber** [comment]
Closing because there's no way to debug this without more information.
