### ISSUE TITLE
Multi-domain support?

### ISSUE THREAD

**Issue by spacemeld** [JosephSilber/bouncer#151]
Can Bouncer be used with multiple domains? Bouncer seems to work with only one domain. I am hoping to define roles and abilities across multiple domains (organizational units) with a single set of users. Domains, on a high-level, functions as a grouping mechanism.

Users will be restricted accordingly to their assigned roles and abilities in each domain. However, all roles and abilities can be managed / viewed, grouped by domain.

I hope this makes sense.

**Comment by JosephSilber** [comment]
This is not currently possible.
