### ISSUE TITLE
How to get all users that don't have any roles?

### ISSUE THREAD

**Issue by alex996** [JosephSilber/bouncer#156]
I am trying to fetch _all_ users that do not have _any_ role associated with them. How can I achieve this in Bouncer? I tried `whereIs('')` and `whereIs(null)`, as well as custom `whereHas`, but neither seemed to work. The only way I can think of is checking `$user->roles->isEmpty()`.  However, is there a way to apply this constraint while fetching `User::whereIs($role)->with('roles')->get()`, so that the query remains generic for every case? Maybe apply a callback only when role is set to `""` or `null`?

Thank you.

**Comment by JosephSilber** [comment]
You can use Eloquent's `doesntHave` method:

```php
$users = User::doesntHave('roles')->get();
```

**Comment by alex996** [comment]
Fantastic, thanks!

**Comment by alex996** [comment]
Another thing is, how would you find all users who do not have a particular role, e.g. `'admin`', to get all non-admin users? I added a callback to `doesntHave` from the original answer:

```
User::doesntHave('roles', 'and', function($query) {
    $query->where('name', 'admin');
})->get();
```

Is this the best approach?
