### ISSUE TITLE
[v1.0.0-beta.2] Incomplete upgrade migrations

### ISSUE THREAD

**Issue by michaeldyrynda** [JosephSilber/bouncer#157]
I'm not sure how best to target a PR, so I've opened an issue to track difficulties I had with upgrading 0.1.x to the latest 1.0.0 beta as we're migrating to Laravel 5.3. Note, some of these are likely missing from earlier alpha/beta tags, but there's probably not much point retrospectively adding them now.

*abilities* 

* `$table->boolean('only_owned')->default(false);`
* `$table->string('title')->nullable()->after('name');`

*roles*

* `$table->string('title')->nullable()->after('name');`
* `$table->integer('level')->unsigned()->nullable()->after('title');`

**Comment by michaeldyrynda** [comment]
In addition, the `create_bouncer_roles` migration - from the previous install - will create a `roles_abilities` table and as part of its `down` method, will drop it. The upgrade migration will also drop this table, so when the migration is being rolled back as part of a `DatabaseMigrations` trait in a test, it barfs.

Any suggestions for best way of handling this (removing the drop statement perhaps?) would be great.

**Comment by JosephSilber** [comment]
I added [these 4 columns](https://github.com/JosephSilber/bouncer/blob/9b290aa5ccdc872e9387bd46d2df5c09e0403dac/migrations/upgrade_to_bouncer_1_dot_0.php#L55-L66).

As for the `down` migrations: read [the comment](https://github.com/JosephSilber/bouncer/blob/9b290aa5ccdc872e9387bd46d2df5c09e0403dac/migrations/upgrade_to_bouncer_1_dot_0.php#L196-L206) in the upgrade migration.

**Comment by michaeldyrynda** [comment]
That addition worked perfectly, thanks!

I was referring the the down migrations from 0.1.7 - https://github.com/JosephSilber/bouncer/blob/v0.1.7/migrations/create_bouncer_tables.php#L80-L84 - because I have that in my migrations, when the rollback occurs during testing, it gets upset.

**Comment by JosephSilber** [comment]
Like it says in the comment in the `down` method of the upgrade migration: if you want the ability to roll back, you should delete both migration files and republish the main one.

**Comment by michaeldyrynda** [comment]
Not enough sleep, reading it now on a full site and everything is clear. Thanks!
