### ISSUE TITLE
Non-static method is() Execption

### ISSUE THREAD

**Issue by JimLfe** [JosephSilber/bouncer#16]
I have a basic Problem with checking if a user has a role:

If I do it in routes.php it works:
```PHP
        $user = User::find(3);
        Bouncer::is($user)->a('admin');
```

If i do it in the CompanyController, I get this Error:
--------------
>at HandleExceptions->handleError('8192', 'Non-static method Silber\Bouncer\Bouncer::is() should not be called statically, assuming $this from incompatible context', '/home/vagrant/Code/torebuild1/app/Http/Controllers/CompanyController.php', '112', array('id' => '3', 'user' => object(User))) in CompanyController.php line 112
---------------

Is there a Issue or am I doing something completely wrong?

**Comment by JosephSilber** [comment]
All examples in the docs use the facade. If you've set up the facade alias, you should be able to use the examples in the docs directly. Do not `use Silber\Bouncer\Bouncer`.

If you don't want to use the facade, inject an instance if Bouncer into your controller:

```php
public function foo(Bouncer $bouncer)
{
    $bouncer->is($user)->an('admin');
}
```

If you go down this path, *do* `use Silber\Bouncer\Bouncer`.

**Comment by JimLfe** [comment]
Hmm I did set the facade alias.. so it should work like I do it?

**Comment by JimLfe** [comment]
If I take the use Silber\Bouncer\Bouncer out of the Controller then I have the Error:
>Class 'App\Http\Controllers\Bouncer' not found

But I did follow the Installation Instructions, means: I did add the Lines to the providers and to the aliases array in config/app.php.

**Comment by JosephSilber** [comment]
Add this instead:

```
use Bouncer;
```

This'll import the global facade alias.

**Comment by JimLfe** [comment]
Ah great, thank you very much.. Now it works.. 

I've been searching for hours about this issue..
