### ISSUE TITLE
Syncing abilities for a role

### ISSUE THREAD

**Issue by Jeroen-G** [JosephSilber/bouncer#162]
Currently this is failing:
```php
Bouncer::allow('editor')->to(['create', 'update'], Post::class);
```
Obviously, there are more than two abilities for managing posts, thus `*` won't cover this case. I could of course use two statements, but that will lead to two runs of the Bouncer class including database calls.

If this is something that you agree would be an added benefit, I'd be happy to help contribute.

**Comment by JosephSilber** [comment]
> I could of course use two statements, but that will lead to two runs of the Bouncer class including database calls.

How often do you do this that you're so concerned?

> If this is something that you agree would be an added benefit, I'd be happy to help contribute.

Adding this would mean it has be added to `allow`, `disallow`, `forbid` & `unforbid`. It would also have to work with collections and with actual ability models.

For consistency, we would also have to allow passing multiple roles to `assign` and `retract`.

Finally, we'd also have to make sure the `HasRoles` and `HasAbilities` trait supports these.

Given that this is quite a bit of work (and I don't think it's really necessary), I have not implemented it.

If you feel its important and are willing to send a proper PR, I'd definitely take a look.
