### ISSUE TITLE
Cant Get the Correct Response From is method

### ISSUE THREAD

**Issue by g0ld3lux** [JosephSilber/bouncer#163]
I have a Role Middleware where i can pass all the roles i want, by default it will use
this method
\Bouncer::is($user)->a($roles);
But if i pass the strict action in routes as true
```
Route::group([
    'middleware' => ['roles'],
    // We can Easily Add Roles in the Middleware
    'roles' => ['admin', 'manager'],
    'prefix' => 'admin',
    'strict' => true, // All Roles Must be Present to be True (optional)
], function() {
```
then i would trigger this bouncer method
\Bouncer::is($user)->all($roles);

The Problem is , The $roles variable,

if i tried passing in array it wont work,

so i tried to implode the roles to return it as a string
```
$roles = $request->route()->getAction()['roles'];

        return isset($roles) ? "'".implode("','",$roles)."'" : null;
```

if i do die and dump that roles ill get this

```
"'admin',' 'manager'"
```

but i should be getting true, and not false if i run the this method 

\Bouncer::is($user)->all($roles);

Since i gave the user an admin role...

Can you adjust the code to allowed to accept arrays and not string for the is All method.?

**Comment by JosephSilber** [comment]
If you want to check an array of roles, spread it into the method:

```php
Bouncer::is($user)->all(...$roles);
```

Two side notes:

1. You're probably looking for the `a` method, not `all`. You want o check if the user has _any_ of the roles, not _all_ of the roles.
2. Checking for roles directly is considered an anti-pattern (that's why Bouncer doesn't ship with such a middleware). It is always better to create a broad ability that encomapsses what you're trying to do, and check for that. Here's a quite from [the docs](https://github.com/JosephSilber/bouncer#checking-a-users-roles):

    > Generally speaking, you should not have a need to check roles directly. It is better to allow a role certain abilities, then check for those abilities instead. If what you need is very general, you can create very broad abilities. For example, an `access-dashboard` ability is always better than checking for `admin` or `editor` roles directly.

**Comment by masterpowers** [comment]
Im actually looking for all method...
coz i have 2 options in my route middleware...
checking role non strict = meaning if the user has at least one of the roles then he can pass
strict mode = all roles must be present to a user for him to pass the route middleware


I tried your suggestion but still i cannot get a true , i always get false

```
factory(User::class,10)->create()
$user = User::find(1)
\Bouncer::assign('admin')->to($user);
 \Bouncer::assign('manager')->to($user);
$roles = ['admin', 'manager']
\Bouncer::is($user)->all(...$roles);
// returns false
```

**Comment by JosephSilber** [comment]
That example you just showed me there actually does work. I just tested it.

Are you sure your `$user` is not `null`?

**Comment by masterpowers** [comment]
The user might be cache, or the roles hasnt been assign or refresh, 
but when i did restart insance of tinker it works , thanks... 

Now my middleware works so Easy :)
💯

**Comment by masterpowers** [comment]
I can make a pull request for this one

**Comment by JosephSilber** [comment]
Laravel already ships with a middleware for abilities.

Bouncer intentionally does NOT ship with a middleware for checking roles. Like I said before, checking for roles directly is an anti-pattern.
