### ISSUE TITLE
Overriding the toOwn Method

### ISSUE THREAD

**Issue by Chrissi2812** [JosephSilber/bouncer#165]
I am using **mpociot/teamwork** and my models are assigend to the teams instead of users.

## team table
<table>
<tr><th>id</th><th>owner_id</th><th>name</th></tr>
<tr><td>1</td><td>1</td><td>team 1</td></tr>
<tr><td>2</td><td>2</td><td>team 2</td></tr>
</table>

## article table
<table>
<tr><th>id</th><th>user_id</th><th>title</th><th>content</th><th>published</th><th>team_id</th></tr>
<tr><td>1</td><td>3</td><td>article 1</td><td>dwadwa</td><td>1</td><td>1</td></tr>
<tr><td>2</td><td>2</td><td>article 2</td><td>dwadwa</td><td>1</td><td>2</td></tr>
<tr><td>3</td><td>1</td><td>article 3</td><td>dwadwa</td><td>1</td><td>1</td></tr>
</table>

_ps. the user_id is only the creator of the article_

## user table
<table>
<tr><th>id</th><th>name</th><th>email</th><th>current_team_id</th></tr>
<tr><td>1</td><td>user 1</td><td>user1@example.org</td><td>1</td></tr>
<tr><td>2</td><td>user 2</td><td>user2@example.org</td><td>2</td></tr>
<tr><td>3</td><td>user 3</td><td>user3@example.org</td><td>1</td></tr>
</table>

____
what i want to achive:

- **User 1** and **User 3** can edit **article 1** and **article 3** because the belong to **team 1**
- **Only User 2** can edit **article 2** because he belongs to **team 2**

___
# What i tried:

## try 1: In ``AppServiceProvider::boot``
The useres have a bouncer permisson to manage their Articles. (only_owned = 1)
```php
Bouncer::ownedVia(Team::class, 'team_id');
```

## try 2:  In ArticlePolicy:
The useres have a bouncer permisson to manage the Articles. (only_owned = 0)
```php
class ArticlePolicy
{
    use HandlesAuthorization;

    public function update(User $user, Article $article)
    {
        return $user->can('update') && $user->current_team_id == $article->team_id;
    }
}
```
But this never gets called..

the ArticlesController uses this code to check the auth:
```php
class Articles extends Controller
{

    public function __construct()
    {
        $this->authorizeResource(Article::class);
    }
}
```

**Comment by JosephSilber** [comment]
Number one, thanks for so clearly articulating your situation and your needs. One can but wish that everyone be as considerate as you :heart: 

---

As to your question: the `ownedVia` method can actually take a closure, where you can assign your own login for ownership determination:

```php
Bouncer::ownedVia(Article::class, function ($article, $user) {
    return $user->current_team_id == $article->team_id;
});
```

The first argument is the type of model that you're defining the ownership logic for, not the model through which the article will be owned.

---

I know all of this would have been much easier for you to figure out if this had proper documentation. I'm truly sorry that I didn't get around to it yet. Documentation is actually the only reason Bouncer is still in beta :disappointed:

**Comment by Chrissi2812** [comment]
Thank you very much for your time to help me 👍

For others having the same problem as me here is the code i have used in my Controller.
```php
namespace App\Http\Controllers;

/* Include Bouncer Facade */
use Bouncer;

class Articles extends Controller
{
    public function __construct()
    {
        /* This is the Code that changes the check to the team_id */
        Bouncer::ownedVia(Article::class, function ($model, $user) {
            return $user->current_team_id == $model->team_id;
        });

        /* And finally authoirze the [view, create, delete, update]-Methods */
        $this->authorizeResource(Article::class);
    }
}
```

**Comment by JosephSilber** [comment]
I would put the ownedVia call in a service provider.

**Comment by JosephSilber** [comment]
Ownership configuration has now been fully documented: https://github.com/JosephSilber/bouncer#ownership
