### ISSUE TITLE
What exactly mean toOwn?

### ISSUE THREAD

**Issue by UksusoFF** [JosephSilber/bouncer#170]
Hi! Thanks for great job!

But I little confused what exactly mean toOwn? It's for allow/disallow interact with models created by user or not?

How I can allow all users with 'admin' role edit all Post and users with role 'editor' edit only own Posts?

```
Bouncer::allow('admin')->to('edit', Post::class);
Bouncer::allow('editor')->toOwn(Post::class, ['edit']); //throws InvalidArgumentException
```

**Comment by JosephSilber** [comment]
The `toOwn` method currently only works for allowing all abilities on a model:

```php
Bouncer::allow('editor')->toOwn(Post::class); // user can create + view + edit +delete etc.
```

For now, allowing only a given ability has to be specified manually:

```php
Bouncer::allow('editor')->to('edit', Post::class, ['only_owned' => true]);
```
