### ISSUE TITLE
what if code doesn't know if role name starts with vowel 

### ISSUE THREAD

**Issue by luckyali55** [JosephSilber/bouncer#172]
I need to pass role name variable like: 
1.
```
$role = 'admin';  
if($user->isAn($role))

```
2)
```
$role = 'subscriber';  
if($user->isA($role))

```

Bouncer shouldn't have a function  $user->is($role)?

**Comment by JosephSilber** [comment]
@luckyali55 This method used to be called `is`. But [then Eloquent added an `is` method](https://github.com/laravel/framework/blob/1728a887e450f997a0dcde2ef84be2947b05af42/src/Illuminate/Database/Eloquent/Model.php#L968-L973) (that does something else), so it clashed.

We [had to change it to `isA` and `isAn`](https://github.com/JosephSilber/bouncer/commit/145bf653015ce6ba1a9c42999805158ef7c4cc40).

**Comment by luckyali55** [comment]
yes, i saw that is method too. so then i created my `actAs ` method which checks for vowel and use the appropriate method. 
so i am closing this. 
Thanks.
