### ISSUE TITLE
Can't supply array of permissions to function 'to' if a model is also supplied to the function

### ISSUE THREAD

**Issue by rhoitink** [JosephSilber/bouncer#173]
**This works:**
```php
<?php
Bouncer::allow('admin')->to('create', Post::class);
Bouncer::allow('admin')->to('edit', Post::class);
Bouncer::allow('admin')->to('update', Post::class);
Bouncer::allow('admin')->to('delete', Post::class);
```
**But this doesn't:**
```php
<?php
Bouncer::allow('admin')->to(['create', 'read', 'update', 'delete'], Post::class);
```

If you try the second block of code, you'll get the following error:
<pre>
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given, called in /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 681
</pre>
As far as I can see, this is caused by the fact that the function `getModelAbility` in the trait `AssociatesAbilities`  ([this file](https://github.com/JosephSilber/bouncer/blob/v1.0.0-beta.2/src/Conductors/Concerns/AssociatesAbilities.php#L49-L64)) doesn't handle arrays properly.

**Used versions:**
Laravel: v5.4.21
Bouncer: v1.0.0-beta.2

**Comment by JosephSilber** [comment]
Closing this, as this works in the current master branch.
