### ISSUE TITLE
User model in different namespace

### ISSUE THREAD

**Issue by eComEvo** [JosephSilber/bouncer#174]
It seems Bouncer includes the `App\User` class in several places statically. How do we get around instances where a project requires the User class to be located in a different namespace?

Ex: App\Models\User

**Comment by JosephSilber** [comment]
Bouncer will use whatever you've defined [in your auth config](https://github.com/laravel/laravel/blob/d09efa26d2b0ed4a2bc9a48df5439d213ad6c052/config/auth.php#L70).
