### ISSUE TITLE
Custom ownership determination

### ISSUE THREAD

**Issue by jl9404** [JosephSilber/bouncer#176]
In the scenario, there is a shop which has many stores in different locations.
How to do with Bouncer, which allows manager to mange all the stores and operator only can access few of stores?

```php
$company = Company::find(1);
$manager = User::find(1);
$operator = User::find(2);
$company->stores->each(function ($store) use ($manager) {
    Bouncer::allow($manager)->toManage($store);
});
Bouncer::allow($operator)->to('view', $company->stores->first());
```

When there are more stores created, how can i make sure that the manager can manage the store?

**Comment by JosephSilber** [comment]
It seems your want to allow the manager to own stores:

```php
Bouncer::allow($manager)->toOwn(Store::class);
```

By default, ownership is determined via a `user_id` column on the `stores` table. This can be customized to instead look up the ownership through the store's company.

Does the company have a `user_id` or `manager_id` column? Or does the user have a `company_id` column? How do you know which company a manager belongs to?

**Comment by jl9404** [comment]
Thank you for your reply.

There is a `company_id` column in the user table to identify which company that user belongs to. 

For the customization of the owner key, do you mean `Models::ownedVia()` method?
```php
use Silber\Bouncer\Database\Models;
Models::ownedVia(Store::class, function ($model, $authority) {
    // Store's company_id compares with User's company_id
    return $authority->isA('manager') && $model->company->id === $authority->company_id;
});
```
For those managers which can only access limited stores, I just need to directly give them access to the stores via `Bouncer::allow(..)->toManage($store)` ?

**Comment by JosephSilber** [comment]
The `ownedVia` lets you specify how ownership is determined:

```php
Bouncer::ownedVia(Store::class, function ($store, $user) {
    $store->company->id === $user->company_id;
});
```

Once you have that in place, you can add ownership permissions to a user:

```php
Bouncer::allow($manager)->toOwn(Store::class);
```

If you want to separately allow certain managers to manage stores on a one-off basis, you can give them the ability to manage a store directly:

```php
Bouncer::allow($manager)->toManage($store);
```

**Comment by jl9404** [comment]
Thank you for your reply.
do you suggest using Policy with Bouncer + authorizeResource() in controller?

**Comment by JosephSilber** [comment]
I don't understand the question. You should definitely be using `authorizeResource`. but from what we've discussed above, you don't need a policy!?

**Comment by hugeps** [comment]
ownedVia is not a static method ?
