### ISSUE TITLE
Can't install on dev 5.5

### ISSUE THREAD

**Issue by autaut03** [JosephSilber/bouncer#179]
I've installed a brand new Laravel dev 5.5 and can't install bouncer.

Please allow to use dev versions in yours composer config.

Thanks.

**Comment by rjvandoesburg** [comment]
see https://github.com/JosephSilber/bouncer/pull/178
The author has said he won't do it until later. If you want to use it now, fork the repository and update the composer.json file to your desired versions.

However, it is not guaranteed it will work

**Comment by autaut03** [comment]
Okay, it's almost fine. Thanks.
