### ISSUE TITLE
Version 1 Release?

### ISSUE THREAD

**Issue by jesephan** [JosephSilber/bouncer#180]
Hi,

I would like to know what will be the road map about the final version 1 release of this package? We will be using this with our upcoming project :)
By the way I'm so happy i found this package. The syntax is awesome so fluent :)

Cheers!

**Comment by JosephSilber** [comment]
At this point, documentation is basically the only thing that's not complete. As soon as that's done, I'll be releasing version 1.0.

I wish I could've gotten this done sooner, but these last few months I've been extremely busy. Hopefully the summer will bring a little more spare time so I can finish this up.

I'm closing this issue, as we already have #43 tracking the progress of the 1.0 release.
