### ISSUE TITLE
role abilities removal

### ISSUE THREAD

**Issue by jesephan** [JosephSilber/bouncer#181]
Hi,

I would like to know if  there is a feature to remove all abilities of a role like
 **Bouncer::disallow('merchant')->everything();**
I check the documentation and also the source code It seems this type of feature is not available? 

Thanks

**Comment by JosephSilber** [comment]
To temporarily forbid all abilities to a given role, you can use the `forbid` method:

```php
Bouncer::forbid('merchant')->everything();
```

If you actually want to completely remove the abilities from the database, you can delete all of the role's abilities using Eloquent directly:

```php
Bouncer::role()->where('name', 'merchant')->abilities()->delete();
```

**Comment by jesephan** [comment]
Great that works. thank you

**Comment by vanessasoutoc** [comment]
Hi, how to checked if role forbid?

Thanks

**Comment by jesephan** [comment]
I think you need to elaborate further what you are trying to accomplish here. What do you mean if role forbid?

**Comment by vanessasoutoc** [comment]
@JosephSilber 

I need to check if the ability of role is forbid, it's true in the view button toogle.

**Comment by JosephSilber** [comment]
Now that [we have syncing in place](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.4), you can remove all abilities from a role by simply syncing an empty list of abilities to the role:

```php
Bouncer::sync('merchant')->abilities([]);
```

**Comment by garygreen** [comment]
You can also do this, right?

```php
Bouncer::disallow($role->name)->to($ability->name);
```

**Comment by garygreen** [comment]
Hmm, whenever I do that I weirdly get another "simple abilities" appear:

![image](https://user-images.githubusercontent.com/1702638/35933974-18ab1688-0c34-11e8-9ecb-a388234b5099.png)

**Comment by JosephSilber** [comment]
@garygreen yes. In fact, you can pass the models directly. No need to pass the `name` property explicitly.

**Comment by JosephSilber** [comment]
@jonathanoh1 like I said before, you can sync an empty list of abilities:

```php
Bouncer::sync('merchant')->abilities([]);
```

**Comment by jonathanoh1** [comment]
Use $role->abilities()->detach() and it works correctly, but I do not know if it's the best option
