### ISSUE TITLE
entity_type not fillable

### ISSUE THREAD

**Issue by appdezign** [JosephSilber/bouncer#182]
I'm creating admin panels (crud) for users, roles, and abilities. But when I'm trying to create a new ability, it seems that I cannot save the entity_type column. I checked the Ability model:

`protected $fillable = ['name', 'title'];`

So, apparently the entity_type column is not fillable.

I know that abilities are created automatically when you assign it to a user or a role, but does that mean that the only way to create a new ability is to assign it to a user or a role? That doesn't seem very practical.

For now, I have created a workaround: I'm using an extra model that extends the Ability model and the only thing this model does is that it overrides the $fillable variable.

Can anyone tell if I'm missing something here?

**Comment by JosephSilber** [comment]
Having the `entity_type` be fillable by default might lead to unexpected data being saved into it.

If you're sure your data is correct, you can use `forceCreate`:

```php
Bouncer::ability()->forceCreate([
    'entity_type' => '...',
]);
```

**Comment by appdezign** [comment]
Ah, great. That's exactly what I need.
Great package, by the way.
