### ISSUE TITLE
What is "Owning" a model?

### ISSUE THREAD

**Issue by hailwood** [JosephSilber/bouncer#183]
I notice there are methods relating to "owning" a model e.g.

```php
Bouncer::allow($user)->toOwn(Post::class);
```

So what effect does owning actually have?

I notice that the code basically evaluates to the line below, but what's the usecase of the `only_owned` attribute?

```php
Bouncer::allow($user)->to('*', Post::class, ['only_owned' => true]);
```

--
Matt

**Comment by JosephSilber** [comment]
toOwn has unfortunately not been fully documented yet.

In the meantime, take a look at this thread: https://twitter.com/joseph_silber/status/887507355092602880

If it's still not clear, feel free to ask.

**Comment by hailwood** [comment]
Hey @JosephSilber thanks for the reply.

So it's purpose makes sense to me; But I'm wondering about how you would do from a code sense as it seems to fill the void I normally use policies for - the methods normally look somethingl like this


```php
Bouncer::allow('customer')->toManage(Order::class);
```

```php
class OrdersPolicy
{
    use HandlesAuthorization;

   // And all the others... you get the idea...
    public function view(User $user, Order $order) 
    {
        return $order->customer_id === $user->id;
    }
}
```

so it looks like I might be able to just do the below is that correct?

```php
Bouncer::allow('customer')->toOwn(Order::class);
```

Given that assumption I have a couple of questions (ideally answering this will help you with documentation as well)

* How does it work out the user column? In the example above you can see my column is called `customer_id` - can we override the column somehow?
* How does it work with create? Do we need to also specify `Bouncer::allow('customer')->to('create', Order::class);`?

Cheers

**Comment by JosephSilber** [comment]
1. Bouncer allows you to set the attribute by which users are owned:

    ```php
    Bouncer::ownedVia('customer_id');
    ```

    Stick that into a service provider, and Bouncer will know to use the `customer_id` attribute to determine ownership.

2. Yes. Since creation doesn't deal with a single model, there's no sense of ownership. You either do or do not allow it.

**Comment by hailwood** [comment]
Ah and I see you can do `\Bouncer::ownedVia(Order::class, 'customer_id')` if it's for a specific model. Fantastic :)

**Comment by JosephSilber** [comment]
Correct. If you have different attribute names on different models, you can set them separately.

**Comment by hailwood** [comment]
Ok we can likely close this issue now, unless you wish to rename it to "document model ownership"?

**Comment by JosephSilber** [comment]
Ownership has no been documented [here](https://github.com/JosephSilber/bouncer#allowing-a-user-or-role-to-own-a-model).

Ownership configuration is documented [here](https://github.com/JosephSilber/bouncer#ownership).

**Comment by hailwood** [comment]
Oh neat trick, I didn't know you could follow up a "toOwn" with a "to" call.

I wonder if it's worth adding "ifOwns" as an alias of "toOwn" so it could read as

`Bouncer::allow('something')->ifOwns(Post::class)->to(['view']);`

Completely pedantic I know, but I like the way it reads.
