### ISSUE TITLE
Abilities Category

### ISSUE THREAD

**Issue by valluminarias** [JosephSilber/bouncer#186]
How can we categorize abilities to group it other than roles?

**Comment by JosephSilber** [comment]
Care to explain a little more? Why and how do you want to group them?

**Comment by valluminarias** [comment]
I wanted to create a page where we can just check or in multiple type select box. Like for example assigning abilities to roles, but what I want is the abilities grouped according to pages or any entities.
For example.
[Group Student]:
    Abilities: View, Create, Delete, Update
[Enrollment Page]
   Abilities: Enroll, Revoke, View

I hope it clearly explain my point.

**Comment by JosephSilber** [comment]
You can modify the database however you want, and add you own columns to the `abilities` table.
