### ISSUE TITLE
Sync user abilities

### ISSUE THREAD

**Issue by jesephan** [JosephSilber/bouncer#190]
Hi, 

How do you sync a user abilities during update? Currently what i'm doing when the admin add/remove abilities is i loop over all abilities and disallow a user then after the loop i do `Bouncer::allow($user)->to($newAbilities)` which actually works but I'm hoping there is a good api for syncing a abilities something like `Bouncer::sync($newAbilities)->to($user);`

 Thanks

**Comment by faabsen** [comment]
Hey, 
I think its already described here #85. You could easily do this:
`$user->abilities()->sync([1,2,3,4]);`
Should be an build in feature of Laravel already. Please correct me, if I am mistaken.

**Comment by jesephan** [comment]
Hello,

@faabsen `$user->abilities()->sync($newAbilities);` doesn't seem to work it results in a query exception **SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'admin' for column 'ability_id'**

**Comment by jesephan** [comment]
@faabsen this requires me to get all the ID's of the abilities and requires to possibly create and get the IDs of new abilities. Sounds like not a good way for me.

**Comment by jesephan** [comment]
related to #197

**Comment by JosephSilber** [comment]
This just in: https://github.com/JosephSilber/bouncer/commit/cc7389378af57765c9f1fd13f7b66b4d08639ece

```
Bouncer::sync($user)->abilities([1, 2, 3]);

// Also works with simple ability name
Bouncer::sync($user)->abilities(['access-dashboard', 'ban-users']);

// As well as with actual ability models:
Bouncer::sync($user)->abilities($collectionOfAbilityModels);

// Also supports syncing roles:
Bouncer::sync($user)->roles(['admin', 'reviewer']);

// Also supports role IDs and role models, like abilities above.
```

I'll be tagging a new release today or tomorrow.

**Comment by jesephan** [comment]
wohooo thank you! Hope to see this in the Readme file to avoid other from opening PR related to this. Once again thank you @JosephSilber :100:
