### ISSUE TITLE
Error - HasRolesAndAbilities::isNot($role) in Laravel v5.4.32

### ISSUE THREAD

**Issue by shawnsandy** [JosephSilber/bouncer#191]
Update to laravel 5.4.32 and got this error

``` php
Declaration of Silber\Bouncer\Database\HasRolesAndAbilities::isNot($role) should be compatible with Illuminate\Database\Eloquent\Model::isNot(Illuminate\Database\Eloquent\Model $model)
```

How can I solve this issue
Appreciate the help

**Comment by ecodrutz** [comment]
This has been fixed with commit 
https://github.com/JosephSilber/bouncer/commit/fb1e4ea3229e75e565ab869aade2ad6e09bc331c
Make sure you have the latest build of the library

**Comment by jesephan** [comment]
I have this issue and got resolved by installing the latest release :)

**Comment by shawnsandy** [comment]
Update solved, I had to manually update it the version in composer file `"silber/bouncer": "v1.0.0-beta.3"` 

Thanks for the help guys
