### ISSUE TITLE
Abilities for guest user

### ISSUE THREAD

**Issue by UksusoFF** [JosephSilber/bouncer#192]
Is there any way to add abilities to guest user?

**Comment by JosephSilber** [comment]
Bouncer uses Laravel's Gate, which doesn't support permissions for guest users.

There has been some discussion on the Laravel side to add such support, but nothing has come of it yet.

**Comment by UksusoFF** [comment]
Just for reference:
https://github.com/laravel/framework/issues/10568
https://github.com/laravel/framework/pull/16239

**Comment by UksusoFF** [comment]
@JosephSilber maybe in 5.7? Looks like this is iplemented: [Guest User Gates / Policies
](https://laravel.com/docs/5.7/releases#laravel-5.7).
