### ISSUE TITLE
Incompatible issues

### ISSUE THREAD

**Issue by webrevllc** [JosephSilber/bouncer#194]
I just did composer update and now I am getting: 

Declaration of Silber\Bouncer\Database\HasRolesAndAbilities::isNot($role) should be compatible with Illuminate\Database\Eloquent\Model::isNot(Illuminate\Database\Eloquent\Model $model)

Laravel 5.4.*
Bouncer 1.0.0-beta.2

**Comment by JosephSilber** [comment]
Laravel 5.4.31 is incompatible with Bouncer 1.0.0-beta.2.

To use Bouncer with that version of Laravel, upgrade Bouncer to version 1.0.0-beta.3
