### ISSUE TITLE
is it possible to assign roles for a user to a specific model instance

### ISSUE THREAD

**Issue by Kane-One** [JosephSilber/bouncer#195]
something like `$user->assign('admin', $post);`
is it possible?

**Comment by JosephSilber** [comment]
What's the end-goal? Do you want the user to be able to manage everything about that post?

Then the `toManage` method is your friend:

```php
Bouncer::allow($user)->toManage($post);
```

Or, if you prefer doing it directly on the user object:

```php
$user->allow()->toManage($post);
```

**Comment by Kane-One** [comment]
thanks. but is there a simple way to allow a group of uses to edit a specific post. these users play editors to the post, while they might play other roles to other posts.

**Comment by JosephSilber** [comment]
@Kane-One I don't understand the question.

**Comment by dhcmega** [comment]
@Kane-One I get the idea and I think it's very interesting.
I don't think you should use a role to manage a specific model instance. You may up having 100s of roles with many relations between roles, users and model instances.

I think a solution in this case scenario would be to loop over all the users that should be able to manage a model instance and assign abilities to them all. You are most likely trying to avoid this I guess.

Any ways, it doesn't sound bad to have something like:
"all this users has AccountAManager role, which will be granted abilities over all this AccountA posts."

@JosephSilber The restriction is that you can add abilities over a Model class or a model instance, BUT you cannot over a group of model instances.

**Comment by JosephSilber** [comment]
@dhcmega how would that group be determined?

**Comment by dhcmega** [comment]
If a user creates an instance, all the other users within the same group, should be able to manage that instance.

I think the only way now would be to get all the other users from the user group and give them edit ability over the $post, so all the users have edit ability over the $post the user creates.

The idea would be not to have to do this:

```
foreach($users as $user) {
    Bouncer::allow($user)->to('edit', $post);
}
```

**Comment by JosephSilber** [comment]
> If a user creates an instance, all the other users within the same group, should be able to manage that instance.

That's what ownership is for. Assuming you have a `group_id` on both your `users` table and your `posts` table, you can do something like this:

```php
Bouncer::allow('some-role')->toOwn(Post::class);
```

Then, in some service provider, set up the ownership relationship:

```php
Bouncer:: ownedVia(Post::class, function ($post, $user) {
    return $user->group_id == $post->group_id;
});
```

**Comment by dhcmega** [comment]
excellent! That's not in the read me though.
Solves my problem. Thanks!

**Comment by JosephSilber** [comment]
@dhcmega BTW, that loop there could be rewritten much more tersely with hugher order `each`:

```php
$users->each->allow()->to('edit', $post);
```

That's still a bunch of DB operations, but reads much better 👍

**Comment by dhcmega** [comment]
way much better, agreed! thanks again.
