### ISSUE TITLE
Custom gate rules result in Clipboard.php error

### ISSUE THREAD

**Issue by pr4xx** [JosephSilber/bouncer#196]
Hey there, I try to create some custom gate rules where I "mix" some bouncer abilities. But as soon as I want a second parameter inside my gate rule, bouncer seem to intefere with the define method.
```
Gate::define('test', function ($user, $test) {
      dd($test);
      return false;
});
```
If i call this gate rule with `auth()->user()->can('test', 'test')` I get this error:
```
(1/1) FatalThrowableErrorClass 'test' not found
--
in Clipboard.php (line 203)
at Clipboard->compileModelAbilityIdentifiers('test', 'test')in Clipboard.php (line 187)

```

**Comment by JosephSilber** [comment]
What's the real-world definition? Laravel's Gate (and Bouncer) are designed to have the second parameter be either a model or or a model class name.

**Comment by pr4xx** [comment]
Oh I thought I can pass anything I want. What is the reason to use the string as a class name for? What is the use case? Is there no way to provide a parameter like an array or number?
