### ISSUE TITLE
Possible issue with associative arrays and Bouncer::allow() / Bouncer::disallow()

### ISSUE THREAD

**Issue by jonagoldman** [JosephSilber/bouncer#197]
I am using ```array_diff``` to get 'removed' and 'added' abilities, like this:

```php
$currentAbilities = ['my-ability-name', 'other-ability-name'];
$newAbilities= ['new-ability-name', 'other-ability-name']

$removed = array_diff($currentAbilities, $newAbilities);
$added = array_diff($newAbilities, $currentAbilities);
```

but when I try this:
```php
Bouncer::disallow($item->name)->to($removed);
Bouncer::allow($item->name)->to($added);
```
I get an error:

```
(1/1) FatalThrowableErrorClass 'my-ability-name' not found
--
in FindsAndCreatesAbilities.php (line 141)
at GivesAbilities->getEntityInstance('my-ability-name')in FindsAndCreatesAbilities.php (line 87)
at GivesAbilities->getModelAbility(4, 'my-ability-name',array())in FindsAndCreatesAbilities.php (line 72)
at GivesAbilities->Silber\Bouncer\Conductors\Concerns\{closure}('my-ability-name', 0)
at array_map(object(Closure), array('my-ability-name'),array(0))in Collection.php (line 767)
at Collection->map(object(Closure))in FindsAndCreatesAbilities.php (line 73)

// ... more
```

I found out this is because ```array_diff``` returns an associative array, and ```getAbilityIds``` in ```Silber\Bouncer\Conductors\Concerns\FindsAndCreatesAbilities```
checks if the passed array is associative in ```Helpers::isAssociativeArray($abilities)```

A workaround is to use ```array_values```, like this:
```php
Bouncer::disallow($item->name)->to(array_values($removed));
Bouncer::allow($item->name)->to(array_values($added));
```

I wanted to point it out in case someone else has the same problem, maybe add a note about this to the docs?

**Comment by jesephan** [comment]
@jonagoldman I believe this is the same issue with the one i [posted ](https://github.com/JosephSilber/bouncer/issues/190)

**Comment by jonagoldman** [comment]
@jesephan it is similar but not the same, #190 is about making it easier for the developer to sync abilities, this issue is about a FatalError beign thrown.
