### ISSUE TITLE
Checking by model

### ISSUE THREAD

**Issue by adifaidz** [JosephSilber/bouncer#198]
Lets say that I use these,

```php
Bouncer::allow($user)->to('edit', Post::class);
Bouncer::allow($user)->to('edit', $post);
```
How can I check if the user can edit all or just that one post using this package? I'm quite confused because there isn't any documentation that says so. I could only find allow and disallow. 

I'm sorry if there is but I missed them

**Comment by Jeroen-G** [comment]
That's because Bouncer sort of extends Laravel's native authorization.
https://laravel.com/docs/5.4/authorization#authorizing-actions-using-policies

**Comment by adifaidz** [comment]
Okay, now its clear. 😆 Thanks, Im closing this
