### ISSUE TITLE
Seeding with DatabaseSeeder

### ISSUE THREAD

**Issue by yahyaerturan** [JosephSilber/bouncer#20]
First thing is first: Great work, thank you.

I am trying to seed the database with my global seeder. Here is my setup:
```php
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $this->call(UsersTableSeeder::class);
        $this->call(WorksTableSeeder::class);
        $this->call(BouncerTableSeeder::class);

        Model::reguard();
    }
}
```
Here is `BouncerTableSeeder.php':
```php
use Illuminate\Database\Seeder;
use Silber\Bouncer;

class BouncerTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Bouncer::seeder(function () {
            Bouncer::allow('admin')->to(['ban-users', 'delete-posts']);
            Bouncer::allow('editor')->to('delete-posts');
        });
    }
}
```

I am doing this because I am mostly using the following command in development.
```
php artisan migrate:refresh --seed
```

However it throws error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Silber\Bouncer' not found 
```

If I use `use Bouncer;` it throws error:
```
[ErrorException]                                                  
  The use statement with non-compound name 'Bouncer' has no effect 
```

How should it be? Thanks.

**Comment by JosephSilber** [comment]
Seeder classes don't exist in a namespace, so you don't have to import anything.

Skip the `use` statement entirely.

**Comment by yahyaerturan** [comment]
I am flushed, I tried too many possibilities except skipping it. It works like a charm, thank you.

**Comment by yahyaerturan** [comment]
It works on artisan without any error but it did not create fields on tables.

**Comment by JosephSilber** [comment]
Did you remove the `Bouncer::seeder(function () {})` section as I've shown you?

**Comment by yahyaerturan** [comment]
Fully removed now and works fine. Thanks again..

**Comment by KillerSquid** [comment]
If anyone else is running into issues on seed where Laravel is throwing a '...Class [classname] not found...' error I had to run my seeder like this for it work. Once I prepended 'App\' to my class names it worked like a charm.

    use Illuminate\Database\Seeder;

    class BouncerSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
        {
            //admin and superadmin
            Bouncer::allow('superadmin')->everything();

            Bouncer::allow('admin')->everything();
            Bouncer::forbid('admin')->toManage(App\User::class);
            Bouncer::forbid('admin')->to('destroy', App\Department::class);
            .......
            //note the 'App\' before the class name
        }
    }
