### ISSUE TITLE
database

### ISSUE THREAD

**Issue by iusky** [JosephSilber/bouncer#200]
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `roles` add unique `rol
  es_name_unique`(`name`))

**Comment by jesephan** [comment]
@iusky you need to upgrade your mysql to the latest version. If you can't then you need to comment out the indexing in the bouncer migration

**Comment by JosephSilber** [comment]
@iusky as @jesephan has said, older versions of MySQL have this restriction.
