### ISSUE TITLE
When will a version compatible with Laravel 5.5 be released?

### ISSUE THREAD

**Issue by webrevllc** [JosephSilber/bouncer#203]

**Comment by monaam** [comment]
Weirdly this commit #178 supposed to fix this, but i can't seem to require the right "composer.json" file

**Comment by Jeroen-G** [comment]
Also not with `composer require silber/bouncer:dev-master`?

**Comment by JosephSilber** [comment]
PR #178 did not update Bouncer to 5.5, it only updated the `composer.json` file.

I updated Bouncer for 5.5 in https://github.com/JosephSilber/bouncer/commit/0d41128e86649336632d1a590bceda9dafd4c4f5, so you can now require it from `master` if you so wish.

Alternatively, you can wait for a tagged version (which is my personal recommendation, as master can break unexpectedly at any time). I'll be tagging a 5.5-compatible release in a day or two.

**Comment by JosephSilber** [comment]
https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.4
