### ISSUE TITLE
Check Role Has Ability

### ISSUE THREAD

**Issue by valluminarias** [JosephSilber/bouncer#208]
How to check if Role has the given ability?
example:
```
$admin->hasAbility('create', User::class);
```

`$admin` here is a role not a user.

**Comment by JosephSilber** [comment]
$admin->can('create', User::class);

**Comment by valluminarias** [comment]
Ohh, I see. Thanks, didn't expect it's as easy as that.

**Comment by valluminarias** [comment]
Sorry to reopen. How about syncing abilities to role?
Can we do this? 
```
$role->sync($abilities)
```

**Comment by JosephSilber** [comment]
Bouncer::sync($role)->abilities($abilities);

**Comment by valluminarias** [comment]
okay, but I have an issue doing that, seems the entity_type disappear after syncing

**Comment by valluminarias** [comment]
I created my abilities like this
```
Bouncer::allow($admin)->to(['create', 'view', 'update', 'delete'], User::class);
```
and I have Roles Management Page where we can assign abilities to Roles with checkboxes.
And my sync code is like this:
```
Bouncer::sync($role)->abilities($data['abilities']);
```

**Comment by JosephSilber** [comment]
What's $data['abilities']? It should probably be list of IDs.

**Comment by valluminarias** [comment]
Thanks. I never thought, `sync` would work with IDs. Thanks much. My previous `$data['abilities']` was list of names. But now I changed to ID and working.
