### ISSUE TITLE
How can we get all the abilities associated to a role?

### ISSUE THREAD

**Issue by flick36** [JosephSilber/bouncer#209]
Well that, is there something like [getting-all-abilities-for-a-user](https://github.com/JosephSilber/bouncer#getting-all-abilities-for-a-user) but for a role? cause right now i'm doing: `$role->abilities()->pluck('name')` but that has a n+1 problem

**Comment by JosephSilber** [comment]
>that has a n+1 problem

How so?

**Comment by flick36** [comment]
Well right now the only way (at least i know) to get all the roles is doing something like `Role::all()` and i can't eager load the abilities, there for if i want to get the abilities i have to make `role->abilities()->pluck('name')` inside a for each to get only the name, thre fore if i have 2 roles, in that for each i'll have 2 queries and later on if i add another role i'll have 3 and so on,

**Comment by JosephSilber** [comment]
>and i can't eager load the abilities

Why not?

**Comment by flick36** [comment]
Thats what im asking here, is there something like getting-all-abilities-for-a-user? Or what can i do to eager load them? Without me having to create a custom model? Is there an out of the box method, w

**Comment by JosephSilber** [comment]
```php
Role::with('abilities')->all();
```

**Comment by flick36** [comment]
> Role::with('abilities')->all();

I've alrady tried that and it returns `Call to undefined method Illuminate\Database\Query\Builder::all()`
