### ISSUE TITLE
Don't assume model App\User

### ISSUE THREAD

**Issue by jonagoldman** [JosephSilber/bouncer#21]
Model ```App\User``` is hard-coded in various classes:

Silber\Bouncer\Database\Models
Silber\Bouncer\Database\Ability
Silber\Bouncer\Database\Role

It is possible to make it configurable?

**Comment by Arcesilas** [comment]
Actually, it already takes care of the configuration. The auth config file has changed as of Laravel 5.2 and Bouncer seems to not have been updated since.

It happens in BouncerServiceProvider on line 130:

```
$model = $this->app->make('config')->get('auth.model');
```

In Laravel 5.2 you should use:

```
$model = $this->app->make('config')->get('auth.providers.users.model');
```

I could propose a pull request, but I'm not sure the best way to do it : 
- check Laravel version and use the appropriate config
- or consider package is for Laravel 5.2 and just change the configuration path ?

**Comment by Arcesilas** [comment]
Anyway, I understand that the use of `use App\User` in the files you mention can be confusing. In fact, it's just a key used for the `Models` class to store the model name. It could be whatever we like, such as a simple string 'User'. Maybe this way it would not lead to confusion.

**Comment by jonagoldman** [comment]
I'm using Laravel 5.1 for this so ```get('auth.model')``` is working for me. Plan to update in about a month.
Regarding ```use App\User```, what do you mean that is just a key? If it doesn't exists, like in my case, then it breaks.

**Comment by Arcesilas** [comment]
Was using 5.1 last week, 5.2 now (project still in development) and never had the problem you mention.
I spent quite some time how it was possible as I did not understand a first glance.
The `Models` class stores the different models names to use in static `$models` array. The user model name is retrieved by passing the name to `Models::classname()` method. Whatever its value, it's just the key of that table to find out what is the actual `User` model name in the application (which is initialized in BouncerServiceProvider depending on the `auth` config file (which is updated with command `app:name`).
You could use `MyPrettyAwesomeUserModelName` everywhere in replacement of `User::class` it would work the same way.

I've done exactly what @andradedev described in #25 on a fresh install:
 - install laravel: `composer create-project --prefer-dist laravel/laravel laravel5`
 - change application name: `artisan app:name laravel52`
 - install package: `composer require silber/bouncer`
 - edit app.php file to load `BouncerServiceProvider` and use `BouncerFacade`
 - publish bouncer migration: `artisan vendor:publish --provider="Silber\Bouncer\BouncerServiceProvider" --tag="migrations"`
 - run migration: `artisan migrate`

Then, I have the following error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'App\User' not found 
```

Ok. Edit BouncerServiceProvider file to change the auth config key to user model as I mentioned, remove tables creating before failing migrations and run `artisan migrate` again:
```
laravel5$ artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_12_26_164210_create_bouncer_tables
```
No error and `use App\user` is still present in the source code. Did I miss something ?

**Comment by jonagoldman** [comment]
I forked the repo and replaced ```App\User``` with my User entity for my project, so I can't go back and check it from scratch right now. But anyways App\User must be removed or taken from the app itself, it cant be hard-coded inside the package.
I will dig into the code later and check why it might be working for you.

**Comment by Arcesilas** [comment]
Even if it's working for me, it's still not very difficult to remove `App\User` to make sure there is no error at any time in any configuration. It would make it less confusing too.

**Comment by jonagoldman** [comment]
@JosephSilber I don't think the PR solves the issue. Model ```App\User``` is hard-coded inside the classes.

**Comment by JosephSilber** [comment]
Have you tried it? Did you get an error?

If so, can you please post the stack trace here?

**Comment by jonagoldman** [comment]
The error is that ```App\User``` doesn't exist. I changed my app namespace and moved the User model to a different location, so it can't find it.
If you read trough the comments you will see that @Arcesilas made a very detailed explanation of the issue:

```
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'App\User' not found
```

I think you are trying for some reason to avoid using config files at all costs.

**Comment by Arcesilas** [comment]
As I explained, this error happened because auth configuration file changed as of Laravel 5.2. Therefore, default was to use `App\User` which actually did not exist.
Using the correct auth config key to get the model solved the problem, as I said in my very detailed explanation ;) Even with `use App\User` hardcoded, no error was raised.
You may consider try with a fresh install of Laravel 5.1 and 5.2, just as I did, to see if the problem is still present or not. The fact you encounter the problem on your application does not mean it's not solved for a fresh install : only you know what changes you made and where and which consequences they may have on the application behaviour.

**Comment by JosephSilber** [comment]
@jonagoldman without a stack trace, I can't tell what's wrong.

Please provide a full stack trace so that we can figure this out together.

Thank you,

**Comment by jonagoldman** [comment]
I could not get the error so I went trough the code.
Looks like you are using App\User as some kind of key, and even the class itself doesn't exists, ```User::class``` returns the string ```'App\User'```, which you save for later use.

Not sure why PHP internals it's ok with this, but it just don't look right to me.
I just don't now how to explain myself correctly, but the class doesn't exists! It can't be right to do this! Even my IDE feels bad about it:

![1](https://cloud.githubusercontent.com/assets/1297559/12011060/4b745caa-acc8-11e5-83a7-1fa7b6d654de.png)
![2](https://cloud.githubusercontent.com/assets/1297559/12011062/4da9cf1e-acc8-11e5-8255-56d2735e3c93.png)

Man it's your package and your call. Maybe I don't understand something. I'm just pointing it out.

**Comment by Arcesilas** [comment]
That's exactly what I meant when I said it was a key. Yes, for PHP it's ok, even if the class does not exist...

I would have proposed to remove `App\User` everywhere and also remove all references to `User::class` and replace them by a simple string : `'User'` to make it more clear. It was very confusing to me first time I tryed to understand what happened and why there was no error...

**Comment by JosephSilber** [comment]
To summarize:

1. There's currently no error. Everything works as expected.
2. PHP is OK with using class constants on a fully qualified class name that doesn't exist.
3. The Bouncer package uses this as a sensible key to locate to user model.
4. You would prefer to use a magic key instead of a sensible key which your IDE doesn't like.

If I've summarized it all correctly, I think there's no point for future discussion here.

Have I missed anything.

**Comment by jonagoldman** [comment]
:+1:

**Comment by Arcesilas** [comment]
About PHP being OK: http://php.net/manual/en/language.oop5.changelog.php#117688
> ClassName::class magically evaluates as "ClassName", without triggering autoloading of that class.

**Comment by JosephSilber** [comment]
@jonagoldman thanks for following through.

 I appreciate all the feedback, even if I don't always agree with everything.

:heart:

**Comment by jonagoldman** [comment]
@Arcesilas I actually looked for that but could not find it, thanks!
@JosephSilber I'm the one that thanks you for this package, will be using in in my next project!

**Comment by dhcmega** [comment]
Hi, this is pretty old, but the problem persists.
My User's model is in \App\Models\User, but Bouncer classes have App\User hardcoded as required class.

For example in IsRole.php

`use App\User;
`

If I modify the package, an update will overwrite the fix, overriding all the methods to use the custom path will be too complex.

How should I overcome this?

Thanks!

**Comment by JosephSilber** [comment]
@dhcmega what exactly is the problem? Bouncer qctually does use the user specified in the auth config. Have you tried it?

**Comment by dhcmega** [comment]
Is role for example:

https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/IsRole.php

It has line9: use App\User;
and line 26: Models::classname(User::class),

May be I'm wrong, I have just started using this package.
When I try to validate abilities for users, the query has 'App\User', but the data base model is 'App\Models\User'.

**Comment by Arcesilas** [comment]
Been a long time, but I remember it has already been answered: `App\User` is registered as an alias. When requesting for `App\User` the container resolves it to the actual User model class and returns the appropriate instance according to your configuration.

**Comment by dhcmega** [comment]
I will do some tests and get back if I can work it out.. I'm using App\User for auth, but App\Models\User for CRUD. Thanks!
