### ISSUE TITLE
Problem using Bouncer::allow($user)->toOwn(Post::class)->to('view');

### ISSUE THREAD

**Issue by fraparisi** [JosephSilber/bouncer#210]
It seems that _Bouncer::allow($user)->toOwn(Post::class)->to('view');_ as reported in documentation doesn't work anymore (i'm using1.0.0-beta4, I don't check if in previous version is working).
I've checked that _toOwn_ method is returning null, i think because in the class _GivesAbilities_ the _to_ method  doesn't have any return statement.

**Comment by JosephSilber** [comment]
It's currently only available in the master branch.

That's a mistake on my part to include it in the documentation 🙈

**Comment by fraparisi** [comment]
Oh thanks, do u have an idea of when it will be merged? And it is possible to achieve the same result with this version?

**Comment by JosephSilber** [comment]
You can currently achieve this as follows:

```php
Bouncer::allow($user)->t('view', Post::class, ['only_owned' => true]);
```

**Comment by fraparisi** [comment]
Great! Thank you!
