### ISSUE TITLE
Ownership, models and roles

### ISSUE THREAD

**Issue by mtveerman** [JosephSilber/bouncer#215]
I have (besides the User model) the following two models:
`Project`
`Team`

A project can have many teams, a team only has 1 project.
There are project managers and project members.
There are team managers and team members.
Managers and members have different permissions.

A User can be manager of a Team in one Project, while a member of a Team in another Project.

My question:
Is it possible to use a `Bouncer::allow($user)->toOwn(Team::class);` in this case, or even better, using roles, like:
`Bouncer::allow('manager')->toOwn(Team::class);`
`Bouncer::allow('member')->toOwn(Team::class)->to('view');`

My idea would be to create a table where I store the many-to-many relation between User and Team models, and check that table in the `Bouncer::ownedVia()` function. However, I believe that would than fail in the case where a user is a manager on one team, while a member on the other. Since he has manager rights on Team::class, he will have manager rights on all teams he's connected to, right?

My question is a bit in line with #195 , but also slightly different because of the the manager/member difference.

**Comment by JosephSilber** [comment]
Like you said, your `manager` and `member` roles aren't global roles, so this won't really work with Bouncer's roles.

You could create an elaborate callback for `ownedVia`, but at that point you're better off with a policy.

Bouncer works well with Laravel's policies. If Bouncer doesn't allow a given ability, your policy will then be checked.

**Comment by mtveerman** [comment]
I see. In the end, this would lead to some sort of intermediate table in the database were I would store users, roles and the link to the Team. 

Wouldn't it be an idea to add and extra `entity_id` and `entity_type` to the `assigned_roles` table? Than that table could serve as the intermediate table, and we would be able to start doing things like:
`Bouncer::assign('manager')->to($user,$team);`

**Comment by JosephSilber** [comment]
Roles in Bouncer are simply a way to assign buckets of abilities to a user. I don’t think it makes sense for Bouncer to have entity-specific roles.

**Comment by mtveerman** [comment]
The power of the roles is indeed the fact we can assign a bucket of abilities to a user, and when the abilities in the bucket are modified, this is reflected to all assigned users.

Now, imagine I have the setup mentioned above. Currently I programmatically assign the necessary permissions to users in a Team. For example:
members:
`Bouncer::allow($user)->to('view', $team);`
managers:
`Bouncer::allow($user)->to('view', $team);`
`Bouncer::allow($user)->to('create', $team);`

This works, but results in a lot of permissions/abilities in the database. Also, when I have X amount of users in the database, and I want to change for example to permissions of all members of a team, I need to go over each of these members to update their permissions. If I would be able to assign I role `teammember` I could simply only update the role.

**Comment by vlascik** [comment]
I'm having a similar conundrum, being able to assign roles to a model would be very helpful.

**Comment by JosephSilber** [comment]
Have no plans to add this currently.

May revisit this in the future, but for now I think roles should simply be buckets of abilities. That's it.
