### ISSUE TITLE
Is possible change default Entity_type

### ISSUE THREAD

**Issue by AnvarGear** [JosephSilber/bouncer#216]
Hello,

I have other table for my Admins with model Admin, but Bounce only relationship the entity_type with model User, is possible change this option?

PDT: Sorry for my little english.

**Comment by JosephSilber** [comment]
I do not understand the question.

**Comment by AnvarGear** [comment]
Hello,

In my installation of "laravel" I have divided into two tables the users and administrators, but I just want to apply the package to the table and model "Admin"

But I can not do it, since the system tries to validate with the User table.

I hope to be a little clearer in this case.

**Comment by JosephSilber** [comment]
Bouncer uses [whichever model you use for Laravel's auth](https://laravel.com/docs/5.5/authentication#introduction).

You can [configure it in your `auth.php` config file](https://github.com/laravel/laravel/blob/d09efa2/config/auth.php#L70).

**Comment by AnvarGear** [comment]
Hello,

Thanks for answer, but my auth.php is thes next:

`    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Admin::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],`

I have tow table for user (admins and users) and only need apply bouncer in model Admin.

**Comment by JosephSilber** [comment]
@AnvarGear what do you have set as [your guard's provider](ttps://github.com/laravel/laravel/blob/d09efa2/config/auth.php#L41)?

**Comment by AnvarGear** [comment]
The guard's provider are

`    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],
        'admin-api' => [
            'driver' => 'token',
            'provider' => 'admins',
        ],
    ],`

**Comment by JosephSilber** [comment]
@AnvarGear again, what is the default, set here? https://github.com/laravel/laravel/blob/d09efa2/config/auth.php#L41

**Comment by AnvarGear** [comment]
@JosephSilber  I understand what it tells me, but in the system I need the default guard's provider to be the 'users'.

In this case I do not know if it is possible to do it any other way.

**Comment by JosephSilber** [comment]
@AnvarGear I'm still not following completely. The user that is authenticated at Laravel's gate is the same user you use for authentication.

Are you saying you're somehow using different users for authentication and authorization? I don't think that's possible.

**Comment by AnvarGear** [comment]
@JosephSilber 
In the system I am creating, I have two types of users that are Administrators and Users, this is done by separating the information in the database into 2 tables and their respective 'Admin' and 'User'

[Auth and Models](https://gist.github.com/AnvarGear/a1e12ab4c682dde0a7b063a071bf2bf3)

What I need is to be able to implement 'Bouncer' only to administrators (Admin model).

When I did the implementation I saw that by default the Bouncer system takes the Model (entity_type) User, but I need to take the model (entity_type) Admin.

I hope to make myself understand a little better this time.

**Comment by JosephSilber** [comment]
@AnvarGear are you saying you're only using Bouncer in your admin portal, but not on the main public site?

If so, is `admin` the guard you use for authentication in your admin portal?

**Comment by AnvarGear** [comment]
Yeah that's right.

The administrator can only access this section

Cordialmente,

*Andrés Felipe Vásquez Ramírez*
CEO & Fundador de *AnvarStudios.CO* <http://AnvarStudios.CO>
Diseño gráfico y Administración Web profesional
Twitter @anvarstudios <http://twitter.com/anvarstudios>

----------------------------------------------------------------------------------------------------------------------------------
P *Se Verde !  Por favor considerelo antes de imprimir este mail.*

Toma 5 segundos imprimir este mail.

El árbol que servirá para hacer el papel, tarda 7 años en crecer.
No imprima este mensaje si no es necesario.

2017-10-03 22:57 GMT-05:00 Joseph Silber <notifications@github.com>:

**Comment by JosephSilber** [comment]
In that case, you have to [tell Bouncer explicitly which to use that user model](https://github.com/JosephSilber/bouncer#custom-models):

```php
Bouncer::useUserModel(\App\Admin::class);
```

**Comment by AnvarGear** [comment]
I will review and be commented.

Thank you very much for the help, what a shame.

**Comment by JosephSilber** [comment]
@AnvarGear I actually went ahead and created a separate section in the docs just for this: https://github.com/JosephSilber/bouncer#user-model

**Comment by AnvarGear** [comment]
Thanks, it's working properly
