### ISSUE TITLE
Multi Tenancy: take it for a spin

### ISSUE THREAD

**Issue by JosephSilber** [JosephSilber/bouncer#217]
After many requests to add multi-tenancy support to Bouncer, I've been gathering some use-cases from people. As I see it, there are 2 types of setups that people have:

1. **Everything scoped.** In this setup, everything is scoped to the current tenant, so that each tenant can set up their own roles and abilities.

2. **Scoped relationships.** In this setup, the roles and abilities are fixed. All tenants have the same set of roles and abilities. Only the relationships are scoped, meaning that the assignment of a given role/ability to a user is restricted to a tenant, but the actual role & ability models are the same across the board.

---

I've been working on implementing these 2 into Bouncer, using the following syntax:

1. **Everything scoped:**

    ```php
    Bouncer::scope()->to($tenantId);
    ```

    This will scope all models and all relationships to the given tenant.

2. **Scoped relationships:**

    ```php
    Bouncer::scope()->to($tenantId)->onlyRelations();
    ```

    This will only scope the relationships to the given tenant, but will keep the actual roles/abilities global.

---

Support for multi tenancy is now in the master branch, which you can install in your project with this command:

```
$ composer require silber/bouncer:dev-master
```

After installation, you should [set up a global middleware](https://laravel.com/docs/5.5/middleware#global-middleware) that calls one of those 2 methods, with the current tenant's ID.

Please report back here with any bugs/issues/ideas/improvements.

Thanks loads :pray:

**Comment by monaam** [comment]
I thank you for your amazing efforts Joseph !
For now the scope is an integer, but shouldn't it be a foreign key to another table?
What I suggest is, a polymorphic relation, so we can take advantage of Laravel's default relations.
What do you think?

**Comment by JosephSilber** [comment]
@monaam

1. A foreign key to which table? The tenants table is something you create in your own app, so Bouncer is not aware of that in any way. You can of course alter the published migration to your liking, adding foreign key constraints where you see fit.

2. Polymorphic relations are not foreign keys at the database level. It’s one or the other.

3. These scopes are not limited to multi-tenancy. They can just as easily be used for [multiple guards](https://github.com/JosephSilber/bouncer/issues/177#issuecomment-334201467).

**Comment by monaam** [comment]
1 & 2: I see, If Bouncer models morphs into a model that I setup in the middleware, gives me access to that table in one way or another, without the foreign key constraint, so yeah, forget the foreign key thing, and lets talk about a polymorphic relation.

3: You hit two birds with one stone ;) but would it hurt if the "scope_type" just stay null ?

**Comment by ufeg02** [comment]
Is used the routemiddleware code you provided here. Set everythingscoped to an integer but my database value scope stays null when I set an ability to a user...

**Comment by JosephSilber** [comment]
@ufeg02 I just pushed this fix: https://github.com/JosephSilber/bouncer/commit/a40951bb7256ac55b4739264025c8b3194cf0e49

Run `composer update` to get the new changes.

**Comment by JosephSilber** [comment]
For all of you following along, the syntax has changed slightly:

1. **Everything scoped**:
    ```diff
    - Bouncer::scopeTo($tenantId);
    + Bouncer::scope()->to($tenantId);
    ```

2. **Scoped relationships**:
    ```diff
    - Bouncer::scopeRelationsTo($tenantId);
    + Bouncer::scope()->to($tenantId)->onlyRelations();
    ```

Part of the reason for this change is so that we can maybe make [this](https://twitter.com/joseph_silber/status/917458513579925504) configurable:

![image](https://user-images.githubusercontent.com/1403741/31453373-fa3bd51e-ae7f-11e7-8ca2-486ba9ad5a72.png)

A possible syntax for would be:

```php
Bouncer::scope()->to($tenantId)
       ->onlyRelations()
       ->excludeRoles();
```

I'm still on the fence on whether to make this configurable, or what the syntax should be, but this change makes it easier to add such config options.

**Comment by monaam** [comment]
@JosephSilber I don't believe scoping the abilities will make a difference, will it?
A role X scoped to tenant Y with the ability to perform TASK 1, won't interfere with role X scoped to tenant Z with the ability to perform TASK 1,
Because what matters most is the role, except in case when attributing an ability without a role (which is possible) then you need to scope it to tenants

So I believe there is two ways to do it:
1. scope everything and don't bother writing conditional scoping
2. be more explicit:
   - If the ability belongs to a role => don't scope the ability
   - If the ability is without a role => scope the ability

**Comment by JosephSilber** [comment]
> I don't believe scoping the abilities will make a difference, will it?

It's not clear whether you're talking about scoping the actual roles, or their relation.

- If you're talking about the abilities themselves: they may need be scoped if each tenant has their own admin UI where they can create/assign abilities to users/roles. You wouldn't want abilities to leak between different tenants.

- If you're talking about the abilities' relations: some people have setups where the roles themselves aren't scoped, because each tenant gets a predefined un-alterable list of roles. But the tenants do get to define which abilities each role has assigned to it.

**Comment by JosephSilber** [comment]
I've just pushed a sample middleware, which can be published into your app with the following command:

```
$ php artisan vendor:publish --tag="bouncer.middleware"
```

**Comment by JosephSilber** [comment]
Not scoping abilities granted to roles
---

From talking to people, I've found the following setup to be quite common:

1. Only relations are scoped. The role & ability models themselves are shared globally.
2. The one exception is abilities assigned to a role. Those are global. In other words, for each tenant, a given role means the same thing as for the other tenants. The only things that end up being scoped are the abilities assigned to a user directly, and the roles assigned to the user.

To accommodate this, the `Scope` class has a new `dontScopeRoleAbilities` method, which can be used like this:

```php
Bouncer::scope()->to($tenantId)
       ->onlyRelations()
       ->dontScopeRoleAbilities();
```

If your setup sounds similar to this, please take this for a spin, and let me know how it goes.

**Comment by JosephSilber** [comment]
Quick update: multi tenancy has now been merged into the master branch, so if you're testing it, make sure to update your composer version dependency to `dev-master`.

**Comment by JosephSilber** [comment]
Another update: the default scope class that ships with Bouncer tries to accommodate the common setups that people have. For more complex scenarios, you can now create your own [`Scope`](https://github.com/JosephSilber/bouncer/blob/ab2b92d4d2379be3220daaf0d4185ea10237ff2b/src/Contracts/Scope.php) with whatever custom logic you need:

```php
use Silber\Bouncer\Contracts\Scope;

class MyScope implements Scope
{
    // Whatever custom logic your app needs
}

Bouncer::scope(new MyScope);
```

At various points in its execution, Bouncer will call some of the methods on the `Scope` interface. You are free to handle that according to your specific needs :+1:

**Comment by JosephSilber** [comment]
Just tagged a [new release with multi-tenancy support](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.5).

Thank you all for helping with testing & suggestion!

May your happiest years be ahead of you :confetti_ball:

**Comment by JGamboa** [comment]
I have a doubt. 

My application has to work this way :

Abilities are global
Roles are per tenant.

the dontScopeRoleAbilities would not work for that right?

**Comment by JosephSilber** [comment]
@jgamboa that's not presently possible without a custom Scope.

**Comment by JGamboa** [comment]
@JosephSilber 
Bouncer::scope()->to($tenantId)
       ->onlyRelations()
       ->excludeAbilities();

should be something like that? 
Do you have an example for creating a scope? (first time im trying to make one)
