### ISSUE TITLE
Expiration Time

### ISSUE THREAD

**Issue by ajwise0521** [JosephSilber/bouncer#218]
I was trying to implement an expiration time on permissions so an admin could allow someone to do something till said expiration time. I added a column to the permissions table, but when I try to update the attribute and save the permission the entry cannot be found because It is a join table without any ID's any ideas how I can implement this easily? Thanks!

**Comment by ajwise0521** [comment]
I find the permission by ability_id, entity_type and entity_id, then:
$permission->expiration_time = $carbon_datetime;
$permission->save();

**Comment by JosephSilber** [comment]
You have a `Permission` model?

**Comment by ajwise0521** [comment]
I do. very basic though, it just points to the table. and connection

**Comment by JosephSilber** [comment]
If you do, then you should add an primary key ID column to the table.

**Comment by ajwise0521** [comment]
That's what I was looking at. I just wasn't sure if there was a better way. Thanks for the help and for getting back so quickly

**Comment by ajwise0521** [comment]
I'm sorry to bug you again but now I'm getting another error about the ID field: 

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id`, `permissions`.`entity_id` as `pivot_entity_id`, `permissions`.`ability_id` as `pivot_ability_id` from `abilities` inner join `permissions` on `abilities`.`id` = `permissions`.`ability_id` where `permissions`.`entity_id` = 19189 and `permissions`.`entity_type` = App\User and `id` in (1) and `permissions`.`forbidden` = 0) in /home/vagrant/Code/metroloads/vendor/laravel/framework/src/Illuminate/Database/Connection.php:729

**Comment by ajwise0521** [comment]
I figured it out. I had to rename the primary key to something like 'permission_id' and set that in the model. I had to also set timestamps to false in the model and then it worked like a charm.
