### ISSUE TITLE
Assigning the same ability to multiple roles not possible if the ability is updated between assignments

### ISSUE THREAD

**Issue by AdKMorris** [JosephSilber/bouncer#220]
Not sure if this is intended or not but when I run the following commands in Laravel 5.4 Tinker I get Multiple Abilities all with the same name. I am actually trying to assign the same ability to each role so I think only one entry should exist in the "abilities" table.

Commands run in tinker:
```
Bouncer::allow('Role1')->to('ability');
Bouncer::ability()->where('name', 'ability')->update(array('entity_type' => 'App\User'));
Bouncer::allow('Role2')->to('ability');
```
The resulting "Abilities" Table has two entries for the name 'ability' one with 'App\User' and one without. I would expect that the reference by "name" should reference the same ability so I can use updates between assignments with the "to" command. If not what command should I be using to make sure 'Role2' assigns the updated ability?

**Comment by JosephSilber** [comment]
Why are you manually updating the ability? Why are you setting `entity_type` yourself?

Essentially, what you’re doing is:

```php
Bouncer::allow('Role1')->to('ability', User::class);
Bouncer::allow('Role1')->to('ability');
```

...which obviously creates 2 separate abilities.

**Comment by AdKMorris** [comment]
Yeah fair enough, I was just exploring what can be done and assumed that each ability name was unique but that does not seem to be the case. Thanks for making that clear, and thanks for the quick reply I really love what you have done with Bouncer 👍
