### ISSUE TITLE
Finding list of models that user can view

### ISSUE THREAD

**Issue by fraparisi** [JosephSilber/bouncer#222]
Hi Joseph,
there is a way to retrieve a list of a particular models that is owned by a user and have a particular ability?
Thank you in advance

**Comment by Gaven-ar** [comment]
There is a wiki page titled "Querying Data". There you can find a method to define in the User model, to retrieve the abilities assigned to the user.
So maybe that's the solution.

**Comment by JosephSilber** [comment]
Can you be a little more specific? What are you trying to achieve?

**Comment by fraparisi** [comment]
For example, i do 

> Bouncer::allow($user)->to('view', $post);

to an user for different posts...
I want to find a list of $posts that $user can view.

**Comment by JosephSilber** [comment]
```php
$postIds = $user->getAbilities()->where(‘entity_type’, Post::class)->pluck(‘entity_id’);
```

**Comment by fraparisi** [comment]
Ok, fine thanks this is good.
But if i do instead

 > Bouncer::allow($user)->toOwn(Post::class)->to('view');

there is a way to find which are all model that i own? because in this case i don't have entity_id saved on permissions table

**Comment by JosephSilber** [comment]
@fraparisi you would then have to include that in your post query:

```php
Post::where(‘user_id’, $user->id)->find($postIds);
```

**Comment by fraparisi** [comment]
But in case of "owning" a model (not a single instance) i don't have the entity_id associated so I cannot have the list of ids in the same way

**Comment by JosephSilber** [comment]
@fraparisi here's the full query you could use:

```php
$canOwn = $user->getAbilities()->contains(function ($ability) {
    return $ability->only_owned && $ability->entity_type == Post::class;
});

$posts = Post::where(function ($query) {
    $ids = $user->getAbilities()
                ->where('entity_type', Post::class)
                ->where('entity_id', '!=', null)
                ->pluck('entity_id');

    $query->whereIn('id', $ids);
})->when($canOwn, function ($query) {
    $query->orWhere('user_id', auth()->user());
})->get();
```

**Comment by fraparisi** [comment]
This should be fine in the case I have default concept of "owning". But I've a special rules for the concept of owning a model and I don't know how I can test it on a collection

**Comment by JosephSilber** [comment]
> But [if I have] special rules for the concept of owning a model and I don't know how I can test it on a collection

If you're testing it against a collection, then there's no need to concern yourself with ownership. Just test it directly like you would test any other ability:

```php
$posts->map(function ($post) {
    return [
        'post' => $post,
        'allowed' => Bouncer::allows('view', $post)
    ];
});
```

**Comment by fraparisi** [comment]
Probably I misunderstood the concept of owning, i'll to explain what I'm trying to achieve. I have multiple roles, one of them can see everything so I have granted to this role a "view" to the class. Another role can see only a subset of post, in this case i'm using the concept of owning to say that user that have this role can view only the subset of post belonging to his group. `Bouncer::allows('view', $post)` doesn't check for this so for Bouncer the user is "allowed" to see the resource.

**Comment by JosephSilber** [comment]
> `Bouncer::allows('view', $post)` doesn't check for this so for Bouncer the user is "allowed" to see the resource.

It sure does.

**Comment by fraparisi** [comment]
In my case, i tried to set an abilities "view" to a role, call it A, and a "view" with only_owned set to 1 to another role, call it B.
When i'm logged with the user that has role B and I check `Bouncer::allows('view', $post)` to a particular post that doens't satisfy the condition defined in the ownedVia rule, Bouncer return true but i'm expecting false.
Am i doing something wrong in this?

**Comment by JosephSilber** [comment]
@fraparisi what you're describing there should work, but I can't help you without seeing the actual code.
