### ISSUE TITLE
 Bouncer::disallow('subscriber')->to('delete', Post::class);

### ISSUE THREAD

**Issue by ifarooq** [JosephSilber/bouncer#225]
Hi,
I have disallowed subscribers to delete post class but they can still delete a post. 
Do I need to do anything else as well? I assume before deleting a post it should automatically check if current user is a subscriber and he is not allowed to delete a Post.
I have used following statement to disallow "subscriber" role to delete a post.  
 Bouncer::disallow('subscriber')->to('delete', Post::class);

I have an additional question as well, please respond. 
Role "subscriber" can't delete a post but can I add ability to delete a post for a specific subscriber ? 
When I try to add ability to delete a post for a specific user it is added to all subscribers.  
Bouncer::allow($user)->to('delete', Post::class);
$user has "subscriber" rule. 
After execution of above statement the delete ability is added to all subscribers, means any subscriber can delete a post, but it should not happen as I have added the ability to delete a post for a specific user not all.

**Comment by codex-corp** [comment]
@ifarooq you have imported "HasRolesAndAbilities" in your model? did you try to refresh cache or resync maybe?

**Comment by ifarooq** [comment]
@codex-corp Yes I have used "HasRolesAndAbilities" in your model and tried to refresh cache as well. But I am not sure why and where sync is used?

**Comment by JosephSilber** [comment]
Have you actually set up the routes/controller to run authorization checks before the action is executed?

You can read here for more information: https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3

**Comment by JosephSilber** [comment]
> I have used following statement to disallow "subscriber" role to delete a post.
> Bouncer::disallow('subscriber')->to('delete', Post::class);

There's no point in disallowing anything. So long as you haven't explicitly allowed something, it won't be allowed.

> When I try to add ability to delete a post for a specific user it is added to all subscribers.

It isn't. I'm afraid you're not authorizing your actions at all. See my previous comment.

**Comment by ifarooq** [comment]
> Have you actually set up the routes/controller to run authorization checks before the action is executed?
No I was not running the authorization checks, this is actually I was asking that should I need to run authorization checks before action is executed. I got your answer thanks. 

Regarding other question, by default the subscribers are not allowed to delete a post but can I authorize a specific subscriber to delete a post?

**Comment by JosephSilber** [comment]
Bouncer::allow($user)->to('delete', Post::class);
