### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mits87** [JosephSilber/bouncer#228]
Hi,

I try install your package and I have problem:

>   Problem 1
>     - Installation request for silber/bouncer ^0.1.7 -> satisfiable by silber/bouncer[v0.1.7].
>     - Conclusion: remove laravel/framework v5.5.19
>     - Conclusion: don't install laravel/framework v5.5.19
>     - silber/bouncer v0.1.7 requires illuminate/database ~5.1.20|5.2.* -> satisfiable by illuminate/database[v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
>     - don't install illuminate/database v5.1.20|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.1.22|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.1.25|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.1.28|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.1.30|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.1.31|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.1.41|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.0|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.19|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.21|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.24|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.25|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.26|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.27|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.28|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.31|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.32|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.37|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.43|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.45|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.6|don't install laravel/framework v5.5.19
>     - don't install illuminate/database v5.2.7|don't install laravel/framework v5.5.19
>     - Installation request for laravel/framework (locked at v5.5.19, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.19].
> 

I use laravel 5.5. How can I install the package for this version of laravel?

**Comment by JosephSilber** [comment]
Which version have you set Bouncer to in your composer.json file?

**Comment by JosephSilber** [comment]
Please use this:

composer require silber/bouncer v1.0.0-beta.4






As outlined in the installation instructions:

https://github.com/JosephSilber/bouncer/blob/master/readme.md#installation
