### ISSUE TITLE
Permissions/Roles on non-User models

### ISSUE THREAD

**Issue by jschutt** [JosephSilber/bouncer#229]
Am I correct in understanding that Bouncer is designed to apply permissions and roles on whatever model is being used for authentication (typically the App\User::model)?

If I have a User::class model that has many Membership::class models, am I able to use Bouncer to assign a set of permissions to each of the Membership::class models and then check those abilities?

**Comment by JosephSilber** [comment]
Correct. You ca do that as follows:

```php
Bouncer::allow($membership)->to('create', a Post::class);

// then to check:
$membership->can('create', Post::class);
```

**Comment by jschutt** [comment]
Excellent - Thank you Joseph!

**Comment by ziming** [comment]
I can't for some reasons. I added the HasAbilities trait to a class similar to Membership for example.

**Comment by sroseman** [comment]
Me too @ziming. :(
