### ISSUE TITLE
Abilities vs Permissions

### ISSUE THREAD

**Issue by jonagoldman** [JosephSilber/bouncer#23]
I understand that the term **ability** sounds better and its more friendly than **permission**, but I find it confusing.
The terms mean different things, for example, a user may have the ability to delete a post, but not the permission. Users can delete posts, but not all of them have permission to do it. I think it's clear that the ability to do something does not implies the permission to do it.

I see there is already a [fork of this repo] (https://github.com/devonzara/bouncer) that fixes but I wanted to point it out, maybe we can have this merged.
Thanks.

**Comment by JosephSilber** [comment]
1. I'm not sure what this means: "Users can delete posts, but not all of them have permission to do it". If a user doesn't have the permission to delete posts then they can't delete posts.
2. Bouncer is built on top of Laravel's gate, which uses the "ability" nomenclature. I makes sense for us to stick to Laravel's terminology.
