### ISSUE TITLE
Best practices for roles and abilities (Question/Advice)

### ISSUE THREAD

**Issue by jschutt** [JosephSilber/bouncer#232]
I'm curious if anyone has opinions on a good way to handle the following scenario:

I have thousands of users where the majority share similar abilities. However, there will be a number of users that will need to have unique abilities assigned. Technically, any of the users will need to have any abilities added or removed.

I would like to have a list of all the abilities available in the system and be able to select which abilities are applied to a user on the frontend.

Initially, I was thinking of assigning roles to the users that would cover the majority of the abilities, but I'm beginning to question that approach. The alternative would be to handle the grouping of abilities elsewhere (via frontend) and simply apply them directly to the user as ability/permissions instead of through roles. 

Any thoughts? Thank you!

**Comment by JosephSilber** [comment]
Answered here: https://github.com/JosephSilber/bouncer/issues/231#issuecomment-343041858
