### ISSUE TITLE
is it possible to get the related models directly through polymorphism

### ISSUE THREAD

**Issue by vesper8** [JosephSilber/bouncer#235]
I see that by doing 

```
        $user = User::first();
        $posts = Post::skip(0)->take(5)->get();

        foreach($posts as $post) {
            Bouncer::allow($user)->toManage($post);
        }

        dd($user->abilities->toArray());
```

This gets me the entity_id and entity_type for my 5 posts I just assigned to my user

But I want to get the posts directly, based on abilities.

I don't know how to write this relationship. I thought maybe using hasManyThrough would work but I don't know how to make it work.

The idea is I want to be able to load my user and use ->with('posts') which will eager load the posts that are managed by the user through its abilities.

```
        class User
        {
            public function posts() {
                return $this->hasManyThrough('Post', 'Abilities'); // ??
            }
        }
```

Is this possible?

Currently I'm doing this but it's very slow on a large list and I assume eager loading would be a lot faster

```
    public function managedPosts()
    {
        $postIds = $this->getAbilities()->where('entity_type', Post::class)->pluck('entity_id')->all();
        return Post::findMany($leagueIds);
    }
```

**Comment by JosephSilber** [comment]
Bouncer itself does not ship with such a relationship. Bouncer has many different features that can affect a user's permission on a given model, such as inherited abilities, forbidden abilities, ownership abilities and more.

Additionally, as far as I'm aware, Eloquent does not have a relationship for double morphed relations (any model may have permissions for any other model).

**Comment by vesper8** [comment]
ah I see.. that's too bad. I understand that given all of Bouncer's possible scenarios this is difficult to bake in.. however in my case it's a simple scenario.. only users are granted abilities/permissions and only on 1 or 2 other models. It would be nice to have an inexpensive query to retrieve all models of a certain type that a user has permissions over
