### ISSUE TITLE
Is there a Admin UI to manage Roles and Abilities??

### ISSUE THREAD

**Issue by altraWeb** [JosephSilber/bouncer#236]
Hello

I just installed Bouncer in my project. My question now is is there any example for an Admin UI to manage all the Boncer's stuff?? Maybe examples or better ready to use packages???

Thanks

**Comment by JosephSilber** [comment]
@PovilasKorop built a sample admin UI a while ago: https://github.com/LaravelDaily/laravel-roles-permissions-bouncer
