### ISSUE TITLE
Target is not instantiable while building

### ISSUE THREAD

**Issue by nbolender** [JosephSilber/bouncer#238]
I am getting this error in my production environment right after running composer install. php artisan optimize refuses to proceed with the following error:

```
> php artisan optimize

In Container.php line 895:
                                                                               
  Target [Silber\Bouncer\Contracts\Clipboard] is not instantiable while build  
  ing [Silber\Bouncer\Bouncer].  
```

This works fine in my local environment. Any ideas?

**Comment by JosephSilber** [comment]
Are you on Laravel 5.5? If you aren't, have you registered the BouncerServiceProvider?

**Comment by nbolender** [comment]
This is on 5.4.36, and yes BouncerServiceProvider is registered:

```
'providers' => [
    ...
    \Silber\Bouncer\BouncerServiceProvider::class,
    ...
]
```

Thank you for the help!

**Comment by JosephSilber** [comment]
What do you get if `tinker` for this?

```php
app(Silber\Bouncer\Contracts\Clipboard::class)
```

**Comment by nbolender** [comment]
I couldn't even run php artisan tinker, the same error from above appeared. I ended up just upgrading my application to Laravel 5.5, which no longer uses php artisan optimize. All good now, but this may be an issue with 5.4.
