### ISSUE TITLE
Role per model instance?

### ISSUE THREAD

**Issue by autaut03** [JosephSilber/bouncer#239]
Hey. Is it possible to assign a role to user per model instance? For example, I have the following models:

User:
  - id
  - projects (belongsToMany)
Project:
  - id
  - users (belongsToMany)

Each project's user has it's own role (customer, executor, project_manager), so the pivot table should look like that:

project_users:
  - project_id
  - user_id
  - user_role

user_role is defined in pivot table since there's no model "ProjectUser". Then the rights:

allow('project_manager')->to('modify')

So now how is that possible to check if a user, which is a project_manager in some project, is authorized to perform 'modify' on it? ```Gate::allows('modify', $project)``` won't work here.

I may have missed something important and I'm sorry if I did.

**Comment by JosephSilber** [comment]
Bouncer currently does not have the notion of per-model roles. Roles are currently buckets of abilities that are applied to a user across the board.

If you need a user to have certain abilities on a specific model type, apply that model's ability directly to the user:

```php
Bouncer::allow($user)->to('edit', Project::class);
```

If you want to allow all actions on that model type, use the `toManage` method:

```php
Bouncer::allow($user)->toManage(Project::class);
```
