### ISSUE TITLE
adding a blade function

### ISSUE THREAD

**Issue by andradedev** [JosephSilber/bouncer#24]
It would be great if we could add functionality with blade

**Comment by jonagoldman** [comment]
What do you mean? How is Blade related to ACL?

**Comment by Arcesilas** [comment]
It already exists : https://laravel.com/docs/5.2/authorization#within-blade-templates

Bouncer uses Laravel's Gate, so, all authorization functionnalities in Laravel can be used.
When checking if a user "can" do something, it uses both Laravel policies and Bouncer roles and abilities.

**Comment by jonagoldman** [comment]
Oh I see...

**Comment by JosephSilber** [comment]
I should probably expand a little more on this in documentation.

Thanks for bringing this to my attention.
