### ISSUE TITLE
Call to undefined method Silber\Bouncer\Bouncer::seeder() 

### ISSUE THREAD

**Issue by OliverGrimsley** [JosephSilber/bouncer#242]
I just upgraded my app from 5.4.* to Laravel 5.5.27 (Sunday AM EST).  My composer file requires  the `dev-master` version.  That upgrade 2 days ago worked.  However when I went to do this on my second dev machine today, the app would not load.  The initial error was `Call to undefined method Silber\Bouncer\Bouncer::seeder() `  

I went in and commented out the `Bouncer::Seeder` in my `AppServiceProvider` and then got this error:  `Class Silber\Bouncer\Seed\SeedCommand does not exist`  So, I downgraded back to `"silber/bouncer": "v1.0.0-beta.4",` which works fine because the SeedCommand exists in that version.  I am in production so probably should not be using dev-master anyway . . . 

Presuming at some point whatever is in dev-master is rolled out to production, can someone help as clearing this error - it seems like the BouncerServiceProvider.php file is referencing `use Silber\Bouncer\Seed\SeedCommand;` but there is no such file in the repo for dev-master?  Or, I may be missing something . . . 

*error:*
`[2017-12-26 07:55:19] local.ERROR: Class Silber\Bouncer\Seed\SeedCommand does not exist {"exception":"[object] (ReflectionException(code: -1): Class Silber\\Bouncer\\Seed\\SeedCommand does not exist at /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Container/Container.php:752)
[stacktrace]
#0 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('Silber\\\\Bouncer\\\\...')
#1 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('Silber\\\\Bouncer\\\\...')
#2 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('Silber\\\\Bouncer\\\\...', Array)
#3 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('Silber\\\\Bouncer\\\\...', Array)
#4 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Console/Application.php(228): Illuminate\\Foundation\\Application->make('Silber\\\\Bouncer\\\\...')
#5 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Console/Application.php(242): Illuminate\\Console\\Application->resolve('Silber\\\\Bouncer\\\\...')
#6 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(267): Illuminate\\Console\\Application->resolveCommands(Array)
#7 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Console/Application.php(147): Illuminate\\Support\\ServiceProvider->Illuminate\\Support\\{closure}(Object(Illuminate\\Console\\Application))
#8 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Console/Application.php(70): Illuminate\\Console\\Application->bootstrap()
#9 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(316): Illuminate\\Console\\Application->__construct(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Events\\Dispatcher), '5.5.27')
#10 /Users/michaeloliver/valetsites/starfile/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Foundation\\Console\\Kernel->getArtisan()
#11 /Users/michaeloliver/valetsites/starfile/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 {main}
"} `

**Comment by JosephSilber** [comment]
Bouncer's own seeders have been removed in favor of using Laravel's built-in seeders.

https://github.com/JosephSilber/bouncer/commit/55c392b7c840caa9aeb9e966d33d4b2b96200156

As you said, you shouldn't be using dev-master directly. When the next version is tagged, there'll be clear instructions that seeders have been removed, and that people should be using Laravel's built-in seeders.

**Comment by JosephSilber** [comment]
Tagged beta 5 over the weekend, with a note about seeders:

https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.5
