### ISSUE TITLE
Upgrading to latest version throws an error (beta-4 to beta-5)

### ISSUE THREAD

**Issue by ecodrutz** [JosephSilber/bouncer#245]
Hello,
When upgrading from beta-4 to beta-5 i get the following error:

Package operations: 0 installs, 7 updates, 0 removals
  - Updating laravel/framework (v5.5.27 => v5.5.28): Downloading (100%)
  - Updating silber/bouncer (v1.0.0-beta.4 => v1.0.0-beta.5): Downloading (100%)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Bouncer.php line 382:

  Using $this when not in object context

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Is there something that needs to be changed in order for this to work or should we wait for a fix?

The problem seems to come from this commit
https://github.com/JosephSilber/bouncer/commit/dc2697663713c24a446d0502237261d06f9eb988#diff-b34a4877ca1f430f25f28b3fc59a1e2e
where return $this was added to multiple static methods.

**Comment by JosephSilber** [comment]
Can you show us your calling code?

Show the first line in your stack trace that is from your app.

**Comment by JosephSilber** [comment]
These methods were never meant to be called statically. If called on an instance, it should work as expected.

The problem was that the methods were marked as static, giving the illusion that they may be called statically. That's been fixed now.

Would really like to see your code that calls any of these statically. Why and how?

**Comment by ecodrutz** [comment]
Hello,
The code never called these methods.
The simple fact that I was using the Facade and loading the file made composer fail with the error as shown in the first post.
I guess it was php giving a 500 error due to syntax.
I will try to reproduce this with an empty laravel 5.5 install, but I think it will not break again due to your change where the methods are not static anymore.

**Comment by JosephSilber** [comment]
> I guess it was php giving a 500 error due to syntax.

If that were the case, all the tests would fail.

Are you sure the stack trace does not contain any line that points to code in your app?

**Comment by JosephSilber** [comment]
> I think it will not break again due to your change where the methods are not static anymore.

Those changes are only on `master`, not in beta 5. So installing the beta will still have the old code with the methods marked as static.

**Comment by ecodrutz** [comment]
There are no failing tests because none of them actually imports the file. If you do a use Bouncer in the tests, they will start failing, hence I modified on the PR the code to use that method.

**Comment by ecodrutz** [comment]
Here is the console print from the composer update:
composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)         Package operations: 0 installs, 7 updates, 0 removals
  - Updating laravel/framework (v5.5.27 => v5.5.28): Loading from cache
  - Updating silber/bouncer (v1.0.0-beta.4 => v1.0.0-beta.5): Loading from cache
  - Updating martinlindhe/laravel-vue-i18n-generator (0.1.20 => 0.1.21): Loading from cache
  - Updating cakephp/chronos (1.1.2 => 1.1.3): Loading from cache
  - Updating nikic/php-parser (v3.1.2 => v3.1.3): Loading from cache
  - Updating psy/psysh (v0.8.16 => v0.8.17): Loading from cache
  - Updating sebastian/comparator (2.1.0 => 2.1.1): Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Bouncer.php line 382:

  Using $this when not in object context


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

And at this point, the application tries to register the Facade and breaks

**Comment by ecodrutz** [comment]
i guess you can reproduce it by simply running
php artisan package:discover
for me it does:
 php artisan package:discover

In Bouncer.php line 382:

  Using $this when not in object context

**Comment by JosephSilber** [comment]
> There are no failing tests because none of them actually imports the file.

Almost every test starts by calling `$this->bouncer()`, which creates an instance of the Bouncer class:

https://github.com/JosephSilber/bouncer/blob/master/tests/BaseTestCase.php#L107-L112

**Comment by JosephSilber** [comment]
> i guess you can reproduce it by simply running php artisan package:discover

I just installed Bouncer beta 5 in a clean install of Laravel 5.5, and I don't get any errors:

![image](https://user-images.githubusercontent.com/1403741/34525529-42c9a322-f06d-11e7-81e8-a8aada1ab1eb.png)

**Comment by ecodrutz** [comment]
./app/Providers/AppServiceProvider.php:34 {
      › // Use local classes to provide logging
      › Bouncer::useAbilityModel(Ability::class);
      › Bouncer::useRoleModel(Role::class);
      arguments: {
        $method: "useAbilityModel"
        $args: array:1 [ …1]
      }
    }
Ok I think I`ve found where the issue was. In the app service provider the code is indeed using the static methods to make sure the local Ability and Role models are being used.

Sadly this trace wasn't showing in the laravel.log:
[2018-01-03 17:00:46] local.ERROR: Using $this when not in object context {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Using $this when not in object context at vendor/silber/bouncer/src/Bouncer.php:382)"}

**Comment by JosephSilber** [comment]
You can call it statically on the facade. Just `use Bouncer` at the top of your `AppServiceProvider` file.

It seems you have instead imported the `Silber\Bouncer\Bouncer` class directly.

**Comment by ecodrutz** [comment]
No, the Facade is properly imported: 
use Bouncer;
But since the facade calls the method on the class, if the method is static, it automatically calls it statically.
When removing the static keyword everything works fine, as on master. Facades for the win :)

**Comment by JosephSilber** [comment]
> since the facade calls the method on the class, if the method is static, it automatically calls it statically

What makes you say that? That's not what the `Facade` class does:

https://github.com/laravel/framework/blob/8c6b80ebfd1ae0b0bdb984a00129cef3a123580f/src/Illuminate/Support/Facades/Facade.php#L213-L222

**Comment by ecodrutz** [comment]
Maybe this example will shed some light on what I`m trying to say:

<?php

class A {
    public static function isStaticOk() {
        return 'static';
    }
    public static function staticError() {
        return $this;
    }
}
$one = new A();
var_dump($one->isStaticOk()); // prints static
var_dump(A::isStaticOk()); // prints static
var_dump($one->staticError()); // Fails because even if we call -> it`s still a static call
