### ISSUE TITLE
How to retract a user from his or her current roles and ability 

### ISSUE THREAD

**Issue by Aggreyluts** [JosephSilber/bouncer#247]
Hello
How can you remove all roles and abilities from a user.
Leaving the user with no role or ability
Like
Bouncer::retract('*')->to($user);

**Comment by JosephSilber** [comment]
You use the `sync` method:

```php
Bouncer::sync($user)->roles([]);
Bouncer::sync($user)->abilities([]);
```

**Comment by Aggreyluts** [comment]
Getting an error
Call to a member function roles() on integer

**Comment by JosephSilber** [comment]
1. Which version of Bouncer are you using?
2. Can you show us your stack trace?

**Comment by Aggreyluts** [comment]
Version : v1.0.0-beta.5
![userrole error](https://user-images.githubusercontent.com/11787097/34622039-9ae9b236-f25c-11e7-9f77-082a809c56a6.png)

**Comment by JosephSilber** [comment]
It seems like you didn't pass the user to the sync() method. You passed it an integer (probably an ID).

**Comment by Aggreyluts** [comment]
Yes I passed the user id,What should be on the user variable($user)

**Comment by JosephSilber** [comment]
```php
$user = User::first($id);
```

**Comment by Aggreyluts** [comment]
Thank you its working
Thou
I have used 
$user=User::where('id','=',$user_id)->first();

**Comment by Aggreyluts** [comment]
Last question
How do you get all ability for a given role
e.g all abilities for an admin

**Comment by JosephSilber** [comment]
Call `getAbilities` on the role, as described in the docs.

```php
$role = Bouncer::role()->where('name', 'admin')->first();

$abilities = $role->getAbilities();
```
