### ISSUE TITLE
How to give human name and description to Role and Permission

### ISSUE THREAD

**Issue by Blair2004** [JosephSilber/bouncer#248]
Hi,
Thank you for your work. After having used the package as suggested on the docs. It seems like there is not way to define human name and description for both role and permission. I would like to register it in order to let administrator to select which role he would like to assign to registered users.

My project is using Bouncer http://github.com/Blair2004/tendoo

Thank you.

**Comment by AnthonyConklin** [comment]
If you look at the roles & abilities tables you'll see a column named "title". This can be set when creating the role or ability.

`Bouncer::ability(['name' => 'create-posts', 'title' => 'Create Posts']);`

**Comment by AnthonyConklin** [comment]
Considering the "get or create" nature of these methods, it might be beneficial to do some of this automatically ie: capitalize and replace - with spaces to in an attempt to guess the role/ability title.

**Comment by Blair2004** [comment]
Thank you for this.

**Comment by JosephSilber** [comment]
The third argument to the `to` method takes an array of additional attributes you want to add onto the ability:

```php
Bouncer::allow($user)->to('create', Post::class, [
    'title' => 'Create New Posts'
]);
```

**Comment by JosephSilber** [comment]
In [the latest release](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-rc.1), Bouncer now automatically sets the title if none is set. It makes its best guess based on all ability attributes :+1:

**Comment by Blair2004** [comment]
Awesome.
