### ISSUE TITLE
Provide documentation around levels and scopes

### ISSUE THREAD

**Issue by AnthonyConklin** [JosephSilber/bouncer#249]
Would be nice to have some information around using role levels and ability scopes inside the documenation. I went through test classes to try to understand whats happening but is still unclear. Also seems ability scope would be nice to have to interface with oAuth implementations. Is that the intended purpose?

**Comment by JosephSilber** [comment]
- Scopes are explained in detail in [the release notes for beta 5](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.5). Didn't get a chance yet to incorporate it into the documentation.

- Role levels are intentionally undocumented. If I were to build Bouncer from scratch now, I wouldn't have included role levels; they're confusing and are not a full solution to the problem. Some people are using it, so I decided to keep it in Bouncer for now, but it's intentionally not documented.

**Comment by JosephSilber** [comment]
[Multi-tenancy](https://github.com/JosephSilber/bouncer#multi-tenancy) is now fully documented.
