### ISSUE TITLE
this dont work with php artisan app:name

### ISSUE THREAD

**Issue by andradedev** [JosephSilber/bouncer#25]
rename my application and install the package, run the migrations I am having the error **App\User not found**, fix this good series, for those who use app: name.

Thanks

**Comment by gmsantos** [comment]
Config files affected by app:name are kind like hardcode on AppNameCommand, see:

https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Foundation/Console/AppNameCommand.php

I don't thing it's a easy modification without extending this command. Also, app:name was designed to be one of the first things you do in your project.

**Comment by jonagoldman** [comment]
https://github.com/JosephSilber/bouncer/issues/21

**Comment by JosephSilber** [comment]
I'm assuming you're using Laravel 5.2, which wasn't officially supported until now.

Support was just added in the [0.1.1 release](https://github.com/JosephSilber/bouncer/releases/tag/v0.1.1). Does upgrading solve your issue?
