### ISSUE TITLE
Scope is null when getting abilities from User instance.

### ISSUE THREAD

**Issue by FrozenDroid** [JosephSilber/bouncer#250]
Hi, first of all, great package. I'm migrating from my own (crappy) permission implementation to this one :)  
  
When I try to get the user's abilities like so: `$user->getAbilities()`, it returns all the abilities,  
or the abilities that the user has under a certain tenant, but in both cases, the scope property remains null.  
This is a problem when I don't specify a tenant and want to get all the abilities from a user, and group by tenant, for example.  
  
Am I doing something wrong or is this a bug with the package?

Cheers!

**Comment by JosephSilber** [comment]
Bouncer considers `null` like a scope of its own, so that you can have a section of your site that's not affected by scopes.

When no scope is explicitly applied, only records whose `scope` is `null` will be returned.

**Comment by FrozenDroid** [comment]
That was indeed what I was saying... but I tried to reproduce it again just now and it worked fine... I'll let you know once I come across this issue again...
