### ISSUE TITLE
Abilities check

### ISSUE THREAD

**Issue by jesephan** [JosephSilber/bouncer#252]
Hi,

I just have some question about check the user abilities. I assigned user abilities using the following `Bouncer::allow($user)->toManage(Post::class); Bouncer::allow($user)->toOwn(Post::class);`

My question is how do you check if the user can manage Post::class and own Post::class?

I tried `$boolean = Auth::user()->can('own', Post::class); $boolean = Auth::user()->can('manage', Post::class)` seems not working or seems not the right one and its not found in the documentation though. 

Thanks

**Comment by JosephSilber** [comment]
The `toManage` method can be thought of as giving the user all abilities on the given model. When checking any ability on that model, the gate will allow it.

There shouldn't really ever be a reason to check if a user has all abilities on a model. Can you please show me a real-world example where that would be useful?
