### ISSUE TITLE
Implementation of Entity based Role structure?

### ISSUE THREAD

**Issue by AnthonyConklin** [JosephSilber/bouncer#255]
Going to explain with a use case:

App has ability for users to create Groups. A group has predefined roles (Manager, Member, Follower). Abilities are defined per group role:

Manager: view, update-page, manage-sections, manage-users, etc.
Member: view, post-comments, post-media, receive-updates etc.
Follower: view, receive-updates

Currently I'm accomplishing this by creating a 3 custom roles per group.

```
// Create roles.
$groupRoles = [
    Bouncer::role()->create([
        'name' => 'group-manager-' . $group->getKey(),
        'title' => 'Manager of ' . $group->title,
    ]),
    Bouncer::role()->create([
        'name' => 'group-member' . $group->getKey(),
        'title' => 'Member of ' . $group->title,
    ]),
    Bouncer::role()->create([
        'name' => 'group-follower-' . $group->getKey(),
        'title' => 'Follows ' . $group->title,
    ]),
]

// Add permissions to each role....

// Assign roles to group.
foreach ($groupRoles as $role) {
    Bouncer::assign($role->name)->to($group)
}
```
This works but obviously is pretty hacky... anytime I need to check if a user has a role for a crowd I have to append the id to the name.  Would be better to be able to define 3 roles, assign those roles to a group, then assign users to the group with the role they have for that group. Maybe adding a entity_user_role pivot table to accomplish this, and possibly adding a entity_type field (nullable) to role table.

Would like some thoughts/feedback if this can already be accomplished that I missed or if it sounds like good idea. I could probably submit PR for it if so.

**Comment by AnthonyConklin** [comment]
Possibly API ... 
```
Bouncer::role()->create([
        'entity' => 'Group',
        'name' => 'group-manager',
        'title' => 'Manager,
 ]);

Bouncer::assign('group-manager', $group)->to($user);
-or-
$group->assign('group-manager')->to($user);
```

**Comment by JosephSilber** [comment]
This has been requested before in #239. For now, this is not something that we'll support in Bouncer.

May revisit this when we get to 2.0. Who knows :man_shrugging: 

Thanks for the suggestions :1st_place_medal:

**Comment by darrencoutts118** [comment]
@JosephSilber could you use scopes?
