### ISSUE TITLE
What place it is more correct to write down redefinition of tables?

### ISSUE THREAD

**Issue by atach** [JosephSilber/bouncer#259]
Prompt in what place it is more correct to write down redefinition of tables?
I now write them in the "__construct" of each controller, but this is not correct.

```
Bouncer::tables([
            'abilities' => 'new_nameTable1',
            'permissions' => 'new_nameTable2',
            'roles' => 'new_nameTable3',
            'assigned_roles' => 'new_nameTable4',
        ]);
```

**Comment by UksusoFF** [comment]
https://github.com/JosephSilber/bouncer/issues/219

**Comment by a-komarev** [comment]
`app/Providers/AppServiceProvider.php` is a good place for it, or any other custom ServiceProvider.

**Comment by JosephSilber** [comment]
What @a-komarev said :+1:

**Comment by atach** [comment]
Thanks
