### ISSUE TITLE
Get all assigned permissions for a Role

### ISSUE THREAD

**Issue by 1e4** [JosephSilber/bouncer#262]
Hi there,

I am working on a permission system and I need to get all permissions that are assigned to each role

I have tried `$role->getAbilities()` but it always returns an empty collection. I couldn't find anything in the docs about returning permissions from a role.

Or is there a way to just directly check `$role->hasAbility()`?

**Comment by JosephSilber** [comment]
$role->getAbilities() is the right way to do that.

Are you sure the role has abilities? Have you maybe turned on Bouncer's cache?

**Comment by 1e4** [comment]
Yep I'm pretty sure, the following is my seeder

```
<?php

use Illuminate\Database\Seeder;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach(config('roles') as $role)
        {
            Bouncer::role()->create($role);
        }

        foreach(config('permissions') as $permission)
        {
            Bouncer::ability()->create($permission);
        }

        // Set super admin to access everything
        Bouncer::allow('superadmin')->everything();

        // Admins can do everything except manage groups, in turn cannot also manage permissions
        Bouncer::allow('admin')->everything();
        Bouncer::forbid('admin')->to('manage-groups');

        // Banned users
        Bouncer::forbid('banned')->everything();


    }
}
```

Then in the users seeder I do `$user->assign('superadmin');`

My `Group` class consists of `class Group extends Role` and a couple of extra methods.

When I do `$user->getAbilities()` it works fine, but `$group->getAbilities()` is just empty.

**Comment by JosephSilber** [comment]
> My `Group` class consists of `class Group extends Role` and a couple of extra methods.

Have you [registered your `Group` model with Bouncer](https://github.com/JosephSilber/bouncer#custom-models) as being the Bouncer's `Role` model?

```php
Bouncer::useRoleModel(Group::class);
```

**Comment by JosephSilber** [comment]
Also, what do you get on the Eloquent relationship?

```php
$abilities = $role->abilities;
```

What do you get for this :point_up: ?

**Comment by 1e4** [comment]
It seems I may have missed that part out. Now I get a `This action is unauthorized.` despite being a super admin having access to all.

That is also an empty collection before I registered the new handlers..

**Comment by JosephSilber** [comment]
@1e4 I'm a little unclear where we're at. Do you still have an issue? If so, what is it?

**Comment by 1e4** [comment]
I still can't retrieve the abilities from a group, I guess this isn't a feature and I need to create the relationship myself, would that be the correct assumption?

I just want to be able to call `$role->abilities()` and it lists all permissions in that role.

**Comment by 1e4** [comment]
So I renamed the column from `ability_id` to `permission_id`, the seed now works fine again. However opening up my site now asks for `ability_id` and not `permission_id` so it seems that a variable is being used to get the `_id` column in some places and not others.

**Comment by JosephSilber** [comment]
> After registering my custom models in the AppServiceProvider, when the seeder runs Bouncer::allow('superadmin')->everything(); I get `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'permissions.permission_id' in 'field list'`

What is the name of your custom model? Is it `Permission` by any chance?

> I still can't retrieve the abilities from a group, I guess this isn't a feature and I need to create the relationship myself, would that be the correct assumption?
> 
> I just want to be able to call `$role->abilities()` and it lists all permissions in that role.

Both `$tole->abilities` and `$role->getAbilities()` should work.

**Comment by 1e4** [comment]
Yes I have 2 custom models for each, mainly due to naming, I dislike Abilities and Roles, I would rather than Roles and Permissions. Personal perspective of course :).

I modified the column to be `permission_id`, and the seeding works fine, but loading up the site it expects `ability_id`. I am looking into the package to see if it's a bug, but that's where I am at at the moment. I'll keep you posted as I do some more digging.

Appreciate all your support so far. Thank you.

**Comment by JosephSilber** [comment]
Eloquent uses your model's name by default as the table name. So if you're not messing around with the migration, add a `$table` property to your `Permission` model:

```php
protected $table = 'abilities';
```

**Comment by 1e4** [comment]
Group.php

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Silber\Bouncer\Database\Role;

class Group extends Role
{

    public $table = 'roles';

    use SoftDeletes;

    public function isProtected() : bool
    {
        if($this->protected === true || in_array($this->id, [1,2,3,4]))
        {
            return true;
        }

        return false;
    }

    public function hasPermission($permission) : bool
    {
        return false;
    }
}
```

Permission.php

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Silber\Bouncer\Database\Ability;

class Permission extends Ability
{
    use SoftDeletes;

    public $table = 'abilities';
}
```

As far as I am aware I have done this.

**Comment by 1e4** [comment]
I have drilled this down a little, I have a helper called `is_admin()` which will eventually do a few more checks

```php
if(!function_exists('is_admin'))
{
    function is_admin()
    {

        if(!user())
            return false;

        return user()->isA('superadmin');
    }
}
```

This is where it is failing, it is expecting a `group_id` column on the `assigned_roles` table.

**Comment by 1e4** [comment]
I couldn't get to the end of this, so I have reverted back to the role/ability models which is unfortunate. Thanks for trying to help.

**Comment by JosephSilber** [comment]
Maybe post the stack trace? That might help.
