### ISSUE TITLE
Sync is not updating scope

### ISSUE THREAD

**Issue by agariaw** [JosephSilber/bouncer#265]
When I try to sync user role or user abilities the scope column is not updated and is null. 
Whereas, allow function for abilities and assign function for roles work as expected

**Comment by JosephSilber** [comment]
I just pushed a fix for syncing roles. Let me know if it works for you on master (and which version of Laravel and PHP you're using).

I'm still working on syncing abilities.

**Comment by agariaw** [comment]
Yes it is working now, 
Thanks 
PHP version is PHP 7.2.2
Laravel version is 5.5

**Comment by JosephSilber** [comment]
Just pushed a fix for syncing abilities.

Please test it and let me know whether it works for you :heart:

**Comment by agariaw** [comment]
Thank you very much, It is perfect now
