### ISSUE TITLE
create table sqls needed

### ISSUE THREAD

**Issue by Cipa** [JosephSilber/bouncer#268]
Hi,

I am using this outside laravel, a simple MySql query to create the tables would be nice to have.
Otherwise I am not sure how to run migrations without installing php artisan I believe.

Thank you

Edit: Or maybe, can someone post their create tables here. For now I manually converted the migrations, but I am not sure they are correct and missing the foreign keys

**Comment by JosephSilber** [comment]
Here's a file with the raw SQL to create all the tables and their relationships: [MySQL.sql](https://github.com/JosephSilber/bouncer/blob/6e409ae897cf58be3c6d42735bd30abfcb5ce43b/migrations/sql/MySQL.sql).

I also added it to the docs for others to discover.

Thanks for the idea :partly_sunny:
