### ISSUE TITLE
Fatal error: Class 'Illuminate\Cache\ArrayStore' not found

### ISSUE THREAD

**Issue by Cipa** [JosephSilber/bouncer#269]
Hi, 

I am using(trying) Bouncer with Codeigniter and I get this when trying

$bouncer = Bouncer::create();

My Controller looks like

```
use Silber\Bouncer\Bouncer;
class Dashboard extends AppController {
        public function index() {
            $bouncer = Bouncer::create();
            $super_admin = $bouncer->role()->create([
                'name' => 'super-admin',
                'title' => 'Super Admin',
            ]);
        }
}
```

Any ideas?

<img width="1013" alt="screen shot 2018-03-20 at 1 52 02 pm" src="https://user-images.githubusercontent.com/293377/37673235-157b0888-2c46-11e8-9f46-3d0d41a72c1c.png">

**Comment by JosephSilber** [comment]
`composer require illuminate/cache` should solve this.

This should probably be installed by default with Bouncer. My bad.

**Comment by Cipa** [comment]
Thank you

**Comment by JosephSilber** [comment]
Keeping this open so that I remember to add it to Bouncer's `composer.json`?
