### ISSUE TITLE
check role and ability in one go, outside laravel

### ISSUE THREAD

**Issue by Cipa** [JosephSilber/bouncer#273]
Hi,

I am trying to do something like 

```
if (
    $this->system_user &&
    ($this->system_user->isAn('super-admin') || $this->system_user->isAn('admin')->can('manage-program_details'))
) {
```

but can() is not available. I believe can() is part of laravel.
Other than getting all the abilities in an array and checking the array, are there other ways of checking role and ability at the same time.
$this->system_user->isAn('admin')->can('manage-program_details')

Thank you

**Comment by JosephSilber** [comment]
As specified in the docs, you shouldn't really ever check directly for a role. Always check directly for the ability you want to check.

**Comment by Cipa** [comment]
Yes, I read that, but in my case only admins have abilities. Not sure how else to logic my way around this structure
- super admin (no abilities, but access all over)
- admin(manage-{section-n}, be-notify-{section-n})(lots of sections available, and some with other types of abilities)
- guest(only view for most sections)
- other roles with custom abilities, like just upload a file, or publish an event only

Thank you

**Comment by JosephSilber** [comment]
Bouncer has very powerful abilities that allow you grant people with a given role very wide-ranging abilities.

For example:

```
Bouncer::allow('super-admin')->everything();
```

Or

```
Bouncer::allow('admin')->toManage(Section::class);
```

Etc.

**Comment by Cipa** [comment]
Will try, but how do I check? I can't seem to use can()

$this->system_user->can('manage-program_details')

An uncaught Exception was encountered

Type: BadMethodCallException

Message: Call to undefined method Illuminate\Database\Query\Builder::can()

Filename: /shared/httpd/humber/hq/application/vendor/illuminate/database/Query/Builder.php

Line Number: 2445


What I am trying to do is show an edit link, if the user can edit
```
if ($this->system_user && $this->system_user->can('manage-program_details')) {
$edit_link = '<a href="' . $row->link . '" target="_blank">' . $row->link . '</a> <a class="btn btn-secondary btn-sm" href="edit/' . $row->id . '/' . $year . '">Edit</a>';
}
```

Thank you

**Comment by JosephSilber** [comment]
```php
$this->system_user->can('manage-program_details')
```

...should work out of the box.

Can I see your full User Eloquent model class?

Also, which version of Laravel are you using?

**Comment by Cipa** [comment]
I am not using Laravel but I use Eloquent with Codeigniter. Here's my model


```

use \Illuminate\Database\Eloquent\Model as Eloquent;
use Silber\Bouncer\Database\HasRolesAndAbilities;

class ORMUser extends Eloquent
{
    use HasRolesAndAbilities;

    //only read for now, no management, just for relations with other ORM models
    protected $table = 'users';

    protected $hidden = ['password', 'token'];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }


    public function can($ability)
    {
        return $this->getAbilities()->contains('name', $ability);
    }

}
```

**Comment by JosephSilber** [comment]
To get the `can` method, you should also `use` the [`Authorizable`](https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/Authorizable.php) trait.

**Comment by Cipa** [comment]
Thank you, this works, I only had to fix the collision 

trait method getClipboardInstance has not been applied, because there are collisions with other trait methods on
```

use \Illuminate\Database\Eloquent\Model as Eloquent;

use Silber\Bouncer\Database\HasRolesAndAbilities;
use Silber\Bouncer\Database\Concerns\Authorizable;

class ORMUser extends Eloquent
{
    use HasRolesAndAbilities;

    use Authorizable {
        HasRolesAndAbilities::getClipboardInstance insteadof Authorizable;
    }

    //only read for now, no management, just for relations with other ORM models
    protected $table = 'users';

    protected $hidden = ['password', 'token'];

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

}
```
