### ISSUE TITLE
everything() but not really

### ISSUE THREAD

**Issue by Cipa** [JosephSilber/bouncer#275]
Hi,

As per your recommendation on #273 issue I used 
Bouncer::allow('super-admin')->everything();

but I actually only want super-admins to manage everything and not be notified
Each section of the site has an admin or more that get notifications, but I don't want superadmins to be notified.

What would be the best way to remove the notification ability from super-admins

I was envisioning something like 
$this->bouncer->disallow('super-admin')->to('notify-*');

but I am not sure it worked as 

$users = ORMUser::with('abilities', function ($query) use ($section){
            $query->where('name', '=', 'notify-'. $section);
        })->get();

returns all users.

Thank you

**Comment by JosephSilber** [comment]
> Please fell free to close this

Is there still an outstanding question, or are your needs met by using `forbid`?

**Comment by garygreen** [comment]
Possibly related to #264
