### ISSUE TITLE
Disallowing an ability on the user removes the ability from role too

### ISSUE THREAD

**Issue by FinnJanik** [JosephSilber/bouncer#278]
Hey,

after playing around for over 5 hours I finally can say when this happens. Recreate my error like this:
1) Create a role and allow abilities
2) Allow the same abilities to the user
3) Make sure the user has no role
4) Disallow the ability from the user and it will also be removed from the user, WHEN user and ability have the same entity_id!

Maybe you can look into it and tell me if this only applies to me.

Kind regards,
Finn

**Comment by FinnJanik** [comment]
I could correct the error, but not really beautiful.
The error is in the [DisassociatesAbilities.php](https://github.com/JosephSilber/bouncer/blob/master/src/Conductors/Concerns/DisassociatesAbilities.php) getAbilitiesPivotQuery function.
The changes I made to the function:
`protected function getAbilitiesPivotQuery(Model $model, $ids){
        $relation = $model->abilities();

        $modelname = get_class($model); //Get the name of the model and put it into $modelname to check because of role entity naming in database
        if($modelname == 'Silber\Bouncer\Database\Role'){
            $modelname = 'roles';
        } //Rename to roles

        list($foreignKeyName, $relatedKeyName) = $this->getRelationKeyNames($relation);

        return $relation->newPivotStatement()
                        ->where($foreignKeyName, $model->getKey())
                        ->where('entity_type', $modelname) // Added this to the query so that the entity_type will considered
                        ->whereIn($relatedKeyName, $ids);
    }`

I think it is really unclean, but it was quick fix to see if this solves the problem. It did.

**Comment by JosephSilber** [comment]
That's a bad one!

Thanks for catching it, investigating it and reporting it in detail :+1:

**Comment by FinnJanik** [comment]
That was a really annoying bug. Took me quiet some time..
The better the information the easier the fix. My pleasure! 👍
