### ISSUE TITLE
Problem with multiple databases

### ISSUE THREAD

**Issue by renanBritz** [JosephSilber/bouncer#28]
Hello!

Thank you for this awesome project, it makes handling roles and abilities a painless task.

Apparently Bouncer does not support multiple databases...

For my project I have my users table on a different database, and trust me, I have good reasons to do that.

The problem is: when I try to assign a role to a user, I get a QueryException, saying that the users table was not found.

I modified the migrations to set the foreign keys correctly, but I think it would be a bad practice to modify the vendor files and fix the relations in the classes...

Is there any way you could help me here?

Thank you!

**Comment by Arcesilas** [comment]
Hi

You could be interested by this article: http://fideloper.com/laravel-multiple-database-connections

The idea is to extend Models and specify your new one the connection to use.

```php
<?php
class SomeModel extends Eloquent {
    protected $connection = 'mysql2';
}
```

Or maybe you already tried something like that ? If so, you should let us know more precisely what the problem is (messages, etc.) and what you changed in the migration to make it work (which is, as you say, not a good idea, but migrations are not intended to be ran multiple times or require any update, so it's not such a big deal IMHO)

**Comment by renanBritz** [comment]
Thank you for your answer @Arcesilas,

Yes, I have two database connections, the 'igni' connection, which is the default connection, and the 'game' connection, which is where my users table is located.

My Users model is using the game connection, while Bouncer has been migrated to the igni connection/database.

**Here is a simple test I did on artisan tinker:**

```
$user = App\User::find(116)
=> App\User {#792 ...

Bouncer::allow('admin')->to('access_admin_cp')
true

Bouncer::assign('admin')->to($user)
Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pw.user_roles' doesn't exist (SQL: select `id` from `users` inner join `user_roles` on `users`.`ID` = `user_roles`.`user_id` where `user_roles`.`role_id` = 1 and `id` in (116))'
```

Note that "pw" is the game database name, and it should be 'igni' in that query.

The first time I ran the migrations, they failed, I'll show you the error messages:

```
php artisan migrate
                                                                                                                                                                                                         
  [Illuminate\Database\QueryException]                                                                                                                                                                      
  SQLSTATE[HY000]: General error: 1005 Can't create table 'igni.#sql-46f_166' (errno: 150) (SQL: alter table `user_roles` add constraint user_roles_user_id_foreign foreign key (`user_id`) references `us  
  ers` (`ID`) on delete cascade on update cascade)                                                                                                                                                          
                                                                                                                                                                                                            
                                                                                            
  [PDOException]                                                                            
  SQLSTATE[HY000]: General error: 1005 Can't create table 'igni.#sql-46f_166' (errno: 150)
```

To fix that, I edited the migrations and added the database NAME to the foreign keys, like this:

```
class CreateBouncerTables extends Migration
{
    protected $database;

    public function __construct()
    {
        $this->database = DB::connection('game')->getDatabaseName();
    }

    //[...]

    //Example modified foreign key
    $table->foreign('user_id')->references('ID')->on($this->database . '.' . $this->users())->onUpdate('cascade')->onDelete('cascade');

    //[...]
```

However, editing the migrations was not enough, the model relationships are still confused with the multiple databases and I can't get it to work without editing the vendor files.

Well, maybe I could extend those classes, but with the knowledge I have currently, I wouldn't know where to start.

Again, thank you for your attention.

Best regards!

**Comment by Arcesilas** [comment]
Ok, I see the problem with the migration.
First of all, you should use the `Schema::connection()` method in the migration. By the way, it is easier to integrate multiple database connections with it.
Take a look at the documentation:
> Connection & Storage Engine
> 
>If you want to perform a schema operation on a database connection that is not your default connection, use the connection method:
>
> ```php
Schema::connection('foo')->create('users', function ($table) {
    $table->increments('id');
});
```
>To set the storage engine for a table, set the engine property on the schema builder:
>
>```php
Schema::create('users', function ($table) {
    $table->engine = 'InnoDB';
>
    $table->increments('id');
});
```

Concerning the relations, I think you don't need to edit the vendor files, Eloquent will use the connection specified in each model, or the default one if none is specified. Did you add the connection to your User model as told in the article I linked ?

Your User model should look like this:

```php
class User extends Eloquent
{
    protected $connection = 'game';
}
```

Eloquent will set the appropriate database name in the query builder depending on the connection to use for that model.

**Comment by Arcesilas** [comment]
I answered to quickly about the migration. I need to dive a little into the code.

**Comment by Arcesilas** [comment]
Actually, it seems that Laravel's Schema Builder does not support creating foreign keys on another database than the one on which the table is being created.

You need to manually edit the migration. As I said, it's not a problem. Schema Builder is supposed to make life easier when writing migrations, but it cannot handle every specific case, like yours.

Migrations provided by packages are intended, generally, to be usable in most common cases (most often, when there is only one database).The Builder uses Eloquent and Models to create relations. so it is perfectly able to create and manage tables and relations over multiple databases. But not foreign keys.

Then, the solution is, as you did, to publish the migration file, and edit it to fit your configuration.

I don't see any other problem.

**Comment by renanBritz** [comment]
Hello again,

Well, I did create my users table using the Schemma::connection syntax, but that was on a different migration. 

The migration I posted on the previous comment was Bouncer's migration, which I had to edit to prevent foreign key errors (which happenned because the users table is on a different database).

Still, even after fixing the foreign keys in bouncer's migration I can't use bouncer functionalities. This is what happens:

```
php artisan tinker

$user = App\User::find(116)
=> App\User {#792 ...

Bouncer::allow('admin')->to('access_admin_cp')
true

Bouncer::assign('admin')->to($user)
Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pw.user_roles' doesn't exist (SQL: select `id` from `users` inner join `user_roles` on `users`.`ID` = `user_roles`.`user_id` where `user_roles`.`role_id` = 1 and `id` in (116))'
```

I may have confused you on the previous comment. I hope this clarifies.

Thank you.

**Comment by Arcesilas** [comment]
Dis you add this line to your User model ?
```
    protected $connection = 'game';
```

**Comment by renanBritz** [comment]
Yes.

**Comment by Arcesilas** [comment]
Going to bed for now. 1 am here.
I'll make some tests tomorrow.

**Comment by renanBritz** [comment]
Np.

Thanks for your time.

Best regards!

**Comment by Arcesilas** [comment]
Hi!

Eloquent expects the pivot table to be in the same database as the parent model. Eloquent models are not intended to use keys in other databases, according to Model::getQualifiedKeyName() method:

```php
    public function getQualifiedKeyName()
    {
        return $this->getTable().'.'.$this->getKeyName();
    }
```

So, it has to be handled by hand, for each relation involving a key in a table from another database.

Here is the way to do it, without editing vendor files.

We first need to override `HasRolesAndAbilities` trait. Create a new `HasRolesAndAbilities.php` file where you want (basically, in the `app` directory, along User model):

```php
<?php

namespace App;

trait HasRolesAndAbilities
{
    use \Silber\Bouncer\Database\HasRolesAndAbilities;

    public function roles()
    {
        $db = DB::connection('test')->getDatabaseName();
        return $this->belongsToMany(Models::classname(Role::class), $db.'.user_roles');
    }

    public function abilities()
    {
        $db = DB::connection('test')->getDatabaseName();
        return $this->belongsToMany(Models::classname(Ability::class), $db.'.user_abilities');
    }

}
```
Change the namespace and connection name according to your project.

Use this new trait in your User model. Simply remove the line:
```php
use Silber\Bouncer\Database\HasRolesAndAbilities;
```
User model will now use HasRolesAndAbilities in its namespace, which is the one we just created.

Then we need to override some methods for Role and Ability models. As for HasRolesAndAbilities, create a new `Role.php` file, in your `app` directory:
```php
<?php

namespace App;

use DB;
use Silber\Bouncer\Database\Models;
use Silber\Bouncer\Database\Role as BouncerRole;

class Role extends BouncerRole
{
    public function abilities()
    {
        $db = DB::connection('test')->getDatabaseName();
        return $this->belongsToMany(Models::classname(Ability::class), $db.'.role_abilities');
    }

    public function users()
    {
        $db = DB::connection('test')->getDatabaseName();
        return $this->belongsToMany(Models::classname(User::class), $db.'.user_roles');
    }
}
```
Note that since it is YOUR file, for YOUR application, you may hard code the database name in the relationship.

Do the same with the Ability model:
```php
<?php

namespace App;

use DB;
use Silber\Bouncer\Database\Models;
use Silber\Bouncer\Database\Ability as BouncerAbility;

class Ability extends BouncerAbility
{

    public function roles()
    {
        $db = DB::connection('test')->getDatabaseName();
        return $this->belongsToMany(Models::classname(Role::class), $db.'.role_abilities');
    }

    public function users()
    {
        $db = DB::connection('test')->getDatabaseName();
        return $this->belongsToMany(Models::classname(User::class), $db.'.user_abilities');
    }
}
```

We're almost done. We now need to tell Bouncer to use the new models instead of the ones from the package. In you AppServiceProvider, in the boot() method, add this:

```php
        \Silber\Bouncer\Database\Models::setAbilitiesModel(\App\Ability::class);
        \Silber\Bouncer\Database\Models::setRolesModel(\App\Role::class);
```

Then:

```
$ artisan tinker
Psy Shell v0.6.1 (PHP 5.6.11-1ubuntu3.1 — cli) by Justin Hileman
>>> Bouncer::assign('admin')->to(App\User::find(1));
=> true
```

**Comment by renanBritz** [comment]
Hello @Arcesilas!

Thank you for your awesome support!

I did as you instructed and tested bouncer functionalities. Most of them are working correctly, and there's only one issue remaining:

When I try to get the user's abilities, the following error occurs:

```
php artisan tinker

$user = App\User::find(116)
App\User {#808...

$user->getAbilities()
Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'igni.users' doesn't exist (SQL: select * from `abilities` where (select count(*) from `roles` inner join `igni`.`role_abilities` on `roles`.`id` = `igni`.`role_abilities`.`role_id` where `igni`.`role_abilities`.`ability_id` = `abilities`.`id` and (select count(*) from `users` inner join `igni`.`user_roles` on `users`.`ID` = `igni`.`user_roles`.`user_id` where `igni`.`user_roles`.`role_id` = `roles`.`id` and `users`.`ID` = 116) >= 1) >= 1 or (select count(*) from `users` inner join `igni`.`user_abilities` on `users`.`ID` = `igni`.`user_abilities`.`user_id` where `igni`.`user_abilities`.`ability_id` = `abilities`.`id` and `users`.`ID` = 116) >= 1)'
```

**PS:** The database name I used in the relationships is "igni", which is the default database connection and where bouncer's tables are stored. Apparently the getAbilities() method depends on the users table which is in the game database.

Any ideas?

Again, thank you for your support.

**Comment by Arcesilas** [comment]
Hi!

Users table is used in Clipboard. Have a look at Clipboard.php file, in `getAbilities()` and `getRoleUsersConstraint()` methods.

As we did for other files, you may extend the Clipboard class to override thoses methods, and then override `getClipboardInstance()` method fro mHasRolesAndAbilities trait (which we have already extended) so that it returns an instance of your extended Clipboard, which will use the correct table from the correct table.

**Comment by renanBritz** [comment]
Hello again!

It's almost done.

It's seems I'm on a dead end though... I can't find a way to add the database name/connection to the ability's constraint.

Apparently the query builder does not provide any methods to change the connection on the fly, and the "database.table" syntax is not working.

This is what I mean:

```php
protected function getRoleUsersConstraint(Model $user)
    {
        return function ($query) use ($user) {
            $query->whereHas('users', $this->getUserConstraint($user));
        };
    }
```

**I whish I could do something like this:**

```php
protected function getRoleUsersConstraint(Model $user)
    {
        $db = DB::connection('game')->getDatabaseName();

        return function ($query) use ($user, $db) {
            $query->whereHas($db . '.users', $this->getUserConstraint($user));
        };
    }
```
**OR something like this:**

```php
protected function getRoleUsersConstraint(Model $user)
    {
        return function ($query) use ($user) {
            $query->connection('game')->whereHas('users', $this->getUserConstraint($user));
        };
    }
```

But I can't find any solution.

Regards.

**Comment by Arcesilas** [comment]
I've read character by character each file of the package to understand why there is still queries on user table without database name.
I've got this non-working query generated by Bouncer:
```sql
select * from `abilities` where exists (select * from `roles` inner join `test`.`role_abilities` on `roles`.`id` = `test`.`role_abilities`.`role_id` where `test`.`role_abilities`.`ability_id` = `abilities`.`id` and exists (select * from `users` inner join `test`.`user_roles` on `users`.`id` = `test`.`user_roles`.`user_id` where `test`.`user_roles`.`role_id` = `roles`.`id` and `test2`.`users`.`id` = 1)) or exists (select * from `users` inner join `test`.`user_abilities` on `users`.`id` = `test`.`user_abilities`.`user_id` where `test`.`user_abilities`.`ability_id` = `abilities`.`id` and `test2`.`users`.`id` = 1)
```
which obviously returns an error: 
```
Table 'test.users' doesn't exist
```
Of course... 

Just adding `test2.` before `users` where it is necessary, and it works:
```sql
select * from `abilities` where exists (select * from `roles` inner join `test`.`role_abilities` on `roles`.`id` = `test`.`role_abilities`.`role_id` where `test`.`role_abilities`.`ability_id` = `abilities`.`id` and exists (select * from `test2`.`users` inner join `test`.`user_roles` on `test2`.`users`.`id` = `test`.`user_roles`.`user_id` where `test`.`user_roles`.`role_id` = `roles`.`id` and `test2`.`users`.`id` = 1)) or exists (select * from `test2`.`users` inner join `test`.`user_abilities` on `users`.`id` = `test`.`user_abilities`.`user_id` where `test`.`user_abilities`.`ability_id` = `abilities`.`id` and `test2`.`users`.`id` = 1);
+----+-----------+-----------+-------------+---------------------+---------------------+
| id | name      | entity_id | entity_type | created_at          | updated_at          |
+----+-----------+-----------+-------------+---------------------+---------------------+
|  1 | access_cp |      NULL | NULL        | 2016-01-08 08:15:34 | 2016-01-08 08:15:34 |
+----+-----------+-----------+-------------+---------------------+---------------------+
1 row in set (0,00 sec)
```

I may be the whereHas constraints. It could be necessary to manually build the constraint and add it to the query :/

**Comment by Arcesilas** [comment]
The `whereHas` constraint creates these queries:
```php
string(108) "select * from `roles` inner join `test`.`role_abilities` on `roles`.`id` = `test`.`role_abilities`.`role_id`"
string(100) "select * from `users` inner join `test`.`user_roles` on `users`.`id` = `test`.`user_roles`.`user_id`"
string(108) "select * from `users` inner join `test`.`user_abilities` on `users`.`id` = `test`.`user_abilities`.`user_id`"
```
Note that all tables are referenced without the database name. Only joins have the db name, because we put it explicitly in the files we have edited.

**Comment by renanBritz** [comment]
I see...

That's exactly what's happenning.

I extended the getUserConstraint method in the Clipboard class, and added the database name to the $column variable. But it only worked with the join clauses, as you mentioned above.

Here's what I changed:

```php
protected function getUserConstraint(Model $user)
{
    $db = DB::connection('game')->getDatabaseName();

    return function ($query) use ($user) {
        $column = "pw.{$user->getTable()}.{$user->getKeyName()}";

        $query->where($column, $user->getKey());
    };
}
```

**This was the generated query:**

```SQL
select * from `abilities` where (select count(*) from `roles` inner join `igni`.`role_abilities` on `roles`.`id` = `igni`.`role_abilities`.`role_id` where `igni`.`role_abilities`.`ability_id` = `abilities`.`id` and (select count(*) from `users` inner join `igni`.`user_roles` on `users`.`ID` = `igni`.`user_roles`.`user_id` where `igni`.`user_roles`.`role_id` = `roles`.`id` and `pw`.`users`.`ID` = 116) >= 1) >= 1 or (select count(*) from `users` inner join `igni`.`user_abilities` on `users`.`ID` = `igni`.`user_abilities`.`user_id` where `igni`.`user_abilities`.`ability_id` = `abilities`.`id` and `pw`.`users`.`ID` = 116) >= 1)
```

There's a **"select count(*) from users"** somewhere which breaks the query...

For some reason, the constraints are not including the database name. Is that a query builder issue?

Regards.

**Comment by Arcesilas** [comment]
Think I've got the solution. I need to clean up all the mess I've put in my files to let you know what to do exactly.
The solution is in the table name in the User Model... Don't know why I didn't think of it earlier...

Anyway, here is what I get:
```php
artisan tinker
Psy Shell v0.6.1 (PHP 5.6.11-1ubuntu3.1 — cli) by Justin Hileman
>>> App\User::find(1)->getAbilities();
=> Illuminate\Database\Eloquent\Collection {#647
     all: [
       App\Ability {#648
         id: 1,
         name: "access_cp",
         entity_id: null,
         entity_type: null,
         created_at: "2016-01-08 08:15:34",
         updated_at: "2016-01-08 08:15:34",
       },
     ],
   }
```

Hope other problems won't reappear :)

**Comment by Arcesilas** [comment]
Ok, actually, that's pretty easy.

In user Model, remove the connection and set the table name:

```php
<?php

namespace App;

//use Silber\Bouncer\Database\HasRolesAndAbilities;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use HasRolesAndAbilities;

    //protected $connection = 'mysql2';

    protected $table = 'test2.users';
```

Forget everything about Clipboard. You can remove the extended one and leave the `HasRolesAndAbilities` trait untouched as after my first answer:

```php
<?php

namespace App;

trait HasRolesAndAbilities
{
    use \Silber\Bouncer\Database\HasRolesAndAbilities;

    public function roles()
    {
        return $this->belongsToMany(Models::classname(Role::class), 'test.user_roles');
    }

    public function abilities()
    {
        return $this->belongsToMany(Models::classname(Ability::class), 'test.user_abilities');
    }

}
```

And that's all. What happens is that we do not use 2 connections, which is not really necessary, since we are on the same server. If your databases were on 2 different servers, it would be different and relations would not work at all.

So, we only use 1 connection, set the permissions to allow the user access both databases and specify that users table is in the second database. Eloquent is able to correctly escape the table name when it has the database name in it:
```
protected $table_name = 'database.table';
```
will result in
```
`database`.`table`
```
It's very simple, actually...

**Comment by renanBritz** [comment]
Hello again.

Everything seems to be working perfectly now.

Thank you for your awesome support @Arcesilas !

Best regards!

**Comment by Arcesilas** [comment]
You're very welcome. It was very enlightening on how Laravel works.
Glad I could help !

**Comment by JosephSilber** [comment]
@Arcesilas thanks for helping out so eloquently :heart:

**Comment by JosephSilber** [comment]
Just one thing I'd add:

No need to use `Silber\Bouncer\Database\Models` directly. You can use the `Bouncer` facade. See the release notes for [v0.0.22](https://github.com/JosephSilber/bouncer/releases/tag/v0.0.22).
