### ISSUE TITLE
Can't get the roles from the $user->getRoles(), returns error

### ISSUE THREAD

**Issue by FoxRocks76** [JosephSilber/bouncer#281]
I am using a custom user model, as per the instructions. My custom model is an existing one in the app, it's called Employee.php. I have changed the Bouncer files from User:: to Employee:: as instructed.

When I do this: 

$employee = Employee::findOrFail(id);
$employee->getRoles();

I get this: 

BadMethodCallException in Builder.php line 2123:
Call to undefined method Illuminate\Database\Query\Builder::getRoles()

When I try this: $employee->isA('admin');
It returns 'true'

When I try this: $employee->isA('user');
It returns 'false'

It appears to have the roles attached, but I cannot retrieve using getRoles();

**Comment by JosephSilber** [comment]
That method is currently only available in master.

You can get the roles off the regular Eloquent relationship:

```php
$employee->roles
```
