### ISSUE TITLE
Get logged in user's roles from session?

### ISSUE THREAD

**Issue by daljit3** [JosephSilber/bouncer#284]
Everytime I do `auth()->user()->isA('newsadmin')`, it looks up in the database to see if that user has that given role. So if I have 5 different sections on the page with above check, it would execute 5 queries. I obviously understand that I could store it an variable if it was just a single role - but I have to check for different roles. 

What I am wondering is if is this value is in user session too so that I can fetch it without having to query the database? and how do I do that? What do you advise?

**Comment by JosephSilber** [comment]
> So if I have 5 different sections on the page with above check, it would execute 5 queries.

1. The query that gets the roles are cached. No matter how may times you check the user's role in a single request, it'll only fetch it once from the database:

https://github.com/JosephSilber/bouncer/blob/67f37827e9fa24b1bc07f8414abe044e49c710d3/src/CachedClipboard.php#L229-L236

2. If you want the query to be cached across requests, enable the cross-request cache: https://github.com/JosephSilber/bouncer#cache

---

BTW, you shouldn't be checking for roles directly. Read the first note in the docs on checking roles: https://github.com/JosephSilber/bouncer#checking-a-users-roles

**Comment by daljit3** [comment]
I haven't explicitly enabled caching yet as I am working on my local yet. 

I am using Laravel Debugbar to see what queries have been executed for the page.

When I do this - 
`$d = auth()->user()->isA('newsadmin');`
or
`\Bouncer::is(auth()->user())->a('newsadmin');`

It executes an additional query (as I can see in the debugbar's Queries tab) 

`auth()->user()->roles->pluck('name')` doesn't execute an additional query. I can see in the auth tab of debugbar that this data is already fetched as pivot (?). 

Yes It makes sense to me using abilities to check if a user is allowed take some action or not but I was hoping to do something like this below - 

if(user has role == admin) 
show nav_admin.blade.php 

if(user has role == moderator)
show nav_moderator.blade.php 

if(user has role == editor)
show nav_editor.blade.php 

Each of these nav as role specific links. I am obviously going to check abilities to secure those linked pages in these navs. 

So perhaps I do need to enable cache to cache queries for the method above (i.e. `auth()->user()->isA('newsadmin')` ... Correct?

**Comment by JosephSilber** [comment]
I believe this should be fixed in `master`.
