### ISSUE TITLE
How to check if the current user can perform a task based on an ability?

### ISSUE THREAD

**Issue by FoxRocks76** [JosephSilber/bouncer#286]
I'm new to Bouncer and I've just finished setting up a custom Policy for my Work Orders. I am now stuck on how I can check to see if the current user is allowed to perform a certain task from within the update policy.

I've assigned the role of "admin" to the user and I've assigned the ability of "update_work_orders" to that role.

What makes sense to me is:

`
Auth::user()->can('update_work_orders');
`

However that throws an error:

`Call to undefined method Illuminate\Database\Query\Builder::can()`

The solution I have come up with is this:

`
$check = Auth::user()->getAbilities()->where('name', 'update_work_orders');
return $check->isEmpty()? false : true;
`

But it's a bit ugly and doesn't feel like the best way to do it, am I missing something?

**Comment by JosephSilber** [comment]
`Auth::user()->can('update_work_orders')` should work.

Can you show me the code where you grant the ability?

(Also, have you enabled caching?)

**Comment by FoxRocks76** [comment]
Thanks for the prompt reply Joseph

The code to grant the ability looks like this:

https://paste.laravel.io/dd9d8c33-32c3-4c36-bfbb-38680a5f7e8c

The way I envision the setup (what I want) is for the abilities to be somewhat static, in that the admin won't be able to change them and there's one for each method, in every model I have in the app. The roles on the other hand I want to have them created dynamically by the admin, so that's why I've used this approach.

I have not enabled caching, should I?

**Comment by JosephSilber** [comment]
There's too much missing from that code to fully understand everything. Can you instead show me the contents of your Bouncer tables?

**Comment by FoxRocks76** [comment]
For sure:

Abilities: http://prntscr.com/jehsag
Roles: http://prntscr.com/jehsk0
Permissions: http://prntscr.com/jehsx5
Assigned Roles: http://prntscr.com/jeht5b

Also, a dump of the current users roles: http://prntscr.com/jehu8o

**Comment by FoxRocks76** [comment]
Here is some more code:

WorkOrderPolicy: https://paste.laravel.io/bac5364f-a657-44e5-8231-162def1a4552
Employee custom can() method: https://paste.laravel.io/da88d636-c724-427e-bbc3-d69a65b0df9a
WorkOrderController@index: https://paste.laravel.io/80b930bb-57e1-4330-881d-33fb2ea15e00

At the moment, as you can see in the previous post, my user "can" index_work_orders...however, the gate does not deny the user from loading the index method.

I realize this is partly due to my skill level in understanding fully how classes and policies and things work, but I think this is how I'm supposed to implement the package?

**Comment by AbderrahimRayes** [comment]
I think you didn't call the trait HasRolesAndAbilities on your user class 
`use HasRolesAndAbilities `

**Comment by JosephSilber** [comment]
Which version of Laravel are you using?

**Comment by FoxRocks76** [comment]
@JosephSilber That was the problem, thank you so much! I would have spent a decade trying to figure that out!

@AbderrahimRayes Thank you for the idea, but I do have that in my user (Employee) class.

**Comment by AnrDaemon** [comment]
Now, what to do if I don't use Laravel at all to begin with?

**Comment by JosephSilber** [comment]
@AnrDaemon [the documentation has this section](https://github.com/JosephSilber/bouncer#installing-bouncer-in-a-non-laravel-app) on using Bouncer outside of a Laravel app.

**Comment by AnrDaemon** [comment]
@JosephSilber , I know that section. It does not explain how to bind user instance to an already initialized Bouncer instance.
I had to write more code to make that happen, than what I'm comfortable with.
