### ISSUE TITLE
Can't assign roles permissions on Silber\Bouncer\Database\Role model

### ISSUE THREAD

**Issue by jalvjim** [JosephSilber/bouncer#287]
I'm assigning abilities to a Role instance with this call:
_$role->allow($ability);_

This works fine for every Model except for Silber\Bouncer\Database\Role. If I try to assign the ability to a User I have no problem. I have not extended Role model. What is happening?

Kind regards.
Jaime Alvarado

**Comment by JosephSilber** [comment]
> This works fine for every Model except for Silber\Bouncer\Database\Role

What error do you get?
