### ISSUE TITLE
Best approch for conditionnal forbidding?

### ISSUE THREAD

**Issue by monaam** [JosephSilber/bouncer#289]
Hello !
I was wondering about the best approch to conditionally forbid certain roles to perform certain actions to models.
For example:
I have Administrators and technical support in my system, along with Clients, all of those are Users (User model)
What's the best way to forbid Technichal support from managing Users except Clients?
```php
// Administration
Bouncer::allow('superadmin')->everything();

// Technical Support
Bouncer::allow('support')->everything();
Bouncer::forbid('support')->toManage(User::class); // How to allow management for Clients?
```

**Comment by JosephSilber** [comment]
How are "clients" determined?

**Comment by monaam** [comment]
@JosephSilber they are roles actually, just like superadmin and support

**Comment by garygreen** [comment]
Possibly related to #264

**Comment by JosephSilber** [comment]
@garygreen is right. This is the same issue as #264. Let's keep this conversation all in one place.
