### ISSUE TITLE
Check if ability is forbidden

### ISSUE THREAD

**Issue by FrozenDroid** [JosephSilber/bouncer#290]
How do I check if an ability is forbidden? I know there's `cant/cannot` and `can`, but those are a bit too high level. I need to check if an ability is specifically forbidden.

**Comment by FrozenDroid** [comment]
Let me know if this is not possible, if not, I'll see if I can write up a PR.

**Comment by JosephSilber** [comment]
Is `$user->getForbiddenAbilities()` not enough?

**Comment by FrozenDroid** [comment]
Nope. That just gets all the abilities that are not allowed, but I need to get the explicit forbidden abilities.
If I'm understanding things wrong, let me know :)

**Comment by JosephSilber** [comment]
getForbiddenAbilities() only returns forbidden abilities, not disallowed ones.

**Comment by FrozenDroid** [comment]
This can be disregarded then :) though, it would still be nice to check singular abilities.
