### ISSUE TITLE
There are bugs in the ability to delete?

### ISSUE THREAD

**Issue by questocat** [JosephSilber/bouncer#291]
Bouncer version:  v1.0.0-rc.1

Give a user an ability directly:
```php
Bouncer::allow($user)->to('ban-users');
```
Create a role called admin and give it the ability to ban-users:
```php
Bouncer::allow('admin')->to('ban-users');
```
Now, we expect to remove an ability previously granted to a user:
```php
Bouncer::disallow($user)->to('ban-users');
```
However, the above code will delete the ability that gives the admin role. Is this expected behavior?

**Comment by JosephSilber** [comment]
Thanks for the bug report!

This has been previously reported here: https://github.com/JosephSilber/bouncer/issues/278

The master branch should already contain the fix. Can you try this in the master branch, and see if it's fixed?

**Comment by JosephSilber** [comment]
I hope to tag the next release sometime next week, if I can find the time to finish off what's still needed for it.
