### ISSUE TITLE
<Question>Large array of permissions + blade

### ISSUE THREAD

**Issue by ereztdev** [JosephSilber/bouncer#293]
Please let me know if this is possible as someone recommended your package in response to my question:

I am looking to use Laravel's policy to authorize a large array of user permissions with Blade.

- My authorizations are under a `ActionPermission` model holding all app permissions.

- `User` has his permission names accessed via a pivot 

using:

    public function permissions(){
    return $this->belongsToMany('App\ActionPermission', 'users__action_permission');
    }
and calling `$user->permissions()->pluck('module_name')->toArray();` I will get the names of permissions as array.

So essentially I am receiving a collection of permissions for user with the ability to pluck the name of the permissions into an array.

Is there a way to bring an array of policies via blade in one line with your package? So in my layout I will insert a one line blade directive that would affect all children blade that are extending layout?

**Comment by JosephSilber** [comment]
Bouncer uses its own tables and its own relationships.

If you want to use Bouncer, you should be using its API to set your roles & permissions.
