### ISSUE TITLE
General error: 1364 Field 'entity_type' doesn't have a default value (SQL: insert into `assigned_roles` (`entity_id`, `role_id`) values (2, 14))

### ISSUE THREAD

**Issue by sherkhanz** [JosephSilber/bouncer#295]
Hi, 

Thanks for the great Package. It's working very well out of box but I have encountered a small issue. 
When doing Sync, I get the above error. My code snippet is as follow: 

`Bouncer::sync($user)->roles($request->role_array);`

where role_array is name of roles submitted via form. I tried using an array of ids but that still gives me the same error. 
I tried to find details on what to provide to sync's roles method as argument in documentation but found nothing except the following example: 

`Bouncer::sync($user)->roles($roles);`

I will be thankful if someone can explain what the argument should be and where am I doing anything wrong thanks.

**Comment by JosephSilber** [comment]
`Bouncer::sync($user)->roles($roles)` should work with role models, role names & role IDs. The list of roles you pass in are ultimately passed to the [`getRoleKeys` method on the `IsRole` trait](https://github.com/JosephSilber/bouncer/blob/9047931b2123b42756bbe549d266df19f4e999ae/src/Database/Concerns/IsRole.php#L120-L129), which handles it all.

The test for role syncing is passing: https://github.com/JosephSilber/bouncer/blob/9047931b2123b42756bbe549d266df19f4e999ae/tests/SyncTest.php#L27

Can you show me exactly what `$request->role_array` is?

**Comment by davidlapham** [comment]
Running into this issue as well. However, I'm just trying to run the following:
`Bouncer::allow( 'superadmin' )->everything();`

What was the final resolution to this?
