### ISSUE TITLE
OwnedVia - set globally or each time model is referenced?

### ISSUE THREAD

**Issue by scottybo** [JosephSilber/bouncer#298]
In the docs it states that you can change the default column to check for the owner via using `Bouncer::ownedVia(Post::class, 'created_by');`

Is this set at the time of seeding the database/updating the model settings or does it need to be defined each and every time we're checking for permissions?

**Comment by scottybo** [comment]
Decided to take a different route with this and simply add a new attribute in the Model, e.g.


```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MyNewModel extends Model
{

    protected $fillable = [
        'data',
        'owner_id',
    ];
    
    // Bouncer defaults to checking for the "user_id" column for ownership, but this table is using 
    // the column name "owner_id". We'll add the user_id attribute and make it return the owner_id value
    public $appends = [
        'user_id',
    ];
    
    public function getUserIdAttribute()
    {
        return $this->attributes['owner_id'];
    }
}

```

**Comment by JosephSilber** [comment]
As mentioned [in the beginning of the configuration section](https://github.com/JosephSilber/bouncer#configuration) in the docs, you should put this in a service provider.
