### ISSUE TITLE
Prevent Duplicates

### ISSUE THREAD

**Issue by scottybo** [JosephSilber/bouncer#300]
When seeding the permissions/roles etc is it possible to skip any permissions/roles that already exist?

**Comment by JosephSilber** [comment]
Bouncer already does this. All roles/abilities you set are first fetched from the DB, and only created if they're not found.

**Comment by kai-yu** [comment]
I think @scottybo has code similar to the example from [Creating roles and abilities](https://github.com/JosephSilber/bouncer#creating-roles-and-abilities) , we will get duplicates on multiple execution of code if use manual creation. 

Using `allow()->to()` to create abilities will prevent duplicates.
