### ISSUE TITLE
Call policy methods directly without Bouncer 

### ISSUE THREAD

**Issue by Kane-One** [JosephSilber/bouncer#303]
sometimes i just want to call methods in policy classes without Bouncer, it would be much faster since it does not require database or cache queries. and it's also slow to traverse all abilities.

how can i do that?

thanks.

**Comment by garygreen** [comment]
Possibly related to #264

**Comment by JosephSilber** [comment]
> it would be much faster since it does not require database

If you enables Bouncer's cache, you won't be hitting the database again.

> it's also slow to traverse all abilities.

How slow? How many abilities do you have??
