### ISSUE TITLE
Duplicate Role Name

### ISSUE THREAD

**Issue by fredbradley** [JosephSilber/bouncer#307]
Hello, 

Should I be able to create two roles, with duplicate names? 

id | name | title
------------ | ------------- | -----
1 | test-role | Test Role
2 | test-role | Test Role

Surely `name` should be a unique field? 

*How was this replicated*
```
Bouncer::role()->create(['name' => 'test-role']); // (Twice)
```

**Comment by fredbradley** [comment]
That's all very well, although 2 things: 
1. That's not what the document on the `README.md` says. 
2. That's very much plugging a hole with lots of tissue paper! 

Surely some extra logic could be added to stop users accidentally doing this?

**Comment by scottybo** [comment]
Just throwing my hat in the ring to say it would be good to have this as a Service config option to either allow duplicates or not

**Comment by JosephSilber** [comment]
[Bouncer's migration actually adds a unique index](https://github.com/JosephSilber/bouncer/blob/9047931b2123b42756bbe549d266df19f4e999ae/migrations/create_bouncer_tables.php#L36-L39) on the `roles` table.

How did you end up with duplicates in your DB?

**Comment by fredbradley** [comment]
`Bouncer::role()->create(['name' => 'test-role']); // (Twice)`

**Comment by JosephSilber** [comment]
@fredbradley that doesn't answer the question: how does your DB allow duplicate roles if there's a unique index on the name?

**Comment by pstrzalka** [comment]
@JosephSilber I think i know why this happens. The index is on name, scope fields. 
Most of users are creating roles with "NULL" scope, but for exmaple PGSQL docs says:

> Null values are not considered equal

https://www.postgresql.org/docs/current/static/indexes-unique.html

Thats the reason why it allow to make duplicate roles.

**Comment by scottybo** [comment]
Just to add - we're using postgres and are facing this issue

**Comment by JosephSilber** [comment]
@pstrzalka good catch. Thanks for the info.

I updated the example in the readme to use `firstOrCreate`.

If you want this enforced at the DB level, there's nothing stopping you from creating your own unique index if you're not using scopes.

**Comment by ctwillie** [comment]
Just to add to this discussion, I had two db entries in ```assigned_roles``` for the same role assigned to the same user. Both entries had ```scope, restricted_to_id, and restricted_to_type``` set to ```null```. This has only happened once, and am unsure why. Very strange. 

I did assign the role in Tinkerwell to give a little more context, ie,
```php
$user->assign('manager');
```

- mysql: 8.0.20
- Bouncer: v1.0.0-rc.8
- Laravel: v7.17.2
