### ISSUE TITLE
crud (bread) permissions

### ISSUE THREAD

**Issue by JDias** [JosephSilber/bouncer#309]
Could i achieve this behaviour using bouncer?

https://github.com/the-control-group/voyager/issues/240

(if yes, could give me some link?)

thanks in advance,

**Comment by JosephSilber** [comment]
That's way too broad a question. Can you narrow down this issue to a singular specific question?

**Comment by JDias** [comment]
Would you use boucer as the tool for crud requests permissions? Is it the right tool for the task?

Im allreading using bouncer around routes and views but im not sure if it will fit for rbac (is that the name?)

Im still thinking about the subject, the question was and is if bouncer will also fit for this scenario or would i need another type of tool.

(Its not an issue, is a question)

**Comment by JosephSilber** [comment]
It's still unclear to me what you're asking, but maybe this will help. Check out this sample admin portal for managing permissions in Bouncer: https://github.com/LaravelDaily/laravel-roles-permissions-bouncer

**Comment by JDias** [comment]
Im allready ok with it 😊
But for use on routes (middleware) and views (blade directive).

It has can/cant verb.

It, afaik, miss an object.

If you look the first link you have a colection of "objects" and an acl matrix (crud) for each object.

I dont have the full view of the issue as im new to this, but i think that i would like to have another layer of protection. 

1 is the route done in the request
2 is the display done in blade view
And the 3rd, that im thinking about and dont have much sure about, would be in the model/database maybe?

If i have an ability for delete i would need to know, delete what?

The concept would be "the user has ability to do something somewhere" , so if a user reach a view but it doesnt have permission to read that the data will not be displayed, and create abilities for each object(model) will be lots of abilities.

Instead of "manage_users" it woul be "manage" and somewhere else grab the object (user, events etc)

Does it make sense?

Mostly add bread/crud habilities and have an objects database? Im not sure, thats why im asking.

I will play a little more this weekend with bouncer to se if i get some enlightment 😊
(I will open another issue about other thoughts)

**Comment by JDias** [comment]
from the voyager docs:

> Our permission keys will be browse_products, read_products, edit_products, add_products and delete_products.
> 
> If a menu item is associated with any kind of BREAD, then it will check for the browse permission, for example for the Posts BREAD menu item, it will check for the browse_posts permission. If the user does not have the required permission, that menu item will be hidden.

it seems that bouncer can do this.

now i will be missing the scope and that i still need to star(later)

```
first triad 	what the owner can do
second triad 	what the group members can do
third triad 	what other users can do
Each triad
first character 	r: readable
second character 	w: writable
```

from what i could saw bouncer rules it all! :)
thanks for that! 💯 %
