### ISSUE TITLE
Cascade deleted roles from abilities

### ISSUE THREAD

**Issue by mix359** [JosephSilber/bouncer#316]
Hi to all,
I'm implementing this package in my system, substituting the old Roles package.
One difference I've noticed looking at the database structure of this package is that using a pivot relation between the Abilities and the other models there isn't a way to cascade delete the relation when the other model is deleted.

So I have implemented this in my User model that could be suggested or integrated in the traits in some way:
```
	public static function boot() {
		parent::boot();

		static::deleting(function (User $model) {
			$model->roles()->detach();
			$model->abilities()->detach();
		});
	}
```

Also would be useful to add something like this to the bootIsRole method in the IsRole trait (if is not already present in any way in the HasAbilities trait):
```
		static::deleting(function ($model) {
			$model->abilities()->detach();
		});
```

Hope this can help
Cheers Mix

**Comment by divdax** [comment]
**+1**

When deleting a Role the assigned permissions should be deleted as well.
