### ISSUE TITLE
Model permission relation 

### ISSUE THREAD

**Issue by mix359** [JosephSilber/bouncer#317]
Hi to all,

I'm experimenting with the relations to simplify the assignation and removal of abilities on an entity to a user.
In my case I want to list/modify the members that could manage an inventory entity so I've imported the FindsAndCreatesAbilities trait on the model and I've done this relation:
```
    public function managers() {
    	return $this->getModelAbility("inventory.manage.items", $this, [])->users();
    }
```

In this way I can list all the users that is currently a manager for that entity, and add/remove it from a simple form (adding that to the collection and saving the entity... laravel do the rest :) )
It seam to work without problem, but I wan't to ask if there's better way to do that or more "official" way. At the moment, the only disadvantage of this way of manage the permission is that for every entity instance, an ability instance would be created, even if there isn't any permission connected.

Thanks to all
Cheers Mix

**Comment by Surt** [comment]
I was wondering if it could be taken beyong. 
A trait to query models with abilities so I can ask things like:

* get all "modelX" that the user/s own or can Y abilitiy/s
``` $post->allowedFor($user, 'view') ```

**Comment by JosephSilber** [comment]
Bouncer has some checks that run in code, so it can't query models directly like that.
