### ISSUE TITLE
Where is getRoles()?

### ISSUE THREAD

**Issue by MukuroSama** [JosephSilber/bouncer#318]
Laravel throw
`BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::getRoles()`
I can find getAbilities() in [HasAbilities.php](https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/HasAbilities.php)
But can't find getRoles() in [HasRoles.php](https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/HasRoles.php)
PS：In github's repo，there is a getRoles() function exists. But when using 
`composer require silber/bouncer v1.0.0-rc.1`
there is no function named getRoles which written in the readme.md.

**Comment by palokankare** [comment]
Take a look at https://github.com/JosephSilber/bouncer/issues/281
