### ISSUE TITLE
Simplify handling of owning model (performance)

### ISSUE THREAD

**Issue by garygreen** [JosephSilber/bouncer#319]
At the moment, when you do:

```php
Bouncer::allow(User::find(1))->toOwn(Post::class)
```

This will allow that particular user to own a post. If you have millions of users and want them to own posts, it will add a million records into your `permissions` table just for them to be able to own their own posts.

It would be cool if you could grant permission to a general user class to own their own post models:

```php
Bouncer::allow(User::class)->toOwn(Post::class)
```

Where this would create only 1 permission record in the database and still allow any users to own their own posts.

**Comment by JosephSilber** [comment]
This is actually on the roadmap. Not just for owning models, but for all abilities.

**Comment by JosephSilber** [comment]
I'm closing this for now. It's on my list of things to get done. I don't want it to clutter up the issues here.

I'll also post an update to this (closed) issue when this feature will be implemented.

**Comment by JosephSilber** [comment]
Just [pushed this update to master](https://github.com/JosephSilber/bouncer/commit/0d6e7b65f46180f89fc228e799dc1e684d6dddb9):

```php
Bouncer::allowEveryone()->to('view', Post::class);
```

or to own:

```php
Bouncer::allowEveryone()->toOwn(Post::class);
```

...or any other ability types.

---

To test this:

1. Update your `composer.json` file's `silber/bouncer` dependency to `dev-master`.
1. Run `composer update`.
1. Make these two columns in the `permissions` table `nullable`: `entity_id` and `entity_type`

Now you're ready to play around with these new methods:

```php
Bouncer::allowEveryone()->to(...);
Bouncer::disallowEveryone()->to(...);
Bouncer::forbidEveryone()->to(...);
Bouncer::unforbidEveryone()->to(...);
```

Please test it, and let me know your findings :+1:
