### ISSUE TITLE
Change requests

### ISSUE THREAD

**Issue by emergingdzns** [JosephSilber/bouncer#32]
I have a couple requests for your fantastic library.

1. Make it work for sites that already have a users table and have the code check to see what the user table primary index name is. Our users table has a primary key of user_id which breaks Bouncer. The migrations don't work right and I had to modify the AssignRole.php Conductors file in the assignRole function to work with it. Would be nice if it was more universal.

2. Right now you have functions for checking to see if a user is in a particular role. But I don't see an option for checking to see if a user has a particular ability. I can fetch all abilities and loop, but something like this would be nice:
```
$check = $user->can('ban-users');
```

Thanks so much!

**Comment by Arcesilas** [comment]
About question 2: I guess you may simply use the Laravel's ACL:
https://laravel.com/docs/5.1/authorization#via-the-user-model
See in Bouncer Readme file

>When you check abilities at the gate, the bouncer will be consulted first.

So, $user->can('do-something') should work out of the box.

**Comment by emergingdzns** [comment]
Hmm. When I try that, I get this:
```
Call to undefined method Illuminate\Database\Query\Builder::can()
```
I'm using Laravel 5.1. Am I missing something from my User.php file?

**Comment by Arcesilas** [comment]
> Alternatively, you may check abilities via the User model instance. By default, Laravel's App\User model uses an Authorizable trait which provides two methods: can and cannot.

https://laravel.com/api/5.2/Illuminate/Foundation/Auth/Access/Authorizable.html

Don't know what to say... The method is defined for the *User Model*. Not the builder.

You should provide some of your code, it's not easy to debug blindly.

**Comment by renanBritz** [comment]
As for the primary key, maybe you can try to define it in your User model, like so:

```php
class User extends Model implements ...
{
    protected $primaryKey = 'user_id';
```

I can access the user abilities normally from the model:
```
php artisan tinker

$user = App\User::find(1)
App\User {#777

$user->can('edit-posts')
true
```

I noticed you got an undefined method in QueryBuilder, notice that something like this will not work:
```php
$user = \App\User::where('user_id', 1)->can('edit-posts'); //Wrong.
```
**You need a user model to perform the ability check, like so:**
```php
$user = \App\User::where('user_id', 1)->first()->can('edit-posts'); //Correct
```

Regards!

**Comment by emergingdzns** [comment]
Thanks @Arcesilas. I figured out that I could use ```@can``` in the view blades.

Thanks @renanBritz. I do have the primary key defined as a protected var in the User.php model as you recommend. It still didn't work. If you look at the AssignRole.php file it says:
```
$existing = $role->users()->whereIn('id', $ids)->lists('id')->all();
```
The whereIn refers to 'id' which doesn't work with a primary key other than 'id' in the users model. So, I had to modify the code to do 'users.user_id' instead of 'id'. But then the lists() function after breaks down with other errors. So I replaced the line shown above with the following:
```
$existingUsers = $role->users()->whereIn('users.user_id', $ids)->get();
$existing = [];
foreach($existingUsers as $ex) {
    $existing[] = $ex->user_id;
}
```
It's not elegant but it's working now. I'm sure I'll run into other areas where this is an issue. I'm just not sure how to fix it. Still getting to know Laravel's dark and mysterious innards.

Thanks for the help!

**Comment by Arcesilas** [comment]
Rather than editing the vendor file, you should extend them and override the methods you need according to your needs.

For instance, extend AssignsRole:

```php
<?php

namespace App;

use Silber\Bouncer\Conductors\AssignsRole as BouncerAssignsRole;

class AssignsRole extends BouncerAssignsRole
{
    protected function assignRole(Role $role, array $ids)
    {
        $existing = $role->users()->whereIn('user_id', $ids)->lists('user_id')->all();

        $ids = array_diff($ids, $existing);

        $role->users()->attach($ids);
    }
}
```

Since this class is used in `Bouncer` class, you need to extend it too:
```php
<?php

namespace App;

use Silber\Bouncer\Bouncer as SilberBouncer;

class Bouncer extends SilberBouncer
{
    public function assign($role)
    {
        return new AssignsRole($role);
    }
}
```
It could seem weird, but this way, your `Bouncer` class will use your `App\AssignsRole` class (just because of the namespace)

It is also used in `HasRolesAndAbilities`:

```php
<?php

namespace App;

use Silber\Bouncer\Database\HasRolesAndAbilities as BouncerHasRolesAndAbilities;

trait HasRolesAndAbilities
{
    use BouncerHasRolesAndAbilities;

    public function assign($role)
    {
        (new AssignsRole($role))->to($this);

        return $this;
    }
}```
There again, the namespace make the method return your `App\AssignsRole`.

In your User model, use your trait, not the one from Bouncer package.

To use the facade, you have to extend it too :) and use yours in your service `config/app.php`

Many files to extend, but you will not have to do it again, ever, and you can update your package. And it's elegant (thanks to Laravel).

Remember that packages generally use the Laravel standards. Here, the package use the default 'id' for the PK name. It could be more flexible, but... you could use Laravel standards too ;) 
When you choose to not follow the standards, you have to adapt your code. It's sometimes long and tedious...

**Comment by emergingdzns** [comment]
Ok. Just in case it helps someone else down the line, I figured out the solution to the error message. As @Arcesilas mentioned, the Authorizable trait has to be added. I was just confused by this because the documentation for Laravel is utterly useless.

In my User.php model, I had to add:
```
use Illuminate\Foundation\Auth\Access\Authorizable;
```
This was confusing because I have ```use Illuminate\Auth\Authenticatable;``` in the same file but it's path is different. When I tried adding the Authorizable line using the same path it failed.

Then, inside the class, I had to add Authorizable to the traits use line like so:
```
use Authenticatable, Authorizable, CanResetPassword, HasRolesAndAbilities;
```
I had assumed (stupidly) that adding the HasRolesAndAbilities was replacing the built-in Authorizable stuff.

I also added ```use Gate;``` to the controllers where I want to use the can/cant functions. Not sure if it's necessary but figured I'd rather be safe.

**Comment by emergingdzns** [comment]
Thanks for that @Arcesilas ! I've never had to extend a vendor class so that helps a lot. I'll mess around with that and change my User class to match.

Unfortunately, the users table was built long before me and there's so much code here using the "user_id" key that changing it would lead to many very cranky days.

**Comment by Arcesilas** [comment]
I don't know what version you are using, but in Laravel 5.2 the trait is present by default. You won't see it in model `app/User.php`, it's in `Illuminate\Foundation\Auth\User` class, which uses the `Illuminate\Foundation\Auth\Access\Authorizable` trait.

I just read your last message (started writing this one before). It seems your version is not so recent... ;)

**Comment by Arcesilas** [comment]
> I also added `use Gate;` to the controllers where I want to use the can/cant functions. Not sure if it's necessary but figured I'd rather be safe.

It's only necessary if, in the file, the class `Gate` is required without namespace (the Gate Facade). If not, you may remove it. Your IDE may tell you if it is used or not (Netbeans does mention it when it's the case).

**Comment by emergingdzns** [comment]
We are on version 5.1.28. The upgrade from 4.2 to 5.1 was a big pain so I haven't wanted to take on jumping to the latest. Not sure what all is different at the moment. Will probably do it soon.

Anyway, I did extend those three and the facade file but then I was getting an error about the Cache/Store not being able to be instantiated. I'll have to dig into that one later. I'm out of time for this week.

Thanks again for all your help! Again, this is a pretty cool system. I had to build an interface to manage the roles and abilities, which is really what led me to the issues started above.

**Comment by JosephSilber** [comment]
@emergingdzns Just added support for custom primary keys in https://github.com/JosephSilber/bouncer/commit/19c7d10bc183cc54237435f1a43c72fa5323f7f9

I tagged it as [v0.1.2](https://github.com/JosephSilber/bouncer/releases/tag/v0.1.2). Please test it and let me know if it works for you.

**Comment by emergingdzns** [comment]
That works beautifully! Thanks so much!

**Comment by emergingdzns** [comment]
Shoot. Spoke too soon @JosephSilber . When I attempt to assign a role to a user I'm getting this:

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'user_id' in field list is ambiguous (SQL: select `user_id` from `users` inner join `user_roles` on `users`.`user_id` = `user_roles`.`user_id` where `user_roles`.`role_id` = 14 and `user_id` in (68))

68 is the user id and 14 is the new role I created. I am having difficulty figuring out how to tell it to get users.user_id for the select fields.

In my controller I'm doing this:
```
        $userRoles = UserRoles::where('user_id', $user->user_id)->get();
        foreach ($userRoles as $ur) {
            $role = Role::find($ur->role_id);
            Bouncer::retract($role->name)->from($user);
        }
        if (Input::get('role_id')) {
            $role = Role::find(Input::get('role_id'));
            Bouncer::assign($role->name)->to($user);
        }
```
So first thing I do is get a list of all roles that the user is assigned to, which in our case, should only be one role. I created the UserRoles model (shown below along with the other models necessary to build a management interface). Then for each entry I get the role name and then retract that role from the user. Then, I take the post submitted `role_id`, fetch the name of the roll and then assign it to the user. This is where I'm getting the error...

Any thoughts? Thank you!


UserRoles.php:
```
<?php

namespace Models;

use Eloquent;
use Log;
use Config;

class UserRoles extends Eloquent
{

    protected $table = 'user_roles';
    public $timestamps = false;
}
```

Role.php
```
<?php

namespace Models;

use Eloquent;
use Log;
use Config;

class Role extends Eloquent
{

    protected $primaryKey = 'id';
    protected $table = 'roles';
    protected $with = 'abilities';
    public $timestamps = false;
    protected $fillable = ['name','customer_id','created_by'];

    public function abilities()
    {
        return $this->hasMany('Models\RoleAbilities');
    }
}
```

RoleAbilities.php
```
<?php

namespace Models;

use Eloquent;
use Log;
use Config;

class RoleAbilities extends Eloquent
{

    protected $table = 'role_abilities';
    public $timestamps = false;

    public function roles()
    {
        return $this->belongsTo('Models\Role');
    }

    public function abilities()
    {
        return $this->hasMany('Models\Ability');
    }
}
```

Ability.php:
```
<?php

namespace Models;

use Eloquent;
use Log;
use Config;

class Ability extends Eloquent
{

    protected $primaryKey = 'id';
    protected $table = 'abilities';
    public $timestamps = false;
}
```

**Comment by Arcesilas** [comment]
Hi,

I'm not sure I understand what you are trying to do... A pivot table does not need, AFAIK, a model.
To retract all roles from a user, why don't you simply use the retract() and assign() methods from User Model ? They are defined in HasRolesAndAbilitiesTrait.

```php
foreach ($user->roles as $role) {
    $user->retract($role->name);
}

if ($role_id = Input::get('role_id')) {
        $role = Role::find($role_id);
        $user->assign($role->name);
}
```

No ?

**Comment by emergingdzns** [comment]
Thanks @Arcesilas I have always had a model for the pivot tables. Not sure why, it's just what I was taught. Laravel is still a pretty big mountain to climb and I'm only about half way there so I'm still learning. 

Thanks for the tip on the traits and how to use that. That never occurred to me to use it that way.

However, I am still getting the same SQL error when running the controller code the way you suggest. While it's definitely cleaner, it doesn't ultimately solve the problem.

**Comment by Arcesilas** [comment]
Is the query the same as the previous one ?
Have you tried to add the table name in the primary key name ?
```
protected $primaryKey = 'users.user_id';
```
I'm not sure the error is related to Bouncer. I rather think it's a conflict Eloquent cannot handle by itself.

If this does not solve the problem, you may need to create the query with the Query Builder.

**Comment by Arcesilas** [comment]
Have you considered adding an `id` column and use a trigger to assign it the same value than `user_id` ? It adds some complexity, but it could help you use Eloquent in a more standard way. Don't really know if it's a good idea. But it's an idea.

**Comment by JosephSilber** [comment]
I believe https://github.com/JosephSilber/bouncer/commit/f6cbc7805bd1f42f4897812f63c9193f0c843016 should have fixed it.

Can you please test it?

You'll have to set the bouncer version in `composer.json` to `dev-master`.

**Comment by emergingdzns** [comment]
VERY close. It still gave the SQL error, BUT I edited the return line of the `getUsersWithRole` function to read:
```
return $role->users()->select($user->getTable().".".$key)->whereIn($user->getTable().'.'.$key, $ids)->lists($key);
```
and it now works. The issue has been the ambiguous 'user_id' in the select, not in the where clauses. So adding the `->select($user->getTable().".".$key)` to the query builder line seems to have fixed it. Hopefully that makes sense and you can wrap that into the build.

Thanks so much!!

**Comment by JosephSilber** [comment]
@emergingdzns did https://github.com/JosephSilber/bouncer/commit/a971e1dd6e924a451e3812df18169eb29e6463b1 fix it for you?

**Comment by JosephSilber** [comment]
@emergingdzns did you get a chance to try it?

**Comment by emergingdzns** [comment]
Yes today in fact. I still get that same error about the user_id being ambiguous. If I add the `->select($column)` bit to the return line it works fine. It seems you have to name the specific field you want in order for the lists() function to work.

**Comment by JosephSilber** [comment]
That's actually a bug in Laravel 5.1, where table-qualified columns weren't being handled properly in the `lists` method.

[It's been fixed it Laravel 5.2](https://github.com/laravel/framework/pull/10890).

**Comment by emergingdzns** [comment]
Ahh. Ok. Yes we are 5.1 now. I guess we have an even better reason to move to 5.2.

**Comment by JosephSilber** [comment]
@emergingdzns my PR to backport that bugfix to 5.1 has been merged.

As soon as a new 5.1.29 release is tagged, you can upgrade to it and it should resolve your problem.

**Comment by dave-ac** [comment]
@JosephSilber Great package many thanks. If I want to get a list of available '
ROLES is that something I need to do (create a Roles model?) I want to have check boxes so I can assign a user a number of roles?

That would lead onto getting all the ROLES a user has as well

Cheers

**Comment by Arcesilas** [comment]
There is already a `Role` model : https://github.com/JosephSilber/bouncer/blob/master/src/Database/Role.php

To get a user's roles : `$user->roles` should to it, since there is a relationship defined : https://github.com/JosephSilber/bouncer/blob/master/src/Database/HasRolesAndAbilities.php
