### ISSUE TITLE
Strict check for ability to access model instance

### ISSUE THREAD

**Issue by mpryvkin** [JosephSilber/bouncer#322]
In my application I need to check whether user has ability to access model instance and ignore wildcard abilities, such as `everything()` and `toManage()`. For example, I grant ability to `view` if user purchases access to a certain service. I need to know whether user has purchased access by testing whether user has `view` ability.

I am currently using the method below which works but I am wondering if there is something simpler that I overlooked.

```
    /**
     * Determines whether user has ability for given model instance
     *
     * @param  string $ability
     * @param  string $model
     *
     * @return boolean
     */
    public function canStrict($ability, $model){
        return $this
            ->abilities()
            ->where('name', $ability)
            ->forModel($model, true)
            ->exists();
    }
```

**Comment by JosephSilber** [comment]
That should do it.

I wonder why you'd ever need to check that.

**Comment by mpryvkin** [comment]
I explained why this is needed in the original question. Bouncer has unique ability (compared to `spatie/laravel-permission`) to grant permissions to individual instances. I am using Bouncer as primary source of information whether user has access to certain instances but there was no native method of performing strict check.

Thanks again for the Bouncer, keep up the good work!

**Comment by JosephSilber** [comment]
My question is about this:

> In my application I need to check whether user has ability to access model instance and ignore wildcard abilities

Why do you need that?

**Comment by mpryvkin** [comment]
Suppose I sell access to individual training courses within my application. I grant user access to the course when user pays for it. I use Bouncer as ultimate source of whether user has purchased access to the course. Administrators also have access to view the courses via wildcard methods such as `everything()`.

I needed a way to distinguish whether user has indeed purchased a course (i.e. user has been granted ability to model instance) or user has access to the course via other abilities (such as `everything()`).
