### ISSUE TITLE
Fatal error when accessing by IP rather than hostname

### ISSUE THREAD

**Issue by Fly4TheKing** [JosephSilber/bouncer#324]
I don't really understand this well enough to write a good issue report, but I'll do my best. For development, I am running Laravel in a Homestead Vagrant box, and normally access it from my development machine using  'hostname.test' with an entry in my hosts file (192.168.10.10 hostname.test). However, for API testing, I also access from other devices on the LAN using just the IP address and port number of my development machine (192.168.16.63:8000). This worked until adding bouncer. Now I get an error message that I don't know how to address:

```
Fatal error: require(): Failed opening required '/home/vagrant/code/laravel-roles-permissions-bouncer/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/vagrant/code/laravel-roles-permissions-bouncer/bootstrap/autoload.php on line 17
```

This is preceded by a similar warning:

```
Warning: require(/home/vagrant/code/laravel-roles-permissions-bouncer/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/code/laravel-roles-permissions-bouncer/bootstrap/autoload.php on line 17
```

Also included is a stack trace that's only two entries deep:

```
# | Time | Memory | Function | Location
1 | 0.0029 | 392960 | {main}( ) | .../index.php:0
2 | 0.0046 | 393200 | require( '/home/vagrant/code/laravel-roles-permissions-bouncer/bootstrap/autoload.php' ) | .../index.php:22
```

I can make this work by adding entries in the hosts files of the other machines. Maybe that's normal, but it wasn't an issue until I started using bouncer.

**Comment by JosephSilber** [comment]
There's nothing in your error log to suggest this has anything to do with Bouncer.

This seems to be caused by something particular to your server settings.

I unfortunately cannot help you with that.
