### ISSUE TITLE
Ownership check returning false

### ISSUE THREAD

**Issue by Crov** [JosephSilber/bouncer#325]
Hi there, please can you assist me with an ownership issue I am having, maybe I am not fully understanding how it works.

I am seeding a 'lender' role with ownership of the model like so
`Bouncer::allow('lender')->toOwn(Lender::class)->to(['show', 'update']);`

And then I seed some test lender data like so:
```// individual
        $user = User::create([
        	'role' => 'user',
            'email' => 'lender1@flickerleap.com',
            'password' => $password,
        ]);

        $mobileNumber = str_replace('-', '', str_replace(' ', '', $faker->mobileNumber));

        $profile = Profile::create([
            'first_name' => $faker->firstName,
            'last_name' => $faker->lastName,
            'mobile_number' => $mobileNumber,
            'identification_number' => $faker->idNumber,
            'user_id' => $user->id,
        ]);

        $lender = Lender::create([
            'type' => 'individual',
            'authorized' => 1,
            'user_id' => $user->id,
        ]);
```
After this I assign the newly created $user the 'lender' role
`$user->assign('lender');`

In my LendersController I check permissions like this in the constructor:
```
public function __construct()
    {
        $this->middleware(function ($request, $next) {
            // Get the method name being requested
            $action = $request->route()->getActionMethod();
            // See if user can acces it
            if ($request->user()->can($action, Lender::class)) {
                return $next($request);
            }

            return $request->expectsJson()
                ? response()->json(null, 404)
                : redirect()->guest(route('login'));
        });
    }
```
This code works for all users who have the 'admin' role assigned (`Bouncer::allow('admin')->everything();`)

But returns 404 for any user with the 'lender' ability.

As I understood it, this should work as per the documentation:
`By default, Bouncer will check the model's user_id against the current user's primary key`

I can see the current user does have the correct abilities by doing
`$request->user()->getAbilities();'

Am I missing something or doing something wrong?

**Comment by nmfzone** [comment]
You're doing wrong. `->toOwn(Lender::class)` doesn't mean you can check against `Lender::class`, you should check agains Lender instance..

Just for example,
`$lender = Lender::find(2);`

```
...
if ($request->user()->can($action, $lender)) {
    return $next($request);
}
...
```

**Comment by Crov** [comment]
Thank you for the assistance on this and pointing me in the right direction. Changing from checking against the class to the instance of the class helped.
