### ISSUE TITLE
Boucer + Hyn multitenant package

### ISSUE THREAD

**Issue by steveerg** [JosephSilber/bouncer#326]
Hi, i'm using a fresh install of laravel 5.6 with silber/bouncer 1.0.0-rc.1 and hyn multitenancy 5.2.

I got a multitenant environment with users tables inside the tenant database instance and roles, abilities and assigned_roles tables in sytem database instance.

I was wondering to use Boucer scope to use a "global" bouncer installation but something goes wrong when i try to store information into system DB.

I'm using hyn UsesSystemConnection traits on both Role and Ability models to "force" connection to system db, but when Bouncer try to store data into assigned_roles tables the connection switch to tenant.

Models extended ...
```
class Role extends BouncerRole
{
    use UuidModelTrait,UsesSystemConnection;
}

class Ability extends BouncerAbility
{
    use UuidModelTrait, UsesSystemConnection;

    protected $fillable = ['name', 'title', 'entity_type'];
}
```

And my middleware for bouncer scope...

```
class BouncerScope {

    /**
     * The Bouncer instance.
     *
     * @var \Silber\Bouncer\Bouncer
     */
    protected $bouncer;

    /**
     * Constructor.
     *
     * @param \Silber\Bouncer\Bouncer $bouncer
     */
    public function __construct(Bouncer $bouncer) {
        $this->bouncer = $bouncer;
    }

    /**
     * Set the proper Bouncer scope for the incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next) {
        // Here you may use whatever mechanism you use in your app
        // to determine the current tenant. To demonstrate, the
        // $tenantId is set here from the user's account_id.
        $tenantId = (app(CurrentHostname::class)->website->uuid) ?? NULL;
        $this->bouncer->scope()->to($tenantId);

        return $next($request);
    }
}
```
The error ...

> SQLSTATE[42S02]: Base table or view not found: 1146 Table '9c1336e02645446db3e6200eb6786c03.assigned_roles' doesn't exist

**How can i force to use system connection on assigned_roles table??**
It seems to not inherited by Role and Ability models.

Hope i wrote in the right place... I cannot say for sure if this is a lack of Bouncer or Hyn package.

**Comment by steveerg** [comment]
No way to extends or create a model to force system connection on assigned_roles? Maybe my question was stupid? In this case, why?
Thank you!

**Comment by JosephSilber** [comment]
Are you also using the `UsesSystemConnection` trait on your `User` model?

Bouncer uses the `User` model's connection whenever it runs a standalone query.
