### ISSUE TITLE
Assigning same with different scope

### ISSUE THREAD

**Issue by donnysim** [JosephSilber/bouncer#327]
So I have some questions before picking this up for a spin, let's say we have an app where there is a default role `client` that has a scope of `null` and the client can create custom roles, what will happen if the client creates a role `client` with scope of `1` and the code does 

```
Bouncer::assign('client')->to($client);
```
?

There will be 2 roles with the name of `client` but on different scope. What will happen in this scenario? How does this handle these kind of things? If the app role of `client` was created later than a the client created it, will it mean that `Bouncer::assign('client')->to($client);` will be assigning the client created role instead of the system one?

**Comment by JosephSilber** [comment]
How does a client create a new role on a different scope?

**Comment by donnysim** [comment]
I edited it so might not be in email. As I understand `scope` is always used as `null` or `$id` when retrieving, `null` meaning it's for all tenants. Now a global `client` role might exist, and the client might create a `client` role, now what would be assigned with `Bouncer::assign('client')->to($client);`? From the digging I'd say the lastest `client` role as it's keyed by name but not sure.
