### ISSUE TITLE
Extending assigned_roles table.

### ISSUE THREAD

**Issue by enbermudez** [JosephSilber/bouncer#329]
Hi! I want to add an extra field to my `assigned_roles` table named: `code` to manage some logic on my project. Is there a way to do something like this?:

`Bouncer::assign('vendedor')->to($user, [
      'code' => '0001'
]);`

Does Bouncer lets me pass extra properties to fill that custom field?

**Comment by JosephSilber** [comment]
Bouncer doesn't support this natively, but if this is important to you you can achive this by manually setting up the pivot table records:

```php
$user->roles()->attach($role, ['code' => '0001']);
```

**Comment by enbermudez** [comment]
That was fast! Thanks a lot!

PD: sorry for forgetting about the question label:
PPD: sorry for my bad english </3
