### ISSUE TITLE
Target Illuminate\Contracts\Cache\Repository is not instantiable

### ISSUE THREAD

**Issue by dbrw** [JosephSilber/bouncer#330]
Hi, loving this package.
I got this error when calling `$container->get('bouncer')->cache()` on my slim based application:
```
"Target [Illuminate\Contracts\Cache\Repository] is not instantiable.","file":"/var/www/app/vendor/illuminate/container/Container.php","line":895
```

Red through bouncer code, I found that when I call `Bouncer::cache()`, it will try to initiate `Illuminate\Contracts\Cache\Repository` which is a contract and not a concrete class [here](https://github.com/JosephSilber/bouncer/blob/master/src/Bouncer.php#L187).

## The context
I am building some permission based menu using bouncer and spatie/menu package. It works okay but the performance is poor since it querying database for each menu entry in order to check the user ability.

Maybe you can help to work around this issue?

**Comment by JosephSilber** [comment]
@dbrw if you're not in a Laravel context, you have to set up the cache driver yourself. That's outside of Bouncer's scope, since it can't possibly know your setup.

Then, once you have a cache instance, you can either register it with the container, or pass it directly to the `cache` method.

**Comment by JosephSilber** [comment]
Here's an example using `Illuminate`'s files cache:

```php
use Bouncer;
use Illuminate\Cache\FileStore;
use Illuminate\Cache\Repository;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Contracts\Cache\RepositoryContract;

$store = new FileStore(new Filesystem, 'path/to/cache/directory');

$cacheRepository = new Repository($store);

// Now either pass your cache repository manually to Bouncer...
$container->get('bouncer')->cache($cacheRepository);

// ...or register it with the container, and Bouncer will pick it up
$container->singleton(RepositoryContract::class, $cacheRepository);
$container->get('bouncer')->cache();
```

**Comment by dbrw** [comment]
Thank you, this is so useful!
