### ISSUE TITLE
ScopeBouncer middleware

### ISSUE THREAD

**Issue by frantischek** [JosephSilber/bouncer#331]
Hello,
Just to clarify why the scopebouncer is not working for me. 
Users have a company_id and so I changed the ScopeBouncer.php to
```
        $tenantId = $request->user()->company_id;
```
Routes:
```
Route::middleware('scope-bouncer')->group(function() {
    Route::get('/users', 'UserController@view')->name('users');
});
```
UserController@view:
```
        $compusers = \App\User::all();
        return view('user.manage', compact('compusers'));
```
In my view there are all users from the user table.
Is this a feature because my user has "superadmin" role or am I doing something wrong?
Thanks for your help!

**Comment by JosephSilber** [comment]
Scoping Bouncer _does not_ scope your users query. It only constrains Bouncer's own queries.

**Comment by frantischek** [comment]
OK. But what does that mean in detail?

**Comment by JosephSilber** [comment]
It's used for when you want to have different roles for different tenants, allowing each tenant to either create their own roles, or manage for themselves which abilities are allowed for which roles.
