### ISSUE TITLE
Problem with Multiple Database 

### ISSUE THREAD

**Issue by birkansava** [JosephSilber/bouncer#333]
Hello,

First I am sorry for my English I hope You can understand :) 

I use multiple database on my project. 

I keep my users on "xx_users" database and each domain of my clients use "xdomain_db" database connection for example.

On the Laravel side I defined connection as "users" on User model and each model except User model use "mysql" connection as default. Each users have "domain_id" and each domains have different connection.

On my project i want to keep Bouncer tables on "xdomain_db". 

But when I use Bouncer. I get an error like:  Table 'xx_users.assigned_roles' doesn't exist.

I see Bouncer uses User's connection. I don't know what to do. Currently Sql query:

select * from `assigned_roles` where `role_id` in (8) and `entity_id` in (1) and `entity_type` = App\User)

I have to change it to:
select * from  `xxdomain_db`.`assigned_roles` where `role_id` in (8) and `entity_id` in (1) and `entity_type` = App\User)

Note: "xxdomain" is dynamic.

**Comment by JosephSilber** [comment]
Bouncer uses SQL `JOIN` statements, and as such cannot work in a setup where the `users` table is in a different connection.
