### ISSUE TITLE
How to use role levels?

### ISSUE THREAD

**Issue by MalindaWMD** [JosephSilber/bouncer#334]
I'm not talking about `level` in db table.

How can I mange user hierarchy like, 
 

- Super admin

    - Admin
    - Editor
    - Writer

- Developer
I know we can create roles for each level, but looking for a solution that i can assign order for each user.
For example, lent's say I gave privilege for editor to edit user permission. But he should be only able to edit privileges for users below the editor level. 
Is there anyway to handle this ?

**Comment by JosephSilber** [comment]
There's no way to do this in Bouncer currently. You'll have to handle this on your own in a policy.

**Comment by MalindaWMD** [comment]
Ok thanks
