### ISSUE TITLE
Is Bouncer::can(...) working properly  in master  ? 

### ISSUE THREAD

**Issue by fico7489** [JosephSilber/bouncer#337]
Do I do something wrong : 

	$user = App\Models\User::find(1);
	$product = App\Models\Product::find(10);

	\Bouncer::allow($user)->to('product-owner', $product );
	\Bouncer::allow($user)->to('product-owner');

	dd(\Bouncer::can('product-owner'));
	dd(\Bouncer::can('product-owner', $product ));
	dd($user->can('product-owner', $product ));

allow() calls fill bouncer tables properly without error, but all three can() outputs are false but they should be true ?

**Comment by JosephSilber** [comment]
The two Bouncer::can() calls check the authorization against the currently authenticated user. Is $user the currently authenticated user?

$user->can() should work regardless.

**Comment by fico7489** [comment]
Clipboard was extended and adjusted : 

	$this->app->singleton(Clipboard::class, function () {
		return new CachedClipboard(new ArrayStore());
	});
