### ISSUE TITLE
Is there something similar to Bouncer::role()->all() for multi-tenancy?

### ISSUE THREAD

**Issue by swvjeff** [JosephSilber/bouncer#338]
I know `Bouncer::role()` returns the underlying model and we can call `Bouncer::role()->all()` to fetch *all* roles in the DB, but unless I'm missing something simple there doesn't seem to be a way to achieve this for multi-tenancy. I know I can manually build the query `Bouncer::role()->whereNull('scope')->orWhere('scope', $tenantId)->get()` but I'm curious if there's a built-in way to achieve this?

Also, I just wanted to give a massive thanks for this package. The multi-tenancy feature is very well thought out and perfect for my needs.

**Comment by JosephSilber** [comment]
The `Role` model has the tenant scope as a global scope: https://github.com/JosephSilber/bouncer/blob/8f95c69f53c70d648feb45c7579e09a284cc888e/src/Database/Concerns/IsRole.php#L30

So `Bouncer::role()->all()` should already be scoped.

**Comment by swvjeff** [comment]
Whoops, you're right. My apologies. I forgot I was defining the scope with `onlyRelations()`
