### ISSUE TITLE
How to disallow all abilities from a role?

### ISSUE THREAD

**Issue by FoxRocks76** [JosephSilber/bouncer#339]
I tried:

`Bouncer::disallow($role)->all();`

however that returned an error.

I'm wanting to remove all permissions (abilities) and then apply all that have been selected in the form checkboxes. I'm unsure of a better way to do it?

**Comment by FoxRocks76** [comment]
Does this require having created the abilities first?

**Comment by FoxRocks76** [comment]
This is what I've done to solve it, but I believe there is a more efficient way, or possibly a way through Bouncer that I don't know about.

https://paste.laravel.io/b26665a6-da41-460f-a8e1-492041f1b9a5

**Comment by JosephSilber** [comment]
Does this require having created the abilities first?

It does.

To answer your original question:

> How to disallow all abilities from a role?

```php
Bouncer::sync($role)->abilities([]);
```
