### ISSUE TITLE
Unsure if Issue... But confused...

### ISSUE THREAD

**Issue by SeoRoman** [JosephSilber/bouncer#34]
So, I created the basic roles for myself... here I will use two...

Bouncer::allow('role1')->to('create', App\User::class);
Bouncer::allow('role1')->to('delete', App\User::class);

Bouncer::allow('role2')->to('create', App\User::class);

Ok... so easy enough?

I created two users... 
$user1 = new User(); // Created and Saved
$user2 = new User(); // Created and Saved

$user1->assign('role1');
$user2->assign('role2'); 

// Again, super easy...

$user1->can('create', App\User::class); // FAILS...

no abilities for this user were set, however they were set through the roles... but through roles are not checked if the user has this ability, it only checks directly...

so even though user belongs to ROLE: role1, which has the 'create' and 'delete' roles, it fails to find it with ->can()... unless I specify that $user1->is('admin') which I really don't want to do...

Thoughts? maybe I am missing something...

**Comment by JosephSilber** [comment]
Have you registered the Bouncer service provider?

**Comment by Gummibeer** [comment]
@SeoRoman This isn't a real issue - the `can()` method also checks abilities that are assigned via roles - if everything is done right.
Including the ServiceProvider, HasRolesAndAbilities Trait and so on.

**Comment by SeoRoman** [comment]
so then why would that break?

Fails, even though the Auth'd user does have the role 'admin' that has this ability....

@if (Auth::User()->can('delete', App\User::class))
   <button class="btn btn-xs btn-danger">Delete</button>
@endif

**Comment by SeoRoman** [comment]
Right now in my DB... I have the following...

Roles: 1, admin : 2, manager

Abilities: 1, Create : 2, Modify : 3, Delete (all for App\User)

Then I have role_abilities
Role_ID: 1, Ability_ID: 1
Role_ID: 1, Ability_ID: 2
Role_ID: 1, Ability_ID: 3
Role_ID: 2, Ability_ID: 1

But when logged into a User with Role: 'admin' it doesn't show the delete button when I check with the above check in blade...

**Comment by SeoRoman** [comment]
Yes, the User model has the trait... yes the service provider and facade are both including in config/app.php for Bouncer...

**Comment by JosephSilber** [comment]
@SeoRoman again I ask: have you properly registered Bouncer's service provider?

**Comment by SeoRoman** [comment]
// Silber/Bouncer
        Silber\Bouncer\BouncerServiceProvider::class,

in config/app.php along with Facade...

        // Silber/Bouncer
        'Bouncer' => Silber\Bouncer\BouncerFacade::class,

**Comment by SeoRoman** [comment]
The only thing I don't have right now in my DB, is anything with user_abilities

because no ability was directly assigned to a user...

**Comment by SeoRoman** [comment]
hmmm one sec, I may have figured it out... it may not be bouncer at all :/

**Comment by SeoRoman** [comment]
Closed.... Non-Issue sorry guys :) Thanks though!

**Comment by JosephSilber** [comment]
What was it?
