### ISSUE TITLE
Bouncer::can(.. returns alyways true

### ISSUE THREAD

**Issue by birkansava** [JosephSilber/bouncer#340]
I have;
roles : Admin, Moderator
abilities like: All abilities, Create user, show user, update user, delete user.

I give Admin role `manage everything` so it has all abilities.

then I give Moderator role only `show user, update user` abilities.

I logged in as Moderator and when i check in Middleware like:

Bouncer::can("show-user"), it always returns true. 

I've checked that `auth()->user()->getAbilities()`

this returns 3 abilities: All abilities, show user, update user. But i didnt give that role All abilities. I also check my database table and there is no problem. Why it returns All abilities for each roles even i didnt give manage everything permission?

EDİT:
When role has no abilities. It still returns true and when i check getAbilities. All Abilities is still there.

**Comment by JosephSilber** [comment]
Can you paste here a dump of your database for the Bouncer tables?

**Comment by birkansava** [comment]
Roles: 
![roles](https://user-images.githubusercontent.com/11615945/45091613-b85aec80-b11b-11e8-879f-d1eb675c2b2d.PNG)

Assigned Roles:
![assigned_roles](https://user-images.githubusercontent.com/11615945/45091611-b85aec80-b11b-11e8-8a9e-f298fa43e391.PNG)

Abilities:
![abilities](https://user-images.githubusercontent.com/11615945/45091612-b85aec80-b11b-11e8-90b9-c2c7fa8d5aa5.PNG)

Permissions:
![permissions](https://user-images.githubusercontent.com/11615945/45091616-b85aec80-b11b-11e8-99af-8c4ef6673ac8.PNG)

as you see; 

User 91 is an Editor. 
Editor has only pages/sliders CRUD permission.

User 68 is an Admin,
Admin has All abilites.

First i didnt give User 91 any roles/abilities. But It still has "All abilities".
Then I gave User 91 an editor role. It still has "All abilities" when I run $user->getAbilities().

**Comment by birkansava** [comment]
Now, I added a new role (sales) and assign to new User (id.92)

I ran `$user->getRole()` and getting `sales ` role its fine.

But when I run `$user->getAbilities();` for this user. I'm getting abilities of `editor `role.

I don't know does it matter or not but I also use `dontCache()`.

**Comment by JosephSilber** [comment]
Why are you setting the `level` property on the roles?

Roles always have all abilities of other roles with a lower level.

**Comment by birkansava** [comment]
Uh.. Thank you so much. I didnt think of it like that :/ now removed levels and it solved.
