### ISSUE TITLE
Issue with the migration for rc2

### ISSUE THREAD

**Issue by krismanning** [JosephSilber/bouncer#342]
Just upgraded to Laravel 5.7 and trying to upgrade Bouncer. Getting the following error when running the migration file...

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right synta
  x to use near 'json null default '{}'' at line 1 (SQL: alter table `abilities` add `options` json null default '{}')`

My migration file looks like this....

```php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class UpgradeBouncerToRc2 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('abilities', function (Blueprint $table) {
            $table->json('options')->default('{}')->nullable();
        });

        Schema::table('assigned_roles', function (Blueprint $table) {
            $table->integer('restricted_to_id')->unsigned()->nullable();
            $table->string('restricted_to_type', 150)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
```

**Comment by krismanning** [comment]
I've poked around and it looks like MariaDB 10.1 doesnt have a JSON datatype. Looks like I'll have to upgrade to 10.2 for that.

**Comment by JosephSilber** [comment]
Yup. You have to upgrade your MariaDB to get support for JSON.
