### ISSUE TITLE
RC2 Migration Fails - JSON column cannot have default value

### ISSUE THREAD

**Issue by vmitchell85** [JosephSilber/bouncer#343]
When attempting to migrate the database I get the following error:

`SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'options' can't have a default value (SQL: create table 'abilities' ('id' int unsigned not null auto_increment primary key, 'name' varchar(150) not null, 'title' varchar(255) null, 'entity_id' int unsigned null, 'entity_type' varchar(150) null, 'only_owned' tinyint(1) not null default '0', 'options' json null default '{}', 'scope' int null, 'created_at' timestamp null, 'updated_at' timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

I'm running MySQL 5.7.22 and I found the following in the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/json.html):

`A JSON column cannot have a default value.`

It seems like the fix would be just to remove the default value that is set in the migration.

**Comment by looksystems** [comment]
Same here. 

See also: https://github.com/laravel/framework/issues/16107

**Comment by bkuhl** [comment]
It also doesn't make sense to define a default _and_ a nullable column.

**Comment by JosephSilber** [comment]
1. [Updated the RC2 release notes](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-rc.2).

1. [Changed Bouncer's migration file](https://github.com/JosephSilber/bouncer/commit/18681f32d6a3b29600f8416debe07bee3aafd0f9).

1. [Tagged a new release](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-rc.3).

Thanks for reporting this :+1:
