### ISSUE TITLE
Recommended way of adding new roles/abilities later in an apps lifecycle?

### ISSUE THREAD

**Issue by jasonlewis** [JosephSilber/bouncer#344]
Great work on the package mate!

Just a general question I hope hasn't been asked too many times. A cursory search didn't give me much.

How would you recommend a new role with abilities is added once an app is beyond that initially stage and is out in the wild. Another seeder? Migration? Or some other method?

Cheers.

---

Just for clarification I understand the initial roles/abilities is recommended to be done within a seeder.

**Comment by JosephSilber** [comment]
It depends on who defines those roles:

- If you allow your users to create their own roles, then the role will of course be created in that request.

- If you as the developer define all roles, then yes: seeders are the correct place for this.
