### ISSUE TITLE
Cross-request caching does not work as expected

### ISSUE THREAD

**Issue by sebdesign** [JosephSilber/bouncer#347]
Bouncer version: 1.0.0-rc3
Laravel version: 5.7.3

Hi @JosephSilber ,

I recently upgraded to Laravel 5.7 and I noticed that the cache does not work anymore.
What I mean is that even with the cache enabled, Bouncer is still making queries to resolve the abilities at the Gate.

Here are some thoughts after my investigation:

1. Bouncer's service provider is registering and booting.
The `boot` method calls `registerAtGate`, which resolves the `Gate` singleton and a `Sliber\Bouncer\Clipboard` instance, and then the Clipboard registers its before/after callbacks in the `Gate`, via the `Clipboard::registerAt()` method.

2. In my code, I'm calling `Bouncer::cache()` in the `AuthServiceProvider`'s `boot`method.
By calling the Bouncer facade, Laravel resolves the `Bouncer` singleton for the first time, which is created through the `Silber\Bouncer\Factory`.
The factory uses a **new** `Sliber\Bouncer\Clipboard` instance, as well as the `Gate` singleton.

3. When the `create` method of the factory is called, this `Clipboard` instance registers its before/after callbacks in the `Gate`, via the `Clipboard::registerAt()` method. Now the `Gate` has two before callbacks, and two after callbacks.

4. Then, the `cache` method is called, which is instantiating a `Silber\Bouncer\CachedClipboard` instance with the `before` slot from the previous clipboard. The `CachedClipboard` instance is then bound into the container, and set to the Bouncer singleton.

So at this point the Bouncer instance has a `CachedClipboard` instance, but the Gate has two sets of callbacks which are bound on two `Silber\Bouncer\Clipboard` instances which are not being used by the Bouncer instance anymore. As a result, for each ability check the queries are performed **twice**, and the cache is **never** used.

However when I use the `isA()`, `isAn()` methods on the user, the `CachedClipboard` is being used.

I believe this issue is related to #345.

**Comment by JosephSilber** [comment]
Wow. Thanks for all the details :+1: 

It seems like calling `Bouncer::cache()` from the service provider's `register` method should solve it all, no?

**Comment by JosephSilber** [comment]
Hmmm. Ok. I'll look into it.

**Comment by raysn0w** [comment]
@sebdesign did you find a workaround for this? I really like this package but it's slowing down my app considerably when checking several "@cans" in my blade templates.

**Comment by JosephSilber** [comment]
I have a fix in the works. Should be out in a few days.

**Comment by JosephSilber** [comment]
Here's a PR that fixes this issue #359.

If any of you want to test it, change your composer's Bouncer dependency to `dev0clipboard-fix` and run `composer update`.

Please report back with your findings.

**Comment by JosephSilber** [comment]
Yep. I missed that. Thanks for spotting it. Will update soon.

**Comment by JosephSilber** [comment]
@sebdesign I just pushed some changes. Want to try again?

:pray:

**Comment by sebdesign** [comment]
@JosephSilber Now I got another error :)

Illegal offset type in isset or empty
...vendor/laravel/framework/src/Illuminate/Container/Container.php:1088

Maybe we should add some tests for the service provider?

**Comment by sebdesign** [comment]
Actually this is not happening in the service provider.

The stack trace shows that I'm calling `isAn()` and then `$clipboard = $this->getClipboardInstance();` is failing.

**Comment by JosephSilber** [comment]
I made a bad assumption 😔

I moved the clipboard registration out of the service provider, into the bouncer factory. However, the bouncer factory is only called in the callback to the container registration, which in turn is only called the first time you use the Bouncer class.

It seems like you're checking roles directly without constructing bouncer first.

I'll have to tweak this a little.

Thanks for the help 👍

**Comment by JosephSilber** [comment]
I've cleaned up that PR. Please try again.

**Comment by sebdesign** [comment]
Great! Everything works fine now. I've tried with and without cache.
Thanks for your good work! 🥇

**Comment by cschra** [comment]
@JosephSilber will you do a realease for the "older" Laravel versions that fixes this? Or will this fix go into the 5.5+ compatibility release?

**Comment by JosephSilber** [comment]
I published RC4 this morning, with the same compatibility as RC3.

https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-rc.4

**Comment by mrajabtech** [comment]
@JosephSilber You, sir are a legend.
