### ISSUE TITLE
Laravel 5.2 Trait 'App\HasRolesAndAbilities' not found 

### ISSUE THREAD

**Issue by JimLfe** [JosephSilber/bouncer#35]
I've set up a new Laravel 5.2 and just installed bouncer, but when I want to do the migrations I get the error:

```
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Trait 'App\HasRolesAndAbilities' not found               
```

Probably I have to do something else in the User model, because the installation docu seems not to be updated to Laravel 5.2.. it says to change the usermodel to:
```
use Silber\Bouncer\Database\HasRolesAndAbilities;

class User extends Model
{
    use HasRolesAndAbilities;
}
```

but in Laravel 5.2 the user model extends the Authenticable class:
```
class User extends Authenticatable
{
```

I'm using "silber/bouncer": "^0.1.2"

Thanks for help.

**Comment by Arcesilas** [comment]
Hi, 

You  should  judt add the trait in your user model, whatever class it extends.

**Comment by JimLfe** [comment]
Thanks.
