### ISSUE TITLE
[Silber\Bouncer\Contracts\Clipboard] is not instantiable. (Non Laravel)

### ISSUE THREAD

**Issue by YuiLingo** [JosephSilber/bouncer#354]
May i know what reason cause the code below will throw [Silber\Bouncer\Contracts\Clipboard] is not instantiable exception.

```
require_once "./vendor/autoload.php";
require_once './Database.php';
require_once './User.php';

use Framework\Database as Database;
use Silber\Bouncer\Bouncer;
use App\Models\User;
new Database();


$user = User::find(1);
$bouncer = Bouncer::create($user);
$bouncer->useUserModel(User::class);

$admin = $bouncer->role()->firstOrCreate([
    'name' => 'admin',
    'title' => 'Administrator',
]);

$permissions = [
    [
        'name' => 'add-users',
        'title' => 'Add User',
    ],
    [
        'name' => 'edit-users',
        'title' => 'Edit User',
    ],
    [
        'name' => 'view-users',
        'title' => 'View User',
    ]
];
foreach($permissions as $index => $permission) {
    $ability = $bouncer->ability()->firstOrCreate($permission);
    $bouncer->allow($admin)->to($ability);
}
$user->assign('admin');

$abilities = $user->getAbilities();
var_dump($abilities->toArray());
```

But i change this `use Silber\Bouncer\Contracts\Clipboard;` to `use Silber\Bouncer\Clipboard;` in HasRoles.php then can run already. Means i need create a new HasRoles class for use?

**Comment by JosephSilber** [comment]
The clipboard contract is not bound in the container.

It should really be bound automatically. It's an oversight that it doesn't (when not used with Laravel). I'll fix it.

For now, you can bind it yourself:

```php
use Silber\Bouncer\Contracts\Clipboard;

Container::getInstance()->instance(Clipboard::class, $bouncer->getClipboard());
```

**Comment by YuiLingo** [comment]
> The clipboard contract is not bound in the container.
> 
> It should really be bound automatically. It's an oversight that it doesn't (when not used with Laravel). I'll fix it.
> 
> For now, you can bind it yourself:
> 
> ```
> use Silber\Bouncer\Contracts\Clipboard;
> 
> Container::getInstance()->instance(Clipboard::class, $bouncer->getClipboard());
> ```

Thanks for reply. It works.

**Comment by YuiLingo** [comment]
> Keeping this open till I get to fix it.

Ok, Thanks.

**Comment by dbrw** [comment]
Hi, how about pimple? It doesn't have `instance()` method in it. This is what I have in my code:

```php
$container[Silber\Bouncer\Contracts\Clipboard::class] = function($c) {
    return $c->get('bouncer')->getClipboard();
};

$container['bouncer'] = function($c) {
    $bouncer = Silber\Bouncer\Bouncer::create();
    $bouncer = $bouncer->useUserModel(App\Model\User::class);
    return $bouncer;
};
```

It was okay with rc-1.

**Comment by JosephSilber** [comment]
@dbrw If you're using Eloquent, you're [already pulling in Laravel's container](https://github.com/illuminate/database/blob/84beb856e86272626c745ad8138ea4c17014b676/composer.json#L19), so I'm not sure what you're asking, or why you'd need Pimple.

Regardless, I don't think anything in `master` (outside of the service provider, which you're not using) is calling `instance`. Does `master` work for you? I plan on tagging that shortly.

**Comment by JosephSilber** [comment]
I'm closing this for now, since the `Factory` class [now registers the clipboard at the container](https://github.com/JosephSilber/bouncer/blob/32d6c0864d41d0ac0aa5ea75ad869030a5041d0d/src/Factory.php#L70).

@dbrw if you still need help with anything, feel free to open a new issue.
