### ISSUE TITLE
Blade templates

### ISSUE THREAD

**Issue by aronzillo** [JosephSilber/bouncer#36]
Do you have directives to use in blade templates? or it isn't necessary
For example: 

```
@role('admin')
    <p>I'm an admin</p>
@endrole
```
```
@permission('create-user')
    <p>I can create users.</p>
@endpermission
```
```
@ability('admin,owner', 'create-user,edit-user')
    <p>Edit data</p>
@endability
```

**Comment by JosephSilber** [comment]
Bouncer works directly with Laravel's gate, so you can use the @can directive:

@can ('ability', $model)

I consider checking for roles directly an anti-pattern, so we don't ship an @is blade directive.

If you insist on checking directly for a role, you can use the standard @if directive:

@if ($user->is('admin'))

**Comment by aronzillo** [comment]
Okay, you have reason. It is not neccesary repeat code. Thank you!

**Comment by Gummibeer** [comment]
If you want this you can do it your own with a _BladeServiceProvider_ and add this blade tag.

But I also don't see any real reason to add this in the package.

**Comment by Gummibeer** [comment]
https://laravel.com/docs/5.2/blade#extending-blade

**Comment by JosephSilber** [comment]
To reiterate, I consider checking for roles directly something that shouldn't really ever be done. To quote the docs:

> Generally speaking, you should not have a need to check roles directly. It is better to allow a role certain abilities, then check for those abilities instead. If what you need is very general, you can create very broad abilities. For example, an `access-dashboard` ability is always better than checking for `admin` or `editor` roles directly.

Like I said above, if you still want to check for a user's role directly, you can use this:

````
@if ($user->is('admin'))
    // $user is an admin
@endif
```

**Comment by Arcesilas** [comment]
> For example, an access-dashboard ability is always better than checking for admin or editor roles directly

I think that this is precisely the reason why there is a `@can` blade directive and no `@role` by default in Laravel.

**Comment by JosephSilber** [comment]
@Arcesilas Laravel's own ACL has no notion of a role, so it wouldn't make sense for Laravel to ship a `@role` directive.

**Comment by Arcesilas** [comment]
Ahem... You're right ^^ Sorry, tired nowadays...
