### ISSUE TITLE
Issue events on granting/revoking permissions

### ISSUE THREAD

**Issue by manraf** [JosephSilber/bouncer#361]
Hi there,
in order to keep a detailed audit trail of permissions granted/revoked to/from users, it would be useful to trigger events whenever permissions and roles are granted or revoked. Since this is internally done with attach() and detach(), the standard Laravel events (updated etc.) are not triggered.

Let me know what you think of it and if you'd accept a corresponding pull request.

Cheers,
Manuel

**Comment by JosephSilber** [comment]
This sounds like a good idea, for which I'd probably accept a well-formed PR :+1:

1. This has to be completely optional. Bouncer works outside of Laravel, so the `events` package might not even be loaded.

1. The event should only broadcast the ability's ID, not the full model. We don't want to have to fetch all models when handling many abilities at once, such as when syncing abilities.

**Comment by JosephSilber** [comment]
I'm closing this for now. Feel free to submit a PR whenever you get around to it.
