### ISSUE TITLE
Migration fails with a syntax error or access violation

### ISSUE THREAD

**Issue by freddieRv** [JosephSilber/bouncer#362]
This error has already been reported on #352. The user decided to close the issue because he/she found a workaround. However I think this issue should still be addressed by the mantainers.

Here the error:

```
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You 
have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for 
the right syntax to use near 'json null, `scope` int null, `created_at` timestamp null, `updated_at` 
timestamp' at line 1 (SQL: create table `abilities` (`id` int unsigned not null auto_increment primary key, 
`name` varchar(191) not null, `title` varchar(191) null, `entity_id` int unsigned null, `entity_type` 
varchar(191) null, `only_owned` tinyint(1) not null default '0', `options` json null, `scope` int null, 
`created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 
'utf8mb4_unicode_ci')

    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

```

**Comment by JosephSilber** [comment]
The answer is the same as it is there: you have an old version of Maria that doesn't support JSON columns.

You have one of two choices:

1. Upgrade your database.
2. Edit the published Bouncer migration file. Change the json colimn to be a strong column.

**Comment by JosephSilber** [comment]
The answer is the same as it is there: you have an old version of Maria that doesn't support JSON columns.

You have one of two choices:

1. Upgrade your database.
2. Edit [the published Bouncer migration file](https://github.com/JosephSilber/bouncer/blob/32d6c0864d41d0ac0aa5ea75ad869030a5041d0d/migrations/create_bouncer_tables.php#L25). Change the `json` column to be a `string` column.
