### ISSUE TITLE
[Question] - Get entities where the user have an ability

### ISSUE THREAD

**Issue by Surt** [JosephSilber/bouncer#365]
Hi all,

I'm getting a little frustrated triying to filter my models lists for the logged user.

Lets say I'm logged with an user and I'm listing all `Post::class` that this particular user can "view".

First I tried (https://github.com/JosephSilber/bouncer/issues/222#issuecomment-336721942) mapping the `Post` collection, adding an "isAllowed` property, using `Bouncer::allows` but this adds a lot of queries... I don't like this even with cached abilities. 

Then I tried (https://github.com/JosephSilber/bouncer/issues/222#issuecomment-335846810) but this users can own or just view... I just want the post that the user can "view", but I would like to check vs manage, own, view too. 

So, it's ok, my permissions are setted, but I want to use them and avoid unnecessary queries. You all are using the library, how did you solve this?

P.D. I miss an entire section about this on the documentation.

**Comment by Surt** [comment]
I've created this, based on https://github.com/JosephSilber/bouncer/issues/222#issuecomment-335846810

```php

trait hasPolicies
{
    public function scopeIsAllowed($query, $user)
    {
        $model = static::class;
        $canOwn = $user->getAbilities()->contains(function ($ability) use ($model) {
            return $ability->only_owned && $ability->entity_type == $model;
        });

        $ids = $user->getAbilities()
            ->where('entity_type', $model)
            ->where('entity_id', '!=', null)
            ->pluck('entity_id');

        return ($user->isAn('admin')) ? $query : $query->whereIn('id', $ids)->when($canOwn, function ($query) use ($user) {
            $query->orWhere('user_id', $user);
        });
    }
} 

```

So I can now assign the trait to any model and use the scope when I want to filter. Anyway I'm not taking care of the ability that I want to check ...
```
example: 
Post::isAllowed(auth()->user())->get()
```

**Comment by JosephSilber** [comment]
Bouncer's full authorization features sometimes require running some things on the application side, so Bouncer can't ship with such a query scope.

People that only use a subset of Bouncer's features can of course create their own query scopes, based on the features they themselves use.
