### ISSUE TITLE
authorizeResource fails after upgrade laravel 5.7

### ISSUE THREAD

**Issue by carlituxman** [JosephSilber/bouncer#366]
After upgrade to laravel 5.7 from 5.6

al construct of controller I have:

$this->authorizeResource(MyModel::class);

the exception is: Class 'mymodel' not found (see the class model is lowercase)
at : /vendor/silber/bouncer/src/Database/Queries/AbilitiesForModel.php40

**Comment by JosephSilber** [comment]
Which version of Bouncer are you using?

**Comment by carlituxman** [comment]
Last rc4. But it's solved. Sorry.
