### ISSUE TITLE
Is there a way to scope only a single query?

### ISSUE THREAD

**Issue by swvjeff** [JosephSilber/bouncer#368]
I'm using scopes in my application and have a need to manage roles for a user of one tenant while scoped to another tenant. I've looked through the documentation and issues but can't find any way to do this. Something like the following would be wonderful:

```php
Bouncer::temporarily()->scope($tenantId)->assign($role)->to($user);
```

or 

```php
Bouncer::temporarilyScope($tenantId)->assign($role)->to($user);
````

I dunno what the syntax would be, but is something like this currently possible? Or is the only way to currently achieve this by doing the following:

```php
Bouncer::scope()->to($tempTenantId);
Bouncer::assign($role)->to($user);
Bouncer::scope()->to($originalTenantId);
```

**Comment by swvjeff** [comment]
As a follow up, is there an elegant way to get the current scope? I'm currently using this, but it seems horribly hacky.

```php
array_get(Bouncer::scope()->getAttachAttributes(), 'scope');
```

**Comment by sebastiaanluca** [comment]
Same request here, but in a somewhat different setup. For instance, in a view I'm checking both global, non-scoped permissions and local, scoped permissions. Once Bouncer's scope has been enabled, any role or ability check coming after it will be scoped. There's no option to scope only one check, while that is quite common (at least in our app).

So I've built a simple proxy class (similar to Laravel's higher order collection methods) that scopes the call, fetches the value of the check (e.g. `can('ability')`), resets the scope, and then returns the value. Problem is, I can't seem to reset the scope either? Setting it to `null` doesn't clear it for some reason. Any advice on that?

**Comment by sebastiaanluca** [comment]
5 seconds after I posted this I found it lol. Misinterpreted the contents of the `scope` method. Resetting it can be done by passing a new scope.

I've made a simple gist to illustrate my setup. Can anyone test them in their project and report their findings? A simple tests allows me to temporarily scope single calls.

https://gist.github.com/sebastiaanluca/00928469f666ec2c73df2da6ac66a5f4

**Comment by ce-brex** [comment]
@sebastiaanluca You don't necessarily need to reinitialize a new scope class, which would replace any custom scope class you may be using.  You can pass NULL to the to() method to reset the scope. `Bouncer::scope()->to(null)`

**Comment by ce-brex** [comment]
@swvjeff You can create a custom scope class, and have a method that changes the scope, runs a callback, and returns the original scope.

```
public function temporaryTo($scope, $callback)
{
    $originalScope = $this->scope;

    $this->to($scope);

    $result = $callback();

    $this->to($originalScope);

    return $result;
}
```

```
Bouncer::scope()->temporaryTo($tenantId, function () use($role, $user) {
    Bouncer::assign($role)->to($user);
})
```

**Comment by JosephSilber** [comment]
Just pushed an update that would allow you to run a callback with a different scope:

```php
Bouncer::scope()->onceTo($tenantId, function () {
	//
});
```

...as well running it without a scope completely:

```php
Bouncer::scope()->removeOnce(function () {
	//
});
```

**Comment by guiassemany** [comment]
Hi Guys, is this working? I am getting Call to undefined method when using onceTo method.

**Comment by JosephSilber** [comment]
It's currently only in master.

**Comment by guiassemany** [comment]
Thank you :)
