### ISSUE TITLE
How to approach customizing table names?

### ISSUE THREAD

**Issue by marcusmoore88** [JosephSilber/bouncer#37]
Hello!

I was browsing this repository and thinking about how I can integrate the package into a project I'm working on. A thought that came to mind is how to approach customizing table names. I need to namespace my tables (`projectname__abilities`) in my case. 

I was wondering what your thoughts on this might be.

Thanks!

**Comment by Gummibeer** [comment]
I think that it will help to create & Register custom models and edit the Migrations. This should solve all problems!?

**Comment by marcusmoore88** [comment]
Thanks, I think that would work as well but if there were a way to configure it within the package it might be helpful. I was just wondering what the maintainer's thoughts were.

**Comment by Arcesilas** [comment]
Hi,

I think that what you need is simply use the `prefix` configuration option : https://laravel.com/docs/5.2/database

**Comment by jonagoldman** [comment]
The prefix config will affect the whole application, not sure that will fit.

I had similar customization needs https://github.com/JosephSilber/bouncer/issues/21, https://github.com/JosephSilber/bouncer/issues/22, but there is no config file and won't be so you have two options: 
1) Extend every class you need to change from Bouncer.
2) Fork the repo and make your changes.

I personally choose option 2, as flexibility and customization is very important to me, the drawback is that you need to keep update with the main repo and merge every now and then.

**Comment by JosephSilber** [comment]
@marcusmoore88 I originally didn't plan on allowing tables to be overridden, since it adds a lot of complexity to the package.

However, I see that I've miscalculated how important this is; I've been getting a lot of requests for this lately.

I've now implemented it in https://github.com/JosephSilber/bouncer/commit/7f42e98ac42325168b37f93d61c396d42f9b2165. Use it like this in your `AppServiceProvider`'s `boot` method:

```php
Bouncer::tables([
    'abilities' => 'projectname__abilities',
]);
```

add whichever tables you want to override.

Please test it out and let me know if it works for you.

**Comment by marcusmoore88** [comment]
@JosephSilber I totally missed the previously mentioned and closed issues that @jonagoldman mentioned. Sorry for bringing it up again but I see that you might be changing your mind on  this.

I should have time this afternoon to test your commit and give you feedback. Thanks for the response. It is appreciated.

**Comment by marcusmoore88** [comment]
@JosephSilber that worked. I made a small change [here](https://github.com/JosephSilber/bouncer/pull/38) but didn't run the tests to make sure nothing else broke.

**Comment by JosephSilber** [comment]
Yeah. Merged now. Thanks.

**Comment by JosephSilber** [comment]
@marcusmoore88 if your issue has been resolved, please close this. Thanks.

**Comment by marcusmoore88** [comment]
Yes we are good to go. Thank you.
