### ISSUE TITLE
php artisan migrate error

### ISSUE THREAD

**Issue by bhdrnzl** [JosephSilber/bouncer#370]
`   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in yo
ur SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json n
ull, `scope` int null, `created_at` timestamp null, `updated_at` timestamp' at line 1 (SQL: create table `abilities` (`i
d` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `title` varchar(191) null, `entity_id
` int null, `entity_type` varchar(191) null, `only_owned` tinyint(1) not null default '0', `options` json null, `scope`
int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unico
de_ci')

  at C:\xampp\htdocs\handicraft\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; chec
k the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `scope` int nu
ll, `created_at` timestamp null, `updated_at` timestamp' at line 1")
      C:\xampp\htdocs\handicraft\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

  2   PDO::prepare("create table `abilities` (`id` int unsigned not null auto_increment primary key, `name` varchar(191)
 not null, `title` varchar(191) null, `entity_id` int null, `entity_type` varchar(191) null, `only_owned` tinyint(1) not
 null default '0', `options` json null, `scope` int null, `created_at` timestamp null, `updated_at` timestamp null) defa
ult character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      C:\xampp\htdocs\handicraft\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

  Please use the argument -v to see more details.`

**Comment by JosephSilber** [comment]
Closing this as a duplicate.

See here: https://github.com/JosephSilber/bouncer/issues/362#issuecomment-431671000
