### ISSUE TITLE
Authorization on Multiple Systems 

### ISSUE THREAD

**Issue by guiassemany** [JosephSilber/bouncer#371]
Hi Guys! 

First of All, sorry if I am posting this at the wrong place.

I need to create a central login system that will provide authentication and authorization for multiple systems (inside the same laravel installation). Is it possible to define a different set of roles and permissions for each system in the app? (systems will be a differente "Module" from this package: https://github.com/nWidart/laravel-modules)

If you could point me on the right direction, that would be awesome! Thank you!

Edit 1 
Its not like multi tenancy. Each module will have different tables and migrations. They will share only the users table, but each user can have differente roles/permissions on each system. Some may not even be able to see some modules.

**Comment by stasgar** [comment]
If i understood you correctly:
1) You could extend default bouncer migrations with something like 'module_id' row and define this row on buncer's models creation event with Laravel observers. For the interfaces - you can extend the default bouncer _HasRolesAndAbilities's (HasRoles, HasAbilities)_ trait.
2) If your moduled user types are fixed or they will only be extended as a code change - you can create different user models extending from your main one, or has it as a dependency, i believe the default bouncer should suit your needs without extra configuration in this case.

**Comment by guiassemany** [comment]
Thank you very much! I think I will follow your suggestion :)

**Comment by guiassemany** [comment]
Hi @stasgar ! How can I extend bouncer to "scope" or "filter" roles and abilities by the module field? Thank you again!

**Comment by JosephSilber** [comment]
It's not clear to me why a regular scope wouldn't work...?

```php
Bouncer::scope()->to($moduleId);
```

**Comment by guiassemany** [comment]
Hello @JosephSilber ! 
I am started to develop this app again. I think you are right.
But I have a few questions that maybe you could help me :)

1 - What is the best way to create a role or ability and give it a scope? Just pass it on the array?
2 - Why is the scope a number? Could it be a string?

Thank you very much!

**Comment by JosephSilber** [comment]
1. Any role or ability created while a scope has been applied will automatically have that scope:

    ```php
    Bouncer::scope()->to($moduleId);
    // Now create your role/ability as you always would
    ```

1. By default the scope is a number, because most people use the scope as a reference to a tenant ID in the database.

    You are of course free to change the column's type in your migrations to whatever you want. A string will work fine just the same.
