### ISSUE TITLE
[Question] How does Bouncer work on apiResource middleware?

### ISSUE THREAD

**Issue by guice** [JosephSilber/bouncer#375]
Honestly, this is a question, but I can't find anywhere in the docs of a forum to ask. Sorry. How does Bouncer work in `apiResource` context:

```php
    Route::apiResource('campaign', 'Api\PermissionsCheck\CampaignController')
        ->middleware(['permission:campaign']);
```

It is possible to use this, but then add in a series of checks for each resource call: GET [list], GET [singular], PUT, POST, DELETE?

What I'm after: 
 - Assign a person to the ability to hit campaigns, but then limit whether they can view A campaign, a list of campaigns, create/modify, or delete.

_Or_ Do I need to assign the middleware permission for each action individually?

**Comment by JosephSilber** [comment]
I've written about this before.

Here's the link: https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3#authorizing-a-full-resource-controller

Let me know if that answers the question for you.
