### ISSUE TITLE
Role::disallow() does not apply scope

### ISSUE THREAD

**Issue by ce-brex** [JosephSilber/bouncer#376]
When running Role::disallow() to remove an ability from a role, the scope is not applied to the query.

**Comment by ce-brex** [comment]
Looks like Role::unforbid() may have the same issue.

**Comment by dwt11** [comment]
The same problem was encountered.

**Comment by JosephSilber** [comment]
I just pushed a fix.

You can test it now in master, by updating your `composer.json`'s bouncer dependency to `dev-master` and running `composer update`.

Please let me know if this change fixed it :pray:

**Comment by ce-brex** [comment]
This does indeed apply the scope to Role::disallow(), however it also includes the `scope is null` condition which may include too many records.  In my use case, I want to only disallow abilities for a role under a specific scope, not including non-scoped records.
