### ISSUE TITLE
How to allow user to own their own user model?

### ISSUE THREAD

**Issue by jamesbeamingwhite** [JosephSilber/bouncer#379]
```php
Bouncer::allow($user)->toOwn(User::class);
```

This does not allow me to, say, view my own user model when using `$this->authorize('show', $user)` on the `show()` method of my `UserController`.

Is `toOwn()` not an "everything" like you see with the superadmin example in the docs?

```php
Bouncer::allow('superadmin')->everything();
```

**Comment by jamesbeamingwhite** [comment]
Okay looks like I solved my own question here.

Dropping ```Bouncer::ownedVia(User::class, 'id')``` in ```AppServiceProvider``` did the trick.

**Comment by kodeFant** [comment]
Hi! Was adding that to line AppServiceProvider enough to make the user able to own its own model?

I got this error message when trying to do that:
"Non-static method Silber\\Bouncer\\Bouncer::ownedVia() should not be called statically",
