### ISSUE TITLE
Feature Request - getRoleTitles()

### ISSUE THREAD

**Issue by ant-g** [JosephSilber/bouncer#381]
My use case is to list for the user the roles that they have been assigned, so  `$user->getRoles()` does the job.  

But it returns the role name not the role title.  For display purposes it would be better to have access to the role title.

**Comment by JosephSilber** [comment]
The `User` model has a regular Eloquent `roles` relationship, on which you can call the `pluck` method to get any column you want:

```php
$titles = $user->roles()->pluck('title');
```

**Comment by ant-g** [comment]
Ah-ha, simple.  Needless to say I am new to Laravel so didn't think to try this.  Thanks.
