### ISSUE TITLE
Custom Cache Repository for non-laravel projet (Slim3)

### ISSUE THREAD

**Issue by rodmar35** [JosephSilber/bouncer#384]
Hello,

First, thanks for this great repo. 

For a project I'm using slim 3 (with php league container) via this skeleton : [https://github.com/madsem/klever-skeleton](https://github.com/madsem/klever-skeleton)

I success using Bouncer within this skeleton but only without cache. When i active it i'v got problem `Target Illuminate\Contracts\Cache\Repository is not instantiable`  like this issue [https://github.com/JosephSilber/bouncer/issues/330](https://github.com/JosephSilber/bouncer/issues/330) 

Do you think it's possible to replace all Bouncer's cache (Laravel Illuminate Cache Contract and Filesystem) in `vendor/silber/bouncer/src/Bouncer.php`  by a custom one or solution like  [https://github.com/PHPSocialNetwork/phpfastcache](https://github.com/PHPSocialNetwork/phpfastcache)
 
Thanks in advance
Rodmar

**Comment by JosephSilber** [comment]
Bouncer uses Laravel's cache driver interface. For the path of least resistance, use Laravel's cache: `illuminate/cache`.

If for whatever reason you don't want to use Laravel's cache, you should write a wrapper around whatever cache you do want to use. That wrapper should implement the 13 methods in [Laravel's cache interface](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Contracts/Cache/Repository.php).

**Comment by rodmar35** [comment]
Hi JosephSilber,

Finally I managed to use Bouncer cache. 
As the slim skeleton was using already Eloquent, no need to write a wrapper for illuminate cache.

Here my simple code : 
```
$acl_folder_path = base_path('storage/acl/');
$store = new FileStore(new Filesystem, $acl_folder_path);
$bouncer = Bouncer::make()
         ->withCache($store)
         ->create();
```
Thanks a lot for your help
Rodmar
