### ISSUE TITLE
Granted abilities entity_type column change after rc.1

### ISSUE THREAD

**Issue by dizco** [JosephSilber/bouncer#386]
I'm not sure this is an issue with the package itself, but maybe it can help someone...

My installation has been using `v1.0.0-rc.1` for a few months, with custom table names like so :

```php
Bouncer::tables([
    'abilities' => 'bouncer_abilities',
    'assigned_roles' => 'bouncer_assigned_roles',
    'permissions' => 'bouncer_granted_abilities',
    'roles' => 'bouncer_roles',
]);
```

After updating to `v1.0.0-rc.4`, and following the migration steps from [the releases](https://github.com/JosephSilber/bouncer/releases), I ran into issues with authorization. It appeared like the granted abilities for any user were always empty, even though there were some. 

Eventually, I figured out that the `bouncer_granted_abilities` table contains a column with `entity_type`, which used to be set to `roles` for all my rows, but now it needs to be set to `bouncer_roles` in order to work. I suspect this might be related to my table names... But couldn't pinpoint the exact breaking change in this repo.

Tested on PHP 7.2.9 and lumen 5.7
```
"require": {
    "php": ">=7.1.3",
    "appzcoder/lumen-routes-list": "^1.0",
    "dusterio/lumen-passport": "^0.2.9",
    "guzzlehttp/guzzle": "^6.3",
    "illuminate/cookie": "5.7.*",
    "illuminate/mail": "^5.7",
    "laravel/lumen-framework": "5.7.*",
    "nordsoftware/lumen-cors": "^2.2",
    "silber/bouncer": "v1.0.0-rc.4",
    "symfony/polyfill-iconv": "^1.10",
    "vlucas/phpdotenv": "~2.2",
    "wn/lumen-generators": "^1.3",
    "znck/belongs-to-through": "^2.3"
},
"require-dev": {
    "fzaninotto/faker": "~1.4",
    "phpunit/phpunit": "~7.0",
    "mockery/mockery": "~1.0",
    "xethron/migrations-generator": "^2.0"
}
```

**Comment by JosephSilber** [comment]
This might be related to #378, for which a fix was already issued.

Can you try your code in master, and see if it's fixed.

If so, I'll tag a new release.

**Comment by dizco** [comment]
Hi @JosephSilber!

What's the new expected behaviour of the fix you pushed? Is it supposed to work with my previous database setup out of the box?

I just tested that by setting my dependency to `"silber/bouncer": "dev-master",` and running `composer update`.
Then, I reverted my database to use the old `roles` value for the `entity_type` column.
I don't notice any change versus before... Still can't seem to fetch the abilities correctly.

**Comment by JosephSilber** [comment]
> I reverted my database to use the old `role`s value for the `entity_type` column.

Why? By default, registering your models with the morph map [will use the table name as the morph type](https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map#customizing-the-morph-type). So your morph types should actually be `bouncer_roles`, not `roles`.

Does that make sense?

**Comment by JosephSilber** [comment]
I'm still not sure what's wrong here.

Using `dev-master` (or manually registering all of the models with the morph map), the values in the type column should be the actual table name.

Are you not experiencing that now? Are the values correct, but the functionality incorrect?

**Comment by dizco** [comment]
Sorry I haven't had time to try again, I will close this issue for now and I will reopen it if it persists after I update. Does that make sense?

Thank you for all your work by the way, it's truly appreciated!
