### ISSUE TITLE
Checking permissions and role based on custom role column

### ISSUE THREAD

**Issue by merfed** [JosephSilber/bouncer#387]
This is sort of confusing to explain, so I hope this isn't too awful. Is there anyway to the permissions check (can, isAn, etc) and force it to also verify that the custom role column is equal to some set variable.

I guess a simpler way, would be, is there a way to force it to use a specific role that I tell it to by giving it an variable which corresponds with a specific column on the roles table, and the user is assigned to it.

**Roles**
```
| id | Title  | custom_column |
|----|--------|---------------|
|1   | Role A | 1             |
|2   | Role B | 1             |
|3   | Role C | 2             |
```

**Abilities**
```
| id | name |
|----|------|
| 1  | view |
```

**Permissions**
```
|ability_id  | entity_id   |
|------------|-------------|
|1           | 1           |
|1           | 3           |
```

**Assigned Roles**
```
| role_id | entity_id  |
|---------|------------|
| 1       | 1          |
| 2       | 1          |
```

So in this above example:
1. User 1 is in Role A and Role B.
2. Role A and Role C has the ability to view.
3. Role B cannot view.

How can I do a `$user->can('view')` where I get the results of Role A  based on the value in ```custom_column ``` and not any of the other roles the user is assigned to or additional roles which may share the same value as ```custom_column ```?

**Comment by JosephSilber** [comment]
It's not exactly clear to me why you'd want to do that, but you can always check permissions on a role directly:

```php
$user->roles()->where('custom_column', 1)->firstOrFail()->can('view', $something);
```

**Comment by merfed** [comment]
I'm using this package for overall site roles, and then as a manger for user created roles within the user created sections of the site. Users can manage their own sections, with roles and permissions unique to those sections. So far, this has been the only hurdle I've run into. This is a very versatile package.

Thanks for the help, I'll give it a go when I get home.
