### ISSUE TITLE
Best way to provide JS with user's abilities?

### ISSUE THREAD

**Issue by francislavoie** [JosephSilber/bouncer#389]
I'll mainly be implementing my frontend with React (same question would apply for Vue, obviously). What's the recommended approach to passing the user's abilities to the frontend so I can conditionally show/hide buttons/links?

Ideally I'd want to be able to do `can()` and whatnot in the frontend as well.

**Comment by AlanGreyjoy** [comment]
Looking for the same thing

**Comment by JosephSilber** [comment]
This is highly dependent on your application.

1. If you only have a small handful of checks you need to run, you can send them along with your initial request:

    ```blade
    @php
    $permissions = [
        'createListings' => $user->can('create', Listing::class),
        'deletePosts' => $user->can('delete', Post::class),
    ];
    @endphp

    <script>
    var App = {
        can: @json($permissions)
    };
    </script>
    ```

1. If your app is more complex, you might want to create an endpoint in your API where you can check permissions:

    ```php
    Route::get('api/authorize', AuthorizationController::class);
    ```

    ```php
    class AuthorizationController
    {
        public function __invoke()
        {
            $ability = request('ability');
            $model = request('model');
            $modelId = request('modelId');

            if ($modelId) {
                $model = $model::findOrFail($modelId);
            }

            return ['allowed' => Gate::check($ability, $model)];
        }
    }
    ```

1. Finally, you can add the authorization checks to all of your API responses, so that the model itself will tell you whether the user has the correct permissions:

    ```php
    class ListingsController
    {
        public function index()
        {
            return Listing::all()->map(function ($listing) {
                $transformedListing = $listing->toArray();

                $transformedListing['can'] = [
                    'view' => Gate::check('view', $listing),
                    'update' => Gate::check('update', $listing),
                    'delete' => Gate::check('delete', $listing),
                ];

                return $transformedListing;
            });
        }
    }
    ```

All of these techniques can be further enhanced and cleaned up. Use any combination of them to achieve what you need in your app :+1:

**Comment by francislavoie** [comment]
Thanks! Very helpful.

**Comment by JosephSilber** [comment]
I should add that for option 2 above, it'd be much better if you're using [Eloquent's morph map](https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map) in your app (which you should anyhow do, for many other benefits).

Using morph maps, the client doesn't have to pass in weird PHP fully qualified class names. Instead, they can pass in the table name, which is much more intuitive:

```
/api/authorize?ability=update&model=listings&modelId=34
                                    ^^^^^^^^
```

Here's an implementation of the controller above, utilizing the morph map:

```php
use Illuminate\Database\Eloquent\Relations\Relation;

class AuthorizationController
{
    public function __invoke()
    {
        return [
            'allowed' => Gate::check(request('ability'), $this->getModel())
        ];
    }

    protected function getModel()
    {
        $className = $this->getModelClassName();

        if (request('modelId')) {
            return $className::findOrFail(request('modelId'));
        }

        return $className;
    }

    protected function getModelClassName()
    {
        $model = request('model');

        $morphMap = Relation::morphMap();

        abort_unless(isset($morphMap[$model]), 404, 'Model type does not exist');

        return $morphMap[$model];
    }
}
```
