### ISSUE TITLE
Is there a way to assign a permission over a subset of a Model?

### ISSUE THREAD

**Issue by ipontt** [JosephSilber/bouncer#390]
The docs say you can do either `$user->assign('permission', Model::class) ` which gives the user the permission over the entire model, or `$user->assign('permission', Model::find($id))` which gives the user the permission over that single resource.

Is there a way to assign a permission to a subset of the model? For example,
`$models = Model::where(condition)->get()
$user->assign('permission', $models)`
That syntax doesn't work right now since $models is a collection and not an Eloquent model but is there a way to do something like this or should I just stuff it all in a foreach loop and give permission one by one?

**Comment by JosephSilber** [comment]
`assign` is used to assign a role to a user.

`allow` is used to grant permission to an ability.

You can pass an array to `allow`, which will grant the ability on all those models:

```php
$models = Model::where($condition)->get();

$user->allow('delete', $models->all());
```

**Comment by ipontt** [comment]
Whoops, mixed `assign` and `allow` in the question.

Thanks for the reply! Passing an **array** instead of a **collection** didn't occur to me. Everything works as expected now. Passing an array also works for `forbid`

Mind if I do a PR later this week? I think the **Cheat Sheet** could use some clarification about this.

**Comment by JosephSilber** [comment]
Sure. Go ahead!

**Comment by ipontt** [comment]
I think we can close this issue then. I'd like to get your opinion on something though. For this example, let's say I've got 

- Two models. **Category** and **Item** where a **category** has many **items**.
- A view where only the **items** are displayed in a list.

For whatever reason, I want to control which items are visible to the users. I do this with the following permissions.

- Allow  `customer` role to view any item belonging to x category. `Bouncer::allow('customer')->to('view-items-of', Category::find($allowed_category_id_array));`
- Allow `customer` role to view any specific item that may or may not belong to an authorized category.
`Bouncer::allow('customer')->to('view', Item::find($allowed_item_id_array));`
- Forbid `customer` role to view any item belonging to a specific category.
`Bouncer::forbid('customer')->to('view-items-of', Category::find($forbidden_category_id_array));`
- Forbid `customer` role to view any specific item that may or may not belong to an authorized category.
`Bouncer::forbid('customer')->to('view-items-of', Item::find($forbidden_item_id_array));`
 
Now I've got two options.
### Option 1: Pass every Item to the view and use a`@can`  or an `@if` directive to filter inside a `@foreach`.

```php
// Controller
public function index()
{
    return view('index', ['items' => Item::all()]);
}
```
```php
// View
@foreach($items as $item)
    @if(Auth::user()->can('view-items-of', $item->category_id) || Auth::user()->can('view', $item->id))
        //
    @endif
@endforeach
```
This approach looks clean but it produces the n+1 problem. The more items I've got, the more Gates need to be checked.

### Option 2: Filter inside the controller (well, inside the user Model really) and pass only authorized Items to the view

```php
// Controller
public function index()
{
    return view('index', ['items' => Auth::user()->getAllowedItemsList()]);
}
```
```php
// User Model
public function getAllowedItemsList()
{
    $abilities = $this->getAbilities();
    $forbidden_abilities = $this->getForbiddenAbilities();

    $allowed_categories = $abilities->where('entity_type', 'App\Category')
        ->where('entity_id', '!=', null)
        ->where('name', 'view-items-of')
        ->pluck('entity_id');
    $allowed_items = $abilities->where('entity_type', 'App\Item')
        ->where('entity_id', '!=', null)
        ->where('name', 'view')
        ->pluck('entity_id');

    $forbidden_categories = $forbidden_abilities->where('entity_type', 'App\Category')
        ->where('entity_id', '!=', null)
        ->where('name', 'view-items-of')
        ->pluck('entity_id');
    $forbidden_items = $forbidden_abilities->where('entity_type', 'App\Item')
        ->where('entity_id', '!=', null)
        ->where('name', 'view')
        ->pluck('entity_id');

    $items = Item::where(function ($query) use ($allowed_categories, $allowed_items) {
        $query->whereIn('id', $allowed_items)->whereIn('category_id', $allowed_categories. 'or');
    })->whereNotIn('id', $forbidden_items)
      ->whereNotIn('category_id', $forbidden_categories)
      ->get();

    /** Translates to following SQL query
     * SELECT * FROM items
     * WHERE
     * (
     *     id IN ($allowed_items)
     *     OR category_id IN ($allowed_categories)
     * )
     * AND id NOT IN ($forbidden_items)
     * AND category_id NOT IN ($forbidden_categories);
     */

    return $items;
}

```
```php
// View
@foreach($items as $item)
    //
@endforeach
```
I can control how many gates are checked with this approach but I needed to make an extra function on the user model to avoid putting that mess on the controller. The view is also cleaner but I still feel as if I'm doing something wrong because of the aforementioned mess.

I'm still thinking of using number 2 but am I complicating things over nothing? What's your opinion on this?

**Comment by JosephSilber** [comment]
> This approach looks clean but it produces the n+1 problem.

As explained [in the docs](https://github.com/JosephSilber/bouncer#cache):

> By default, all queries executed by Bouncer are cached for the current request.

No matter how many times you call the gate, Bouncer won't pull the abilities again.
