### ISSUE TITLE
Disallow All for Model Instance

### ISSUE THREAD

**Issue by tylerwiegand** [JosephSilber/bouncer#392]
Hopefully there's already a way to do this and I just can't find it in the code/docs.

I can successfully add an ability and permission for a specific model.

```
Bouncer::allow($user)->to('edit', $event);
```

But what I foresee needing is the ability to "kick out" a user, or have them opt out of all of their existing permissions for that model only. Currently I can accomplish this with a little SQL, but if there's a Bouncer way to do it, that'd be great!

```
Bouncer::disallow($user)->everything($event);
```
or maybe
```
Bouncer::disallow($user)->to(null, $event);
```

And the goal being leaving the Ability table alone but removing all permissions for that user on that model.

Of course I could just remove each individual permission, but because of the fluent nature of adding permissions (having them created when needed) it would be kinda sad to need to keep an array in the config or something for this stuff.

Anyways, great package, can't wait for 1.0 official!

**Comment by JosephSilber** [comment]
Are you looking to forbid abilities?

https://github.com/JosephSilber/bouncer/blob/master/readme.md#forbidding-an-ability

**Comment by tylerwiegand** [comment]
I greatly appreciate being responded to so quickly. Unfortunately no, I was thinking of that for a different use case.

Forbid I would intend on using when say, an admin is preventing someone from having permissions of any sort, but this would be more of a voluntary leaving situation. Like the difference between someone quitting and being fired -- you don't have access either way, but in one scenario you could get it back easily, in the other you'd need to be "unforbidden" so to speak.

I plan to have a few different abilities per model instance, so forbidding would still need to be done on an individual basis.

For instance...
```
Bouncer::forbid($user)->to('view', $model);
Bouncer::forbid($user)->to('invite', $model);
Bouncer::forbid($user)->to('edit', $model);
```

It would be awesome if I could assign roles on a per-model-instance basis as well, because that would solve THIS problem, but I imagine that'd be a bit more intense. So, if I could use roles like this...

```
Bouncer::allow($role)->to('edit', $post);
Bouncer::disallow($role)->to('edit', $post);
```

then that would be awesome! I can see you have very ambitious plans from reading other closed issues, and I can imagine this might even be on your roadmap already, but it's some things that have come up that I need to work around, and I imagine some other people may benefit as well. I tried to poke around in the code for a bit but I admit I feel I don't really have the experience to suss out how the package even works to suggest a PR =(

Hopefully I'm not asking for something thats painfully obvious, like forbid abilities thought =P

**Comment by JosephSilber** [comment]
> Forbid I would intend on using when say, an admin is preventing someone from having permissions of any sort, but this would be more of a voluntary leaving situation.

There's no reason it can't be used for both.

```php
Bouncer::forbid($user)->everything();
```

> you could get it back easily

If you're saying that the user can re-instate their permissions on their own, then that can be another ability:

```php
Bouncer::allow($user)->to('unforbid', $user);
```

> So, if I could use roles like this
>
> ```php
> Bouncer::allow($role)->to('edit', $post);
> Bouncer::disallow($role)->to('edit', $post);
> ```
>
> then that would be awesome!

This already works.

**Comment by tylerwiegand** [comment]
Again I appreciate you taking time out of your day to answer me. Unfortunately, either my message is not being conveyed properly or the functionality I'm proposing isn't going to be implemented.

I tried to be as specific as possible to explain why I want to use it the way I'd like. Roles aren't scoped to a specific model, and without making a role named "admin-for-post-3" I can't adapt it to my use case.

Thank you for your help, but this is not the way I intend on using it, and maybe I was wrong about not being the only one lol

**Comment by JosephSilber** [comment]
> Roles aren't scoped to a specific model, and without making a role named "admin-for-post-3" I can't adapt it to my use case.

Why do you want to scope roles to a specific model?

**Comment by tylerwiegand** [comment]
In short, because of a difficult client. And hey, maybe I'm not thinking about this whole thing right, but here goes:

Individual Users MUST be able to be individually allowed to have differing permissions for different "events." And when I say event, think more of a...traveling event. So the traveling event would have multiple "managers," and still more "participants."

So we've got our "Trip" model, which I'm assigning permissions to. Then there are site admins. Later still, the client wants to add multi-tenancy (kind of white-labeling the service to different businesses). It's rather ambitious imo, but I'm attempting to keep a lot of the future needs in mind while keeping it very simple for now. Right now, I'm just adding the Trips and allowing users to Manage the trip and travel in it.

I've resigned to the fact that each Permission for a specific trip will need to be individually assigned, but it would be nice to create a few roles like "Trip Participant" and then that person wouldn't be able to say, post updates, but they could see who else is going on the trip. Something like that.

Again, thank you for your continued interest and your prompt replies! I'm rather surprised I've gotten this much attention...heh...

**Comment by JosephSilber** [comment]
> Individual Users MUST be able to be individually allowed to have differing permissions for different "events [...] So the traveling event would have multiple "managers," and still more "participants."

Why does it _have_ to be done via a role? Can't the abilities be granted directly to those users?

**Comment by tylerwiegand** [comment]
I am doing it individually currently, but without the ability to remove all granted permissions to that one model (which is what started this whole thing) assigning them to a role would allow me to assign and revoke compartmentalized groups of permissions instead of manage, say, an array of permissions per role (but not a bouncer role).

So, to accomplish that, I've gotta get all of the users permissions that are related to a specified Trip model and granted to a specified User and delete the entries. Almost got there with $user->abilties()->where... but that also deleted the ability itself, not just the permission, and I didnt see a way to get at just the permissions in a similar way, so DB facade it is!

**Comment by JosephSilber** [comment]
> without the ability to remove all granted permissions to that one model

Like I said, you can accomplish this with `forbid`:

```php
Bouncer::forbid($user)->to('view', $trip);
```

**Comment by tylerwiegand** [comment]
That does it for one granted permission. I want the ability to do it for ALL granted permissions on that model.

**Comment by JosephSilber** [comment]
> I want the ability to do it for ALL granted permissions on that model

Ask, and you shall receive:

```php
Bouncer::forbid($user)->toManage($trip);
```

**Comment by tylerwiegand** [comment]
And then unforbidding needs to take place. Thanks again, but thats not desired behavior.

**Comment by JosephSilber** [comment]
> And then unforbidding needs to take place

Yep:

```php
Bouncer::unforbid($user)->toManage($trip);
```
