### ISSUE TITLE
CachedClipboard.php does not use service container for dependency resolution

### ISSUE THREAD

**Issue by mindfullsilence** [JosephSilber/bouncer#393]
`CachedClipboard@compileModelAbilityIdentifiers($ability, $model)` should use the service container for instantiating the model if needed on ~line 170:

`$model = $model instanceof Model ? $model : new $model;`
When using service contracts, this code breaks because it is not resolving the dependency wiring.

Should be:
`$model = $model instanceof Model ? $model : app()->make($model);`

**Comment by JosephSilber** [comment]
You're saying an Eloquent model should be resolved out of the container?

That makes no sense to me.
