### ISSUE TITLE
 Call to undefined function Silber\Bouncer\app_path() 

### ISSUE THREAD

**Issue by hazeem1991** [JosephSilber/bouncer#395]
Lumen (5.7.7) (Laravel Components 5.7.*)
> Call to undefined function Silber\Bouncer\app_path()

In BouncerServiceProvider.php line 113:

`$target = app_path('Http/Middleware/ScopeBouncer.php');`
**this make error with lumen cuz app_path undefined**

**Comment by JosephSilber** [comment]
The `BouncerServiceProvider` is only meant to be used with Laravel.

If you're using it with Lumen then you should either create your own `app_path` helper function that mimics Laravel's, or follow the instructions for [**Installing Bouncer in a non-Laravel app**](https://github.com/JosephSilber/bouncer/blob/9c3703ba149b07b617a047f64776b873973c2730/readme.md#installing-bouncer-in-a-non-laravel-app).
