### ISSUE TITLE
Will I get any issues when giving multiple abilities the exact same name? (Using only model objects in methods)

### ISSUE THREAD

**Issue by PepijnDeWachter** [JosephSilber/bouncer#398]
A little breakdown: 
in my current project I have added a tree structure to the ability model/table.
the structure I have planned means that I have abilities for my models, which have children that are just called 'view', 'edit', 'delete' and some one-off special permissions that wouldn't exist on all of them, the exact tree has a few more levels to it, but this example should suffice.
This means that I have multiple permissions called 'edit', but I'm not using the names in Bouncer methods, I'm finding them by the id provided by the front-end and then using the nestedset library to find the exact ability 'node(s)' I need, after that I provide the full models to the Bouncer method.

So here's the question: if I always provide full models and never provide names, will Bouncer use the name anywhere potentially matching the wrong ability?

**Comment by PepijnDeWachter** [comment]
While looking in the code I ran into the clipboard using only the name when checking if an ability is allowed at the gate. I've now extended the checkGetId CachedClipboard to use the uuid of the ability before before calling parent::checkGetId with the id instead of the ability model (originally a string)

however while looking through the CachedClipboard class I noticed the following 2 things:

this class does not reimplement its own getForbiddenAbilities method, instead just calling the BaseClipboard method wich runs a query every time the gate gets checked? (I didn't test this specifically, just followed the method calls in phpstorm)

in the method findMatchingAbility there is the following code:

```
if ($this->isOwnedBy($authority, $model)) {
            return $this->getMatchedAbilityId(
                $abilities,
                $applicable->map(function ($identifier) {
                    return $identifier.'-owned';
                })
            );
        }
```
that static '-owned' string seems to only be referenced in this block, now I didn't completely dissect this class but I have a feeling that this would clash with my choice of changing out the name for the id

feel free to give me feedback on this, I realize that what I'm doing isn't the proposed way of handling things, but I'd rather save my tree structure in the database than having to concatenate the 'parents' into the name and building a tree from the strings when sending it to the frontend and working with flat abilities on my table

**Comment by JosephSilber** [comment]
I don't understand what you're doing, or why you even need it.

Regardless, authorization checks at the gate will always use an ability name, so Bouncer will always find the ability by its name.

**Comment by PepijnDeWachter** [comment]
I could easily agree with you that this is heavily outside the scope of any normal application.
The short explanation is that I'm using a rather complex tree structure of pre-defined abilities in my application, which is a rest api that is being made together with a front-end that relies on these abilities to be defined, and because there's so many of them I decided to put them in a tree structure so that they can be 'easily' displayed on a screen.

Most of the ability tree structure actually is almost a direct copy of the routing structure of the front-end (similar to breadcrumbs)

To be honest even though it might not make sense to some people to do it this way, I'm the kind of stubborn person that thinks about an idea that should work, and then makes it work, so I've actually tackled most of the issues already.

The only problem I ran into just now (which should be the last thing I'd need to extend) is the final public function IsAbility::getIdentifierAttribute() (custom attribute accessor)
I totally get why it's final, it prevents accidental overriding, but in my case I actually need to override it
I think I'll temporarily override the magic __get() on my own Ability Model to handle that (I know that it's not the best practice)

So in short, if you don't mind giving me the possibility to override the cache identifier accessor on my Ability Model, I'd appreciate it if you could push a commit where you remove the final keyword from that accessor.
If you'd rather keep that method final I'll just keep using the magic __get().

In any case I guess we can both agree that this is overly complicated and I should've probably looked into using an explode on ordinary ability names to generate a tree structure for the front-end without having parent-child relationships in my database. (although the tree structure helps me to automatically fetch parent abilities to attach to a role when attaching an ability to a role)

Kind regards and thank you for taking the time to read this issue that probably never have existed in the first place.

**Comment by JosephSilber** [comment]
The method was marked final precisely because people were overriding it without realizing that they're breaking Bouncer in the process.

**Comment by PepijnDeWachter** [comment]
> The method was marked final precisely because people were overriding it without realizing that they're breaking Bouncer in the process.

That's what I expected the reason would be, in my case however I want to use the uuid of the ability as the main slug part instead of the name, because in my case that's not unique, I know it's not an ideal scenario, but I do understand your reason for implementing that final keyword and won't further ask you to undo that change, I'll work my way around it.
Thanks for your insights, and to close this issue off, words can't express how thankful I already was and how much more I am now after looking through a bunch of the source, for this well-written and highly extensible permission library.
