### ISSUE TITLE
Meaning of "the gate" in section 1 of readme?

### ISSUE THREAD

**Issue by mikew1** [JosephSilber/bouncer#399]
I've read carefully the entire readme file (which is excellently written) and now installed bouncer.

One point I'm not clear on yet is whether I must add code to laravel's own gates and/or policies for Bouncer to be called when I simply call Gate::, or @can, or whether that is integrated somehow under the hood. I tried to read the relevant source but it's slightly over my head at this point.

Looks like a great package and I'm looking forward to getting going with it.

I am writing this note at this point simply as feedback on the docs, from someone who is about to get started with it.   --- when you say ___the___ gate (quoted below), I don't know what you're referring to -- laravel's gate, or is bouncer thought of as "the" gate in this instance.

> When you check abilities at the gate, the bouncer will be consulted first.

**Comment by JosephSilber** [comment]
> One point I'm not clear on yet is whether I must add code to laravel's own gates [...] or whether that is integrated somehow under the hood.

Everything is wired up under the hood. All of Laravel's code points to check authorization will run through Bouncer automatically.

> when you say the gate (quoted below), I don't know what you're referring to -- laravel's gate, or is bouncer thought of as "the" gate in this instance.

Bouncer doesn't have its own `Gate`. There's only one `Gate`: Laravel's.
