### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalErrorException]   Class 'App\User' not found

### ISSUE THREAD

**Issue by happyDemon** [JosephSilber/bouncer#40]
Using laravel 5.1,
some classes in your Database namespace expect App\User to be present in my installation.

However, my app namespace is different and my models were put in to a folder called 'Models' under the app namespace.

I see that you're just using it as a reference to load the actual user model class. Wouldn't it be better to just use a string instead of a reference.

A lot of applications won't have it present in the App namespace and/or have it available at the top of that namespace.

**Comment by Gummibeer** [comment]
Have you used the `setUsersModel()` method to tell Bouncer where your User model is?
https://github.com/JosephSilber/bouncer/blob/148af1ada52b2628f36eadd25bac8885d241e72a/src/Database/Models.php#L51

**Comment by jonagoldman** [comment]
You should read the repo issues first and check if your question was already asked: https://github.com/JosephSilber/bouncer/issues/21

**Comment by happyDemon** [comment]
This is the exact stacktrace I'm getting:
[2016-01-21 13:18:40] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\User' not found' in /Users/maximkerstens/Desktop/projects/xarona-app/vendor/silber/bouncer/src/Database/Models.php:105
Stack trace:
#0 {main}  


when I correct it to the correct namespace manually, there's no error

**Comment by JosephSilber** [comment]
@happyDemon when you change the `User` model's location, you have to [let Laravel's auth system know about it](https://github.com/laravel/laravel/blob/master/config/auth.php#L70).

Bouncer will use that information to correctly get the model.

**Comment by JosephSilber** [comment]
@happyDemon has this been fixed? If not, can you please provide more information about your isuue?

**Comment by happyDemon** [comment]
It's been fixed, I'm completely baffled why it didn't give an error the second time I installed.
User model's path was correctly filled in for laravel's auth system.
oh well, works now
