### ISSUE TITLE
retract / assign with role_id

### ISSUE THREAD

**Issue by sourcegr** [JosephSilber/bouncer#400]
Hello and congrats for this great piece of software :)

Is it possible to `assign` and `retract` permissions by `role_id` ?

for example, is it possible to write 

`Bouncer::retract($request->role_id)->from($user);`

Thank you.

**Comment by JosephSilber** [comment]
Yep. This already works 👍

**Comment by sourcegr** [comment]
thank you!

**Comment by ctwillie** [comment]
@JosephSilber Any reason why this is not working?
```php
$user = User::first();
$role = Bouncer::role()->first();

$user->assign($role->id);
$user->roles->contains($role->id); // true
$user->isA($role->name); // true

$user->retract($role->id);
$user->roles->contains($role->id); // true
$user->isA($role->name); // true
```
The role assignment works fine with the role id. But retracting the role with the role id is not working. Using the Bouncer facade produces the same result. When using the role name, the assignment and the retracting of the role works perfectly.

- Bouncer: v1.0.0-rc.8
- Laravel: v7.17.2
- mysql: 8.0.20

**Comment by JosephSilber** [comment]
@ctwillie `$user->roles` is a cached Eloquent Collection.

`$user->roles()->get()->contains($role->id)` should be `false`.

**Comment by ctwillie** [comment]
@JosephSilber I see. A little surprised the cache is not updated during the same request. So is the recommendation to always check using role names?
