### ISSUE TITLE
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.

### ISSUE THREAD

**Issue by miklcct** [JosephSilber/bouncer#402]
When I load my app, it throws an `Illuminate\Contracts\Container\BindingResolutionException` with `Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.` in `BouncerServiceProvider::register()` after upgraded my laravel from 5.6 to 5.7

It's because the `registerBouncer()` method try to call `$this->app->make(Gate::class)`, which isn't available before all service providers are registered.

Note that I have overridden `Illuminate\Auth\AuthServiceProvider` as `App\OverridingLibraries\Illuminate\Auth\AuthServiceProvider` and listed it as the first in my `config/app.php`.

**Comment by JosephSilber** [comment]
Which version of Bouncer are you using?
