### ISSUE TITLE
Optimal way to use cache

### ISSUE THREAD

**Issue by Sergzy** [JosephSilber/bouncer#404]
I am interested to use a cross-request cache and was wondering what would be the optimal way to do that? Spatie's package automatically updates cache and I couldn't find anything similar for Bouncer (wouldn't it make sense that cache would be automatically reset, if we use Bouncer::cache()?).

There was proposal (#361) to call an event when Bouncer changes things, but it got nowhere. It would make cache handling much easier.

Can someone give me an advice on how to properly utilize cache and make sure that it always has the latest values?

**Comment by JosephSilber** [comment]
Bouncer currently does not automatically clear the cache for you.

It's planned for the future, but for now you'll have to manually clear the cache when you make changes.
