### ISSUE TITLE
Problem in route

### ISSUE THREAD

**Issue by franviera92** [JosephSilber/bouncer#406]
I have the following code currently:

```
Route::group(['middleware' => 'auth'], function () {    
  

    Route::group(['middleware' => 'can:view,App\User'], function () {
        Route::get('users', 'Admin\UserController@index')->name('users');
        Route::get('users/{id}', 'Admin\UserController@show')->name('users.show'); 
    });
});
```

But I upgraded from silber / bouncer v1.0.0-rc.4 to silber / bouncer v1.0.0-rc.5.

Laravel 5.7 a Laravel 5.8

Now with silber / bouncer v1.0.0-rc.5 the route protection does not work, I get error "403 This action is unauthorized."

Previously it worked for me, what can it be?

**Comment by franviera92** [comment]
Add new config in migrations

**Comment by JosephSilber** [comment]
It's unclear whether you're still experiencing any issue, or what it might be.

Was this resolved?

**Comment by Dries-SF** [comment]
Indeed, I'm having the same issue. Update from v1.0.0-rc.4 to v1.0.0-rc.5 I get 403.
