### ISSUE TITLE
Permissions to single user when role has all the permissions

### ISSUE THREAD

**Issue by gierappa** [JosephSilber/bouncer#407]
If the role has all abilities but I want to disallow user to use one of models how to do that?

`Bouncer::role()->firstOrCreate([
    'name' => 'user',
    'title' => 'User',
]);`

`Bouncer::allow('user')->everything();`

`Bouncer::disallow($user)->to('access', $model);`

When doing something like that permission is not added. 
When I put entry manually in permission table and setting forbidden to true it works.

**Comment by JosephSilber** [comment]
The `disallow` method only removes a specific ability that has been previously granted.

You're looking for [the `forbid` method](https://github.com/JosephSilber/bouncer/blob/master/readme.md#forbidding-an-ability):

```
Bouncer::forbid($user)->to('access', $model);
```

**Comment by gierappa** [comment]
Works like a charm! it's obvious now.Thanks for help.
