### ISSUE TITLE
Hierarchical permissions for user groups

### ISSUE THREAD

**Issue by dakisan** [JosephSilber/bouncer#408]
Hi 

I have a web app in development which provides a niche service, and I want to implement something not unlike a programme management hierarchy.
```
|- Customer (entity) A
|- ...
|- Customer (entity) X
     |
     |- Programme Owner A (role/permission?)
     |- ...
     |- Programme Owner E (role/permission?)
           |
           |- Project E1
           |- ...
           |- Project E5
                 |
                 |- Manager of E5 (role/permission?) 
                 |- Assignee 1 of E5 (role/permission?)
                 |- ...
                 |- Assignee n of E5 (role/permission?)
```
Here is how I think it might work out, and I wonder if this package can handle it, or if there's another one, what it is. Or how to extend this one!

- Mary, a user "M" becomes a Member (role: Member)
- User M can optionally become a Customer (handled by customers table, fk etc, all good so far)
- If User M *is* a customer, then they may create a Programme
- User M still has the "member" role, but now also has an additional role, as owner "owner" of Programme P
- Programme owners may create Projects per Programme and may assign work to other users to wok on certain Stuff, on a per project basis. 
- For example, Bob, a new User "B" joins, and through some steps, User M wishes to Promote User B to Manager of one of the Projects in her Programme.
- We would then have a need to describe certain permissions such as (pseudo-coded), 
`$user->withRole('owner')->for(programme $programme)->can("promote user to project manager")->for(project $project)`

So now, I will need to be able to represent this somehow in my app. That User B has the role of manager, but only for one project inside Programme P which is owned by User M. In all other scenarios User B is just a plain old member.

This would allow me to create a sort of marketplace where users can be available to perform tasks on the platform in a sort of freelance way. Any use may become a customer. be assigned work by any other customer and only be able to access their own programmes and any assignments assigned by other members.

Any pointers how to do this with your package (or alternatives) will be appreciated - thanks.

**Comment by JosephSilber** [comment]
> Mary, a user "M" becomes a Member (role: Member)

```php
Bouncer::assign('member')->to($mary);
```

> User M can optionally become a Customer (handled by customers table, fk etc, all good so far)

```php
Bouncer::assign('customer')->to($mary);
```

> If User M is a customer, then they may create a Programme

```php
Bouncer::allow('customer')->to('create', Programme::class);
```

> User M still has the "member" role, but now also has an additional role, as owner "owner" of Programme P
>
> Programme owners may create Projects per Programme and may assign work to other users to wok on certain Stuff, on a per project basis.
>
> For example, Bob, a new User "B" joins, and through some steps, User M wishes to Promote User B to Manager of one of the Projects in her Programme.

Check out Bouncer's [ownership abilities](https://github.com/JosephSilber/bouncer/blob/master/readme.md#allowing-a-user-or-role-to-own-a-model):

```php
Bouncer::allow('customer')->toOwn(Programme::class)->to(['create-project', 'assign-manager']);

Gate::check('create-project', $program);
Gate::check('assign-manager', $program);
```
