### ISSUE TITLE
Bouncer sync removes wrong permissions

### ISSUE THREAD

**Issue by rodriguesjhz** [JosephSilber/bouncer#409]
**Do you want to request a feature or report a bug?**
Report a bug

**What is the current behavior?**
When calling `Bouncer::sync($user)->abilities($abilities)` Bouncer removes all permissions with `entity_id = $user->id` not taking into account the `entity_type`  `App\User`. Because of this, even the permissions with `entity_type = roles` gets removed from database when syncing.

**What is the expected behavior?**
`Bouncer::sync($user)->abilities($abilities)` should sync permissions using the adequate `entity_type`, in this example may be `entity_type = App\User` and `entity_id = $user->id`.

Current workaround is `$user->abilities()->sync($abilities)`.

**Example (permissions table)**
Before syncing:

![before_sync](https://user-images.githubusercontent.com/24320716/55177165-55857d00-5161-11e9-84fd-2445bec9283c.PNG)

After syncing (user id = 2, ability_id = 3):

![after_sync](https://user-images.githubusercontent.com/24320716/55177234-836ac180-5161-11e9-9164-9e4d4604c80e.PNG)
You can see that the permissions with ids **6** and **7** are removed from the table even belonging to **roles** entity_type.

**Laravel, Bouncer, MySQL and PHP versions**

Laravel: v5.4.36
Bouncer: v1.0.0-rc.5
MySQL: v5.6.43
PHP: 5.6

**Comment by JosephSilber** [comment]
Thanks for reporting this :pray:
