### ISSUE TITLE
Can't retract abilities or view abilities

### ISSUE THREAD

**Issue by renanBritz** [JosephSilber/bouncer#41]
Hello again,

I just started a fresh project with laravel 5.2, using the latest version of Bouncer. I noticed that when I try to retract an ability directly from a user, it always returns false, and the user DOES have the ability.

**Here's a test I did on artisan tinker:**

``` 
>>> $user = App\User::find(1)
=> App\User {#718
>>> Bouncer::allow($user)->to('access_admin_cp')
=> true
>>> Bouncer::retract('access_admin_cp')->from($user)
=> false
>>> 
```

And, if I try to check the user's abilities, it doesn't return an array/collection of abilities, it returns a BelongsToMany relation:

```
>>> $user = App\User::find(1)
=> App\User {#718
>>> Bouncer::allow($user)->to('access_admin_cp')
=> true
>>> Bouncer::refreshFor($user)
=> Silber\Bouncer\Bouncer {#713}
>>> $user->abilities()
=> Illuminate\Database\Eloquent\Relations\BelongsToMany {#707}
```

Not sure if the refresh was necessary, but anyway...

What am I doing wrong here?

Regards!

**Comment by JosephSilber** [comment]
1. `retract` [removes a role from the user](https://github.com/JosephSilber/bouncer#retracting-a-role-from-a-user). To remove an ability, [use the `disallow` method](https://github.com/JosephSilber/bouncer#removing-an-ability).
2. To get all abilities for a user, [use the `getAbilities` method](https://github.com/JosephSilber/bouncer#getting-all-abilities-for-a-user).

**Comment by renanBritz** [comment]
Hello!

I'm really sorry. I used the API incorrectly and some coincidences made me believe it was an issue.

Anyway, everything works perfectly.

Thank you for your support.

Best regards!
