### ISSUE TITLE
abilities

### ISSUE THREAD

**Issue by dbdxlzw** [JosephSilber/bouncer#410]
$user = Auth::user();
$admin_role->getAbilities();// [ 'A','B','C']
$user->isAn('admin_role');//true
$user->getAbilities();//[]

Why it came out like this?

**Comment by JosephSilber** [comment]
That doesn't look right. Can you show us a little more of what you did to get to that state?

Is it reproducible?

**Comment by JosephSilber** [comment]
I'm closing this for now.

Feel free to open it again if you can reproduce this.
