### ISSUE TITLE
allow to access through relations

### ISSUE THREAD

**Issue by khanzadimahdi** [JosephSilber/bouncer#411]
imagine we have some departments and some jobs in each department.
a user can access to all jobs of the department that he/her has access to it.
how can we allow a user to have access into his/her department->jobs ?
i can do it by checking user ability to access department, however is there a method in this package to do such thing in a clean way?

**Comment by hailwood** [comment]
You could look into "ownership"
https://github.com/JosephSilber/bouncer#ownership in fact it has an example very similar to what I'm about to provide below

#### In your seeder
```php
// Allow admins to do everything regardless of dept
\Bouncer::allow('admin')->toManage(\App\Job::class);

// Allow managers to do everything to jobs in their dept
\Bouncer::allow('manager')->toOwn(\App\Job::class);

// Allow employees to only view jobs in their dept
\Bouncer::allow('employee')->toOwn(\App\Job::class)->to('view');
```

#### In your service provider
```php
\Bouncer::ownedVia(\App\Job::class, function(\App\Job $job, \App\User $user) {
    // Many Relationship
    // return $user->departments()->whereKey($job->department_id)->exists();

    // Single Relationship
    return $user->department_id === $job->department_id;
});
```

**Comment by khanzadimahdi** [comment]
very nice. tnx
