### ISSUE TITLE
how to determite if a role has an ability ?

### ISSUE THREAD

**Issue by khanzadimahdi** [JosephSilber/bouncer#412]
there is no documents about determining if a role has an ability or not. how can i do that?

**Comment by khanzadimahdi** [comment]
i found a way but it not supports only_owned abilities

```php
$role->can('create', \App\Models\Ticket::class)
```
i think you must add another parameter for determining only_owned or not.

**Comment by JosephSilber** [comment]
"create" abilities don't make sense in tandem with `only_owned`, since they're now being created from scratch.

**Comment by khanzadimahdi** [comment]
how about other abilities, for example `update` or `delete` ?

**Comment by JosephSilber** [comment]
Those are definitely checked for ownership.
