### ISSUE TITLE
Querying users by their abilities

### ISSUE THREAD

**Issue by khanzadimahdi** [JosephSilber/bouncer#413]
how can i get all users that can edit or update a model? or users have an ability?

**Comment by JosephSilber** [comment]
Here's a solution: https://github.com/JosephSilber/bouncer/issues/126#issuecomment-246983616

**Comment by khanzadimahdi** [comment]
thanks. it would be better if you add this methods into the package.

**Comment by JosephSilber** [comment]
The reason this is not in the package is because there are many features in Bouncer that rely on actual code, which makes it impossible to query directly in the database.

But if you don't use any of those features, adding that query to your app is quite trivial.

**Comment by pryley** [comment]
@JosephSilber 

I am having some trouble re-implementing the "whereCan" scope that works for a specific model ability.

For example:

```php
$users = User::whereCan('create', Ledger::class)->get()
```

The code below always returns an empty Collection.
```php
public function scopeWhereCan(Builder $builder, $ability, $model = null)
{
    $builder->where(function ($query) use ($ability, $model) {
        $query->whereHas('abilities', function ($query) use ($ability, $model) {
            $query->byName($ability);
            if (! is_null($model)) {
                $query->forModel($model);
            }
        });
     });
}
```

I have tried in Laravel Tinker to do this the other way around in a very basic way:

```php
$ability = Bouncer::ability()->where('name', 'create')->where('entity_type', 'ledger')->first();
// This correctly lists a collection of roles that contain this ability (i.e. admin, manager)
$ability->roles;
// This is supposed to list all users that have this ability, but it always returns an empty Collection
$ability->users;
```

Is it possible that the `users` relation on an Ability model is not working correctly?
