### ISSUE TITLE
Forbid everything for a user, but allow some abilities

### ISSUE THREAD

**Issue by rodriguesjhz** [JosephSilber/bouncer#415]
Hello, I am trying to forbid all abilities for a user and keep him in a role, but allowing specific abilities.  The way I did was first syncing the desired abilities then forbidding all the other ones like this: `Bouncer::forbid($user)->to([1, 5, 7 ...]);`.

Is there a way to easily override permissions when using `Bouncer::forbid($user)->everything()`?

**Comment by JosephSilber** [comment]
If you need this, then they shouldn't be in that role.
