### ISSUE TITLE
Scopes 

### ISSUE THREAD

**Issue by AndrewOzarko** [JosephSilber/bouncer#416]
Hello, dear mr Silber. Thank You for help in previous issue. I have a task implement next: "User with Role A can see only post with Group A". We have nexts: "User can has a lot of groups, Group can has a lot of posts". I want solve this task with scopes, but we have little informantion about scopes. Can you send a few samples how to use scopes ?

**Comment by JosephSilber** [comment]
This is not really about scopes. Look into [customized ownership](https://github.com/JosephSilber/bouncer#ownership):

1. Add this in a service provider:

    ```php
    Bouncer::ownedVia(Post::class, function ($post, $user) {
        return $user->groups->contains('id', $post->group_id);
    });
    ```

2. When setting up your users' permissions, add this to that user:

    ```php
    Bouncer:allow($user)->toOwn(Post::class);
    ```

    or if you want every logged-in user on your site to have this ability:

    ```php
    Bouncer:allowEveryone()->toOwn(Post::class);
    ```

**Comment by AndrewOzarko** [comment]
Thank you) I will try

**Comment by AndrewOzarko** [comment]
But in my case, group has a lot of posts and post can has a lot of groups

**Comment by JosephSilber** [comment]
You can put whatever you want into `ownedVia`'s callback.

For example:

```php
Bouncer::ownedVia(Post::class, function ($post, $user) {
    return $user->groups->pluck('id')->intersect($post->groups->pluck('id'))->isNotEmpty();
});
```
