### ISSUE TITLE
Matching by role id

### ISSUE THREAD

**Issue by sergiz** [JosephSilber/bouncer#418]
I did this:
```
foreach (Role::all() as $role) {
    if($user->isAn($role->id)) {
        .....
    }
}
```
and I noticed that Bouncer queries the DB every time, getting the name of the role and only then checking, if that user has that role. If I use ->isAn($role->name) no additional queries are needed.

It makes no sense to me, why would Bouncer go and convert role ID to name and only then proceed. Before that it already retrieved all info about roles from the DB (and cached it I guess), so why not simply make a check against the role ID (or at least find name in the cache, not the DB)?

If this isn't a bug, it should at least be noted in the documentation as, if I wasn't paying attention I wouldn't even notice that checking by the role name is "preferred" way.

**Comment by JosephSilber** [comment]
Just pushed up [an update](https://github.com/JosephSilber/bouncer/commit/5a8c806760bc393a6028bdf42f5d76a8bceb930a). Can you test it in `master` to see if it fixes your issue?

**Note:** this required a change in the way Bouncer caches roles. If you've enabled [cross-request caching](https://github.com/JosephSilber/bouncer#cache), be sure to clear the cache, by calling `Bouncer::refresh()` after upgrading.
