### ISSUE TITLE
Assigning and retracting roles by custom_column

### ISSUE THREAD

**Issue by merfed** [JosephSilber/bouncer#419]
Is there anyway to currently do this?

If I have multiple roles that share the same name, it just assigns the last one. I'd like to get it so it assigns a specific role based on the value of custom_column.

**Comment by Sergzy** [comment]
Get that role's ID using your custom conditions (they are just a regular eloquent model) and then assign it by that ID. Same for retracting.

**Comment by JosephSilber** [comment]
```php
$roles = Bouncer::role()->where('custom_column', 'some_value')->get();

Bouncer::assign($roles)->to($user);
```
