### ISSUE TITLE
Undocumented "options" field - can we use it?

### ISSUE THREAD

**Issue by cjke** [JosephSilber/bouncer#420]
Looking through the source, I can't see much use for it. 

Even though it is undocumented, is it ok to set the options field and use it for our own meta data?

        \Bouncer::allow(auth()->user())->to('view', $document, [
            'title' => "View $document->title",
            'options' => ['meta' => 'This is too meta'],
        ]);

**Comment by sergiz** [comment]
It is probably better to just add a new column and use it for your own purposes.

Now ... I am more interested to know what all this "constraints" thing is, which is the reason why options column even exists.

**Comment by JosephSilber** [comment]
> Is it OK to set the options field and use it for our own meta data?

Yes. That's what it's there for :+1:

**Comment by cjke** [comment]
Champion! Thanks @JosephSilber

**Comment by timyourivh** [comment]
@JosephSilber Is there an easy way to set these options? Like in the `->to()` method? Or do we manually set them using the `Ability` model?

**Comment by JosephSilber** [comment]
@timyourivh the first message in this issue uses the `to` method, as you suggest 👍
