### ISSUE TITLE
Question about migration publishing process

### ISSUE THREAD

**Issue by riboflan** [JosephSilber/bouncer#421]
Why is in this package migration published in way: 

$target = $this->app->databasePath().'/migrations/'.$timestamp.'_create_bouncer_tables.php';

This creates each time new migration for bouncer with actual timestamp. If you read for axample Laravel/Passport package they just publish migrations with exact timestamp as they were created in time of development - this aproach is valid in case of update etc...

Is this a bug in Bouncer package or some plan? I am just asking in consideration of future updates of Bouncer itself.

Thanks.

**Comment by sergiz** [comment]
In case of a (table) update, you will have to create your own migration to get to the new state. The publishing is useful only for when you install the application for the first time.

**Comment by JosephSilber** [comment]
> Why is in this package migration published [...] This creates each time new migration for bouncer with actual timestamp.

This way, when you publish Bouncer's migrations, it'll always be the last migration (running after your other existing migrations), which is what you'd expect.

> Is this a bug in Bouncer package

No.
