### ISSUE TITLE
Rename facade path

### ISSUE THREAD

**Issue by sergiz** [JosephSilber/bouncer#426]
Opening this for discussion.

Currently, you have the following two options when you want to use the Bouncer facade:
```
use Bouncer;

use Silber\Bouncer\BouncerFacade;
```

Some of us prefer to always use the long versions since it's easy to recognize what package exactly it is about. If we wanted to to with bouncer we would have to use 
`use Silber\Bouncer\BouncerFacade as Bouncer;`
to retain the "default" facade name.

Considering that the common (generally accepted?) practice is, that whether you use the alias or the full path you should get the same result, I propose that the Bouncer's facade path is changed to
`Silber\Bouncer\Facades\Bouncer;`

That way we get the same result no matter, if we use the full namespace or the alias. What do you think?

**Comment by JosephSilber** [comment]
You can easily use dynamic facades:

```php
use Facades\Silber\Bouncer\Bouncer;
```

**Comment by sergiz** [comment]
Makes no sense from the rational point of view. Create a dynamic facade and put additional strain on the framework, when there is already facade created.

Is there a special reason why the package doesn't follow common convention?
