### ISSUE TITLE
List all models but a forbidden one

### ISSUE THREAD

**Issue by cristianofromagio** [JosephSilber/bouncer#427]
Let's say we have the following permissions:

```php
$user->allow('list:projects', Project::class);
Bouncer::forbid($user)->to('read:project', $classifiedProject);
```

How would we go on to list all the projects the user have access BUT the one he is forbidden to read?

I know this might not be a Bouncer issue/problem, but if anyone could point me in the right direction I would be really thankful!

**Comment by JosephSilber** [comment]
See here: https://github.com/JosephSilber/bouncer/issues/126#issuecomment-246983616
