### ISSUE TITLE
How to check, if a role has these "special" abilities?

### ISSUE THREAD

**Issue by sergiz** [JosephSilber/bouncer#428]
```
Bouncer::allow('myrole')->toOwn(Post::class);

Bouncer::allow('myrole')->toManage(Post::class);

Bouncer::allow('myrole')->everything();

etc..
```

How do I check, if a role has these? For simple abilities, I can use ->can, but here that is not an option.

EDIT: I was wrong, you can do it with ->can. Checking the tests answered all my questions.

**Comment by benrowe** [comment]
@sergiz Could you give an example of how you got this working? I am trying to figure out if a role has specific abilities but `->can()` is undefined as per:

```
Bouncer::allow('myrole')->can('*')
```
