### ISSUE TITLE
How can we help Bouncer get to 1.0?

### ISSUE THREAD

**Issue by marcusmoore** [JosephSilber/bouncer#43]
Hello!

Do you have a checklist of features or ideas that need to be hashed out before you're comfortable tagging a 1.0 release that anyone might be able to help with?

I want to start contributing to OSS and Bouncer might be a good place to start.

**Comment by Arcesilas** [comment]
That's a good initiative. I don't have enough time to contibute with code, but I can help too, with support, as I already started. I can also help produce documentation with examples. Would MD pages be ok for that ?

**Comment by Gummibeer** [comment]
I'm also trying/wanting - most things I'm doing are testing and fixing found bugs.

**Comment by JosephSilber** [comment]
@marcusmoore88 thanks for your interest!

I don't have a clear checklist. I have some small things here and there that I want to finish up. The biggest change I still want to make is having the roles/abilities relationship be polymorphic, so that you can assign roles/abilities to any model, not just the users.

Besides for that, it's simply finishing up some tests and documentation.

Also @Arcesilas and @Gummibeer, thanks for all your help thus far.

**Comment by Arcesilas** [comment]
You're welcome. May I start writing some markdown pages for more complete documentation ? Are there any specifications you prefer ?

Concerning polymorphism, it looks great! Not sure to have relevant examples coming to my mind, though.

**Comment by Gummibeer** [comment]
We have an example for the need of polymorphic relations:

We have a tool for an Agency but also their customers and there are abilities for: User, Contact & Agency - it's solveable by normal relations to the User but simpler by relations in different models.

**Comment by JosephSilber** [comment]
I started work on a polymorphic system in a separate branch. Here's the commit: https://github.com/JosephSilber/bouncer/commit/2734f9c9c66007fb0a072e73d3e00aeeaca0f329

All tests pass, but there's still a lot of work to do. There are many places where users are hard-coded, so it won't truly work with any model yet.

Testing and PRs welcome :)

**Comment by JosephSilber** [comment]
@Arcesilas regarding creating markdown pages: I don't think this project is big enough to warrant a full wiki with many disparate pages. I think the current readme format is enough. It just needs some stuff that's missing, and clarification on others.

**Comment by JosephSilber** [comment]
I believe [the polymorphic branch](https://github.com/JosephSilber/bouncer/tree/polymorphic) is now complete. If any of you can give it a spin, it'd be really helpful.

Once I'm a little more confident that it actually works, I'll merge it into the master branch, tag it, and provide an upgrade DB migration script.

Thanks for all your help.

**Comment by JosephSilber** [comment]
If any of you can take the new polymorphic system for a spin, I'd highly appreciate it.

1. Backup your database.
2. Set the version of Bouncer in your `composer.json` file to `dev-polymorphic`.
3. Run `composer update`.
4. Follow [this upgrade guide](https://github.com/JosephSilber/bouncer/tree/polymorphic#upgrading-to-02) to migrate your schema and data to the new structure.
5. Please report back on how it went.

You don't have to change any of your existing code. Bouncer's API has not changed.

Thank you all :heart:

**Comment by marcusmoore88** [comment]
I have a project I'm working on this week that I can drop the new polymorphic branch into.

**Comment by ognjenm** [comment]
I'm testing it, also trying to make some sort of UI for managing roles and permissions.
This is great package.

**Comment by JosephSilber** [comment]
@ognjenm thanks for trying it out! Don't forget to report back on how it works.

Is this for a new project, or you're upgrading from Bouncer 1.x?

**Comment by marcusmoore** [comment]
I planned on testing the polymorphic branch on a personal project but I haven't been able to drop it in yet. I think it'll be a while before I can give any feedback after all.

**Comment by coolynx** [comment]
I played around with v1.0.0-alpha.1 version and not familiar with any previous versions of Bouncer. And do not know much about it.

**More detailed documentation with examples would be nice.** 
I'm one of the users who is not very fluent in Laravel (and programming/php) and such tricks as mentioned in #86 are excellent - they keep package lean and yet functional. Just reference those issues from documentation as examples on how to. No need to rewrite everything.

Maybe I missed another one about the same table `abilities`. There is a field `entitiy_id`. I'm guessing that it is meant for a more specific entity record. 

For example, an ability `delete-admin` that has `ID` (entity_id = 1) in `App\User` model. So that this specific ability allows only one thing in a system - that another user with `Admin` role and `abilities` can not delete the originator.
`{
"id": 5,
"name": "delete-admin",
"entity_id": 1,
"entity_type": "App\User",
"created_at": "2016-04-28 19:42:04",
"updated_at": "2016-04-28 19:42:04"
}`
**How to access/use it?** ;) Or it is just a hidden feature for manual usage?

There could be a problem if there is another `entity_type` (App\Post) with the same id (1), because of `unique` field.

And the last one - `permissions` table has a field `forbidden`. Did not get how to use it.

I did not check syncing and caching. Otherwise I like it. Thank you! 👍

**Comment by JosephSilber** [comment]
@coolynx Support for denying abilities [has been requested before](https://github.com/JosephSilber/bouncer/issues/45). It's not gonna make it into 1.0, but I'm considering it as a possible addition down the road. And yes, the `forbidden` column is there to enable this in the future.

With regards to the documentation, you are absolutely right. Better documentation is part of the roadmap for the 1.0 release, as I've outlined in [the release notes](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-alpha.1) for the first first alpha release of the 1.0 branch.

**Comment by GKMelbo** [comment]
Hi, I've just started trying out Bouncer and Laravel 5, and maybe it's just me who is a noob, but I've followed the installation in the readme and are stuck at **Usage**.
Where do I put the `Bouncer::allow('admin')->to('ban-users');`?
The readme states it will create a Role and Ability model for me, but I can't get it to do that. Would it be possible to update the documentation to explain this better? Sorry if this isn't the right place to ask this.

**Comment by coolynx** [comment]
@GKMelbo in whatever place (Controller/Model) you want to use it and if you have done all the steps mentioned in documentation.

But the easiest way to check the package without writing any code (almost) is using Artisan command `tinker`. Here is an example. Assuming that there is at least one user in database.

```bash
php artisan tinker
```
And in tinker:
```php
$user = App\User::find(1); // find the first user
Bouncer::assign('admin')->to($user); // give admin Role to this user
Bouncer::allow('admin')->to('ban-users'); // give permission to admin role
$user->getAbilities(); // get all permissions to check if a user has got the given permission
```
And the output:

>       Silber\Bouncer\Database\Ability {#684
         id: 9,
         name: "ban-users",
         entity_id: null,
         entity_type: null,
         created_at: "2016-05-04 20:28:23",
         updated_at: "2016-05-04 20:28:23",

Probably the best way to learn is to read [Laravel documentation](https://laravel.com/docs/5.2/authorization) and maybe [Roles and Permissions in Laracasts](https://laracasts.com/series/whats-new-in-laravel-5-1/episodes/16) (paid) or [ACL basics](https://laracasts.com/series/whats-new-in-laravel-5-1/episodes/13) (free).

**Comment by GKMelbo** [comment]
@coolynx I see. That clears it up! Where can I find the Role and Ability model that Bouncer creates? It doesn't show up in the app directory.
Thanks for the help and the resources. I'm actually already a subscriber to Laracasts and discovered Bouncer in the ACL videos comments section. Looking forward to keep learning about Laravel and Bouncer :)

**Comment by coolynx** [comment]
@GKMelbo Bouncer does not create any files. AFAIK none of the packages (any) are creating files for you. Except for configuration, migration or seed files. This is your responsibility to make models in app directory.

**Comment by GKMelbo** [comment]
@coolynx Okey. I was just a bit confused from the **Creating roles and abilities** section that states 

> Behind the scenes, Bouncer will create both a Role model and an Ability model for you.

**Comment by Smokexyz** [comment]
Inheritance! please, if it could be made possible for a role to inherit abilities of another, it would be great.

**Comment by antoniopaisfernandes** [comment]
@JosephSilber when are you considering releasing a new version? At the same time Laravel 5.3?

Great work!

**Comment by JosephSilber** [comment]
@antoniopaisfernandes I hope to release another alpha with Laravel 5.3 support by the end of the week (no promises).

**Comment by Smokexyz** [comment]
@JosephSilber looking forward to it working with laravel 5.3. 👍

**Comment by andyscraven** [comment]
Did you ever release a 5.3 version @JosephSilber ?

**Comment by JosephSilber** [comment]
The latest alpha, which you can install by requiring v1.0.0-alpha.3, supports 5.3.

I hope to have a stable beta out by the end of the month.

**Comment by andyscraven** [comment]
Thanks @JosephSilber. Can you drop a message when it is stable?  The company I am doing a contract for do not allow alpha releases.  Thanks a lot!

**Comment by base-zero** [comment]
Such a nice and easy to use package ! @JosephSilber Any update on v1.0.0 becoming stable ?

**Comment by JosephSilber** [comment]
@base-zero I've been a little busy of late, and didn't really have much time to dedicate to Bouncer. I hope to get back into it towards the end of this week, and aim to have a beta out sometime next week.

The beta period will be dedicated to documentation. While I do not anticipate any breaking changes in the beta, writing comprehensive documentation often leads to finding pain points in the product that have been glossed over before (I'd say DDD<sup>1</sup> is the most useful thing I've learn from Taylor Otwell). So while breaking changes aren't likely, they cannot be guaranteed either.

<sup>1</sup> <sub>Documentation Driven Design.</sub>

**Comment by andyscraven** [comment]
That should be perfect timing for me as I need to start thinking about roles etc next week in my project.  Thanks again @JosephSilber

**Comment by andyscraven** [comment]
Hi @JosephSilber.  How is the update coming?  I am going to go ahead and use the latest version as I am up against a deadline.  I will feedback any issues I find.  Is it still  v1.0.0-alpha.3?

**Comment by JosephSilber** [comment]
@andyscraven not as fast as I'd hoped. Hopefully I'll have it out within a few days.

**Comment by andyscraven** [comment]
@JosephSilber I need to be able to return the specific role of the User so I can preselect his/her role in my edit users form.  I see getAbilities() but not getRoles() although I can see it deeper in your code.  Can I access it?  Ideally I need $user->getRole();

**Comment by nmfzone** [comment]
@andyscraven Is [this](https://github.com/JosephSilber/bouncer/blob/master/src/Database/HasRoles.php#L19) not enough?

**Comment by coolynx** [comment]
@andyscraven i found many answers in closed issues section. 😄 

Get user's roles list https://github.com/JosephSilber/bouncer/issues/67
how to get all roles (list with all related issues) https://github.com/JosephSilber/bouncer/issues/125
How to get all the user who have certain role? https://github.com/JosephSilber/bouncer/issues/96
Get abilities from roles https://github.com/JosephSilber/bouncer/issues/97#issuecomment-222342058
Assign and check abilities (permissions) https://github.com/JosephSilber/bouncer/issues/98

And there are more.

**Comment by andyscraven** [comment]
Thanks @coolynx. I guess I should have guessed that :-)

**Comment by andyscraven** [comment]
@JosephSilber. Just to let you know I have integrated the Alpha release with my 5.3 project and so far so good!  I have not come across any issues.

**Comment by JosephSilber** [comment]
Just released the long overdue beta.

https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.1

**Comment by andyscraven** [comment]
@JosephSilber Great to know, thank you.

**Comment by brianmclachlin** [comment]
@JosephSilber I would love to use this package on one of my projects, model based permissions is exactly what I'm looking for; however, it seems like it's still under active development. 

> Besides for that, it's simply finishing up some tests and documentation.

There have been quite a few commits since the last tagged beta release, including schema changes.

Should I hold off on using this package or is it in a production ready state?

**Comment by JosephSilber** [comment]
@brianmclachlin it has been in a production-ready state for a very long time (and is in fact used in production by many many projects), although it has had some backwards-incompatible changes that required a very minimal amount of changes on the user's end.

From where I stand now, the latest set of schema changes seems to be the last one before 1.0, besides for _maybe_ [removing roles' levels](https://github.com/JosephSilber/bouncer/issues/223). If you don't plan on using levels, this won't affect you at all.

One final breaking change I still intend to make is [remove the undocumented seeder class](https://github.com/JosephSilber/bouncer/commit/f19f9734c28cd108eebb3ffa9d730537b52282a8). People should just be using Laravel's built-in seeders.

I plan on tagging a new beta before the end of the year with multi-tenancy support and its new schema, the seeder class removed & _maybe_ remove role levels.

So to get back to your original question: the package is definitely in a production-ready state. If you lock your composer dependency to a particular version as described in the readme (instead of blindly using `dev-master`), you'll be ok. Then, if there are any minor breaking changes going forward, you can deal with them when you upgrade. They'll be clearly documented, [like all other releases](https://github.com/JosephSilber/bouncer/releases).

Do note: when Bouncer reaches 1.0 it'll only support Laravel 5.5 and PHP 7.1. If you're using an older version of Laravel/PHP you can stay on the current version till you upgrade.

---

Finally: I'm really sorry to everyone patiently waiting for 1.0. I wish I'd have more time to spend on Bouncer, but the second half of this year I've been bogged down by other responsibilities. I'm still committed to getting Bouncer to 1.0 in due time, just at a longer timetable than I originally expected. 

In the meantime, thank you all for using Bouncer  🎉

**Comment by marcoraddatz** [comment]
First of all, thanks for this great package!

The current version seems to be very stable. What if it becomes v1.0 and your next major update will become v2.0?

**Comment by JosephSilber** [comment]
Just tagged a new release with multi-tenancy support: **[v1.0.0-beta.5](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.5)**.

I plan for this to be the last beta. Besides for bumping the minimum requirements, I seriously hope not to have any more breaking changes till 1.0.

May your happiest years be ahead of you :confetti_ball:

**Comment by brianmclachlin** [comment]
@JosephSilber Thanks for the feedback, really appreciate it. I'm excited to implement this package!

**Comment by Keoghan** [comment]
@JosephSilber almost there! Keep it up, it's a lovely package.

**Comment by Cipa** [comment]
Please keep a version working for php 5.6.
Thank you

**Comment by FrittenKeeZ** [comment]
When will RC2 be released?

**Comment by sebastiaanluca** [comment]
RC1 has been working like a charm here since it's release, looking forward to the official release! 🙌

**Comment by faustbrian** [comment]
@JosephSilber what is the current status of bouncer? Still the plan to get to a stable 1.0 release and keep it maintained?

**Comment by JosephSilber** [comment]
@faustbrian definitely!

I've been extremely busy these last few months (we moved recently), so haven't really had much time to dedicate to Bouncer.

Hope to get back into it soon, go through all the issues and PRs, finish up a few in-the-works features, and see how we can actually get to a 1.0.

Hold on tight, good days are coming 😃

**Comment by faustbrian** [comment]
Great to hear that! Was questioning wether it's still maintained so wanted to make sure before integrating it but good to hear it's on its way to 1.0 👍

**Comment by tormjens** [comment]
Not to be a nag or anything; but is there any news on a 1.0? I've been using Bouncer on the regular for the last 2 years and haven't experienced much issues at all. I only get reminded that Bouncer is "unreleased" when I install one of my packages that depend on Bouncer in a new project. I always have to change `minimum-stability` in my composer.json for that. 

Is there a plan on how to get to 1.0? Happy to help get there as well.

**Comment by alec-joy** [comment]
@JosephSilber I'm also curious if there's anything we can do to help get this to what you would consider a 1.0 release, I have a week off in the near future that I'd be willing to dedicate to getting this done as well as some scheduled FOSS time I give myself every week. Bouncer is exactly the package I'm looking for but unfortunately my org has minimum stability requirements so I can't use Bouncer for that project without a 1.0, even if the current RC is stable enough for production use (which it seems to be). 

If there are specific open issues you'd like the community to tackle or if it's a matter of getting a documentation site together or something like that I'd be willing to dive in. This is still your project though, not trying to push you into handing it over or anything, just want to help if I can.

**Comment by JosephSilber** [comment]
There are two features currently in limbo (half implemented):

1. Per-entity roles
2. Model ability constraints

Both of these are part of the DB structure (in the migrations), but are only partially implemented.

I don't feel like it makes sense to release a 1.0 with the code in this state.

**Comment by ajoy39** [comment]
> There are two features currently in limbo (half implemented):
> 
>     1. Per-entity roles
> 
>     2. Model ability constraints
> 
> 
> Both of these are part of the DB structure (in the migrations), but are only partially implemented.
> 
> I don't feel like it makes sense to release a 1.0 with the code in this state.

Hi, I am also @alec-joy but that was a work account for a company I no longer work for

In my new position I have a lot more leeway to work on FOSS stuff, especially if we use it in our application. Some time in early January I'll be given 6 weeks to essentially integrate this package into our application. During that time I would like to help get to 1.0. You mentioned Per-entity roles and model ability constraints are the two things left, can you go into a bit more detail on whats left and what state their in? I don't want to create a ton of extra work for you to get this all documented but if I can get some info on those two items I can get approval to spend a not-insignificant amount of time working on Bouncer during that 6 week period.

**Comment by JosephSilber** [comment]
@ajoy39 thanks for offering your help :+1: 

I'll try to find some time to write up what those features are supposed to do, how they're supposed to work, and which parts are already done.

No promises, but I'll try.

**Comment by realmxsandr** [comment]
@JosephSilber Hi! I would like to get some update on this topic.

Our company using this great package for our purposes and it fits perfect, but unfortunately we have minimum stability requirements too and having some difficulties at this point, just as @alec-joy said before.

We are ready to offer some free hands to help this package get its firs stable release.

Please, If there is anything I can do, I would like to help get things done.

Thank you!

Btw, we are using rc10 in production environment at this moment and it looks to be fine.

**Comment by Ragaga** [comment]
@JosephSilber Hi. What about this issue?

**Comment by Ragaga** [comment]
Any updates here?

**Comment by cjaoude** [comment]
Yep, quite like Bouncer, better than Spatie pkg. Let the community help get it to v1.0 and squash all the open issues as needed. 👍

**Comment by JosephSilber** [comment]
Bouncer 1.0 has now been released!

You can read more about it in **[Releasing Bouncer: Roles and Permissions for Laravel apps](https://josephsilber.com/posts/2022/05/17/releasing-bouncer-laravel-roles-and-permissions)**.
