### ISSUE TITLE
[Qusetion] What's the difference between `toOwn` and `toManage`?

### ISSUE THREAD

**Issue by winter-ice** [JosephSilber/bouncer#433]
```
Bouncer::allow('admin')->toOwn(Post::class);
Bouncer::allow('admin')->toManage(Post::class);
```
What are the differences between the two methods in behavior?

**Comment by ipontt** [comment]
`toManage`allows you to do everything to the model class specified. These two lines are equivalent.

```php
Bouncer::allow('admin')->to('*', Post::class);
Bouncer::allow('admin')->toManage(Post::class);
```
`ToOwn` allows you to do everything (by default) to the model class specified **IF** he 'owns' the model.

For example, let's say we have two users (id 1, id 2) and and a Post with the following attributes. 
```php
['id' => 1, 'user_id' => 2]
```
```php
// Admins own Post class
Bouncer::allow('admin')->toOwn(Post::class)
// Assign Admin role to our two users
User::find(1)->assign('admin')
User::find(2)->assign('admin')
// Check permissions
User::find(1)->can('edit', Post::find(1)) // False since the User id 1 does not match with the Post user_id 2
User::find(2)->can('edit', Post::find(1)) // True since the User id 2 matches with the Post user_id 2
```

You can also define a subset of permissions for owned models by adding a `to()` add the end
```php
Bouncer::allow('admin')->toOwn(Post::class)->to(['create', 'edit'])
```
And if the model you are trying to own does not have a user id, you can define the way ownership resolves itself by adding a `Bouncer::ownedVia` statement in a service provider's `boot` method.

**Comment by winter-ice** [comment]
Thanks!
