### ISSUE TITLE
Eager load abilities

### ISSUE THREAD

**Issue by sergiz** [JosephSilber/bouncer#435]
Let's say we have a user list, and we want to display an icon besides username, if user ->can() do a specific thing. Currently, we will run into n+1 problem with such approach.

There should be an option to eager load abilities (and roles) for selected users, so then we can do can() checks without it getting stuff from the DB for each user separately.

**Comment by JosephSilber** [comment]
That's a nice request.

I don't really know how that would work, since the query for an individual user's roles and abilities is quite complex. I don't even know whether it would be possible to achieve this.

**Comment by OliverGrimsley** [comment]
@sergiz I also wanted to grab the user role and all abilities in a single go, using eloquent with lazy loading. (I don't use blade, my app is an API, so not sure about your exact issue) and while I could not figure out the morphmaps in the library - so this is probably not very elegant, I did add several models to my app and now I can do this, and use all the other builder methods as necessary:  

`return User::with('userRoles.role.abilities')->get();`

If it helps anyone, here is the code:

New Models, Abilities.php, Role.php and AssignedRoles.php:

```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Abilities extends Model
{
    protected $table = 'abilities';
}
```
```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Role extends Model
{
    protected $table = 'roles';
    public function abilities()
    {
        return $this->belongsToMany('App\Abilities', 'permissions', 'entity_id', 'ability_id');
    }
}
```

```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class AssignedRoles extends Model
{
    protected $table = 'assigned_roles';
    public function role()
    {
        return $this->hasMany('App\Role', 'id', 'role_id');
    }
}
```

Then in User model, I added this:
```
public function userRoles()
  {
    return $this->hasMany('App\AssignedRoles', 'entity_id');
  }
```

**Comment by masroore** [comment]
@OliverGrimsley `AssignedRoles::role()` should be `hasOne()` and not `hasMany()`

**Comment by SignetPlanet** [comment]
Laravel eager loading already works for me without adding any additional code or models as @OliverGrimsley gave as a solution.  I did a quick test and regardless of the number of users I see three queries with one for the Users, one for abilities and one for roles/abilities. I'm using the latest Laravel version so maybe it was an older version issue.

```php
$Users = User::with('roles')->get(); 
// eager loads all the roles for each user via $User->roles property

$User = User::with('abilities')
// eager loads all the abilities that are "extra" - where I have assigned 
// abilities directly to the user (will not show an ability assigned 
// through a role).  accessible via $User->abilities property

// using nested eager loading
$User = User::with('roles.abilities')->get();
// eager loads all roles as the with('roles') above but now each $User->roles
// record contains the $Role->abilities property which contains the abilities
// assigned to that role. 

// to combine it all I can do
$User = User::with(['abilities','roles.abilities'])->get();
// here I get both $User->abilities and $User->roles->abilities
```

I haven't checked how this works with forbidden or scopes as I have not used those.

Also note, it also worked with eager loading of just specific columns like with('abilities:name') to keep the results smaller but if nesting it will fail if you do not include fields it needs to access the pivot table. Hope this helps.

@JosephSilber perhaps it is just a matter of adding this to the docs as it seems to work fine as is.
