### ISSUE TITLE
[Proposal] Start Subreddit

### ISSUE THREAD

**Issue by wbunthof** [JosephSilber/bouncer#436]
I think it is useful to start a subreddit, for asking small things. And also mention it in the docs!

**Comment by ppisecky** [comment]
I think a discord would be a better idea. Unlike reddit Discord actually at least has code formatting.

**Comment by JosephSilber** [comment]
I don't use Reddit. It's generally a cesspool of people just being horrible to each other for no good reason.

But if anyone here wants to start a subreddit on their own, feel free to do so!
