### ISSUE TITLE
Just check ownership

### ISSUE THREAD

**Issue by hexatex** [JosephSilber/bouncer#437]
I am new to bouncer, but all I really need to do is verify that the user owns the model instance. The ownedVia closure does run, but even if I force it to return false the Report model is returned when I request the route. What am I missing?

**ReportController**
```php
public function get(Report $report)
{
    return new ReportResource($report);
}
```

**UserService**
```php
Bouncer::allow($user)->toOwn(Report::class);
```

**User**
```php
class User extends Authenticatable
{
    use Notifiable, HasApiTokens, HasRolesAndAbilities;
```

**AppServiceProvider**
```php
Bouncer::ownedVia(Report::class, function ($report, $user) {
    Log::info('Closure ran!');
    return $report->hub->user_id === $user->id;
});
```

**Comment by hexatex** [comment]
I wasnt using a gate, duh

**Comment by enbermudas** [comment]
How is that about the gate? I'm having the same problem!

**Comment by JosephSilber** [comment]
@enbermudas please open a new issue, describing your problem in detail.
