### ISSUE TITLE
Checking Ownership at the gate

### ISSUE THREAD

**Issue by hexatex** [JosephSilber/bouncer#438]
I am new to bouncer, I would like to verify ownership using middleware. The ownedVia closure does run, but even if I force it to return false the Report model is returned when I request the route. What am I missing?

**AppServiceProvider@boot**
```php
Bouncer::ownedVia(Report::class, function ($report, $user) {
    Log::info('Closure ran!');
    return $report->hub->user_id === $user->id;
});
```

**Route**
```php
Route::get('report/{report}', 'ReportController@get')->middleware('can:view-report,report');
```

**ReportController**
```php
public function __construct()
{
    $this->authorizeResource(Report::class);
}

public function get(Report $report)
{
    return new ReportResource($report);
}
```

**UserService**
```php
Bouncer::allow($user)->toOwn(Report::class);
```

**User**
```php
class User extends Authenticatable
{
    use Notifiable, HasApiTokens, HasRolesAndAbilities;
```

**Comment by JosephSilber** [comment]
Does it log `Closure ran!`?

If not, are you sure you're importing `Report`'s namespace?

**Comment by JosephSilber** [comment]
Oh, I missed the part where you clearly stated that "The ownedVia closure does run".

**Comment by JosephSilber** [comment]
Are you sure the user doesn't have a different ability that is allowing that?

Try this instead:

1. Remove the middleware.

1. Remove the call to `authorizeResource` in the constructor.

1. Then, at the top of your `get` method, add this:

    

        dd(\Gate::check('view', $report));

This should log the actual ability that allowed the action.

**Comment by hexatex** [comment]
It was granted by an ability assigned to a the "user" role allowing it,

> Bouncer granted permission via ability #1 

However, If I remove the ability from the role the request is denied when the closure returns true. And now when the request is denied dd() does not return anything because the gate ends the request immediately

**Comment by JosephSilber** [comment]
So what's the question now?

Just to be clear: has the question now switch to why _doesn't it_ allow the check?

**Comment by JosephSilber** [comment]
I'm closing this issue, pending further details.
