### ISSUE TITLE
Automatic detaching of roles on deleting is an issue with soft deletes.

### ISSUE THREAD

**Issue by hailwood** [JosephSilber/bouncer#439]
Hey @JosephSilber,

Right now we're automatically detaching the roles and abilities from the user on model deletion
https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/HasRoles.php#L21-L26
https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/HasAbilities.php#L22-L27

This works well normally, but if we're soft deleting the user then it's actually not what we want.

I see two ways forward here (in the example below I'm using `roles` only, but the same would apply to `abilities`)

1) Check for soft deletes and don't automatically detach
```php
    public static function bootHasRoles()
    {
        static::deleted(function ($model) {
            if(!method_exists($model, 'isForceDeleting') || $model->isForceDeleting()) {
                $model->roles()->detach();
            }
        });
    }
```

2) Add a new method to the trait to control whether we automatically detach the roles
```php
    public function detachRolesOnDelete() 
    {
        return true;
    }

    public static function bootHasRoles()
    {
        static::deleted(function ($model) {
            if($model->detachRolesOnDelete()) {
                $model->roles()->detach();
            }
        });
    }
```

A third option would be a combination of the two, by moving the `isForceDeleting` logic into the `detachRolesOnDelete` method which I prefer, however the proposed second implementation is currently backwards compatible but gives us the flexibility to override it.

Thoughts?

**Comment by ewerkema** [comment]
I just encountered the same problem with soft deletes on the User models. This would be a great addition to the package. The simple solution of only removing the assigned roles and abilities on force delete sounds like a good one.

**Comment by jesephan** [comment]
@hailwood maybe you could submit a pull request regarding your proposal so everyone can check your solution. thanks

**Comment by JosephSilber** [comment]
This has been fixed here:

https://github.com/JosephSilber/bouncer/commit/2d58aac3e4ae6fdd29bb327c7c8cc84b65f36209
