### ISSUE TITLE
column name entity_id and entity _type use?

### ISSUE THREAD

**Issue by masterpowers** [JosephSilber/bouncer#44]
I see abilities have extra field called entity_id and entity_type

What is the purpose of that extra column?

my hint is it is a polymorphic relationship.

but what would use the entity?

can you explain it thanks

**Comment by masterpowers** [comment]
i tried using your example in artisan tinker 

\Bouncer::allow('admin')->to('create', Order::class);

and it populates the abilities table  like so
```
 7 | create         |      NULL | App\Order   | 2016-01-26 04:05:31 | 2016-01-26 04:05:31
```

so the entity type is NULL , is there a way to pass an entity ID? or model id

is it Ok to be NULL? what is the meaning if the entity id is null and also if it has an ID?

**Comment by JosephSilber** [comment]
It's used when you restrict an ability to a particular model:

Bouncer::allow('admin')->to('delete', Order::first());

**Comment by masterpowers** [comment]
so it pertains to the model instance currently taking...
so for example when a user create a order

$order = new Order;
$order->name = 'name';
$order->save();

then ill use it like so to assign an ability 
Bouncer::allow('admin')->to('edit', $order);

got it.. but how can i use it to show inside my view?

is there a blade directive? like
@can('edit', $order)
    <a href="/post/{{ $post->id }}/edit">Edit Post</a>
@endcan

so the 'edit' is the ability and the $order at the can is the instance or the selected id in url...

THanks for your answer

**Comment by masterpowers** [comment]
My understaning now is 
this can allow a user to edit all kinds of post id on the Model Post
Bouncer::allow($user)->to('edit', Post::class);

but this one can only edit an specific post....
Bouncer::allow($user)->to('edit', $post);

am i correct?

**Comment by JosephSilber** [comment]
You are correct. Yes. It's all in the docs.

And yes: you can use the @can directive like that.

**Comment by masterpowers** [comment]
Dont know if im doing it wrong to Authorize a user using this Bounce Method 
```
Authorizing users
$abilities = $user->getAbilities();
----------------------------------------
Silber\Bouncer\Database\Ability {#734
  id: 9,
  name: "create",
  entity_id: 1,
  entity_type: "App\Order",
  created_at: "2016-01-26 04:23:15",
  updated_at: "2016-01-26 04:23:15",
},
-----------------------------------------
Bouncer::allows($ability);
```
i tried passing id of the ability  and get a return false even if i got that abilities
Bouncer::allows(9);

Am i Doing it wrong, nothing says about this on documentation in Authorizing users

**Comment by JosephSilber** [comment]
You check abilities by their name:

```php
$order = Order::find(1);

Bouncer::allows('create', $order);
```

BTW, this ability of yours doesn't make much sense. Since the order is already created, there's no point in allowing it to be created. But you get the point.

**Comment by orkempire** [comment]
@JosephSilber sorry for reopening this thread, but where are the entity_id, entity_type mentioned in the docs? Could you please provide a link?

**Comment by JosephSilber** [comment]
@orkempire they aren't, because they're not meant to be used directly. Bouncer uses it behind the scenes.
