### ISSUE TITLE
How to protect a route against anyone  excluding admin and owner?

### ISSUE THREAD

**Issue by ramundo** [JosephSilber/bouncer#443]
So the problem is, that i need to open a route only for an entity owner and admin.
For admin i use this:
->middleware('can:*,App\User')
but how can i pass an owner too?
Right now im thinking to create a middleware, where to check , if a route parameter ID is matching auth user id, or if auth user is admin
But maybe there is more convinient ways to do a work? Please help

**Comment by JosephSilber** [comment]
Here's a link to the documentation on ownership:

https://github.com/JosephSilber/bouncer#allowing-a-user-or-role-to-own-a-model
