### ISSUE TITLE
$ability->users relation does not seem to be working

### ISSUE THREAD

**Issue by pryley** [JosephSilber/bouncer#444]
@JosephSilber 

Is it possible that the `users` relation on an Ability model is not working correctly?
 
```php
// This correctly returns the requested ability
$ability = Bouncer::ability()->where(['name' => 'create', 'entity_type' => 'ledger'])->first();
// This correctly lists a collection of roles that contain this ability (i.e. admin, manager)
$ability->roles;
// This is supposed to list all users that have this ability, but it always returns an empty Collection
$ability->users;
```

```php
// This does not work either, it gets the ability model but the users relation is always empty
Bouncer::ability()->with('users')->where(['name' => 'create', 'entity_type' => 'ledger'])->first();
```

```php
// This returns a collection of Role models as expected
$abilities = User::find(1)->roles
// This however, always returns an empty collection
$abilities = User::find(1)->abilities
```

1. `$user->getAbilities()` works correctly, just not the other way around
2. The application has a custom namespace (i.e. not `\App`)
3. All users in the application have roles applied to them
4. All abilities are mapped to models (i.e. `Bouncer::allow('manager')->to('create', Ledger::class);`
5. Bouncer works as expected (i.e. `$hasPermission = Bouncer::can('create', Ledger::class);`)

I also tried re-implementing the "whereCan" scope on the `User` model that works for a specific model ability, but this has the same issue where it always returns an empty Collection.

For example:

```php
public function scopeWhereCan(Builder $builder, $ability, $model = null)
{
    $builder->where(function ($query) use ($ability, $model) {
        $query->whereHas('abilities', function ($query) use ($ability, $model) {
            $query->byName($ability);
            if (! is_null($model)) {
                $query->forModel($model);
            }
        });
     });
}
```

```php
// This always returns an empty Collection
$users = User::whereCan('create', Ledger::class)->get();
```

Any ideas?

**Comment by pryley** [comment]
Unless...perhaps I have misunderstood how this works.

The `users` relation on the Ability model works if an ability is assigned directly to a user (i.e. not through a role), that's why it's a polymorphic relation. Since I have been assigning abilities through roles (instead of directly to the users), this must be working as intended.

I can get the users that have an ability for a specific model like this: 

```php
$users = app(User::class)
    ->join('assigned_roles', 'assigned_roles.entity_id', '=', 'users.id')
    ->join('roles', 'roles.id', '=', 'assigned_roles.role_id')
    ->join('permissions', 'permissions.entity_id', '=', 'roles.id')
    ->join('abilities', 'abilities.id', '=', 'permissions.ability_id')
    ->where([
        'assigned_roles.entity_type' => app(User::class)->getMorphClass(),
        'permissions.entity_type' => Bouncer::role()->getMorphClass(),
        'abilities.name' => 'create',
        'abilities.entity_type' => app(Ledger::class)->getMorphClass(),
    ])
    ->get();
```

Is there a simpler (i.e. more eloquent) method to do this through a custom `scopeWhereCan` method on the User model, using built-in Bouncer methods, or would I just use a query with multiple manual joins as above?

**Comment by JosephSilber** [comment]
You have correctly figured out that `$ability->users` is a regular Eloquent relationship, and will not include abilities available through a role.

> Is there a simpler (i.e. more eloquent) method to do this using built-in Bouncer methods

Bouncer currently does not ship with a way to query users by ability. See here: #126
