### ISSUE TITLE
bouncer:clean returns error

### ISSUE THREAD

**Issue by panayotisk** [JosephSilber/bouncer#446]
I get an error when trying to run the bouncer:clean command like so:
`php artisan bouncer:clean`
> SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "*" (SQL: select distinct "entity_type" from "abilities" where "abilities"."entity_id" is not null and "abilities"."entity_id" != * and "abilities"."entity_type" != *)

This refers to the code in CleanCommand.php lines 165-168.   

I am using latest bouncer with laravel and postgresql.

The code I have executed before calling bouncer:clean from the command line in a migration up() is:
```
Bouncer::allow('viewer')->to('view');
Bouncer::allow('commenter')->to(['view', 'comment']);
Bouncer::allow('editor')->to(['view', 'comment', 'edit']);
Bouncer::allow('owner')->to(['view', 'comment', 'edit', 'invite-user', 'forbid-user', 'delete']);
```
and in migration down()
```
Bouncer::disallow('viewer')->to('view');
Bouncer::disallow('commenter')->to(['view', 'comment']);
Bouncer::disallow('editor')->to(['view', 'comment', 'edit']);
Bouncer::disallow('owner')->to(['view', 'comment', 'edit', 'invite-user', 'forbid-user', 'delete']);
```
I just wanted to delete all roles and abilities if the migration is taken back...
What is going wrong here?

**Comment by panayotisk** [comment]
After a few hours of trying to figure out exactly the query's intentions I came to the conclusion that we just need to remove line 163 from CleanCommand.php. The command then seems to work as expected.

**Comment by Zanzavar** [comment]
+1 ^^

**Comment by JosephSilber** [comment]
> After a few hours of trying to figure out exactly the query's intentions I came to the conclusion that we just need to remove line 163 from CleanCommand.php.

Can you explain what's wrong with that piece of code that would cause it to fail on Postgres?

> The command then seems to work as expected.

Well it doesn't, since it'll now also delete abilities not connected to a given entity.

**Comment by panayotisk** [comment]
I have dropped Bouncer and decided to implement a custom solution, so I will not be able to help more. For directions on how to reproduce the error see my first post. If you find that this is not reproducible on your machine please feel free to close this thread.

**Comment by JosephSilber** [comment]
I don't understand what's wrong, so I'm closing this issue for now.

If anyone runs into this again, feel free to open another issue.

**Comment by flowdau** [comment]
Hi Joseph,
I have this issue on a Postgresql instance (Homestead, cloud).

When the scheduled  clean command runs:

 `$schedule->command('bouncer:clean')->weekly();`

I get the following error:

```
Message
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: select distinct "entity_type" from "abilities" where "abilities"."entity_id" is not null and "abilities"."entity_id" != and "abilities"."entity_type" != *)
Level
ERROR
Exception
{
    "class": "Illuminate\\Database\\QueryException",
    "message": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"*\" (SQL: select distinct \"entity_type\" from \"abilities\" where \"abilities\".\"entity_id\" is not null and \"abilities\".\"entity_id\" != * and \"abilities\".\"entity_type\" != *)",
    "code": 22,
    "file": "/var/task/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678",
    "trace": [
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Connection.php:638",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Connection.php:346",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2303",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2291",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2786",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2292",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:549",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:533",
        "/var/task/vendor/silber/bouncer/src/Console/CleanCommand.php:149",
        "/var/task/vendor/silber/bouncer/src/Console/CleanCommand.php:103",
        "/var/task/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:238",
        "/var/task/vendor/silber/bouncer/src/Console/CleanCommand.php:108",
        "/var/task/vendor/silber/bouncer/src/Console/CleanCommand.php:42",
        "/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36",
        "/var/task/vendor/laravel/framework/src/Illuminate/Container/Util.php:40",
        "/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93",
        "/var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37",
        "/var/task/vendor/     


```
