### ISSUE TITLE
[Solved] Not working after upgrade from L5.5 to 5.8 (v1.0.0-beta.4 to v1.0.0-rc.5)

### ISSUE THREAD

**Issue by dhcmega** [JosephSilber/bouncer#447]
Hi
I have upgraded and now I'm getting not authorized.
`Illuminate\Auth\Access\AuthorizationException [This action is unauthorized.]`

My code is in the controller:
```
    /**
     * @param null $method
     * @throws AuthorizationException
     */
    public function canOrFail($method = null)
    {
        if (!Gate::allows($method)) {
            throw new AuthorizationException('This action is unauthorized.');
        }
    }
```

All my controllers have this method and all other methods call it passing the method name.

EDIT1:
I have updated the tables:
```
alter table `abilities` add `options` json null after `only_owned`;
alter table `abilities` add `scope` int null after `options`;

alter table `assigned_roles` add `restricted_to_id` int null after `entity_type`;
alter table `assigned_roles` add `restricted_to_type` int unsigned null after `restricted_to_id`;
alter table `assigned_roles` add `scope` int null after `restricted_to_type`;

alter table `permissions` add `id` int(11) unsigned NOT NULL primary KEY AUTO_INCREMENT first;
alter table `permissions` add `scope` int null after `forbidden`;

alter table `roles` add `scope` int null after `level`;
```

EDIT2:
I'm using custom model
`Bouncer::useRoleModel(\App\Models\Role::class);`

EDIT3:
So, I should have changed `App\Models\Role` with `roles` in my permissions table in column `entity_type` 
`update permissions set entity_type = 'roles'`

**Comment by bkuhl** [comment]
If you figured out the solution, please close the issue.
