### ISSUE TITLE
Check permission in the controller?

### ISSUE THREAD

**Issue by asivaneswaran** [JosephSilber/bouncer#448]
Hi,

I am currently using Policies to verify the permissions of a user. What I do is that in my controller I use:

` $this->authorize('index', Account::class);`

How can I use this with Bouncer? I can check to update my policy to use the Bouncer but I wanted to know if there is a better way?

Thanks,

**Comment by ipontt** [comment]
`$this->authorize($ability, $arguments)` works with Bouncer. And it has the added benefit of throwing an Authorization Exception autmatically on failure (which gets translated to a 403).

If you only need to return a boolean (as a condition for an if/else statement for instance), you could use `$user->can($ability, $arguments)`, `$user->cant($ability, $arguments)` or  `$user->cannot($ability, $arguments)`

A third option is to use the Gate class to do your checking.

**Comment by JosephSilber** [comment]
If you've given the user the ability to view all accounts:

```php
Bouncer::allow($user)->to('view', Account::class);
```

Then you can guard for that in your controller using:

```php
$this->authorize('view', Account::class);
```
