### ISSUE TITLE
Laravel Roles and Permissions with parameters (models)

### ISSUE THREAD

**Issue by liamoreilly** [JosephSilber/bouncer#449]
Hi,

I will try to keep this short. I know this has already been asked in [#239](https://github.com/JosephSilber/bouncer/issues/239) and [#255](https://github.com/JosephSilber/bouncer/issues/255). The answer was, more or less, this is a nice feature to want but might only be implemented in the future.

Is there any progress or plans for this feature.

I am planning on extending a system that helps me mark students off in lab classes of various courses that they are enrolled in. I have a basic version of the system working, but it needs a better permission system.

I have users and courses. What I want is the ability to have roles such as "Coordinator" and "Grader" but based on a course.

So a particular user might be a "Grader on Course1" and a "Coordinator on Course2"

The role of "Grader on Course X" would have underlying abilities of "Can view Course X", "Can Grade Course X" etc. "Coordinator on Course X" might have other abilities such as "Can enroll students on Course X".

So my roles and abilities are sort of parameterized by courses (i.e., a model). I believe this is often referred to as row permissions.

The abilities can already be tied to a model, but roles cannot. I think the way I would expect this to work is that if you have a user "MyUser" having a role "MyRole" on a course "C" then this would mean that the user has all the abilities of the role but applied only to course "C".

I think adding this would make Bouncer standout even more. I cannot find any other Laravel Package that has the ability to deal with roles and abilities at the model level properly. What I mean by this is that you need roles as an abstraction level to support this model restriction.

Anyway, any update on this feature would be great.

Thanks,
Liam

**Comment by JosephSilber** [comment]
As you said, this has been requested before. I have it on my list of requested features, but haven't gotten around to really doing anything concrete about it.
