### ISSUE TITLE
How to delete Roles?

### ISSUE THREAD

**Issue by Synchro** [JosephSilber/bouncer#454]
Creating new Roles is easy, and removing assignment of them with `retract` is also covered - but what is the right way to delete a Role altogether? I don't want to use the cleanup functions as there may be roles that are unused that I don't want to delete. I can delete them in the database directly, but that seems kind of ugly - is there a better way?

**Comment by JosephSilber** [comment]
Roles in Bouncer are regular Eloquent models, so you have all of Eloquent's power available to you:

```php
Bouncer::role()->where('name', 'admin')->delete();
```

**Comment by Synchro** [comment]
Thanks, I'll do that.
