### ISSUE TITLE
Ability to support user's with multiple roles, but restricted by multi-tenancy

### ISSUE THREAD

**Issue by abodnar** [JosephSilber/bouncer#455]
I'm working on an application that does multi-tenancy and I'm looking at trying to replace a custom permission system with Bouncer due to it's ability to grant permissions across models or individual objects. Because of the multi-tenancy, we allow a user to have a different role per group they are in. I've read through the documentation and I'm not seeing an easy way to support that functionality with Bouncer. 

I assume I would have to modify the migration to add a new column to the "roles" table. But I've run into a roadblock with customizing Bouncer to support that new field and restrict by it when checking permissions. Would I create a scope? or create a new Role object? or am I making this too complicated?

Any help is appreciated.

**Comment by JosephSilber** [comment]
> Because of the multi-tenancy, we allow a user to have a different role per group they are in. I've read through the documentation and I'm not seeing an easy way to support that functionality with Bouncer.

Have you read through [the documentation on multi-tenancy](https://github.com/JosephSilber/bouncer#multi-tenancy)? I think that describes exactly what you're looking for.

If not, can you explain what's missing?

**Comment by abodnar** [comment]
Yeah and I'm not sure what I didn't get at the time, but it makes sense now.

Thanks.
