### ISSUE TITLE
[Question] Role, ability, user access.

### ISSUE THREAD

**Issue by ManukMinasyan** [JosephSilber/bouncer#456]
I created a role, I assign a role to the user. After that, I assign the ability to the role. But the user does not have access to this ability.

Assign a role to the user:
```php
$user->assign(Role::find($id));
```
Assign a ability to the role.
```php
Bouncer::allow($role)->to($ability);
```

**Comment by JosephSilber** [comment]
This is the most basic usage of Bouncer, which seems to work for everyone.

Can you please provide more details? Or even an actual reproduction?

**Comment by ManukMinasyan** [comment]
![1](https://user-images.githubusercontent.com/2556185/64920704-a77f9500-d7cb-11e9-8fc6-617a46fe8615.PNG)
![2](https://user-images.githubusercontent.com/2556185/64920705-a8182b80-d7cb-11e9-9d57-f81f4d50b6b3.PNG)

Please look at this code and the result. Thanks.

**Comment by ManukMinasyan** [comment]
I successfully solved this problem using the getAbilities () method. Thank you
