### ISSUE TITLE
How to implement toOwn and ownedVia method?

### ISSUE THREAD

**Issue by shseah601** [JosephSilber/bouncer#457]
I am experiencing an issue that client with id 1 is able to view a booking that is created with client_id 2, which is supposed forbidden.

```
$client = Bouncer::role()->create([
            'name' => 'client',
            'title' => 'Client'
        ]);
```
Above is the role.
```
Bouncer::allow($client)->toOwn(Booking::class)->to(['view']);
```
Above is to let the role to own Booking model.
```
Bouncer::ownedVia(Booking::class, function ($booking, $user) {
  $client = Client::where('user_id',$user->id)->first();
  return $booking->client_id == $client->id;
});
```
Above is to set the custom logic.

The booking model has client_id but does not have user_id. There is a Client model which create with user_id. So, my logic is that the client create a booking with client id (not same as user id), then only the client can view the booking by checking its client id.

How do I actually implement in my controller or my application?

**Comment by ipontt** [comment]
You put the `Bouncer::ownedVia` bit inside the boot method of a service provider. That's it. Whenever you check permissions, if it can be solved through ownership of a model, and Bouncer has an `ownedVia` for that model, it will run that bit of logic.

What you're describing sounds like the same user id is present in both client 1 and 2

**Comment by JosephSilber** [comment]
> How do I actually implement in my controller

Are you asking where you should put that code?
