### ISSUE TITLE
What is the utility of the `restricted_to` columns in `assigned_roles` table?

### ISSUE THREAD

**Issue by ImadSalimi** [JosephSilber/bouncer#462]
What is the utility of the `restricted_to` columns in `assigned_roles` table if the method to assign a role to a user doesn't take into consideration this restriction?

`Bouncer::assign('some role')->to($user)` as you can see there's no restriction here. It would be awesome to give someone a role just for a given model, and I assume that's what the columns are for, but there is no method that achieves this.

**Comment by JosephSilber** [comment]
> What is the utility of the `restricted_to` columns in `assigned_roles` table

It's currently not being used. It's there for potentially adding the ability to grant a user a role only for a specific model.

> It would be awesome to give someone a role just for a given model, and I assume that's what the columns are for, but there is no method that achieves this.

Correct. It's there so that potentially adding this feature at a later date won't be a breaking change.

**Comment by ImadSalimi** [comment]
Ehhh :( would it be hard to implement? if so I might have a go at a pull request
