### ISSUE TITLE
Support multiple role and permission tables?

### ISSUE THREAD

**Issue by xlkit456852** [JosephSilber/bouncer#464]
Laravel Version: 5.5.*

Description:
Our project has two different user type (platform/brand) and they have their own role table and permission table , like this:

user tables:
administrator_platforms、administrator_brands

role tables:
role_platforms、role_brands

permission tables:
permission_platforms、permission_brands

permission_role tables:
role_permission_platforms、role_permission_brands

Is there a way to handle roles and permission in different user type independently ?

**Comment by ctwillie77** [comment]
I'm trying to understand the same thing. I have two "admin" roles that should have different permissions in either section of my app. Should my permissions have a prefix? Or how do I scope permissions by the route? Not sure how this is done.

**Comment by JosephSilber** [comment]
Have you read the documentation?

https://github.com/JosephSilber/bouncer/blob/master/readme.md

**Comment by JosephSilber** [comment]
Have you read the documentation?

https://github.com/JosephSilber/bouncer/blob/master/readme.md#can-i-use-a-different-set-of-roles--abilities-for-the-public--dashboard-sections-of-my-site-respectively

**Comment by ctwillie77** [comment]
@JosephSilber Thanks for your reply. I did read the documentation. Just need clarification on implementation. If I do the above, then, Bouncer::allow('new_admin_role')->everything(), how are the permissions distinguished between to sections of my app. I only want "new_admin_role" to have every permission within a scope of my app. I don't understand this from just reading the docs, so I asked. Thanks!

**Comment by JosephSilber** [comment]
@ctwillie77 the documentation I linked to has an exact, three-step process for how to achieve that. Have you tried following that?

**Comment by ctwillie77** [comment]
Correct me if I am wrong. That three step process is only scoping a piece of middleware to certain routes. I get that. I'm wanting to know how to scope permissions to a section of my app where the other section has no idea those permissions exist. Again, I have two "admin" roles. I want each to be able to do "*" without specifically adding each permission to the admin role. I can use the scoped middleware later, but that doesn't help me in my blade templates for permission checks.

**Comment by ctwillie77** [comment]
Ok, got it working by doing "exactly what the docs say". Great package, no doubt. But I must say, there are several things not expounded upon enough in the docs that leave us to figure out the practical usage. After showing how to change Bouncer scope using the middleware, I would have liked to see one or two practical use cases. And maybe answering a couple edge case questions, like, "if I have a role that is scoped, then allow it a permission, does the permission inherit the roles permission". Thanks anyway!  : )

**Comment by JosephSilber** [comment]
> there are several things not expounded upon enough in the docs that leave us to figure out the practical usage

Can you please elaborate hat that is? How can we improve the docs?

> I would have liked to see one or two practical use cases

What kind of usecases are missing? After setting up the scope, you use Bouncer just like you normally would. There's no additional step.
