### ISSUE TITLE
Adding permissions to different Model?

### ISSUE THREAD

**Issue by ctwillie** [JosephSilber/bouncer#465]
How would one go about adding permissions to another model? I am using the default user model in laravel with bouncer. I want to be able to add permissions to my "Department" model and have bouncer work the same with. So, If I allow a permission to a Department, then check for that permission on a user that belongs to that department, bouncer will authorize.

What would need to be done to accomplish this for permissions. I don't plan to assign roles to Departments, only permissions.

**Comment by JosephSilber** [comment]
Bouncer lets you grant roles and abilities to any type of model:

```php
Bouncer::allow($department)->to('create', Coo::class);
```

However, when checking a user's ability, Bouncer won't automatically check the department. For that, you'll need a policy class:

```php
class CooPolicy
{
    public function create($user)
    {
        return $user->department->can('create', Coo::class);
    }
}
```

**Comment by ctwillie77** [comment]
So after doing the first step above, the ability is created in "abilities" table, but there is no record for assignment in "permissions" table.

I planned to query the "permissions" table in my policy logic for this check, but no record is being created. Is it something to do with the lazy conductor?

**Comment by ctwillie77** [comment]
Also, in reference to,

> Bouncer lets you grant roles and abilities to any type of model:

I'm getting this error when trying to grant a department permission to a specific resource.

Example:
$page = App\Page::first();
$department = App\Department::first();
Bouncer::allow($department)->to('view', $page);

Error:
BadMethodCallException with message 'Call to undefined method App/Department::abilities()

**Comment by JosephSilber** [comment]
To add permissions to other models, be sure to use [the `Authorizable` trait](https://github.com/JosephSilber/bouncer/blob/master/src/Database/Concerns/Authorizable.php):

```php
use Illuminate\Database\Eloquent\Model;
use Silber\Bouncer\Database\Concerns\Authorizable;

class Department extends Model
{
    use Authorizable;
}
```

**Comment by ctwillie77** [comment]
So, I'm working in tinker for testing.
I added the "Authorizable" trait to my department model.
after running: 
```php
Bouncer::allow($department)->to('view', $page)
```
I still get an error in tinker:
```php
BadMethodCallException with message 'Call to undefined method App/Department::abilities()
```
Despite the error in tinker, the record is SUCCESSFULLY created in the "abilities" table, but NO RECORD is created in the "permissions" table.
Is there something I am missing?

**Comment by ctwillie77** [comment]
Any help here? I created a work around to add and check department abilities, but its definitely not the laravel way.

**Comment by ctwillie77** [comment]
I get a policy is required to check the permissions, but this

```php
Bouncer::allow($department)->to('create', Coo::class);
```

isn't even working properly. And yes, I did add the Authorizable trait.

**Comment by ziming** [comment]
Hi @ctwillie 

Encountered the same problem today. Hope you solved yours.

The solution I found is to add Authorizable trait and HasAbilities trait as follows

```php
use Authorizable, HasAbilities {
        Authorizable::getClipboardInstance insteadof HasAbilities;
    }
```

Hope it helped you as it has helped me. The docs could benefit from an update on this. Cheers!

**Comment by ctwillie** [comment]
I appreciate helpful response. Im going to try this out now. Will give you an update.
