### ISSUE TITLE
Not compatible with laravel 6 

### ISSUE THREAD

**Issue by mithublue** [JosephSilber/bouncer#466]
I am trying to require it with composer command

composer require silber/bouncer

But, an error is shown like below

Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Conclusion: remove laravel/framework v6.0.1
    - Conclusion: don't install laravel/framework v6.0.1

Which means, it is not compatible to use with laravel 6.

How to use it in laravel 6 ?

**Comment by JosephSilber** [comment]
Try this:

```
composer require silber/bouncer v1.0.0-rc.6
```
