### ISSUE TITLE
How can I use Laravel Bouncer on a microservice architecture.

### ISSUE THREAD

**Issue by akmalhazim24** [JosephSilber/bouncer#468]
Hi,

I'm using laravel bouncer to handle the authorization part of my microservices. I'm thinking of using the 'entity_type' column as the microservice name and the 'entity_id' for the model in the microservice respectively.

Is they anyway to achieve this?

Thank you!

**Comment by merlinblack** [comment]
I'm looking for the same use case. Users in a Auth microservice, Orders in another microservice. We want to assign abilities to users on particular orders.  I really don't want to make a proxy table in our Auth service for Orders.

**Comment by JosephSilber** [comment]
Bouncer relies heavily on `join`s, so I'm not sure what you're asking for is possible.
