### ISSUE TITLE
Github Actions and Bouncer

### ISSUE THREAD

**Issue by agentphoenix** [JosephSilber/bouncer#471]
I've started playing around with Github Actions the last couple of days, but every time I run a workflow, I get a `BindingResolutionException` from Bouncer. I realize Actions is still in beta and not everyone has access to it yet, but wanted to see if anyone has run into this issue or has ideas of how it might be solved.

I don't see this exception when I'm using the app and this is a straight-up stock Bouncer implementation. Any ideas why the exception below would be happening?

Illuminate\Contracts\Container\BindingResolutionException: Target [Silber\Bouncer\Contracts\Clipboard] is not instantiable while building [Silber\Bouncer\Bouncer, Silber\Bouncer\Guard].

**Comment by JosephSilber** [comment]
[Bouncer's tests](https://github.com/JosephSilber/bouncer/actions) now actually run on [GitHub Actions](https://github.com/JosephSilber/bouncer/blob/master/.github/workflows/tests.yml).

It seems like this has something to do with the way your app is set up 🤷‍♂
