### ISSUE TITLE
Correct way to use Bouncer AND Laravel Policies for different application sections

### ISSUE THREAD

**Issue by romanzipp** [JosephSilber/bouncer#472]
Hey!

I've built an application which is splitted between an

- **Administration Dashboard**
  - uses authorization through Bouncer
  - Bouncer scope 1

and an

- **API**
  - should utilize code defined Laravel Policies
  - Bouncer scope 2 (to get rid of the admin permissions data) without any defined roles/abilities

I've already separated both application sections through Bouncer scoped middlewares and told Bouncer to run before the defined policies.

```php
Bouncer::runAfterPolicies(false);
```

Is there recommended a way to strictly differentiate between these two application sections?

**Comment by rdcx** [comment]
I'm also looking for a solution to this? @JosephSilber I've got policies defined which are not being called if the user has the ability with Bouncer. Because bouncer gives it the thumbs up callAuthCallback is never called in the Gate::raw method. Was this done on purpose?

Thanks

**Comment by rdcx** [comment]
Turns out this issue actually answered my question runAfterPolicies was what I was looking for. Sorry for the notification.

**Comment by rdcx** [comment]
If the Policy returns true does this then not run the Bouncer check at all?

**Comment by hailwood** [comment]
@romanzipp you're using the bouncer scopes correctly,
they serve the purpose of differentiating the sections. Is there a specific issue you're having?

@rdcx I *believe* that if `runAfterPolicies` is `true` then the bouncer rules will only be checked if the policy returned null (I.e. if it returns `true` or `false` bouncer is not consulted).

**Comment by SteenSchutt** [comment]
I ended up in this situation as well. I think I'm going to scope out the admin panel (Which uses Bouncer) and the token auth pages, and then run `Bouncer::runAfterPolicies(true);` as well as `Bouncer::forbidEveryone()->everything();` for the token auth pages, such that missing policies etc. are denied, as is the default without Bouncer.
