### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::hasRole()

### ISSUE THREAD

**Issue by cvlug** [JosephSilber/bouncer#473]
Why do i get Call to undefined method Illuminate\Database\Query\Builder::hasRole(), when using public function __construct()
    {
        $this->middleware('auth');

        $this->middleware(function ($request, $next) {
            Bouncer::can('adminX').
            return $next($request);
        });
    }

Same error occures when using:
Route::group(['middleware' => 'can:adminX'], function () {
    Route::resource('users', 'UserController');
});

php:7.2, laravel: 5.6

**Comment by hailwood** [comment]
Have you added the trait to the user model?

**Comment by cvlug** [comment]
thanks for your anser.
In the meanwhile is stopped using bouncer, so i don't know anymore if i had added the trait.
I stopped with Bouncer, because it requires a very recent version of the database server, while in the documentation, therre is nothing written about that. If i brougth bouncer to production, that has a less recent database server, i would have a big problem.

**Comment by JosephSilber** [comment]
> Why do i get Call to undefined method `Illuminate\Database\Query\Builder::hasRole()`

Nowhere in Bouncer's codebase (nor in Laravel's codebase) is there a call to any `hasRole` method. You must have that method call somewhere in your own codebase, or some other package.

> it requires a very recent version of the database server

What would make you think that?

**Comment by cvlug** [comment]
Thanks.
Maria db support json only since 2 years (https://mariadb.com/kb/en/library/json-data-type/)

**Comment by JosephSilber** [comment]
I'll just leave this here:

https://github.com/JosephSilber/bouncer/blob/master/readme.md#im-trying-to-run-the-migration-but-im-getting-a-sql-error-that-there-is-a-syntax-error-or-access-violation-1064--to-use-near-json-not-null

**Comment by JosephSilber** [comment]
https://github.com/JosephSilber/bouncer/blob/master/readme.md#im-trying-to-run-the-migration-but-im-getting-a-sql-error-that-there-is-a-syntax-error-or-access-violation-1064--to-use-near-json-not-null
