### ISSUE TITLE
Parameterized/Nested Roles

### ISSUE THREAD

**Issue by hamidwaqas** [JosephSilber/bouncer#474]
I am planning on extending a system that helps me mark students off in lab classes of various courses that they are enrolled in. I have a basic version of the system working, but it needs a better permission system.

I have users and courses. What I want is the ability to have roles such as "Editor", "Writer", "Coordinator" and "Grader" but based on a course.

So a particular user might be a "Grader on Course1" and a "Coordinator on Course2" and "Editor on Course 3" (Editor will be able to add Chapters and Writers will be able to write about assigned chapters)

So my roles and permissions are sort of parameterized by courses and chapters.

With JosephSilber/bouncer I understand that I can make roles such as Grader and Coordinator (along with the underlying permissions). But that would not allow me to make a particular user a Grader on one course but not all the others.

Combining this package (JosephSilber/bouncer) with Laravels policies I think I get closer. The policies are parameterized by models (i.e., the Course model in my case). But I don't understand how the policies would tie in with the roles and permissions unless they are too parameterized.

Any ideas on the best way to solve this?

One way I thought of was to have roles such as "coordinator_course1", "coordinator_course2", "coordinator_course3" ... and permissions such as "can_view_course1", "can_view_course2", "can_view_course3", ... But this feels like a poor choice.

Another way would be adding two columns on abilities tables "resource_type" and "resource_id", resource_type will be courses table or chapters table and resource_id will be their primary key

Any advice would be most welcome.

**Comment by hailwood** [comment]
@hamidwaqas If you really wanted to use bouncer here you could look at scopes, or bouncer does have the ability to assign permissions against specific models. But this actually seems like you don't need bouncer at all and adding it is just going to complicate the scenario.

I'd just have on each course a many_many relationship of "graders", "editors", and "coordinators" and then in your policy just check that list.

Obviously other parts of the system bouncer will be useful, I'm not saying don't use it at all, just don't try and make it fit everywhere, it's not made to "replace" laravels built in access control, it's made to augment it!
