### ISSUE TITLE
Some functions are not recognized by laravel 6?

### ISSUE THREAD

**Issue by hesamzakerirad** [JosephSilber/bouncer#479]
I'm trying to check current logged in user's role like `Auth::user()->isAn('admin')` and every time I'm faced with this error: 
```
BadMethodCallException
Call to undefined method App\User::isAn()
```

and when I'm tryign `Bouncer::is(Auth::user())->an('admin')` I get : 
```
BadMethodCallException
Call to undefined method App\User::roles()
```

By the way, Bouncer is added to the middleware class.
Have I forgot something or is this an issue to be fixed?
Thank you :)

**Comment by Wikiki** [comment]
Hi,

Working perfectly on my side with Laravel 6.4.
Don't you forget to add <code>Silber\Bouncer\Database\HasRolesAndAbilities</code> Trait on your User Model ?
