### ISSUE TITLE
How to use bouncer in php unit tests?

### ISSUE THREAD

**Issue by Tjoosten** [JosephSilber/bouncer#48]
I was wondering. How can i integrate Bouncer in the laravel testing API???

**Comment by JosephSilber** [comment]
You shouldn't need anything special for bouncer to work in your tests.

What issues have you run into?

**Comment by Tjoosten** [comment]
I gave specific routes that are required to be accessed with an admin role.

**Comment by JosephSilber** [comment]
It is no different than anywhere else. Assuming you're using the migrations trait, you'll just create your user and give them the ability.

**Comment by Tjoosten** [comment]
I don't get it. Do you have a example?

**Comment by JosephSilber** [comment]
Here's an example, using [the included sample test case file](https://github.com/laravel/laravel/blob/master/tests/ExampleTest.php):

```php
<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ExampleTest extends TestCase
{
    use DatabaseMigrations, DatabaseTransactions;

    public function testBasicExample()
    {
        $user = factory(App\User::class)->create();
        $post = factory(App\Post::class)->create(['title' => 'My post'])

        Bouncer::allow($user)->to('view', $post);

        $this->be($user)
             ->visit('posts/'.$post->id)
             ->see('My post');
    }
}
```

**Comment by Tjoosten** [comment]
Thx! U rock this!

**Comment by JosephSilber** [comment]
@Tjoosten since the migrations files are not within their own namespace, don't import the `Bouncer` facade. I didn't import it in the example I posted above.

**Comment by Tjoosten** [comment]
fixed it thx!
