### ISSUE TITLE
Entity users having ability to view the entity?

### ISSUE THREAD

**Issue by alituzunkan** [JosephSilber/bouncer#480]
is there anyway to get the list of users who has permission to view an object lets say $classifiedDocument

**Comment by SteenSchutt** [comment]
I agree, something along the lines of `User::whereCan('view', $model)` would be super helpful. I'm not sure how well it could be optimized, though.

**Comment by JosephSilber** [comment]
This is a commonly requested feature, but is not possible in Bouncer, since many checks are done in code and can't be replicated in just a query.
