### ISSUE TITLE
Not working with SoftDeletes

### ISSUE THREAD

**Issue by CreativeBulma** [JosephSilber/bouncer#485]
Hi,

When I use softdelete with my user Model and try to delete a user all assigned roles assigned are completely removed from my DB  and I can't have a real soft delete behavior. How can I activate softdelete on role assigned ? So I'll be able to restore my users with their origin roles !

regards,

**Comment by emilas44** [comment]
This is true....

I have reproduced it like this:

Create a user and assign him a role...
Soft delete the user
Restore the user

And that user will not have that role anymore...

**Comment by hailwood** [comment]
Related #439

**Comment by emilas44** [comment]
still waiting for this to be fixed/merged :(

**Comment by JosephSilber** [comment]
The linked issue has been fix. Closing this for now. If it's still an issue, please reopen with more details.
