### ISSUE TITLE
Document Constraints

### ISSUE THREAD

**Issue by Hobadee** [JosephSilber/bouncer#486]
Poking around in the code I see references to Constraints.  (Silber\Bouncer\Constraints and associated classes)

I have played around with them some and even got them to write out their configuration to the database, but I can't figure out how to actually use them.  They appear to be completely undocumented, and I can't quite figure out how they tie into things, although they also appear to be VERY powerful.

If you could get me started on using them, I could whip up some documentation for them.  I already created a holding page on the Wiki: https://github.com/JosephSilber/bouncer/wiki/Ability-Constraints

**Comment by JosephSilber** [comment]
Constraints are not fully implemented yet, which is why they're not documented. They're useless in their current form.
