### ISSUE TITLE
Documentation part 3

### ISSUE THREAD

**Issue by barhom** [JosephSilber/bouncer#49]
In the docs it says;

3) Add the bouncer's trait to your user model:
use Silber\Bouncer\Database\HasRolesAndAbilities;

class User extends Model
{
    use HasRolesAndAbilities;
}

Clarifying;

I would like to suggest that this needs clarification.
If I understand correctly then "use HasRolesAndAbilities;" goes to app/User.php.

app/User.php looks totally different from that example - Take a look: https://github.com/laravel/laravel/blob/master/app/User.php

**Comment by JosephSilber** [comment]
The model can look very different depending on what you did to it.

Also, in 5.1 the model looked totally different: https://github.com/laravel/laravel/blob/5.1/app/User.php

It makes no sense to include all that crap in the docs. A basic understanding of PHP is a reasonable prerequisite.
