### ISSUE TITLE
How would you check users access through teams permission

### ISSUE THREAD

**Issue by grenadecx** [JosephSilber/bouncer#492]
I understand that this section isn't for for support, but I think the question and answer could benefit more users. 

In my application I have users and teams (teams extends Illuminate\Foundation\Auth\Access\Authorizable and uses the HasRolesAndAbilities trait), and when I apply permissions to specific models, I'm doing it by either allowing a user or team a certain ability. And then one or more teams could be added to a user.

Now, when I want to check if a user has access to something, it would make sense to keep the:

```
    $user->can('view');
    // or
    $user->can('view', $model);
```

But that would only check the abilities applied directly to the user or by the users roles.

What would be the best way to achieve this so that it would also check the teams access?

Right now I'm overriding the can method on the user model to the following:

```
    public function can($ability, $arguments = []){

        $check = app(Gate::class)->forUser($this)->check($ability, $arguments);

        if($check === true){
            return $check;
        }

        if (!isset($this->relations['teams'])) {
            $this->load(['teams']);
        }

        foreach($this->teams as $team){
            $check = app(Gate::class)->forUser($team)->check($ability, $arguments);

            if($check === true){
                return $check;
            }
        }

        return false;
    }
```
And that seems to work, though I haven't tested it all that well yet. But is there a better way to do this?

One thought I had was to try using the Gate::after to make the extra check instead, but it felt more messy and in the end it didn't seem that bouncer respected that at all.

Also keep up the good work, I think bouncer is really powerfull, does a good job and is very flexible when it comes to allowing/denying permissions for different stuffs.

**Comment by bpuig** [comment]
Wouldn't it be a [scope](https://github.com/JosephSilber/bouncer#the-scope-middleware)?

But it would work only for a User belongs to one Team, because the scope uses ` $query->where()` instead of ` $query->whereIn()`. You'd need to fork and modify the package if you want more than one team per user, maybe it should be like this:

```
public function handle($request, Closure $next)
{
    $teamIds = $request->user()->teams->pluck('id');

    Bouncer::scope()->to($teamIds);

    return $next($request);
}
```


And you'd have to fork the code with `whereIn` in `src/Database/Scope/Scope.php`:
```
/**
     * Apply the current scope to the given query.
     *
     * This internal method does not check whether
     * the given query needs to be scoped. That
     * is fully the caller's responsibility.
     *
     * @param  \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder  $query
     * @param  string  $table
     * @return \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder
     */
    protected function applyToQuery($query, $table)
    {
        return $query->where(function ($query) use ($table) {
            $query->whereIn("{$table}.scope", $this->scope)
                  ->orWhereNull("{$table}.scope");
        });
    }
```
Take this as a hint because I have not tested it. I'm getting myself into the package because I'm facing other relationship issues, so this may work or not, I'm not that deep in knowledge about it.

**Comment by grenadecx** [comment]
Thanks for the reply. Since I don't want to fork this I'll keep using my solution until I find something else.
