### ISSUE TITLE
Different Ownership by abilities

### ISSUE THREAD

**Issue by githubjakob** [JosephSilber/bouncer#493]
In my usecase a User can view some Data in case the Data belong to User's Client. I'm implementing this with the Bouncer Ownership feature.

```
Bouncer::allow($user)->toOwn(Data::class)->to(['view']);

Bouncer::ownedVia(Data::class, function ($data, $caller) {
    return $caller->clients->contains($data->client->id);
}
```

This works fine! 

But now a User can also edit Data in case the Data is created by the User. 

If I do this, then the user can edit and view the same group of Data.
```
Bouncer::allow($user)->toOwn(Data::class)->to(['view', 'edit']);
```

How can I have different "ownerships" for various abilities? Like this:

```
Bouncer::ownedVia(Data::class, function ($data, $caller) {
    // if ability is view 
    return $caller->clients->contains($data->client->id);
    // else if ability is edit
   return $data->owners()->contains($caller->id);
}
```

**Comment by JosephSilber** [comment]
It seems like you're not looking at ownership, and more at custom logic for your abilities.

I believe at this point you'll be better off sticking this logic into a policy.
