### ISSUE TITLE
Fail if ability or role is not in database (Strict Mode)

### ISSUE THREAD

**Issue by Ghustavh97** [JosephSilber/bouncer#495]
Is there a way to make bouncer throw an exception/fail if I try to assign a role or ability that does not exist in the database instead of creating it?

**Comment by JosephSilber** [comment]
Instead of assigning the role by name/ID, assign it using the actual role model:

```php
$admin = Bouncer::role()->where('name', 'admin')->firstOrFail();

Bouncer::assign($admin)->to($user);
```
