### ISSUE TITLE
@can not working in blade

### ISSUE THREAD

**Issue by woottonn** [JosephSilber/bouncer#498]
Hello. I'm trying (and failing!) to install bouncer to a project. I've got a couple of things working, like being able to assign roles and assign abilities to roles etc. However I'm struggling with the following...

I have this code in a blade file:

```
@can('USERS-view-users')
        <a class="dropdown-item" href="{{ route('users.index') }}">View Users</a>
@endcan
```

It throws this error: **Call to undefined method App\User::hasRole() (View: C:\Users\User\PhpstormProjects\run-bouncer\resources\views\admin\nav.blade.php)**

This is my User model...

```
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Silber\Bouncer\Bouncer;

class User extends Authenticatable
{
    use Notifiable, HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}
```

Is there something I'm missing here? I can check roles perfectly well - for example, this works for me..

```
@if(Auth::user()->isA('SuperAdmin')||Auth::user()->isA('PLTStudent'))
         @include('admin.nav')
@endif
```

**Comment by JosephSilber** [comment]
The `@can` directive is a native Laravel Blade directive, It should be calling `hasRole` at all.

Are you sure this is where the error is?

**Comment by woottonn** [comment]
Yeah its a weird one. For now I have abandoned this route and gone with core laravel gates, thanks for your help!
