### ISSUE TITLE
Get the title field instead of name with getRoles

### ISSUE THREAD

**Issue by uicabpatweyler** [JosephSilber/bouncer#499]
When using $user->getRoles(), the query returns the role or roles associated with the user, however I have noticed that it actually returns the value of the "name" field of the "roles" entity. Is it possible that this query returns the value of the "title" field? Since it is necessary that in the application the "name" of the role remains intact, since it would be used in several parts (models, views, controllers) for certain checks. For example: A user with the Administrator role name could not delete a role name as Super User. 
Or maybe, is there any suggestion not to depend on the name of the role?

Thanks for your comments, regards.

**Comment by JosephSilber** [comment]
You can always get the titles yourself using the `roles` relationship:

```php
$user->roles()->pluck('title');
```
