### ISSUE TITLE
Policies usage

### ISSUE THREAD

**Issue by a-komarev** [JosephSilber/bouncer#5]
Is your package supporting Laravel Policies in any way?
Because I've already got a policies with some complex logic like checks for the groups membership subscriptions state and it's type and etc or it suppose that application should grant an abilities for the user on groups joining\leaving and so on?

**Comment by JosephSilber** [comment]
Policies are for permissions logic that lives in the code, while the bouncer is for permissions that are stores in the database.

The Bouncer package has been specifically designed to play nicely with permissions defined in your policies; they work hand in hand.

The bouncer will not block any permissions that your policies grant.

**Comment by a-komarev** [comment]
I like how it's done... Even Gate::allows() working together with Bouncer::allows(), same way exactly.

**Comment by a-komarev** [comment]
But I'm not clearly understand if I had policy:
```php
class PostPolicy
{
    public function update() { ... }
}
```

And in controller:
```php
Gate::denies('update', $post);
```

And have 'update' for Post model in Bouncer's ability. It will use Bouncer one, am I right? But if there is no such ability it will look for policy method?

**Comment by a-komarev** [comment]
Yes, I've rechecked. If there is bouncer ability with this name exists - it will check is action is allowed or not in Bouncer abilities and would skip Policy checks. I'm not sure is it good or not...

The only way to solve it for this moment is prefixes in names.

What do you think about ability to perform policy check if bouncer returned `true` or perform policy checks first and then go to Bouncer checks if there is a same name for Policy and Bouncer ability?

**Comment by JosephSilber** [comment]
The two systems are meant to complement  each other, not battle it out :smile: 

If you don't want to allow a certain ability, then don't register it with the bouncer.

**Comment by martimarkov** [comment]
@JosephSilber I have a policy that allows 'update'-ing when $user->id == $post->id but I want every $user in role 'admin' to be able to edit every Post. How would you suggest that should be done?

**Comment by Jeroen-G** [comment]
A `before` method in your policy to check for admin status. I believe this is explained in the Laravel documentation.

**Comment by Gummibeer** [comment]
Like @Jeroen-G  said or a check in the policy method itself like `if(isAdmin() || $post->id == $user->id)`

**Comment by JosephSilber** [comment]
> Yes, I've rechecked. If there is bouncer ability and Policy method name are intersecting - it will check is action allowed or not in Bouncer abilities and will skip Policy checks. I'm not sure is it good or not...

It will always check with Bouncer first. If Bouncer allows it, the permission will be granted. Otherwise it'll continue to check if there are any policies that allow it. No need to add any prefixes.

> I have a policy that allows 'update'-ing when $user->id == $post->id but I want every $user in role 'admin' to be able to edit every Post. How would you suggest that should be done?

No need for policies here. This can be fully handled with Bouncer:

```php
Bouncer::allow($user)->toOwn(Post::class);
Bouncer::allow('admin')->toManage(Post::class);
```

If you want the ownership ability to apply to all users, you can either add that `toOwn` call to all users, or create a base role that you apply to all users.

*I'm assuming you mean `$user->id == $post->user_id`, because comparing the user's ID to the post's ID doesn't make much sense.*

---

If you instead want to use a policy, here's how you'd do it:

1. First tell Bouncer that you want all admins to be able to `update` all posts:

    ```php
    Bouncer::allow('admin')->to('update', Post::class);
    ```

2. Create a policy that allows all users who own a given post to update it:

    ```php
    class PostPolicy
    {
        puclic function update($user, $post)
        {
            return $user->id == $post->user_id;
        }
    }
    ```

**Comment by martimarkov** [comment]
@JosephSilber This is a great explanation. Just one final question

> If you instead want to use a policy, here's how you'd do it:


How should I be doing the check in the controller action? I'm currently doing it with:

`\Gate::allows('update', $post)`

can I use 

` $this->authorize('update', $post);`


Which one would you recommend? 

----
Also just to comfirm `Bouncer::allow($user)->toOwn(Post::class);` will create only one record in the DB, if so I think that would be the best approach?

**Comment by JosephSilber** [comment]
1. `allows` returns a Boolean, `authorize` throws an error if the ability is not allowed. Use whichever one you want.

2. `toOwn` only works for a single user. So if you want that for every user, it'd still be one row per user.

3. Put it in a seeder file. You only want to run it once, when you originally deploy your app.
