### ISSUE TITLE
Seeding error in AppServiceProvider

### ISSUE THREAD

**Issue by barhom** [JosephSilber/bouncer#50]
Doing the following in AppServiceProvider.php (boot method):

Bouncer::seeder(function () {
    Bouncer::allow('admin')->to(['ban-users', 'delete-posts']);
    Bouncer::allow('editor')->to('delete-posts');
});

Gives;

  Non-static method Silber\Bouncer\Bouncer::seeder() should not be called statically

Unsure what I am missing.

**Comment by Arcesilas** [comment]
Hi,

Please be sure to add
```php
use Bouncer;
```

in your file so that it uses the Facade registered in IoC by Laravel.

**Comment by barhom** [comment]
My bad, I was trying to use "use Silber\Bouncer\Bouncer;".
Im closing this ticket.

**Comment by andyscraven** [comment]
Hi,

I used Bouncer in the normal Laravel Seeder and:

    use Bouncer;

could not find the Bouncer facade.

So to make it work I used: 

    use Silber\Bouncer\BouncerFacade as Bouncer;

which worked fine.

I did not want to put the roles in the AppServiceProvider but alongside my normal seeders.

**Comment by andyscraven** [comment]
For some reason when I used the normal Laravel Artisan seeder:  php artisan db:seed

    use Bouncer;

could not find the Facade, so I used:

use Silber\Bouncer\BouncerFacade as Bouncer;

and it worked a treat.

I just wanted all my seeders in the same place.

**Comment by andyscraven** [comment]
Do you know what would be really cool is if we could also check roles like this:

    $user->isNot('admin|editor');

I say this because it would work really well with my Roles route middleware:

    'middleware' => 'roles:admin|editor',

Just a thought :-)

Andy
