### ISSUE TITLE
Composer Install Fails With illuminate/database ^6.10

### ISSUE THREAD

**Issue by sundayz** [JosephSilber/bouncer#500]
```
composer require silber/bouncer v1.0.0-rc.6
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 4096 bytes)
```

I tried giving it more memory in php.ini but it didn't help. According to answers I found online it could be stuck trying to find packages which match my version requirements.

I tried just running `composer require silber/bouncer` with no version and it picks bouncer 0.1.7 which fails because it requires illuminate/database 5.1 or 5.2 but I'm using 6.10.

I'm using Eloquent ORM outside of a Laravel project.

Any ideas?

**Comment by JosephSilber** [comment]
Can I see your full `composer.json` file?

**Comment by sundayz** [comment]
```json
    "require": {
        "slim/slim": "^3.12",
        "slim/twig-view": "^2.5",
        "ext-pdo": "*",
        "slim/flash": "^0.4.0",
        "bryanjhv/slim-session": "~3.0",
        "ext-json": "*",
        "vlucas/phpdotenv": "^3.3",
        "php-di/slim-bridge": "^2.0",
        "php-di/php-di": "^6.0",
        "monolog/monolog": "^2.0",
        "illuminate/database": "^6.10",
        "silber/bouncer": "v1.0.0-rc.6"
    },
    "require-dev": {
        "phpunit/phpunit": "^8",
        "codeception/codeception": "^3.1"
    }
```

**Comment by JosephSilber** [comment]
When I tried it locally in a new directory, I also got this same error. That's weird, and I don't understand why.

Here's what did work for me:

1. Remove all entries in `require` and `require-dev`.
2. Delete the `vendors` directory and the `composer.lock` file.
3. Run `composer require silber/bouncer v1.0.0-rc.6`.
4. Re-add all dependencies in `composer.json`.
5. Run `composer update` to pull in all other dependencies.

**Comment by sundayz** [comment]
Thanks for the reply, I will try it out later and let you know. It will probably work.

I wonder if it happens because of illuminate 6.10, or if it's some long chain of dependencies that just happens to break composer.

Maybe if I give composer 16GB of ram it will eventually resolve the dependencies, but I doubt it, looks like it's stuck in a loop trying to find versions that work.

**Comment by sundayz** [comment]
Sorry for delay. Just so others know, 1.0-RC8 has the same issue but your solution works.
