### ISSUE TITLE
Ability not assigned with multiple user type

### ISSUE THREAD

**Issue by seintzz** [JosephSilber/bouncer#501]
Hi,

I'm having some issues working with Bouncer.

On the DB everything seems fine, roles and permissions seems to be assigned correctly but when I do `@can('view', $customer)` in the view, nothing is displayed.

User Class:
```
class User extends Authenticatable
{
    use Notifiable;
    use HasRolesAndAbilities;

    protected $fillable = [
        'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function userable()
    {
        return $this->morphTo();
    }
}
```
Customer Class:
```
class Customer extends User
{
    use HasRolesAndAbilities;

    protected $fillable = [ 'name', 'surname', 'user_id'];

    public function user()
    {
        return $this->morphOne('App\User', 'userable');
    }
}
```
Route
```
Route::get('profiles/{profile}', 'CustomerController@update')
    ->name('customer.update')
    ->middleware('can:view,customer');

Route::resource('profiles', 'CustomerController')->except('update');
```
I modified laravel's default registration method in order to register a new user with polymorphic relationship
```
protected function create(array $data)
{
    //Bouncer::allow('customer')->toOwn(Customer::class)->to(['view', 'edit']);
    Bouncer::allow('customer')->to('view', Customer::class);

    $new_user = User::create([
        'email' => $data['email'],
        'password' => Hash::make($data['password']),
    ]);

    $new_customer = Customer::create([
        'name' => $data['name'],
        'surname' => $data['surname'],
    ]);

    Bouncer::assign('customer')->to($new_customer);
    //$new_customer->assign('customer');
    $new_customer->user()->save($new_user);
    $new_user->userable()->associate($new_customer)->save();

    return $new_user;
}
```
Used those in the `edit` method of `CustomerController`:
- `Bouncer::is($customer)->a('customer');` returns `1`
- `Bouncer::can('view', Customer::class);` returns `empty`

The problem seems to be the fact that the current customer doesn't have the ability to 'view'

- PHP version: `7.3.10`
- Laravel Framework: `6.1.0`
- MySQL: `5.5`
- Bouncer: `v1.0.0-rc.6`

Thank you for your time

**Comment by JosephSilber** [comment]
What does...

```
`Bouncer::can('view', Customer::class);` returns empty
```

...mean?

`can` always returns a Boolean. Is it `true` or `false`?

**Comment by JosephSilber** [comment]
This syntax here is wrong:

```php
Route::get('profiles/{profile}', 'CustomerController@update')
//                    ^^^^^^^
    ->name('customer.update')
    ->middleware('can:view,customer');
//                         ^^^^^^^^
```

The second argument to the `can` middleware should be the name of the route binding.

**Comment by JosephSilber** [comment]
> when I do `@can('view', $customer)` in the view, nothing is displayed.

Blade's `@can` directive authenticates the currently logged-in user. Since the user has no permissions (you only gave the customer permissions), it doesn't render anything inside.

**Comment by seintzz** [comment]
> What does...
> 
> > `Bouncer::can('view', Customer::class);` returns empty
> 
> ...mean?
> 
> `can` always returns a Boolean. Is it `true` or `false`?

I assigned it to a variable and printed it in the view with `{{ $test_can }}` and it doesn't return neither 1 nor 0, the line is empty

**Comment by seintzz** [comment]
> > when I do `@can('view', $customer)` in the view, nothing is displayed.
> 
> Blade's `@can` directive authenticates the currently logged-in user. Since the user has no permissions (you only gave the customer permissions), it doesn't render anything inside.

oh I haven't thought about it, thanks for the help

**Comment by JosephSilber** [comment]
Has this been resolved?
