### ISSUE TITLE
Class 'Silber\Bouncer\InvalidArgumentException' not found

### ISSUE THREAD

**Issue by oad-dwarf** [JosephSilber/bouncer#503]
`Class 'Silber\Bouncer\InvalidArgumentException' not found {"userId":176,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Silber\\Bouncer\\InvalidArgumentException' not found at /Users/odinn/sites/husweb/vendor/silber/bouncer/src/BaseClipboard.php:69)
`

Found when accidentally doing a `$user->isNotA($roles)`, where `$roles` was `null`.

Seems that BaseClipboard.php is missing a `use InvalidArgumentException;`

**Comment by JosephSilber** [comment]
Thanks for catching that :+1:
