### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by desthercz** [JosephSilber/bouncer#507]
Hi, can you please update your package to support Laravel 7? I don't think there is any breaking changes which may impair use of this package, so it should be easy on your part. I am using your package and like it a lot, but currently it is preventing me to upgrade my site for Laravel 7.

Official release date of Laravel 7 should be March 3rd, but the documentation is already updated so there is no reason to delay it.

**Comment by JosephSilber** [comment]
> there is no reason to delay it

The individual illuminate packages haven't been updated yet.

---

Regardless, I added `7.0` to `composer.json`. Once those packages are tagged, it should work.

**Comment by desthercz** [comment]
Awesome, thanks.
