### ISSUE TITLE
How scope / multi-tenancy actually works

### ISSUE THREAD

**Issue by Excelautomation** [JosephSilber/bouncer#509]
I'm trying to make some sort of grouping based on Users associations with different Organizations and Departments and scoping might be the way to handle this properly. However, I'm not so quite familiar with tenancy - and how I'm actually suppose to implement it.

When looking through your documentation regarding Mutli-tenancy I can see that you're appending a "account_id" which is a attribute on the user model. However, I really can't understand how the middleware actually knows it's a "account_id" to look for. You just parse in the id into the "to"-method. 

Where is this scope actually set? And how does it know to look for "account_id" and not for instance "payment_id" or some other foreign key on the user table? 

Seems like I'm missing one essentiel part of this. Is it in the seeder (or whatever) you bind "account_id" to a specific ability? 

I don't understand it. Would appreciate if you could elaborate on this.

https://github.com/JosephSilber/bouncer#multi-tenancy

**Comment by pryley** [comment]
The most basic way to understand multi-tenancy is to think of yourself as a landlord who owns an apartment block and rents out the apartment units to people.

Your application = This is the apartment block of which you are the landlord
Your application tenants = These are the apartment units that you rent out to people
Your users = These are the people who live in each apartment unit
Your application permissions = These are the set of keys that are used to access each apartment unit

In the example Joseph gives in the documentation, the `account_id` from the user model is like the apartment number that the user lives in.

**Comment by thoresuenert** [comment]
@Excelautomation 

Roles and Abilities have both a generic table column called `scope`.

When you create a Role/Abilitie for a tenant you have to set this value.

When the identifier of the tenant is user()->account_id you have to create the role and ability for this tenant like:

```php
// pseudo code
$admin = Bouncer::role()->firstOrCreate([
    'name' => 'admin',
    'title' => 'Administrator',
   'scope' => usert()->account_id
]);
```

hope fully it helps.

You can dive into the migrations and see it in there:
https://github.com/JosephSilber/bouncer/blob/c6a9a981eab8389175f46f21c9b7e4726444c457/migrations/create_bouncer_tables.php#L35
https://github.com/JosephSilber/bouncer/blob/c6a9a981eab8389175f46f21c9b7e4726444c457/src/Database/Scope/Scope.php#L169

**Comment by JosephSilber** [comment]
@thoresuenert you don't actually have to set the `scope` yourself when you create the role. Bouncer will add that for you automatically.

**Comment by thoresuenert** [comment]
@JosephSilber when the middleware is active?
But in a seeder the middleware is not active.

**Comment by JosephSilber** [comment]
Use the `onceTo` method:

```php
Bouncer::scope()->onceTo($identifier, function () {
    // code
});
```
