### ISSUE TITLE
$user->isAll('editor', 'moderator') not working!

### ISSUE THREAD

**Issue by MuhammadSulman** [JosephSilber/bouncer#511]

**Comment by JosephSilber** [comment]
The tests beg to differ:

https://github.com/JosephSilber/bouncer/blob/c716ee07f9568e9774b6934314620bc9d9d1d65a/tests/HasRolesAndAbilitiesTraitTest.php#L210-L222

Can you show an example that doesn't work?

**Comment by emilas44** [comment]
@MuhammadSulman those are very strong words "**not working!**"

you have to back that up with code AND explanation

**Comment by MuhammadSulman** [comment]
``` private function checkIfUserIsAdmin($user)
    {
        return $user->isA(User::ROLE_SUPER_ADMIN) || $user->isA(User::ROLE_COMPANY_ADMIN);  
    }```
When I used isAll() method in above function than it shows false all time even if that user had assigned role. But when, I changed it to this like show above, its working fine.

**Comment by ctwillie** [comment]
@MuhammadSulman Are you sure the $user you were checking against actually did have the 'super_admin' and the 'company_admin' roles. Based on the code examples you've given, it is a possibility the $user did not. The isAll() function checks for all roles existence on the $user, while your alternative implementation is only checking for one of the roles. Which could be the reason isAll() was returning false and your current code returns true.
