### ISSUE TITLE
Different role for user to manage multiple account

### ISSUE THREAD

**Issue by keval6706** [JosephSilber/bouncer#512]
Hello guys,
I need a help. I want to manege Below things :
1. User  can manage multiple account and account has an owner. So user can have different role for manage each account.

Example:
User X manage Account A, Account B and Account D
So User X can have role "view" for Account A, role "moderator" for Account B and role "author" for Account D. So for same user it is need different role for manage different account.

How I can achieve this scenario with this package?

Thanks in advance

**Comment by emilas44** [comment]
Even if Joseph answers this question you won't like the answer.

**Comment by JosephSilber** [comment]
@keval6706 you're asking for entity-based roles.

This has been requested many times before.

Bouncer does not currently support that. I would love to get to it one day.

In the meantime, you can assign the abilities to the user directly.
