### ISSUE TITLE
Permissions and Roles on Person.php

### ISSUE THREAD

**Issue by sroseman** [JosephSilber/bouncer#513]
Within my project, I have Users and People. Users only holds login info. People houses a lot of attributes about people (some of these people exist in the Users table. All users exist in people table.) 

My question is can I have all of these permissions and roles tied to my Person model instead of the User who authenticates? Could I then use Person::find(1)->can('create posts')?
 Is there a way to authenticate with the User but authorize with Person? 

![image](https://user-images.githubusercontent.com/45442058/78962942-0b90e000-7ab3-11ea-962d-df0b2c868260.png)

**Comment by grenadecx** [comment]
Not sure if you solved this or not, but yes you can. In my project I have teams and I use bouncer to authorize teams access. Your people model needs to implement the **AuthorizableContract** contract and the **Authorizable** trait. Here's an example for you:

```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Silber\Bouncer\Database\HasRolesAndAbilities;

class People extends Model implements AuthorizableContract
{
    use HasRolesAndAbilities, Authorizable;
}
```

With that, you can check using can on the people object.

**Comment by ctwillie** [comment]
@sroseman If you have a hasOne() relationship for uses and people, you can check like so,

```php

$authorized = Auth::user()->person->can('permission-name');

```
This should work fine being every user has a person, but not vica versa;

Have you tried this?

**Comment by ctwillie** [comment]
@sroseman 

**Correction**
You should actually do what @grenadecx mentioned above first.

> ```php
> <?php namespace App;
> 
> use Illuminate\Database\Eloquent\Model;
> use Illuminate\Foundation\Auth\Access\Authorizable;
> use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
> use Silber\Bouncer\Database\HasRolesAndAbilities;
> 
> class Person extends Model implements AuthorizableContract
> {
>     use HasRolesAndAbilities, Authorizable;
> }
> ```

Then, make sure you have the ```User``` to```Person``` relationship defined.

```php
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    // other code
    
    public function person()
    {
        return $this->hasOne(Person::class);
    }
}
```

Then, you will be able to authorize against the ```Person``` model like so.
```php
if(Auth::user()->person->can('edit-posts')) {

    // person is authorized to edit posts

}
```
