### ISSUE TITLE
Allow an ability to user that has role that denies it

### ISSUE THREAD

**Issue by mariosvasiliou** [JosephSilber/bouncer#514]
Hello, I want to ask something about hierarchy,
I have a user that has everything();
Also, the user has a role assigned that cannot view contacts and other 30 forbidden abilities from a total of 200 abilities for example.
But I want to allow a user a specific ability that role disallows it.
I don't want to remove the user from the role because there are another 29 abilities that are disallowed. Also, I don't want to allow ability for all users in the role, only for this user.
How can I do this? 
I tried several ways but it seems that forbidden in the role is the one that wons in the hierarchy...
Thanks

I have laravel 5.5 and bouncer version v1.0.0-rc.6

**Comment by JosephSilber** [comment]
Once an ability has been forbidden, there's no way to allow it.

I understand your use case, but that's not how Bouncer works.

**Comment by mariosvasiliou** [comment]
Hello Joseph,
Thanks for your reply and your good work.
I understand what you are saying but just in theory... why to have an allow method and insert new record in database if it is already has been forbidden and not going to work? 
It's a little bit confusing and unnecessary for performance if you think about it...
I know that everything happens in checkGetId() and you get first forbidden ability, but not checking for allowing id that's why works that way...
So tweaking that method can make my case work if I understand well...
But wouldn't it be ideal to have a config for a user to choose for explicit allow? 
Or at least not insert new allow records for forbidden abilities to prevent overhead and confusion?
