### ISSUE TITLE
[Feature Request] Get CRUD abilities

### ISSUE THREAD

**Issue by sausin** [JosephSilber/bouncer#515]
While listening to Jeffery in [this](https://laracasts.com/series/laravel-6-from-scratch/episodes/54) video at Laracasts, I realized it would be nice to do what he was doing (providing abilities to his javascript side of the application) using `Bouncer`.

A one liner to get the CRUD abilities would be awesome. These could be sent out to the frontend portion to allow for a convenient way to select the options to be provided to the user (`edit`, `delete` etc). So if we do something like:

```php
$user->getCrudAbilities($model);
```
or 

```php
$user->getCrudAbilities(App\Model::class);
```
Then an array would be returned. Something like `['create', 'delete']`. This array can be passed on to the frontend.

Of course, this is not relevant to the security of the application (that must be handled on the backend through appropriate middleware). But if this is possible, it would be super convenient.

If there is already a way to achieve this, I would be glad to be corrected :+1:

**Comment by francislavoie** [comment]
I know this is over a year later... but...

I think the key for this is in the `AuthorizesRequests` trait which is usually added to your base Controller. For a resource, you'd typically use `$this->authorizeResource(Model::class)` in your resource controller's constructor.

In `AuthorizesRequests`, it has these two maps:

```php
    /**
     * Get the map of resource methods to ability names.
     *
     * @return array
     */
    protected function resourceAbilityMap()
    {
        return [
            'index' => 'viewAny',
            'show' => 'view',
            'create' => 'create',
            'store' => 'create',
            'edit' => 'update',
            'update' => 'update',
            'destroy' => 'delete',
        ];
    }

    /**
     * Get the list of resource methods which do not have model parameters.
     *
     * @return array
     */
    protected function resourceMethodsWithoutModels()
    {
        return ['index', 'create', 'store'];
    }
```

Basically what you need is to write a function that does the same work as `authorizeResource($model)` but instead of invoking middleware, it should do essentially:

```php
public function getCrudAbilities($user, $model)
{
    $gate = Gate::forUser($user);

    $can = [];
    foreach ($this->resourceAbilityMap() as $method => $ability) {
        $allowed = $gate->allows(
            $ability,
            in_array($method, $this->resourceMethodsWithoutModels()) ? $model : []
        );
        if ($allowed) {
            $can[] = $method;
        }
    }
    return $can;
}
```

Didn't test this, but that should be essentially what's needed.

**Comment by sausin** [comment]
@francislavoie Thanks a lot for the suggestion! I had implemented something like this after the original post:

```php
    /** @var array */
    protected $permissions = [
        'viewAny', 'view', 'create', 'store', 'delete',
    ];

    /**
     * Get the list of permissions for the user.
     *
     * @param  mixed $object
     * @param  string $specific
     * @return array|bool
     */
    protected function getPermissions($object, $specific = null)
    {
        $user = Auth::user();
        $allowed = [];

        if (! is_null($specific)) {
            return in_array($specific, $this->permissions) &&
                $user->can($specific, $object);
        }

        if ($user->isAn('owner', 'superadmin')) {
            return $this->permissions;
        }

        foreach ($this->permissions as $permission) {
            if ($user->can($permission, $object)) {
                $allowed[] = $permission;
            }
        }

        return $allowed;
    }
```
I'll borrow some code from yours for improvements :-)
