### ISSUE TITLE
Failing to Manage users

### ISSUE THREAD

**Issue by smartified** [JosephSilber/bouncer#517]
I have created this role and given all abilities but i can manage any model apart from the user model. I can view but can't create or edit

![image](https://user-images.githubusercontent.com/16135819/81194326-d1850200-8fbc-11ea-8a7f-8db1262b7bc1.png)

**Comment by JosephSilber** [comment]
I'm not sure what you're doing there, nor do I understand your question.

`allow(...)->everything()` already allows everything, so it doesn't really make sense to use that in conjunction with `allow(...)->toManage(...)`
