### ISSUE TITLE
Suggestion on package description

### ISSUE THREAD

**Issue by flartet** [JosephSilber/bouncer#518]
Hello,
on packagist, your library is described as 
```Eloquent roles and abilities```
Reading the description, it's more than that. I am approaching your library because digging into details I realized that you can restrict/contextualize everything + the own concept. That's great and you're the only one to do this in the quite popular packages. I read some topics everywhere about restricting roles but all the solution were around customizing spatie/laravel-permissions.
So, I suggest you could add a word on it right into the description.
```Eloquent roles and abilities. Restricting roles and abilities to specific Model or instances. User owning of Model or instances```
Thanks for your work. I'll dig into it right now.

**Comment by JosephSilber** [comment]
> I am approaching your library because digging into details I realized that you can restrict/contextualize everything + the own concept. That's great and you're the only one to do this in the quite popular packages.

:+1: 

> So, I suggest you could add a word on it right into the description.
> `Eloquent roles and abilities. Restricting roles and abilities to specific Model or instances. User owning of Model or instances`

It's always tricky to get a short description right, without just listing out all of the feature set.

I'll have to think about it. Thanks!
