### ISSUE TITLE
Accessing users linked to model through abilities

### ISSUE THREAD

**Issue by dylanglockler** [JosephSilber/bouncer#520]
When I link an ability to a model, how can I query all users who have access to that model? In my application I have users who are granted access to a vessel:

        $vessel = Vessel::find(1);
        $user = User::find(1);
        $user->allow('crew', $vessel);

Which generates: 
id | name | title | entity_id | entity_type | only_owned | scope
9 | crew | Crew vessel #1 | 1 | App\Vessel | 0 | NULL

Now I want to find all users who are crew for that vessel #1. Is there a way to tell my Vessel model that it's linked to the abilities? Maybe I have to define it as a polymorphic relationship?

**Comment by NazarShershen** [comment]
I see that it's an old issue but maybe help somebody

check `Silber\Bouncer\Database\Concerns\IsAbility` trait there are useful scopes 

```
$crewAbility = Ability::forModel($vessel, true)->byName('crew')->first()
$users = $crewAbility->users;
```
