### ISSUE TITLE
Attempting to use with LdapRecord

### ISSUE THREAD

**Issue by snazy2000** [JosephSilber/bouncer#527]
I'm trying to use Bouncer with LdapRecord package, I'm overriding the user model with App\User within the AppServiceProvider in the boot function.

However when Bouncer loads it first loads the LdapRecord user model and I get 

"Call to undefined method LdapRecord\Query\Model\ActiveDirectoryBuilder::getTable()"

Which is coming from

```php
public static function setUsersModel($model)
    {
        static::$models[User::class] = $model;

        static::$tables['users'] = static::user()->getTable();
    }
```

Guessing its because its not a eloquent model.

I tried putting the 
```php
Bouncer::useUserModel(\App\User::class); 
```
within the register function so it kicks it off first which works but then the standard one overrides that. 

I added an override flag against the setUsersModel 

```php
public static function setUsersModel($model, $override = false)
    {
        if (!isset(static::$models[User::class]) || $override == true)
        {
            static::$models[User::class] = $model;

            static::$tables['users'] = static::user()->getTable();
        }
    }
```
Then the useUserModel is setup like this

```php
public function useUserModel($model)
    {
        Models::setUsersModel($model, true);

        return $this;
    }
```

I then had the useUserModel within the register function and it works as expected because its not trying to load something it shouldn't.

I'm not sure this is the best way to do this which is why I'm asking for any other options / feedback before I create a PR. The changes above wouldn't have any effect on previous cases as it still would override if required in the boot for other models, its just in this case it doesn't work because the LdapRecord model doesn't contain getTable.

Another possible option would be to have a config file that the model is read from instead of looking it up against the default guard which still allow an override if that config is not found (so it doesn't break all current implemented things)

**Comment by stevebauman** [comment]
Just ran into this as well -- and I agree on the use of an override flag (whether it be a static variable somewhere, or be added to the `useUserModel` method.

I'll see if I can write a PR to patch this.

**Comment by stevebauman** [comment]
To elaborate further for @JosephSilber, the LdapRecord auth provider is registered like so:

```php
To elaborate for Joseph -- the LdapRecord authentication provider is configured like so:

```php
'ldap' => [
    'driver' => 'ldap',
    'model' => LdapRecord\Models\ActiveDirectory\User::class,
    'database' => [
        'model' => App\User::class,
        'sync_passwords' => false,
        'sync_attributes' => [
            'name' => 'cn',
            'email' => 'mail',
        ],
    ],
],
```

So Bouncer is calling `getTable()` on an incorrect model instance -- even when configured manually via `Bouncer::setUserModel()`.

**Comment by itshaydendev** [comment]
+1 to this, it's caused a halt in one of my company's projects

**Comment by ankorinek** [comment]
The PR seems to not fully mitigate this issue. It defaults to App\User as the model when it should be App\Models\User as set in the ldapconfig.
