### ISSUE TITLE
FatalErrorException after upgrading to Laravel 5.2.19

### ISSUE THREAD

**Issue by waxain** [JosephSilber/bouncer#53]
After upgrading to Laravel 5.2.19 Bouncer start returning FatalErrorException while trying to run methods Bouncer::denies('something') or Bouncer::allows('something'). 

> Class name must be a valid object or a string
Symfony\Component\Debug\Exception\FatalErrorException
…/­vendor/­silber/­bouncer/­src/­Clipboard.php116

Probably problem comes from changes in Laravel file src/Illuminate/Auth/Access/Gate.php
https://github.com/laravel/framework/commit/416cbab6b32d7ef26434a284e7aadcc7766b0a25

**Comment by waxain** [comment]
Ok, I see that problem was resolved recently, but there is no update (^0.1.2).
By the way, great library!

**Comment by JosephSilber** [comment]
This happened in [this PR](https://github.com/laravel/framework/pull/12305). It was championed as a bug, which I disagree with.

Anyhow, it's now been fixed and [tagged as v0.1.3](https://github.com/JosephSilber/bouncer/releases/tag/v0.1.3).
