### ISSUE TITLE
Unable to create ability with entity_type and entity_id

### ISSUE THREAD

**Issue by medo3337** [JosephSilber/bouncer#530]
I'm trying to create ability which will be associated with certain model (entity_type, entity_id) and I keep getting null values in (entity_type, entity_id) when I have those values assigned:

```
Bouncer::ability()->firstOrCreate([
      'name' => 'create',
      'title' => 'Create Test',
      'entity_type' => App\Test::class,
      'entity_id' => 1,
]);
```

**Comment by bpuig** [comment]
It's because Ability model only allows `name` and `title` to be mass assignable. 

You can do it like this:
```
$testAbility = Bouncer::ability()->firstOrCreate([
      'name' => 'create',
      'title' => 'Create Test',
]);

$testAbility->entity_id = 1;
$testAbility->entity_type = App\Test::class;
$testAbility->save();
```

**Comment by medo3337** [comment]
@bpuig Any reason to make entity_type and entity_id not mass assignable? can we change it and allow mass assignment to those fields?

Thanks!

**Comment by bpuig** [comment]
I have no idea, I'm just an user, I had the same thought when I was looking at the code to help you... maybe @JosephSilber can tell you why.
