### ISSUE TITLE
Disable/Skip Bouncer Based on Condition

### ISSUE THREAD

**Issue by medo3337** [JosephSilber/bouncer#532]
How do I disable bouncer (for the current HTTP request only using Middleware)?

Based on certain condition in the Middleware, I need full permissions to be granted to a user (even if they don't have full permissions).

**Comment by dircm** [comment]
Hey medo, Laravel has built in support to intercept auth calls before all gates are run.  Checkout https://laravel.com/docs/7.x/authorization#intercepting-gate-checks

**Comment by medo3337** [comment]
Hi @dircm I tried adding the following in AuthServiceProvider boot() but it has no effect and permissions are still enforced.

```
if (...) {
   // Disable Bouncer (for this request only)
   Gate::before(function ($user, $ability) {
        return true;
   });
}
```
The function inside Gate::before is never called, I'm using Laravel latest.

**Comment by medo3337** [comment]
Update: It seems to be working after I moved the function from boot() to register().

Thanks!

**Comment by dircm** [comment]
Awesome!
