### ISSUE TITLE
Can helper always returns true, after removing an ability from role

### ISSUE THREAD

**Issue by MalindaWMD** [JosephSilber/bouncer#538]
Hi,

I have multiple roles in my application that uses to handle user access. There are no direct abilities are set to users.

My problem is, when I check a disallowed ability using `can()`, it returns true.

For example,

I have there two abilities `view-users`, `edit-users` and two roles `admin`, `editor`.
These two roles are assigned to different users.

If i disallow `editor` to `edit-users` and check in the controller using `can()` it returns true.

I have trying refreshing Bouncer couple of times, but no luck.

Any idea what is happening here?

Thanks

**Comment by JosephSilber** [comment]
Which version of Bouncer are you using?

**Comment by justasSendrauskas** [comment]
i have the same issue in unit tests, using Bouncer v1.0.1

```
allow('some-admin')->to('manage', Some::class);
Bouncer::dontCache();

$user->assign('some-admin');
Bouncer::refresh();

$user->isA('some-admin'); // returns true
$user->can('manage', Some::class); // returns true

$user->retract('some-admin');
Bouncer::refresh();

$user->isA('some-admin'); // returns false
$user->can('manage', Some::class); // returns true where it should be false
```

not using any scopes
