### ISSUE TITLE
Clipboard closure arguments in v0.1.3

### ISSUE THREAD

**Issue by a-komarev** [JosephSilber/bouncer#54]
```php
@can('user-edit', $user)
    <a href="#" class="edit">Edit user</a>
@endcan
```

> Argument 3 passed to Silber\Bouncer\Clipboard::Silber\Bouncer\{closure}() must be of the type array, object given.

Started to throw this exception since v0.1.3.

**Comment by JosephSilber** [comment]
Seems like you're still on 5.1, yes?

Yeah. They only hanged it for 5.2 😟

I'll have a fix soon.

**Comment by a-komarev** [comment]
@JosephSilber Yep, forgot to said it... it's 5.1

**Comment by JosephSilber** [comment]
I just published [v0.1.4](https://github.com/JosephSilber/bouncer/releases/tag/v0.1.4) with that fix.

Can you please test it in your project?

**Comment by JosephSilber** [comment]
Whoops. I missed the `array` type hint. Here goes [v0.1.5](https://github.com/JosephSilber/bouncer/releases/tag/v0.1.5).

**Comment by a-komarev** [comment]
:'( Nope
> Missing argument 1 for App\Presenter\Presenter::__construct(), called in /home/ell/Development/sitterland/vendor/silber/bouncer/src/Clipboard.php on line 169.

My user model is wrapper in presenter, but I dont think this will change things.

**Comment by JosephSilber** [comment]
This does not seem to be related to this issue. Does it work in 0.1.2?

Do help debug this, can you show me the code for your User model?

**Comment by a-komarev** [comment]
Yes it's working in 0.1.2.

All the code is in the traits, but I've rechecked all of them, none overwriting __construct method.

```php
class User extends Model implements AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract,
    HasMediaConversions,
    Reviewable
{
    use Authenticatable,
        Authorizable,
        CanResetPassword,
        PresentableTrait,
        ReviewableTrait,
        HasRolesAndAbilities,
        Messagable,
        LastSeenTrait,
        OnlineTrait,
        HasMediaTrait,
        EmailableTrait,
        AddressableTrait,
        ApplicantTrait,
        SoftDeletes,
        BannableTrait;

    public $presenter = UserPresenter::class;
}
```

And presenter is pretty simple:

```php
<?php

namespace Cog\Presenter\Traits;

use Cog\Presenter\Exceptions\PresenterException;

trait PresentableTrait
{

    /**
     * View presenter instance
     *
     * @var mixed
     */
    protected $presenterInstance;

    /**
     * Prepare a new or cached presenter instance
     *
     * @return mixed
     * @throws PresenterException
     */
    public function present()
    {
        if (!$this->presenter or !class_exists($this->presenter)) {
            throw new PresenterException('Please set the $presenter property to your presenter path.');
        }

        if (!$this->presenterInstance) {
            $this->presenterInstance = new $this->presenter($this);
        }

        return $this->presenterInstance;
    }
}
```

**Comment by a-komarev** [comment]
\Silber\Bouncer\Clipboard::compileModelAbilityIdentifiers:169 is trying to create `UserPresenter` model, not the User model. That's the problem.

**Comment by a-komarev** [comment]
In `parseGateArguments` method User model transforms to UserPresenter model:

```php
return [
    head($arguments) ?: null,
    null
];
```

**Comment by JosephSilber** [comment]
Why is it trying to create a user presenter model? And why would that be any different in 0.1.2?

It tries to create a new instance of whatever was passed in. Is the $user you're passing in an Eloquent model, or an instance of the presenter.

If it's a model, it should always work. If it's a presenter, it shouldn't be working on 0.1.2 either.

**Comment by JosephSilber** [comment]
Oh I see now. It should be returning $arguments directly, not call head on it.

Curious that calling head on the model would return the presenter.

I'll publish a fix for this in the morning.

**Comment by a-komarev** [comment]
And here you can see `dd($arguments)`:

```
User {#731 ▼
  +presenter: "App\Presenters\UserPresenter"
  #table: "user"
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:10 [▶]
  #original: array:10 [▶]
  #relations: array:1 [▶]
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
  #presenterInstance: null
  +mediaConversions: []
  #forceDeleting: false
}
```

Maybe

**Comment by JosephSilber** [comment]
I see.

Why did you close this issue?

**Comment by a-komarev** [comment]
It was a stupid missclick :}

```php
return $arguments;
```

Yes, as you said - it solved an issue. Should I make PR for it, or you will do it yourself?

**Comment by JosephSilber** [comment]
If you send a PR now I'll merge it.

return [$arguments, null];

I'm on my phone.

**Comment by JosephSilber** [comment]
Can you now please try it with dev-master before I tag yet another release?

**Comment by a-komarev** [comment]
Not more errors, confirmed!

Could releases be deleted? Don't ever tried to do so.
