### ISSUE TITLE
Push latest commit (PHP8 support) to composer site?

### ISSUE THREAD

**Issue by OliverGrimsley** [JosephSilber/bouncer#544]
Not sure if this is a composer issue, but v1.0.0-rc.9 still only shows php ^7.2 @ the composer site - or do I have to use dev-master?  The last commit 7 days ago added php8 in composer.json but I cannot update my composer file on my dev machine where I am testing php8

**Comment by JosephSilber** [comment]
Still sorting out the unit tests for PHP 8. Once that's done, I can tag another release.

**Comment by thyseus** [comment]
@JosephSilber I dont want to start a new thread just for my question so i ask it here - when can we expect a "first official 1.0 stable" release of bouncer ?
