### ISSUE TITLE
info permission stronger between user and role

### ISSUE THREAD

**Issue by massimodevitis** [JosephSilber/bouncer#546]
I have a question:

if I give the delete permission for a specific user, but at the same time this user belongs to a role which however does not have the delete permission what happens? is the user's or role permission stronger?

br
Max

**Comment by emilas44** [comment]
There is no such thing 'stronger' in Bouncer.
Either it has the permission or it doesn't... be it through a role or directly.

**Comment by massimodevitis** [comment]
Thanks for the reply

br
Max
