### ISSUE TITLE
Error Level Field in Roles Table

### ISSUE THREAD

**Issue by massimodevitis** [JosephSilber/bouncer#549]
hi,
i use oracle 12c after: Bouncer::can('index', Tbc_Automezzo::class);
oracle show this error "Error Message : ORA-01788" becouse LEVEL field is a reserved word.
I'ts Possible to change the Field name in Roles Table?

Br
Max

**Comment by emilas44** [comment]
The fact is that Laravel doesn't officially support Oracle DBMS...

**Comment by massimodevitis** [comment]
ok, 
i will try to override your class, thanks
br
max
