### ISSUE TITLE
AssignRolles restrictred_to

### ISSUE THREAD

**Issue by webstudios1** [JosephSilber/bouncer#556]
Hi,
I would start saying this is an very good supplement to the Laravel Community.

I'm currently working on a project where it would be extremely helpful using the RestrictedTo function planed in assigned_rolles table. Is there a timeline for this function to be released?

**Comment by JosephSilber** [comment]
> Is there a timeline for this function to be released?

No timeline. I work on Bouncer on my own free time, whenever I have some and am in the mood :smile:
