### ISSUE TITLE
Polymorphic role ownership

### ISSUE THREAD

**Issue by mix359** [JosephSilber/bouncer#557]
Hi to all,

I'm using the bouncer package from many years in one of my project where I need to implement a new Module that will have a more complex permissions situation:
For this module I have some categories, similar to some post categories. I need to assign the permission using roles that is related to one of those categories.
To give an example I can give to a user the role "moderator" of the category with id 1. Then I can specify the permission (abilities) for the moderator of all the categories (let's say that in the category 1 they can delete the post, but not in the category 2)

If I'm not wrong, I can't do that type of permission checking with the current database structure of Bouncer because I would need something like the polymorphic relation that is used in the Ability model to reference an ability specific to a single entity but on the roles model, in this way I can specify a role only for one entity.

Would it possible to implement something like that? Any way to customize only the control related to the roles? Or it would add too many performance problems (like more complex query for checking)?
Anyone could be interested?

Thanks
Cheers Mix

**Comment by JosephSilber** [comment]
Bouncer works in tandem with your policies. So you can achieve this with the following policy:

```php
class PostsPolicy
{
    public function delete($user, Post $post)
    {
        if (Gate::can('moderate', $post->category) {
            return true;
        }
    }
}
```

Then you can use Bouncer's permissions:

```php
Bouncer::allow($user)->to('moderate', $category);
```

When you later check `@can('delete', $post)`, Laravel will check your policy, which in turn will defer to Bouncer.

**Comment by mix359** [comment]
Dear @JosephSilber,
Many thanks for the answer and this awesome package!

I've red your answer but sadly it doesn't solve my situation. Probably I have to explain it better, because it's a little bit more complicated than this. I'll try using again the post/forum example that I've used before.

Let's say I have 3 users, User A, User B and User C, and I have 4 post categories, Category 1, Category 2, Category 3 and Category 4.
Also let's say that in my application there's 3 Abilities that I can check to give a user the permission to do something, that are view.post, modify.post and delete.post.

Currently with bouncer I can create those 3 Abilities and I can assign that directly to the user or I can assign that to a role (let's say moderator) and that assign the users to the role to give the abilities.
Also, using the polymorphic relation on the Abilities table, I can assign that ability only for a category of entities (for example Post::class) or to a specific entity (for example Post with id 1).

What I would like to have is a more complex way to assign those Abilities to the user. In particular I would like to assign the abilities to a particular implementation of Role that is only valid for a particular Category.
For example I will have the roles "Moderator of category 1", "Moderator of category 2", "Moderator of category 3" and "Moderator of category 4". Then I would like to assign different permission to those roles, like for example specify that the role moderator for the category 1 can have the view.post, modify.post and delete.abilities abilities, but the moderator fo the category two can only have view.post and modify.post abilities.

Under the hood all of those roles would have his id like any other role in the roles table and I can assign abilities and users to that roles like I can do now with every roles. 
The big difference would be that like the Abilities there can be more then one role with the same name (for example moderator) and there will be the columns entity_type and entity_id to create the polymorphic relation with the entity, that in my example is the PostCategory.

Then when the code will do the check for the abilities of the user, it will filter the roles by the Models that is passed in the check, like now is done for the Abilities, so that if I'm looking for the abilities and I'll pass the model of the Category 1, the code will only get the abilities for the roles that doesn't have any entity restriction of for the roles that have the entity matching.

I've started looking in the source code of the library what this modification would impact, and from one first check there's many part of the code involved, but many of them depend by the data that is retrieved using the query generated by the function "getRoleConstraint" inside the Database\Query\Abilities. So passing the Model to be checked down to this function and adding some more constrain here would probably do the job. But maybe I haven't considered something in the analysis I've done.
Do you think this modification would be possible? In case, if I take care of trying do that, would you be interested in accept that as a PR?

Let me know if something of the explanation is not clear, or there's any information missing.
Many thanks
Cheers
Mix

**Comment by JosephSilber** [comment]
> For example I will have the roles "Moderator of category 1", "Moderator of category 2", "Moderator of category 3" and "Moderator of category 4". Then I would like to assign different permission to those roles, like for example specify that the role moderator for the category 1 can have the view.post, modify.post and delete.abilities abilities, but the moderator fo the category two can only have view.post and modify.post abilities.

This has been requested many times in the past: to have per-model roles.

It's something that I've started working on quite a while ago (see [the `retricted_to` columns on the `assigned_roles` table](https://github.com/JosephSilber/bouncer/blob/429262a84414569be2fad1fad417f05d752c075b/migrations/create_bouncer_tables.php#L49-L50)), but have yet to finish it.

So the short answer to your question is: no. Bouncer cannot currently do this via roles. You'll have to assign the permissions directly to the user (with the help of the policy guard above).

> Do you think this modification would be possible?

I think so, which is why I started down that path.

> In case, if I take care of trying do that, would you be interested in accept that as a PR?

First off, thanks for offering your help.

But I think I'm gonna have to end up writing this myself.

- This is more complex than it seems on the outset. It touches quite a bit of points throughout Bouncer, and is tricky to get right.
- It'll also need extensive tests, to make sure it works properly and doesn't break other stuff.
- I also have to come up with an API that I'm comfortable with.

Others (see @joy31 in https://github.com/JosephSilber/bouncer/issues/43#issuecomment-735872029) have also ofered to help. While I'm truly grateful to you all, I think I'll have to tackle this on my own.

---

Hopefully your request, coupled with all outstanding requests, will further motivate me to do this.

When, [I cannot say](https://github.com/JosephSilber/bouncer/issues/556). Hopefully sooner rather than later.

**Comment by mix359** [comment]
Hi @JosephSilber 
thanks again for your answer and your work!

> But I think I'm gonna have to end up writing this myself:
> 
>- This is more complex than it seems on the outset. It touches quite a bit of points throughout Bouncer, and is tricky to get right.
> - It'll also need extensive tests, to make sure it works properly and doesn't break other stuff.
> - I also have to come up with an API that I'm comfortable with.
> 
> Others (see @joy31 in #43 (comment)) have also offered to help. While I'm truly grateful to you all, I think I'll have to tackle this on my own.

I've digged a bit in the library for an integration I've done and I can understand that! It's really complex and very segmented. Also I've noticed that the procedure is different in the case of the cached data or the direct access to them.
So if you prefer to project it yourself I can understand ;)
If you need a tester let me know!


> It's something that I've started working on quite a while ago (see the retricted_to columns on the assigned_roles table), but have yet to finish it.

It's a good news that you're starting to work on that :D 
Only one suggestion related to the implementation that you're creating:
With the polymorphic relation on the assigned_roles relation you're managing only half of the case:
You're restricting the usage of a role for a single entity, but the permission associated to that role are the same for all the entities. There's some usage case, like the one I'm using as an example, that would require to have different user and permission association to a role for every category. To take my example with the restriction on the assigned_roles relation I can associate different users to the role moderator based on the category, but all the moderator would have the same permission like modify and delete in all the categories.
Instead, having the two field of the polymorphic relation to the roles table create more flexibility, because you can also personalize the permission for every category.
So to cover all the possible case can be useful to have those restriction field both on the assigned_roles and on the roles table


> Hopefully your request, coupled with all outstanding requests, will further motivate me to do this.
> 
> When, I cannot say. Hopefully sooner rather than later.

Thanks again!
Meanwhile I will probably realize a custom Gate that mimic the check done by the Bouncer library registered after Bouncer, so if no matching ability is found by Bouncer and a Category model is passed, I will try to do my check.

Cheers
Mix

**Comment by JosephSilber** [comment]
> There's some usage case, like the one I'm using as an example, that would require to have different user and permission association to a role for every category.
>
> To take my example with the restriction on the assigned_roles relation I can associate different users to the role moderator based on the category, but all the moderator would have the same permission like modify and delete in all the categories.
>
> [...]
>
> Instead, having the two field of the polymorphic relation to the roles table create more flexibility, because you can also personalize the permission for every category.

That would still be possible:

```php
$category1 = Category::find(1);
$category2 = Category::find(2);

Bouncer::allow('moderator')->to('delete-posts', $category1);
Bouncer::allow('moderator')->to(['update-posts', 'delete-posts'], $category2);
```

The above already works. Now couple that with the proposed feature of assigning roles on specific categories:

```php
// NOTE: this does not work yet...

Bouncer::assign('moderator')->to($user1)->on($category1);
Bouncer::assign('moderator')->to($user2)->on($category2);
```

I think that would cover all of your use-cases, no?
