### ISSUE TITLE
Using allow everything [roles with no abilities show as having all abilities]

### ISSUE THREAD

**Issue by ZaidBarghouthi** [JosephSilber/bouncer#559]
I have the following code in a seeder: 

```php
Bouncer::role()->firstOrCreate([
    'name' => 'super-admin',
    'title' => 'Super Adminstrator',
]);

Bouncer::role()->firstOrCreate([
    'name' => 'customer',
    'title' => 'Customer',
]);

Bouncer::allow('super-admin')->everything();

$user1 = User::firstOrCreate([
    'email' => 'u1@email.com',
], [
    'name' => 'User 1',
    'password' => \Hash::make('password'),
]);

$user1->assign('customer');
```

yet when I view the user's abilities, for some reason, the user has all abilities, the following code

```php
Route::get('/test', function () {
    $user = User::whereEmail('u1@email.com')->firstOrFail();

    return [
        'roles' => $user->getRoles(),
        'abilities' => $user->getAbilities(),
    ];
});
```

outputs: 
```js
{
    roles: [
        "customer"
    ],
    abilities: [
        {
            id: 1,
            name: "*",
            title: "All abilities",
            entity_id: null,
            entity_type: "*",
            only_owned: false,
            options: [ ],
            scope: null,
            created_at: "2021-03-11T07:18:32.000000Z",
            updated_at: "2021-03-11T07:18:32.000000Z"
        }
    ]
}
```  

I don't understand how is this happening! How is the customer getting all abilities?
 
Repo to reproduce
https://github.com/ZaidBarghouthi/bouncer-test

**Comment by ZaidBarghouthi** [comment]
I think this is quiet serious. I am completely wrong? @JosephSilber

**Comment by JosephSilber** [comment]
That's caused by the role's `level`, as you can see here:

https://github.com/JosephSilber/bouncer/blob/429262a84414569be2fad1fad417f05d752c075b/src/Database/Queries/Abilities.php#L82

---

Regardless, [I advised you not to use the `level` feature at all](https://github.com/JosephSilber/bouncer/issues/558#issuecomment-795485547).

**Comment by ZaidBarghouthi** [comment]
Thank you for your reply. Truly appreciate the package.
