### ISSUE TITLE
Q: Is it okay if i restrict 'scope' to another table in migrations?

### ISSUE THREAD

**Issue by FunctionDJ** [JosephSilber/bouncer#565]
My application has many locations. Most roles should be given to a user 'at a location'.

So a user can view items etc. on one location, but not another, unless they also have the role there for example.

So i was thinking about changing Bouncer's migration from this:
```php
$table->integer("scope")->nullable->index();
```
To this:
```php
$table->foreignIdFor(Location::class, "scope");
```

Is this a good idea? Are there better ways to do this?

Also, is this the right place to ask questions? :D

**Comment by JosephSilber** [comment]
LGTM. Can't think now of any reason that should be a problem.

---

How are you gonna activate the scope? Is each request running within the context of a location?

**Comment by FunctionDJ** [comment]
The frontend is an SPA that will keep the currently active location in localStorage. The location is then sent with every API request: `/api/location/1/item/2`.

I use the Bouncer middleware to set it's scope by getting the location from the request and finding the Location model with that id. I also use nested routes to automatically get the location id in my controllers: `Route::resource("location.item", ItemController::class);`

**Comment by JosephSilber** [comment]
A h nice 👍
