### ISSUE TITLE
Bouncer::is() is not a static method, yet documentation refers to it this way.

### ISSUE THREAD

**Issue by SignetPlanet** [JosephSilber/bouncer#572]
Bouncer::is() is **not** a static method, yet the documentation refers to it a few times on checking roles. If used as a static method then the app fails with a 
```
"Non-static method Silber\Bouncer\Bouncer::is() cannot be called statically" error.
```
There is no code that uses "Bouncer::is(...)" statically except in the documentation. The only code I found that uses the is() method (non-statically) is in the tests.

The is() method requires us to pass a User model instance to it but if we already have the User instance it is much simplier to do the same check via:
```php
$user->isA('rolename');
```
Unless there is caching issues, I don't think it is necessary to have the static method and so rather than changing the code, it would make more sense to me to pull out all the documentation in the readme.md file that refers to using the is() method statically.  I'll save you the work and do that now but wanted an explaination as to why.

**Comment by JosephSilber** [comment]
As I mentioned in [the PR](https://github.com/JosephSilber/bouncer/pull/573#issuecomment-889414554), the docs uses [the facade](https://github.com/JosephSilber/bouncer/blob/master/readme.md#facade), which enables static access to all methods.

**Comment by SignetPlanet** [comment]
Sorry. I totally forgot about laravel facades being able to do that. I just went with the default namespace my IDE was suggesting and went down the rabbit hole. My bad.

**Comment by ykamal** [comment]
Using this worked for me: 
```
use Silber\Bouncer\BouncerFacade as Bouncer;
```

Sorry for reviving this. I was going crazy.
