### ISSUE TITLE
Failed permission check due to SQL query failing to find role for a class with back slashes

### ISSUE THREAD

**Issue by hugeps** [JosephSilber/bouncer#574]
Laravel 8
Bouncer is querying entity_type without using addslashes() - results in failing permission checks

mysql> select * from assigned_roles where `assigned_roles`.`entity_type` = "App\\Models\\User" limit 1 ;
+---------+-----------+-----------------+------------------+--------------------+-------+------------+
| role_id | entity_id | entity_type     | restricted_to_id | restricted_to_type | scope | deleted_at |
+---------+-----------+-----------------+------------------+--------------------+-------+------------+
|       4 |         6 | App\Models\User |             NULL | NULL               |  NULL | NULL       |
+---------+-----------+-----------------+------------------+--------------------+-------+------------+
1 row in set (0.00 sec)

mysql> select * from assigned_roles where `assigned_roles`.`entity_type` = "App\Models\User" limit 1 ;
Empty set (0.00 sec)

Below is the actual Bouncer query that fails to find any permissions 

 select * from `abilities` where ( exists ( select * from `roles` inner join `permissions` on `roles`.`id` = `permissions`.`entity_id` where `permissions`.`ability_id` = `abilities`.`id` and `permissions`.`forbidden` = 0 and `permissions`.`entity_type` = 'roles' and ( exists ( select * from `users` inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id` where `assigned_roles`.`role_id` = `roles`.`id` and `assigned_roles`.`entity_type` = 'App\Models\User' and `users`.`id` = 16 ) or `level` < ( select max(level) from `roles` where exists (  select  *  from  `users`  inner join `assigned_roles` on `users`.`id` = `assigned_roles`.`entity_id`  where  `assigned_roles`.`role_id` = `roles`.`id`  and `assigned_roles`.`entity_type` = 'App\Models\User'  and `users`.`id` = 16 ) ) ) ) or exists ( select * from `users` inner join `permissions` on `users`.`id` = `permissions`.`entity_id` where `permissions`.`ability_id` = `abilities`.`id` and `permissions`.`forbidden` = 0 and `permissions`.`entity_type` = 'App\Models\User' and `users`.`id` = 16 ) or exists ( select * from `permissions` where `permissions`.`ability_id` = `abilities`.`id` and `permissions`.`forbidden` = 0 and `entity_id` is null ) )

**Comment by JosephSilber** [comment]
I'm not exactly sure what your specific issue is, since this is standard Laravel, and not specific to Bouncer.

Regardless, you should consider [registering your models in Eloquent's morph map](https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map), in which case there'll be no slashes there.
