### ISSUE TITLE
Nested Scopes

### ISSUE THREAD

**Issue by lukebouch** [JosephSilber/bouncer#575]
I have a quick question that I have been struggling with for a while, I’m trying to create roles and abilities that are scope to an organization or sometimes a group within the organization.

On the platform I’m helping build out, a user is affiliated with an organization. There will be at least one organization admin for each organization. Since it is multi-tenant, I need to be able to scope an ability check to the organization when the user is accessing something organization specific. There will also be moderators for each group in the organization. How can I scope roles a user has on the fly and then check that a user has a given ability later on the fly?

I know bouncer already has a middleware for multi-tenancy but I do not want an entire request scoped, I just need to check in certain instances inside my polices wether a user has permission to do something within the context of a group or organization.

I would really appreciate any recommendations or help you can provide!
Thank you for creating such an amazing permission package!

**Comment by JosephSilber** [comment]
The scope has [a `onceTo` method](https://github.com/JosephSilber/bouncer/blob/master/src/Database/Scope/Scope.php#L203-L221), specifically for this:

```php
Bouncer::scope()->onceTo($organizationId, function () {
    // All assignments and checks in here will be scoped to that organization.
});
```

**Comment by lukebouch** [comment]
That may work but it needs to be polymorphic. How would I modify it to allow me to scope to either an Organization or a Group model?

**Comment by lukebouch** [comment]
I created this function on my User model and it seems to work for the propose. Not sure if it will stand the test of time.
It basically gets the `role_id` from the pivot table and checks wether or not that role has the passed in ability.


`public function canIn($ability, $userable)
    {
        $roleId = DB::table('userables')->where('userable_type', '=', get_class($userable))->where('userable_id', '=', $userable->id)->where('user_id', '=', $this->id)->select('role_id')->first()->role_id;
        /** @var Role $role */
        $role = Role::findOrFail($roleId);
        return $role->can($ability);
    }`
