### ISSUE TITLE
ErrorException in Clipboard.php line 30: Missing argument 3 for Silber\Bouncer\Clipboard::Silber\Bouncer\{closure}()

### ISSUE THREAD

**Issue by Keoghan** [JosephSilber/bouncer#59]
Hi Joseph, 

Still using Bouncer in my project, and found it very useful :)

I've just tried moving from 0.1.2 to 0.1.6 and come across an issue with the clipboard - it looks to be related to the changes for the Gate. 

It appears when I do: 

```php
    $user->can('do-something');
```

It looks like the required `$arguments` var is lost in the Gate processing during an array merge since it is an empty array.

I think a simple fix is to make the closure signature:

```php
  function ($user, $ability, $arguments = [], $additional = null) {
      ...
  }
```

I'll happily put together a pull request if you'd like.

Cheers,

Keoghan

**Comment by JosephSilber** [comment]
Did this fix it? https://github.com/JosephSilber/bouncer/commit/7014b8013c92e9658bfff166a831b44ab1005bc7

**Comment by Keoghan** [comment]
It has definitely fixed my issues. Thanks :)

**Comment by JosephSilber** [comment]
Tagged as [v0.1.7](https://github.com/JosephSilber/bouncer/releases/tag/v0.1.7).
