### ISSUE TITLE
How to separate authorize calls from controller. 

### ISSUE THREAD

**Issue by Surt** [JosephSilber/bouncer#594]
Hi!

I'm wondering if its possible to separate the ``` $this->authorize ``` from the controller actions. 
What I would like is some way to tell the controller wich class file will be "adding autorization" to the methods.
In some way, I look for something like "Policies" but for Controllers. 

In this way, I can have a "clean controller without permissions stuff"  and a "class script with authorizations for the actions".
Why? because I could have a "single" point of truth for authorization and I can even change the authorization "script" programatically when I like. 

Of course, I can use "extends" on the controller, or traits, etc and create my own way but, just wondering if this is already solved so I don't reinvent the wheel.

Thanks

**Comment by JosephSilber** [comment]
You're looking for either [the `can` middleware](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3#the-can-middleware) or  [the `$this->authorizeResource()` method](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3#authorizing-a-full-resource-controller).

**Comment by Surt** [comment]
> You're looking for either [the `can` middleware](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3#the-can-middleware) or [the `$this->authorizeResource()` method](https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3#authorizing-a-full-resource-controller).

Hi @JosephSilber thanks. Nope, I'm already using ```authorizeResource``` but I wanted to decouple more. And I don't like ```can```  on large projects. 
Seems that there is nothing like I'm looking for. Will try to look on how Policies make it's magic and try to recreate something similar for Controllers.

**Comment by JosephSilber** [comment]
You could probably create a global middleware that would deduce the permission check from inspecting the current controller and route. It would probably be quite a bit of work, but should be doable.

BTW, this is not unique to Bouncer. This is a general feature you want for Laravel's permission checks 👍
