### ISSUE TITLE
OwnedVia does not work

### ISSUE THREAD

**Issue by Dennise89** [JosephSilber/bouncer#597]
I want to be able to own a specific model via the ownedVia method you have in your [documentation](https://github.com/JosephSilber/bouncer#ownership). 

Now I am declaring the ownedVia method in the `AppServiceProvider` boot() method like this

```
Bouncer::ownedVia(Application::class, static function ($application, $profile) {
    Log::debug('closure run', ['profile' => $profile]);
    Log::debug('Query: ', ['result' => $application->whereHas('profiles', function (Builder $q) use ($profile) {
        $q->where('profile_id', '=', $profile->id);
    })->count() > 0]);
    return $application->whereHas('profiles', function (Builder $q) use ($profile) {
        $q->where('profile_id', '=', $profile->id);
    })->count() > 0;
});
```

Now I will attach an application to a profile so there is a relationship.

Now if I do the following: `$profile->can('edit', $application)` it should return true, right? But this will return false.
If we look at the log statements I added in the ownedVia method, we see that the result of the query return `true`, so that is what we expect.

Do you know why the `$profile->can(...)` statement does not work?

**Comment by JosephSilber** [comment]
Your question is not very clear. Can you please try to post again with a little more clarity?

**Comment by Dennise89** [comment]
@JosephSilber I will update the question

**Comment by JosephSilber** [comment]
The `ownedVia` method simply sets up the logic. You still must tell Bouncer that a profile is allowed to own an application.

In your seeder (or wherever you set up your DB-based permissions), add the following:

```php
Bouncer::allow(Profile::class)->toOwn(Application::class);
```

This says that any profile that owns an application can do everything with that application.

Now, when the gate checks will actually run, your closure will be consulted to determine whether the given application is owned by that profile.

**Comment by Dennise89** [comment]
> The `ownedVia` method simply sets up the logic. You still must tell Bouncer that a profile is allowed to own an application.
> 
> In your seeder (or wherever you set up your DB-based permissions), add the following:
> 
> ```
> Bouncer::allow(Profile::class)->toOwn(Application::class);
> ```
> 
> This says that any profile that owns an application can do everything with that application.
> 
> Now, when the gate checks will actually run, your closure will be consulted to determine whether the given application is owned by that profile.

Ah okay! I will try this and let you know if it worked. (maybe a good idea to also include this in the documentation?) Thanks for the answer.

**Comment by JosephSilber** [comment]
> maybe a good idea to also include this in the documentation?

This has been documented since the beginning:

https://github.com/JosephSilber/bouncer#allowing-a-user-or-role-to-own-a-model

**Comment by Dennise89** [comment]
> The `ownedVia` method simply sets up the logic. You still must tell Bouncer that a profile is allowed to own an application.
> 
> In your seeder (or wherever you set up your DB-based permissions), add the following:
> 
> ```
> Bouncer::allow(Profile::class)->toOwn(Application::class);
> ```
> 
> This says that any profile that owns an application can do everything with that application.
> 
> Now, when the gate checks will actually run, your closure will be consulted to determine whether the given application is owned by that profile.

I added this in the seeder, but still `$profile->can('edit', $application)` is returning false. Anything I'm still missing? Closure in the ownedVia method is still returning true.

**Comment by JosephSilber** [comment]
That should definitely work.

Can you create a small isolated reproduction repo?

**Comment by Dennise89** [comment]
> That should definitely work.
> 
> Can you create a small isolated reproduction repo?

I made a repo that you can download and test with. [Test repo here](https://bitbucket.org/dennis89e/bouncerepo/src/master/)

I'm using sqlite as a database for convenience, only thing you have to do is copy .env.example to .env, generate Laravel key and run migrations and seeders. `php artisan migrate --seed`
Then you can go in tinker and do the following:
`$profile = Profile::find(1);`
`$application = Application::find(1);`
`$profile->can('edit', $application);`

This will return false, but in the logs you will see that the closure will return true.

**Comment by JosephSilber** [comment]
I see this in your seeder class:

```php
Bouncer::ability()->firstOrCreate([
    'name' => 'view',
    'title' => 'View'
]);

Bouncer::ability()->firstOrCreate([
    'name' => 'create',
    'title' => 'Create'
]);

Bouncer::ability()->firstOrCreate([
    'name' => 'update',
    'title' => 'Update'
]);

Bouncer::ability()->firstOrCreate([
    'name' => 'destroy',
    'title' => 'Destroy'
]);
```

What is that? `view`/`create`/`update`/`destroy` on their own don't do anything. They have to either be connected to a model, or explicitly be set to to apply on all models.

It is generally advisable to always use Bouncer's own `allow` (etc.) methods, since that'll set the correct attributes on the abilities.

**Comment by Dennise89** [comment]
> I see this in your seeder class:
> 
> ```
> Bouncer::ability()->firstOrCreate([
>     'name' => 'view',
>     'title' => 'View'
> ]);
> 
> Bouncer::ability()->firstOrCreate([
>     'name' => 'create',
>     'title' => 'Create'
> ]);
> 
> Bouncer::ability()->firstOrCreate([
>     'name' => 'update',
>     'title' => 'Update'
> ]);
> 
> Bouncer::ability()->firstOrCreate([
>     'name' => 'destroy',
>     'title' => 'Destroy'
> ]);
> ```
> 
> What is that? `view`/`create`/`update`/`destroy` on their own don't do anything. They have to either be connected to a model, or explicitly be set to to apply on all models.
> 
> It is generally advisable to always use Bouncer's own `allow` (etc.) methods, since that'll set the correct attributes on the abilities.
> 
> I'm just mentioning this as an aside. It's not connected to the issue at hand.
> 
> I didn't get a chance yet to pull down the code and debug it. Was just reading in online. My comment above wouldn't affect this issue.

I just copied this from my actual seeder, but that has a little more logic in there that I removed. But I am using the abilities for some models.

**Comment by JosephSilber** [comment]
Sorry for not having an answer yet. It's summer. I checked it out and started playing with it, but didn't have time to fully dig in yet.

Just checking in with to say that I didn't forget, and thanks for the reproduction.

**Comment by Dennise89** [comment]
No problem. I'm also on holiday at the moment. Thanks for letting me know.

**Comment by gerard122021** [comment]
@JosephSilber Have you been able to look at this in the meantime?

**Comment by JosephSilber** [comment]
I think the code in my original post in this thread never worked:

```php
// DOES NOT WORK. Was never supported.
Bouncer::allow(Profile::class)->toOwn(Application::class);
```

...the `allow` never supported passing in a model class.

What does work is this:

```php
Bouncer::allowEveryone()->toOwn(Application::class);
```

...which would give ownership abilities it for everyone, not just profiles. So if you were to then run a check, for example, on a user directly:

```php
$profile->can('edit', $application);
```

...and Bouncer would determine that the user owns that application (either via an explicit `user_id` on the `$application`, or a registered callback), then it would allow it.

---

Since I thought it does work (as evidenced by my offhand comment on top), I think it's expected to work and should be made to work. I added it to my list of requested features.

---

As a workaround for @Dennise89, you can use `allowEveryone` if you're sure the application doesn't have a `user_id` column that would grant it for users as well if queried directly.

---

On an entirely different, your code within the `ownedVia` callback can be simplified by using the `whereRelation` method 👍 

```php
Bouncer::ownedVia(Application::class, function ($application, $profile) {
    return $application
        ->whereRelation('profiles', 'profile_id', $profile->id)
        ->exists();
});
```
