### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by a-komarev** [JosephSilber/bouncer#6]
What do you think about middleware?

Something like this for roles:

```php
Route::get('post.create', [
    'as' => 'post.create',
    'middleware' => 'role:admin,editor',
    'uses' => 'PostController@create',
]);
```
And one more for an ability:

```php
Route::get('post.create', [
    'as' => 'post.create',
    'middleware' => 'ability:create-post',
    'uses' => 'PostController@create',
]);
```

**Comment by JosephSilber** [comment]
I don't think having a middleware to check roles is a good idea. Roles are simply a way to give a user abilities. If you want all admins and editors to be able to create posts, give them that ability:

```php
Bouncer::allow('admin')->to('create', Post::class);
Bouncer::allow('editor')->to('create', Post::class);
```

To check abilities in middleware, I'd suggest you use Spatie's excellent [authorize middleware](https://github.com/spatie/laravel-authorize).

**Comment by a-komarev** [comment]
wow thanks a lot! This link is exactly what I was looked for.
