### ISSUE TITLE
Multiple Database Connection

### ISSUE THREAD

**Issue by asyraf-loop** [JosephSilber/bouncer#606]
Hi to all maintainers and readers.

My Laravel apps is using 2 database connections. One is Postgres where the silber/bouncer is installed. Then one more is using MySQL. The reason for this is the apps is expanding then need to read other system database.

I have follow this step https://github.com/JosephSilber/bouncer#configuration

I add new model called BouncerAbility extends to Role and Ability, and BouncerRole extends to Role. then I add new connection for both of these models.

protected $connection = 'pgsql';

I also add the BouncerServiceProvider add the provider in config array. then I add

Bouncer::useAbilityModel(BouncerAbility::class);
Bouncer::useRoleModel(BouncerRole::class);

in that provider.

But I still got the problem where the bouncer keep reading the MySQL database, not reading the Postgres database.

Any clues how to resolve this?

Thanks.

**Comment by JosephSilber** [comment]
Bouncer uses `JOIN`s extensively, which means that all tables must reside in the same DB.
