### ISSUE TITLE
Check if a role owns a model

### ISSUE THREAD

**Issue by obrunsmann** [JosephSilber/bouncer#612]
To implement a settings UI it is necessary to find out if a role can own or manage a model. So I'd suggest a method like

```php
$role->canOwn(Task::class);

$role->canManage(Task::class);
```

**Comment by JosephSilber** [comment]
The way to handle it in the UI would be to have a list of actual `Ability` instances. For example:

```php
$available = Bouncer::ability()->pluck('title', 'id');
$granted = $role->getAbilities();
```

And then have the user toggle those directly.
