### ISSUE TITLE
Frontend - Check if user can own a model

### ISSUE THREAD

**Issue by webstudios1** [JosephSilber/bouncer#624]
I've been looking for most of the day after this question. Meybe looking in the wrong place so here it goes.

Is there a way to check in blade if a user has the ability to own a model..
eks. @canOwn(App\Models\Sale::class)

**Comment by JosephSilber** [comment]
What would `canOwn` mean?

You simply want to check whether they `can` do something, such as `@can('view', $model)`. If they own that model (and have ownership permissions), that `can` check will return `true`.

So all you really need is Laravel's built-in `@can` Blade directive.

**Comment by webstudios1** [comment]
But if I dont have a $model? Is there a way to check if the user has the canOwn permission.
