### ISSUE TITLE
Get Direct Abilities - Not via Roles

### ISSUE THREAD

**Issue by Aniket-IN** [JosephSilber/bouncer#630]
Hi 👋,

I was just getting started with this pacakge, needed a small help.
I'm trying to get direct abilities of a user, saw there'a method `$user->getAbilities()` but, this method includes abilities assigned via roles as well 🤔. 
How do I get only abilities those are directly assigned to the user and not via roles.
 
Thank you 😊.

**Comment by JosephSilber** [comment]
You can get those vu the regular `abilities` Eloquent relationship:

```php
$user->abilities
```

**Comment by Aniket-IN** [comment]
Exactly what I neded. 
Thank you so much for the amazing package. 😃
