### ISSUE TITLE
Polymorphic

### ISSUE THREAD

**Issue by barhom** [JosephSilber/bouncer#64]
Hey,

Has the polymorphic branch been merged with master? I switched to polymorphic a while ago to test it after Joseph requested some people to try it.

**Comment by JosephSilber** [comment]
It hasn't been merged into master yet. I've been asking people in #43 to test it out first and report back.

If you've tested it, please let us know in #43 how it went.

**Comment by JosephSilber** [comment]
Just letting you know that this was merged into master.

Tagged as [v1.0.0-alpha.1](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-alpha.1).
