### ISSUE TITLE
Fatal error: Call to a member function intersect() on boolean

### ISSUE THREAD

**Issue by masterpowers** [JosephSilber/bouncer#65]
Im getting error when i 
$user->is('admin')
Fatal error: Call to a member function intersect() on boolean

This Happens when i included it in
AppServiceProvider Boot Function
```
\Bouncer::cache();
```

I running it on homestead, is this normal or not?

**Comment by JosephSilber** [comment]
Can you provide us the full stack trace please?

**Comment by JosephSilber** [comment]
Can you provide us the full stack trace please? It'll make it much easier to debug.

**Comment by JosephSilber** [comment]
Closing pending further details.
