### ISSUE TITLE
[Feature Request] Protecting Routes

### ISSUE THREAD

**Issue by bkuhl** [JosephSilber/bouncer#66]
It'd be great if there was a way to protect routes similar to https://github.com/Zizaco/entrust#short-syntax-route-filter.

**Comment by JosephSilber** [comment]
Add this line to [your route middleware](https://github.com/laravel/laravel/blob/a282304/app/Http/Kernel.php#L46-L51):

```php
'can' => \Silber\Bouncer\Middleware\Authorize::class,
```

Then use it in your routes:

```php
Route::get('dashboard', 'DashboardController@index')->middleware('can:view-dashboard');
```

**Comment by bkuhl** [comment]
Wow, thanks for dropping this in.  I've switched from Entrust (which isn't getting very much attention for upgrading to L5.2) to Bouncer since you added this.  This would make a great addition to the readme!!

**Comment by JosephSilber** [comment]
In case anyone else bumps into this discussion: know that [the middleware will soon be removed](https://github.com/JosephSilber/bouncer/issues/82).

**Comment by Gregor-Agnes** [comment]
5.3: Seems like middleware on Routes doesn't work anymore, but works on Route::group

```php
Route::group(['middleware' => 'can:administrate-users'], function () {
    Route::resource('users', 'UserController');
});
```

**Comment by JosephSilber** [comment]
Can you show me an example of what doesn't work?

**Comment by Gregor-Agnes** [comment]
```php
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UserController')->middleware('can:administrate-users');
});
```

**Comment by JosephSilber** [comment]
Laravel 5.3 doesn't support putting middleware on a resource route. This has been added in Laravel 5.4.
