### ISSUE TITLE
Get role's abilities list

### ISSUE THREAD

**Issue by gitricardosoares** [JosephSilber/bouncer#68]
Hi there, i found that package usefull, but there is anyway to get role's abilities list? 

For example : 
```
foreach($roles as $role) {
     $role->name; // outputs Admin
     $role->getAbilities(); // outputs all admin permissions
}
```

**Comment by JosephSilber** [comment]
This is currently possible in polymorphic branch.

Please take it for a spin, and report back in [this thread](https://github.com/JosephSilber/bouncer/issues/43#issuecomment-184018996).

**Comment by gitricardosoares** [comment]
I still can't do it with that branch,
It's giving me an "Call to undefined method stdClass::getAbilities()"

**Comment by JosephSilber** [comment]
It seems like `$roles` Is not a collection of Eloquent models.

How did you get that `$roles` collection?

**Comment by gitricardosoares** [comment]
Hoo right, since i dont have the Role model i just made a `DB::table('roles')` call, so how can i call the collection without the Role model? Normally i would do `Role::get()` but since i dont have the model i cant do it right?

**Comment by JosephSilber** [comment]
```php
$roles = Bouncer::role()->all();
```

**Comment by gitricardosoares** [comment]
That worked this `$role->getAbilities()` now gives me this on my blade:

` [{"id":8,"name":"ban-users","entity_id":null,"entity_type":null,"created_at":"2016-03-18 02:18:43","updated_at":"2016-03-18 02:18:43"},{"id":9,"name":"other-thing","entity_id":null,"entity_type":null,"created_at":"2016-03-18 03:38:24","updated_at":"2016-03-18 03:38:24"}]`

can you just help me with one more little thing pls?

**Comment by gitricardosoares** [comment]
So im going to say it anyawy so like i said it's returning the code right and im doing the foreach on blade: 
`[{"id":8,"name":"ban-users","entity_id":null,"entity_type":null,"created_at":"2016-03-18 02:18:43","updated_at":"2016-03-18 02:18:43"},{"id":9,"name":"other-thing","entity_id":null,"entity_type":null,"created_at":"2016-03-18 03:38:24","updated_at":"2016-03-18 03:38:24"}]`

What is the easyest away to get just the "name" ?

**Comment by JosephSilber** [comment]
```php
$roles = Bouncer::role()->pluck('name');
```

If you're still using Laravel 5.1, replace `pluck` with `lists`.

**Comment by gitricardosoares** [comment]
Yes, but that just give me the Role name like `admin` and for that im doing `$role->name` inside the foreach and that does the work, what i want its the `abilities` name when i do `$role->getAbilities()` insire the loop instead of that output:

`[{"id":8,"name":"ban-users","entity_id":null,"entity_type":null,"created_at":"2016-03-18 02:18:43","updated_at":"2016-03-18 02:18:43"},{"id":9,"name":"other-thing","entity_id":null,"entity_type":null,"created_at":"2016-03-18 03:38:24","updated_at":"2016-03-18 03:38:24"}]`

**Comment by JosephSilber** [comment]
```php
$abilities = $role->getAbilities()->pluck('name');
```

**Comment by gitricardosoares** [comment]
Well, that worked thank you, just one more little thing, sorry for being a pain in the ass but, there are little thing that i cant understand. 
So my blade locks like that for now:
```
@foreach($roles as $role)
    <li> {{ $role->name }}</li>
          <ul>
                 <li> {{ $role->getAbilities()->pluck('name') }}</li>
          </ul>
@endforeach
```
And the `getAbilities `outputs me this : `["ban-users","shit-pants"]` the away i worked around that was in front of `pluck('name')` put a `[0]` and that outputs me the first abilitie like "ban-users" but who can i do it without `[0]` there so it outputs not just the first one but all?

**Comment by jonagoldman** [comment]
You are asking a general programming question. You can find the answer by googleing it. You basicallly want to echo the values of an array. There are different ways to do it. You can use ´´´echo join(', ', $array);´´´ or ´´´foreach´´´ or ´´´for´´´. Also read the Laravel docs, its a good way to get a general picture of what can be done with the framework.

**Comment by ctwillie77** [comment]
@gitricardosoares Just use another foreach loop:

```
@foreach($roles as $role)
    <li> {{ $role->name }}</li>
          <ul>
                 @foreach( $role->getAbilities()->pluck('name') as $name )
                        <li> {{ $name }}</li>
                 @endforeach
          </ul>
@endforeach
```
