### ISSUE TITLE
Class not found when trying to add wildcards

### ISSUE THREAD

**Issue by DanielOlckers** [JosephSilber/bouncer#69]
Hi

I get an 

> Fatal error: Class '*' not found

error when I try to add add wildcard abilities.

This works:

`Bouncer::allow('admin')->to('*');`

This does not:

`Bouncer::allow('admin')->to('*', '*');`

I followed the examples as discussed here:

#56 

Not sure if I'm missing something. This is a stock standard installation via composer on a Laravel 5.2 project.

Any help would be appreciated.

Thanks for an awesome package btw. :-)

**Comment by JosephSilber** [comment]
Are you using the polymorphic branch?

These wildcards haven't been merged into the main branch yet.

**Comment by DanielOlckers** [comment]
That explains a lot... PEBKAC problem ;-)

Will take the polymorphic branch for a spin then. Any idea when the wildcards will be merged into the main branch?

Thanks for the reply @JosephSilber.

**Comment by JosephSilber** [comment]
@DanielOlckers I'm still waiting for more feedback on the polymorphic branch; from both new installs and, more importantly - from upgrades. See #43.

**Comment by JosephSilber** [comment]
Just letting you know that this was merged into master.

Tagged as [v1.0.0-alpha.1](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-alpha.1).

**Comment by DanielOlckers** [comment]
Awesome, thanks, so far everything seems to be running like a dream.
