### ISSUE TITLE
App\User is hard coded

### ISSUE THREAD

**Issue by bgies** [JosephSilber/bouncer#71]
I've noticed that you don't seem to have a config file that would allow us to change the model we are using. I have all my models in App\Models, so I'm using App\Models\User as my User Model. That causes an error because Ability.php, Models.php, Role.php and BouncerServiceProvider.php all hard code the App\User; 

Perhaps the User Model should be type-hinted ?

**Comment by bgies** [comment]
Ah.. well, your Service provider does set the correct model, so just commenting out the App\User in Ability.php, Models.php, Role.php fixed the problem....

**Comment by jonagoldman** [comment]
https://github.com/JosephSilber/bouncer/issues/21

**Comment by JosephSilber** [comment]
@bgies if you've changed the default location for the user model, you have to let Laravel's `Auth` service know about it. You do that by setting it in the `config/auth.php` file.

Bouncer uses whatever model is registered with the `Auth` service. Once you update that config file, Bouncer will work as expected.

**Comment by bgies** [comment]
Yes, of course... but the App\User was hardcoded in Ability.php, Models.php, Role.php in the use section. As I said, your service provider does load the correct model, so commenting out the hardcoded "use App\User" fixed it.
