### ISSUE TITLE
Conflict with sluggable package. Check if attributes exist before assigning.

### ISSUE THREAD

**Issue by shanecp** [JosephSilber/bouncer#72]
`Ability.php` has a public method called `getSlugAttribute`. Seems like this is undocumented.

I use the https://github.com/cviebrock/eloquent-sluggable package for slugging on my application with `name` as the slugged field. 

This throws a `name` is undefined error if the auto-generated slug already exist in the DB.

I was able to resolve this by overriding the `getSlugAttribute` and check if the attributes exist before assigning.

Following is the suggested fix.
```
	final public function getIdentifierAttribute()
	{
		$slug = (!empty($this->attributes['name']))? $this->attributes['name']: '';

		if (!empty($this->attributes['entity_type'])) {
			$slug .= '-'.$this->attributes['entity_type'];
		}

		if (!empty($this->attributes['entity_id'])) {
			$slug .= '-'.$this->attributes['entity_id'];
		}

		return strtolower($slug);
	}
```

**Comment by Gummibeer** [comment]
Why do you want to fix the `getIdentifierAttribute` Method if the problem is the `getSlugAttribute`? And if you can solve your very specific problem by overriding the method I don't think that's neccessary to implement it in the package.

**Comment by JosephSilber** [comment]
@Gummibeer is right. The package ships with a sensible default. If you want to override it in your app, that's fine:

```php

namespace App;

use Silber\Bouncer\Database\Ability as BouncerAbility;

class Ability extends
{
    public function getSlugAttribute()
    {
        // return ....
    }
}
```

Then in your `AppServiceProvider`'s `boot` method, register your own `Ability` model:

```php
Bouncer::useAbilityModel(App\Ability::class);
```
