### ISSUE TITLE
Problem Upgrading to 1.0

### ISSUE THREAD

**Issue by knox2** [JosephSilber/bouncer#78]
Im getting this error
`
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "bouncer:upgrade" is not defined.                       
  Did you mean this?                                              
      bouncer:seed
`

**Comment by JosephSilber** [comment]
Are you sure you're actually using 1.0? Have you set the composer dependency properly?

What do you get when you run `composer show | grep bouncer`?

**Comment by JosephSilber** [comment]
Closing pending further details.

**Comment by knox2** [comment]
Sorry, I didn't set 1.0 in composer.json..
