### ISSUE TITLE
How do i get all the users off a specific role

### ISSUE THREAD

**Issue by Tjoosten** [JosephSilber/bouncer#79]

**Comment by jonagoldman** [comment]
Like you do it with a regular Eloquent model ```->users()```. Take a look at the [Role ](https://github.com/JosephSilber/bouncer/blob/master/src/Database/Role.php) model.

**Comment by Tjoosten** [comment]
@jonagoldman how i get the all the roles of the returned user?

**Comment by Arcesilas** [comment]
@Tjoosten You should start reading [Laravel documentation](https://laravel.com/docs/5.2/eloquent#retrieving-multiple-models), since this is a very basic functionnality of Eloquent ORM

**Comment by jonagoldman** [comment]
@Tjoosten please read the docs

**Comment by JosephSilber** [comment]
Closing this now, as it's a simple Eloquent question and has been sufficiently answered here.
