### ISSUE TITLE
Unable to use can: to protect routes

### ISSUE THREAD

**Issue by bkuhl** [JosephSilber/bouncer#81]
The issue described in #76 still exists in the most recent version.

My route is setup like so:

```
                    Route::group([
                        'middleware' => ['can:'.Ability::MANAGE_GROUPS]
                    ], function () {
                        Route::get('groups', 'GroupController@index');
                        Route::get('groups/outstanding-registration-fees', 'GroupController@outstandingRegistrationFees');
                        Route::get('groups/{groupId}', 'GroupController@show');
                    });
```

and using the "out of the box" 1.0.0-alpha1 bouncer version leads to an error in the tests:

```
1) GroupsTest::searchGroupList
Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> callable $userResolver ]] in class Illuminate\Auth\Access\Gate

/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:839
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:777
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:633
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:853
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:808
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:777
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Container/Container.php:633
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:152
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:508
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:78
/path/to/project/tests/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:61
/path/to/project/tests/Admin/GroupsTest.php:27
```

Adjusting the import as indicated in #76 leads to passing tests:

<img width="981" alt="screen shot 2016-04-10 at 7 13 17 pm" src="https://cloud.githubusercontent.com/assets/524933/14413706/7862311c-ff50-11e5-8157-8e0018d72c87.png">

I understand the IOC binding for the contract does not match the method's usage, but that's Laravel's problem not yours.

**Comment by bkuhl** [comment]
To recreate this issue, checkout https://github.com/BibleBowl/account/commit/9317720dff41f8456f145dc7deb60304ac726440 and run:

- `docker-compose up`
- `docker exec -it $(docker-compose ps -q fpm) php artisan migrate --seed` (runs migrations within the fpm container
- `docker exec -it $(docker-compose ps -q fpm) vendor/bin/phpunit` // tests will fail
- Update use statement in `Sibler\Bouncer\Middleware\Authorize\Gate`
```
use Illuminate\Contracts\Auth\Access\Gate;
```
- `docker exec -it $(docker-compose ps -q fpm) vendor/bin/phpunit` // tests will pass

Is there a test case you've encountered to suggest using the contract is not the solution?

**Comment by JosephSilber** [comment]
> The issue described in #76 still exists in the most recent version.

That fix hasn't been tagged yet, so it's not in `1.0.0-alpha1`.

---

Anyhow, I'm about to remove this middleware from Bouncer, since [I got it merged into Laravel directly](https://github.com/laravel/framework/pull/12913).

Update your kernel to use the Laravel middleware instead:

```php
'can' => \Illuminate\Foundation\Http\Middleware\Authorize::class,
```

Its usage stays the same.
