### ISSUE TITLE
Removing the Authorize middleware and the AuthorizesRequests trait

### ISSUE THREAD

**Issue by JosephSilber** [JosephSilber/bouncer#82]
This is simply an announcement that I'm about to remove the `Authorize` middleware and the `AuthorizesRequests` trait, since [they've now been merged into Laravel](https://github.com/laravel/framework/pull/12913).

If you've been using the `Authorize` middleware, simply update your kernel to use the Laravel middleware instead:

```php
'can' => \Illuminate\Foundation\Http\Middleware\Authorize::class,
```

Its usage stays the same.

---

If you're still on 5.1, you can [copy the middleware](https://raw.githubusercontent.com/laravel/framework/5.2/src/Illuminate/Foundation/Http/Middleware/Authorize.php) into your own app directory @ `app/Http/Middleware/Authorize.php`. Don't forget to update the namespace.

Once you do so, use that middleware in your kernel:

```php
'can' => \App\Http\Middleware\Authorize::class,
```

Its usage stays the same.

**Comment by fredrkr** [comment]
I'm curious about this middleware. I've been trying to make it work when using token-based authentication. My app has session-based auth set as default, so when I authenticate with the token-guard, this middleware always returns 403. Is it currently possible to tell the middleware which guard to use when fetching the user?

**Comment by JosephSilber** [comment]
I fixed this in Laravel 5.3. If you use the auth middleware before the can middleware, the can middleware will use the guard specified there.

->middleware('auth:api|can:update,post');

**Comment by fredrkr** [comment]
Awesome. Good work!

**Comment by Gummibeer** [comment]
@fredrkr It's a problem in the userResolver itself.
`\Illuminate\Auth\AuthManager::__construct()` sets the `userResolver` with the optional parameter for the used guard. But starting in the `\Illuminate\Auth\AuthServiceProvider::registerAccessGate()` it doesn't pass the used guard to the `\Illuminate\Auth\Access\Gate`.

Regarding to `\Illuminate\Auth\AuthManager::guard()` and `\Illuminate\Auth\AuthManager::getDefaultDriver()` it uses the default driver from the config if no guard name is passed. The only solution for earlier 5.3 could be to set the default guard in a middleware deppending on the used auth system.

**Comment by fredrkr** [comment]
@Gummibeer My futile investigation stopped at the userResolver, so thanks for the info. 

Well, if you're gonna roll your own middleware, you might as well replace the middleware that 'can' uses (Authorize), specify the guard, and do the authorization in there. This is what I did, only, similar to the auth-middleware, I accept the auth-guard to use as a parameter.
