### ISSUE TITLE
How can You Grant Super Admin with No Restriction At All?

### ISSUE THREAD

**Issue by masterpowers** [JosephSilber/bouncer#84]
I see the latest video of Jeffrey way now at laracast...
About Policy Object ... 
Using the before method, the logic for Admin can bypass all other authorization...
How can we do it using your package?

**Comment by JosephSilber** [comment]
Bouncer::allow($user)->to('*', '*');

We'll eventually have better alias methods for this, but for now you can use this in its raw form.

**Comment by JosephSilber** [comment]
```php
Bouncer::allow($user)->to('*', '*');
```

We'll eventually have better alias methods for this, but for now you can use this in its raw form.
