### ISSUE TITLE
Helper to Sync abilities to role?

### ISSUE THREAD

**Issue by OliverGrimsley** [JosephSilber/bouncer#85]
Working on admin backend using this - going great thanks to comments here but hit a snag.  A form I have returns an array of revised IDs to _abilities_ to update on a _role_.  I want to sync them instead of clearing them and re-assigning using the documented helper function (i.e. not using `Bouncer::allow('admin')->to('ban-users');`).  Code snippet below, which does not work - is there a helper function for syncing revised _abilities_ to _roles_ - and if not, just wondering if some additional non user based helper functions would be helpful for others - ? 

Code:

`//obtain model instance of Role to update from form submission`
`$roleToUpdate = Role::find($request->roleToEdit); // i.e. $roleToUpdate = Role::find(1);`
`//sync submitted array of abilities to Role model`
`//array rolePerms[$request->roleToEdit] : list of abilities IDs to sync to Role`
`$roleToUpdate->abilities()->sync($request->rolePerms[$request->roleToEdit]);`

The above returns bad method call, as does use of "...ability()->sync(..." .  Assuming no helper/method, could someone suggest a solution or should I just retrieve the names from the form and construct an update using the above helper function?

I wish I could help with contributing to this excellent role-ability-authorization package, I am not a professional developer or I would have probably been able to figure out the above . . . (I did search issues and read a lot of them, which allowed me to figure out syncing new roles to users). 

I am using the current polymorphic version.  

thx / mike oliver

**Comment by Gummibeer** [comment]
The method is called `abilities()` so it is:
```php
$role = Role::findOrFail($roleId);
$role->abilities()->sync($abilityIds);
```

**Comment by OliverGrimsley** [comment]
Thank you.  My issue was that I had added manual models in my app to test functions, and I was calling them and not the models from Bouncer.  I removed them and referenced 'Bouncer::[method]()->' etc and it works fine.  my fault, thx again mike oliver
