### ISSUE TITLE
Problem when using Bouncer::cache()

### ISSUE THREAD

**Issue by reado** [JosephSilber/bouncer#9]
I've followed the instructions outlined in the readme doc and everything is working properly with Bouncer except the caching functionality.

As soon as I added the following to my AppServiceProvider.php's boot() function
```
Bouncer::cache()
```
I got the following error

```
  [Illuminate\Contracts\Container\BindingResolutionException]
  Target [Illuminate\Contracts\Cache\Store] is not instantiable.
```

Note: I also set the package up to use Facades and added a 
```
use Bouncer;
```
to the top of my AppServiceProvider.php file

and I have already setup my caching using the redis driver and from everything I can tell, its working correctly.

Any help would be appreciated!

**Comment by JosephSilber** [comment]
Thanks for the report :heart:

**Comment by reado** [comment]
Yep that commit fixed it

Thanks for the great package!
