### ISSUE TITLE
Migrate rollback or refresh fails

### ISSUE THREAD

**Issue by OliverGrimsley** [JosephSilber/bouncer#90]
Using the Bouncer dev (so I have these 2 migrations):
Migrated: 2016_03_27_235610_create_bouncer_tables
Migrated: 2016_04_01_001800_upgrade_to_bouncer_02

Databases migrate fine.  But . . . I recently needed to rollback entire database.  I get these errors:

[Illuminate\Database\QueryException]                                                                                             
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'homestead.role_abilities' (SQL: drop table `role_abilities`)  
                                                                                                                                   
[PDOException]                                                                                
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'homestead.role_abilities'

Tried commenting out the following in the base migration (because these tables were deleted during upgrade):
//Schema::drop(Models::table('role_abilities'));
//Schema::drop(Models::table('user_abilities'));
//Schema::drop(Models::table('user_roles'));

refresh still fails:
[Illuminate\Database\QueryException]                                                                                                                  
SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table `roles`)  
                                                                                                                                                        
[PDOException]                                                                                                              
SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails

I can manually remove all tables and migrate.  Not sure how to fix the last set of rollback issues.
/mike

**Comment by JosephSilber** [comment]
The Bouncer 1.0 upgrade migration doesn't have anything in the `down` method, because it's not possible to roll back. Once you've upgraded, going back to the old schema will make your data be in a corrupted state.

If you need to make changes to your database, you'll have to handle this yourself.
