### ISSUE TITLE
Give multiple permissions in one go

### ISSUE THREAD

**Issue by svenluijten** [JosephSilber/bouncer#93]
To my surprise, I noticed you can't do something as simple as 

```php
Bouncer::allow('owner')->to([
    'see', 'create', 'edit', 'delete'
], $post);
```

In my mind, it makes sense if we could do this to keep our seeders small and still make it readable for the end user. What do you think?

**Comment by JosephSilber** [comment]
Use wildcards:

```php
Bouncer::allow('owner')->to('*', $post);
```

**Comment by kunhalil** [comment]
Can this be done on a controller level?

**Comment by kunhalil** [comment]
The approach to my problem was flawed. This is what I needed -https://github.com/laravel/framework/pull/12913
