### ISSUE TITLE
How to get all the user who have certain role?

### ISSUE THREAD

**Issue by mramitkumarraj** [JosephSilber/bouncer#96]
I want to get all the user which has role "owner". Somewhere I am stuck. I don't know why Bouncer
doesn't provide such kind of function? Is it possible to get something like $user->hasRole('owner'); or i have to use a row query?

**Comment by jonagoldman** [comment]
Why do you need Bouncer to do such a simple thing?  You do a regular database query as you would with anything in your database. If you want you can add a hasRole() method to your User model too.

**Comment by mramitkumarraj** [comment]
I am using Eloquent, and i don't want to use regular/raw query.

**Comment by hotvic** [comment]
I used something like this:

```php
public static function admin()
{
        return self::whereHas('roles', function ($query) {
            $query->where('role_id', 1);
        })->first();
}
```

Member of User model that returns the admin user (role_id = 1).

**Comment by JosephSilber** [comment]
> I don't know why Bouncer doesn't provide such kind of function

It actually does, but we didn't get around to document it yet:

```php
$users = User::whereIs('admin')->get();
```

**Comment by bkuhl** [comment]
It'd be great to get this added to the documentation / cheat sheet
