### ISSUE TITLE
Should assigning a role to a user also assign role's abilities?

### ISSUE THREAD

**Issue by OnceWas** [JosephSilber/bouncer#97]
I have a minimal seeder script which creates an 'Admin' role, adds 'admin-users' as an ability to that role:

`Bouncer::allow('Admin')->to('admin-users');`

Then the script assigns the 'Admin' role  to a user:

`Bouncer::assign('Admin')->to($user);`

The user gets the role properly assigned, but when I retrieve this user's abilities, the Abilities collection that is returned is empty. I am retrieving the abilities and roles for the user like this:

```
    public function getUserDetail($id)
    {
        return User::where('id', $id)
                    ->with('roles')
                    ->with('abilities')
                    ->first();
    }
```

![screen shot 2016-05-25 at 8 02 13 pm](https://cloud.githubusercontent.com/assets/12662769/15562467/4fc9544c-22b4-11e6-9489-3c7d10572a05.png)

My role_abilities table contains the role to ability relationships, but my user_abilities table is empty.

What is the proper way to get / display a user's (effective) abilities if the abilities have been assigned via a role?

Thanks.

**Comment by JosephSilber** [comment]
The get the effective abilities, use the `getAbilities` method, as [shown in the docs](https://github.com/JosephSilber/bouncer/blob/master/readme.md#getting-all-abilities-for-a-user):

```php
$abilities = $user->getAbilities();
```

**Comment by OnceWas** [comment]
Thank you. `getAbilities();` definitely works.

Is there a way to get the user's abilities using a method similar to `->with('roles')` when retrieving a user record?

Otherwise, I can work with `$user->getAbilities();`

**Comment by JosephSilber** [comment]
You can use Eloquent's `setRelation` method to dynamically set it. Your example would look like this:

```php
public function getUserDetail($id)
{
    $user = User::with('roles')->find($id);

    return $user->setRelation('abilities', $user->getAbilities());
}
```
