### ISSUE TITLE
Give all the abilities of one role to another role

### ISSUE THREAD

**Issue by ethan4ma** [JosephSilber/bouncer#98]
Case: If i already has a role A and it has several abilities, then i wanna to create a new role named B.

Problem: How can i give all the abilities of A to B at once, i wrote the code below, but it does not work well..

`
$abilities = $A->getAbilities();

Bouncer:allow('B')->to($abilities)`

**Comment by JosephSilber** [comment]
Loop over them:

```php
$a->getAbilities()->each(function ($ability) use ($b) {
    Bouncer:allow($b)->to($ability);
});
```

**Comment by ethan4ma** [comment]
@JosephSilber I've checked the source code in GiveAbility.php line 39 , the method "to" can accept abilities but the abilitiesByName in line 145 really puzzled me? can u give me some suggestions?

**Comment by kunhalil** [comment]
How can I do this for abilities assgined to a Role (without identifying the user assgined to the Role)?

**Comment by JosephSilber** [comment]
@ethan4ma & @kunhalil can you both please be more specific? I'm not sure I understand what either of you is saying.

**Comment by kunhalil** [comment]
My use case scenario;

I am using Bouncer's seeding functionality to pre-seed data as follows;

\Bouncer::allow('student-viewer')->to('student-list');
\Bouncer::allow('student-viewer')->to('student-record');

\Bouncer::allow('student-updater')->to('student-create');
\Bouncer::allow('student-updater')->to('student-edit');

and for 'student-admin' role can I assgin all the above abilities using the role as a reference?;

or do I need to do the following;

\Bouncer::allow('student-admin')->to('student-list');
\Bouncer::allow('student-admin')->to('student-record');
\Bouncer::allow('student-admin')->to('student-create');
\Bouncer::allow('student-admin')->to('student-edit');
\Bouncer::allow('student-admin')->to('student-action');

**Comment by JosephSilber** [comment]
@kunhalil

1. I'd suggest you use [proper model abilities](https://github.com/JosephSilber/bouncer#restricting-an-ability-to-a-model) instead of these simple named abilities:

    ```php
    Bouncer::allow('student-viewer')->to('list', Student::class);
    Bouncer::allow('student-viewer')->to('record', Student::class);

    Bouncer::allow('student-updater')->to('create', Student::class);
    Bouncer::allow('student-updater')->to('edit', Student::class);
    ```

2. You can then simply allow the admin to do everything on the student model:

    ```php
    Bouncer::allow('student-admin')->to('*', Student::class);
    ```

With these in place, you can later easily check permissions as such:

```php
$user->can('create', Student::class);
```

Which will return `true` for `student-updater` and `student-admin`, but not for `student-viewer`.
