### ISSUE TITLE
Some Eloquent methods will no longer function

### ISSUE THREAD

**Issue by fredrkr** [JosephSilber/bouncer#99]
Thanks for your great work with Bouncer so far.

In your recent 1.0 pre-release, you changed the schema quite a bit. One change created a lot of extra work in my case.

I have a GUI for creating a role and associating various abilities with that role (in the form of checkboxes). In my controller, I end up with an array of ability-ids that I need to associate with a certain role. There really is no better way of doing this than calling ``` $role->abilities()->sync($abilityIdsArr)```. The Bouncer-facade, offers no equivalent of this method, and rightly so, since Eloquent has the sync-method.

This was working fine up until the schema was changed. For some reason the "entity_type"-column in the permissions-table is simply 'roles' when pointing to a role. A regular polymorphic relationship in Eloquent, needs the FQCN to the model to which the entity is related, for instance 'App\Models\Ability'. Due to this change, effectively I can no longer use n:m Eloquent-methods in the way I used to. 

Is the entity_type-column supposed to be just "roles" in the permissions-table in these instances?

**Comment by fredrkr** [comment]
I've been digging a little into why this happens and I found that the problem seems to be when Laravel's getMorphClass()-method is called on Bouncer's Role-model. A simple demonstration:

```php
$role = \Silber\Bouncer\Database\Role::first();

$role->getMorphClass(); // 'roles'
```
I believe ```getMorphClass()``` should return ```'Silber\Bouncer\Database\Role'```, that is the FQCN. In my case, in which I have extended Bouncer's model, and overridden the ```$fillable```-attribute, I would expect ```getMorphClass()``` to return the FQCN to *my* Role-model.

I tested overriding the method in my ```App\Models\Role```-class which I use to extend Bouncer's model. 

```php
<?php

namespace App\Models;

class Role extends \Silber\Bouncer\Database\Role
{
    protected $fillable = ['name', 'label', 'description'];

    public function getMorphClass()
    {
        return 'roles';
    }
}
```

After that, all Bouncer-methods still work as normal and I can use all of Eloquent's methods again. I can only conclude that Bouncer's Role-model believes its morphed classname is 'roles', so I have to trick Eloquent into believing this as well.

**Comment by JosephSilber** [comment]
In order for Eloquent to properly map the model to the table name, you have to register your model with the relation morph map.

Add this to `AppServiceProvider@boot`:

```
Illuminate\Database\Eloquent\Relations\Relation::morphMap([
    \App\Models\Role::class,
]);
```

**Comment by fredrkr** [comment]
The Eloquent-methods work when I modify the morph-map but now, the user's ```can()```-method return's ```false``` when it's supposed to return ```true```.

```php
auth()->user()-can('changeSomething'); // false.... should be true
```

Here, the logged in user has a role which, in turn, has the ability 'changeSomething'. The Authorize-middleware, now a part of Laravel, also denies when it's not supposed to. The Bouncer facade-methods ```denies()``` and ```allows()``` also returns ```true``` and ```false``` respectively which is wrong.

All the methods work again, if I remove my classes from the morph map.

**Comment by JosephSilber** [comment]
When you change the morph map, you also have to update the values in the DB. Otherwise it won't map it correctly.

**Comment by fredrkr** [comment]
I tried that. The results are the same; can(), allow(), etc. does not return expected values. Eloquent-methods sort of work. That is, sync() saves the roles, but entity_type gets the value 'roles' and the authorization-methods won't work. Consider my example (Role and Ability models are empty and just extend Bouncer's models):

```php
print_r( \Illuminate\Database\Eloquent\Relations\Relation::morphMap() );

// Here's my modified morph map:
//
// Array
// (
//    [roles] => App\Role
//    [abilities] => App\Ability
// )

$role    = \App\Role::find(1);
$ability = \App\Ability::find(1);
$user    = $role->users->first();

$role->abilities()->sync([$ability->id]);
// entity_type: 'roles'

$user->can($ability->name);
// false

Bouncer::allow($role->name)->to($ability->name);
// entity_type: 'Silber\Bouncer\Database\Role'

$user->can($ability->name);
// true
```
Apparently, if the entity_type is set to ```'Silber\Bouncer\Database\Role'```, can() and allow() works as expected. Isn't it supposed to be ```'App\User'``` after I change the morph map?

I'm confused at this point.

**Comment by JosephSilber** [comment]
If you use your own `Role` model, [you have to let Bouncer know about it](https://github.com/JosephSilber/bouncer/releases/tag/v0.0.22):

```php
Bouncer::useRoleModel(App\Role::class);
```

**Comment by fredrkr** [comment]
There were actually dedicated methods for it this whole time? Thanks, although this should definitely be mentioned in the docs somewhere.

At this point, I would like to suggest offering a config-file. I remember you saying you're not a fan, but keep adding functionality to Bouncer, and more users will probably be asking for it. The two methods added in 0.0.22 for instance, are prime examples of stuff that belongs in a config-file.

I will do some further testing and let you know.

**Comment by JosephSilber** [comment]
@fredrkr I still don't want a config file.

The problem here is with the documentation, which is incomplete [as mentioned here](https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-alpha.1).

When we're all done with it, there'll be a full section on configuration.

**Comment by fredrkr** [comment]
> I still don't want a config file.

Why? I mean, I'm just curious about your reasoning behind your aversion to config-files beyond just "they're ugly".

Anyway, after a bit more testing, I've found that the correct FQCN is saved and everything works as long as I do not touch the morphMap as you first suggested, but instead, use the methods you mentioned (```useRoleModel()```, ```useAbilityModel()```).

Thanks for your help! :)
